package.json
yarn.lock

Currently, `yarn install` is failing because this version of `npm-run-all` is depending on `flatmap-stream` v0.1.1 that has been removed due to the [incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).
```
error https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
```
This PR updates `npm-run-all` to the latest version.

Update npm-run-all to 4.1.5

---

src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownTrigger.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.tsx
src/components/Modal/ModalContent.tsx
src/components/Modal/ModalEraser.tsx
src/components/Modal/ModalTrigger.tsx

I've refactored `Modal` and `Dropdown` component with Context API to reduce the complexity.
I've removed some classNames because they are no longer required.
But it might have to revert if the classNames is used as an interface overriding the style.

:recycle: Refactor Modal and Dropdown

---

.circleci/config.yml
package.json

This is a PR to add a setting for CircleCI.
I'll add `npm test` later so it is added as a dummy.
In addition to that, I've changed a place to run `yarn release` from `prepublish` to `prepack` because `prepublish` is executed even after running `yarn install`.
https://docs.npmjs.com/misc/scripts

add a config for CircleCI

---

src/components/Modal/Box.tsx

Currently, focusing input on Modal doesn't work because the children of Modal doesn't rerender even the Modal state has been changed. The reason is that current implementation mounts children at the same time as Modal is mounted and then the Modal only changes the state of Wrapper, which means children are always the same reference so React skips to update children.
This PR makes to mount children only when the `active` state is `true`.

:bug: fix to focus input on Modal

---

package.json
yarn.lock

fix #56
This PR introduces `np` as a tool to publish a npm package.
https://github.com/sindresorhus/np
After merging this PR, you can just run `yarn release` to do the following tasks.
- bump a version
- add a tag for the new version
- publish a npm package
- open a release page in GitHub with the changelog
I've also added `prepublishOnly` script into the npm-scripts, which is run only before `npm publish`
https://docs.npmjs.com/misc/scripts
So it can guarantee to be run `clean` and `build` command before publishing a package.

:wrench: use np for npm publish

---

.github/auto_assign.yml

Added [auto-assign](https://github.com/apps/auto-assign) to assign reviewers automatically.
Reviewers will be randomly assigned from the four members nabeliwo, @wacky, @im36-123 and @AtsushiM.
You can avoid assigning a review by putting the word 'WIP' in the PR title.

Set auto-assign setting

---

src/components/Input/Input.tsx

Currently, override style of Input component using styledComponent doesn't work. Because, className of Base component is only `error` or empty.
After merge this PR, Input component recieve className from parent component.

Pass className prop to component for styled-components

---

src/components/Balloon/Balloon.stories.tsx
src/components/Balloon/Balloon.tsx

This PR specifies font size for Balloon component. The value 12px is from https://github.com/kufu/smarthr-ui/projects/1#card-18945646.

Style Balloon component

---

src/components/Pagination/Pagination.tsx
src/components/Pagination/PaginationItem.tsx

According to https://github.com/kufu/smarthr-ui/projects/1#card-18945881 this PR changes colors 
of Pagination component as followings. 7 is active, 10 is hovered.
In the card https://github.com/kufu/smarthr-ui/projects/1#card-18945881, only background color on hover is specified but white text on Mono_P50 is difficult to read. so I picked Main color for text but i'm not sure this is appropriate.

Change Pagination component colors

---

package.json
tsconfig.build.json
tsconfig.json

The editor's lint error now occurs during this PR ( https://github.com/kufu/smarthr-ui/pull/162 ).
When I import README.md, `module not found` is displayed.
Lint error is displayed but it was merged because It build was successful.
I solved this problem with the configuration file.

Fix editor lint error

---

src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/__test__/__snapshots__/index.test.tsx.snap

When CheckboxLabel does not have enough space, Checkbox is shrinked by flex layout.
So I modified Checkbox style not to be shrinked.

Modify style that do not shrink the Checkbox

---

src/index.test.ts
tsconfig.build.json

Fix #188
This PR adds a test to verify that all components are exported from `src/index.ts`.
The test only checks whether component files are exported from `src/index.ts` or not, which means it doesn't check each `export` statements.
(If we need to verify that every `export` statement in components are exported from `src/index.ts`, I'll add the test in later.)
I've also added an ignore list to allow non-exported components.
```
const IGNORE_DIRS = ['__tests__', 'Base', 'Icon']
```
@nabeliwo Is it ok to ignore `Base` and `Icon` components?

test: add a test for missing exports in src/index.ts

---

src/index.test.ts

`src / index.test.ts` checks that all components are exported
Since `Base component` was not supposed to be exported so far, it was set to ignore during testing.
The test was fixed because there was a change to export `Base component`.

fix: Fix export test

---

.gitignore
package.json
src/libs/lodash.ts
tsconfig.esm.build.json

This PR is to add a new entry point that is for ES Modules, which is intended to enable Tree Shaking with webpack.
To use `esm/` for bundling with webpack, I've added a `module` field in `package.json`.
But this is an issue  with the sentence `import _merge = require('lodash.merge')`.
Because `import 〜 require('xxx')` can't use with `module: es2015 or esnext` in `compilerOptions` so I use import/export statement instead of `import ~ require`.
It seems to be fine because we enable `esModuleInterop` compilerOption.

feat: add an entry point for ES Modules

---

src/components/Modal/Box.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/Modal.tsx
src/components/Modal/ModalContent.tsx

The background click cannot be handled when Modal is imported.
Added onClickBackground props to allow the user to click the background and close the modal.

Add onClickBackground props to Modal

---

src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownControllableContent.tsx

The theme is not applied to the content displayed in the Dropdown.
When passing DropdownContent to ReactDOM.render, also pass ThemeProvider.

fix: Add ThemeProvider to DropdownContent

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownTrigger.tsx
src/components/Dropdown/dropdownHelper.ts

This PR makes implementations of Dropdown simple.
It uses a reference of a DOM element by `useRef` instead of using `className` to manage the elements in a Portal.
Also, I've moved DOM operations located in DropdownContent into Dropdown to make DOM operations cohesion.

refactor: Dropdown

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownContent.tsx

This is an addition PR of #391. 
This PR makes the implementation related to Portals not expose outside `Dropdown` so the implementation of `DropdownContent` becomes simple and doesn't have to know it's rendered on Portals.
I've also fixed a warning of `react-hooks/exhaustive-deps`.

refactor: do not expose about Portals to outside the Dropdown

---

.circleci/config.yml

we use `yarn` instead of `npm` so we should use `yarn` on CircleCI as well.

ci: use yarn for reg-suit on CircleCI

---

src/components/Button/BaseButton.tsx

Deleted `line-height` property for the Button component as it is unnecessary.

Delete unnecessary style propery for Button component

---

src/components/Dropdown/Dropdown.tsx

This fixes a bug that DrowdownContent loses the state when an update happens outside its Dropdown.
The state includes a focus state,  a controlled value, and so on.
This is caused by that DropdownContentRoot is created at every time when Dropdown is rendered.
So I've fixed the issue to memoize DropdownContentRoot using `useMemo`.

fix: memoize DropdownContentRoot

---

src/components/Dropdown/DropdownContentInner.tsx
src/components/Dropdown/dropdownHelper.ts

☝️ Can no longer scroll upward
Under the following conditions, DropdownContent display position will be strange as shown in the image above.
- The sum of the position at the bottom of DropdownTrigger and the height of DropdownContent exceeds innerHeight
- The number obtained by subtracting DropdownContent from the upper position of DropdownTrigger is less than 0
For the conditions listed above, the DropdownContent is displayed at the appropriate size below the DropdownTrigger and is scrollable.
I made it ideal!!!!!!

Fix dropdown content position bug

---

src/components/Button/BaseButton.tsx
src/components/CheckBox/CheckBox.test.tsx
src/components/CheckBox/CheckBox.tsx
src/components/Select/Select.tsx

Reissued this PR (https://github.com/kufu/smarthr-ui/pull/395).
The reason is that the change in CheckBox (https://github.com/kufu/smarthr-ui/pull/425) was so big that it was hard to resolve the conflict...

Change interface of Button, Select and Checkbox to conform to the DOM interface

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/Dialog.controllable.stories.tsx
src/components/Dialog/MessageDialog.tsx

In `ActionDialog` and `MessageDialog`, the function specified for `onClickClose` props has been specified for both the close button and overlay click handlers so far.
However, I felt that it was strange that the function specified in `onClickClose` was called when the overlay was clicked, so I added a new props called `onClickOverlay`.

Add onClickOverlay props to to ActionDialog and MessageDialog

---

src/components/Dialog/Dialog.controllable.stories.tsx
src/components/Dialog/DialogContentInner.tsx

`Dialog` is re-rendered after rendering children of `Dialog`.
For example, if autoFocus was used for input in children of `Dialog`, autoFocus would be lost due to re-rendering of `Dialog`.
Since `DialogContentInner` used the setter of useState after mount to rewrite `className` to generate a fade-in  animation, re-rendering occurred.
Change the animation method of fade-in from `transition` to `keyframe`.
As a result, you can animate without adding `className` after mounting.

Quit re-rendering Dialog

---

src/components/Table/Cell.tsx
src/components/Table/README.md
src/components/Table/Table.stories.tsx

The current Cell props `colspan` and `rowspan` are not correct for props naming, so change them to `colSpan` and `rowSpan`.
This change is a destructive change, but I do not want to increase the major version now, so I will deprecate the previous props and upgrade the patch version.
Issue: https://github.com/kufu/smarthr-ui/issues/480

Change TableCell props name

---

src/components/Input/Input.tsx

`type` props corresponds to the following items.
- text
- search
- tel
- url
- email
- password
- datetime
- date
- month
- week
- time
- datetime-local
- number
Issue: https://github.com/kufu/smarthr-ui/issues/483

Input component supports anything other than text, number, password

---

.storybook/config.js
src/themes/ThemeProvider.tsx
src/themes/createTheme.ts

Since the default theme is set internally, giving the default theme to the ThemeProvider component can be optional.

Make `theme` props for ThemeProvider component optional

---

src/components/Dropdown/DropdownContentInner.tsx

Change the initial position for `DropdownContentInner` from `top: 'auto', left: 'auto'` to `top: '0', left: '0'`.
When the position is `auto`, the `DropdownContentInner` component possibly appears outside the window for a moment, and that causes an unexpected scrollbar flash.
1. Hit the trigger.
2. An unexpected scrollbar shows up for  a moment because the invisible `DropdownContentInner` is outside the window.
3. As the `DropdownContentInner` is set to the right position, the scrollbar goes away.
Setting `top: '0', left: '0'` solves it.

fix(dropdown): change initial position for dropdown component

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownCloser.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownTrigger.tsx
src/components/Dropdown/dropdownHelper.ts

`DropdownContent` does not disappear even if `DropdownTrigger` is clicked again with `DropdownContent` displayed.
`onClickBody` caused `DropdownTrigger` click event with `DropdownContent` disappeared first, so it was displayed again.
Stop `onClickBody` when clicking `Trigger`, `Content` or `Closer`.

Fix Dropdown trigger bug

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContent.tsx
src/components/Dialog/Dialog.controllable.stories.tsx
src/components/Dialog/Dialog.tsx
src/components/Dialog/DialogContent.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContent.tsx
src/hooks/useHandleEscape.ts

This PR enables us to close a dialog using `esc` key, many libraries support this, so I think `smarthr-ui` should support this.
To support this, I've added `onPressEscape` prop into dialog components.
I haven't tested this on Windows, so please test this on Windows if you could 🙏

feat(Dialog): close a dialog when escape key is pressed

---

src/components/Base/Base.tsx

Sorry, I set invalid box-shadow value in [this Pull Request](https://github.com/kufu/smarthr-ui/pull/527) 🙇 
I fixed the css property to valid value again.

fix: box-shadow value in Base

---

src/components/Table/Cell.tsx
src/components/Table/README.md

Removed rowspan and colspan props.
Use rowSpan and colSpan from previous PR.
BREAKING CHANGE: rowspan and colspan cannot be used.

Remove deprecated props for Table component

---

src/components/DefinitionList/DefinitionList.stories.tsx
src/components/DefinitionList/DefinitionList.tsx
src/components/DefinitionList/DefinitionListItem.tsx
src/components/Heading/Heading.tsx

In `DefinitionList`, I want to modify the type of props so that it can support UI like the following image

Change 'term' prop type of DefinitionListItem to React.ReactNode

---

src/components/Dropdown/DropdownContentInner.tsx

細かな条件は調べきれていませんが、DropdownContent の内容が画面左上に一瞬表示されてしまう場合があります。
コンポーネントのマウント後に位置を計算していますが、 visibilityの設定もマウント直後に行っているため、 計算後の値が反映される前に一瞬表示してしまうようです。
`setContentBox` 後に `active` クラスをつけるためのstateを変更するように修正しました。

fix: dropdown flickers

---

src/components/InformationPanel/InformationPanel.stories.tsx
src/components/InformationPanel/InformationPanel.tsx

InformationPanelの既存のコードではtitleに長い文字列が設定されるなどした場合、開閉ボタンの下に回り込んでしまう場合があります。
titleが複数行になった場合にも適切に表示させるように修正しました。

fix: long title InformationPanel

---

src/components/Select/Select.tsx

Fixed that the text for the Input component possibly goes under the icon.
before | after
-- | --

fix: Add enough padding to Input so the text doesn't go under the icon

---

src/components/Table/Cell.tsx

Currently, some styles of Cell component has problem, because of missing `;`. 
This problem became apparent with the update of Styled-components. There seems to be a difference in output between v4 and v5.
**Input**
_Note: some properties have no `;`_
```tsx
const Th = styled.th<{ themes: Theme}>`
${({ themes}) => {
const { size, palette, interaction } = themes
return css`
font-size: ${size.pxToRem(size.font.SHORT)}
font-weight: bold;
padding: ${size.pxToRem(size.space.XS)};
color: ${palette.TEXT_GREY};
transition: ${isTouchDevice ? 'none' : `background-color ${interaction.hover.animation}`}
text-align: left;
line-height: 1.5;
vertical-align: middle;
`
}}
`
```
**Output (v4)**
```css
.foo {
font-size: 0.6875rem;
font-weight: bold;
padding: 1rem;
color: #767676;
-webkit-transition: …
```

fix: fix that some styles doesn’t work

---

src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownContentInner.tsx
src/components/Dropdown/README.md

Added a props called scrollable. This solves the problem of not able to separate scrollable areas from non-scrollable areas in dropdown.

add scrollable props for DropdownContent

---

src/components/RadioButton/RadioButton.tsx

A radio button is squashed when the label text is long.
Adding `flex-shrink: 0;` fixed the problem.
before | after
--- | ---

fix: radio button style bug happening when the label text is long

---

src/components/Loader/Loader.stories.tsx

**[SHRUI-30]**
The color of the storybook loader was changed because it is not the main color.
|before  |after  |
|---|---|
|![Apr-10-2020 18-27-05](https://user-images.githubusercontent.com/23610884/78980520-025a4e80-7b59-11ea-92fd-901e0dc1f021.gif)|![Apr-10-2020 18-27-31](https://user-images.githubusercontent.com/23610884/78980545-0dad7a00-7b59-11ea-8df4-1587544b0bf0.gif)|

fix: change storybook loader color

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownCloser.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownTrigger.tsx
src/components/Dropdown/dropdownHelper.ts

This is just a refactoring for style, so feel free to merge this or close this.
This PR is to remove the usage of a className generated randomly.
I've used a ref of `DropdownTrigger` and verified whether an event came from the `DropdownTrigger` or not.
I've also ignored events that come from within `DropdownContent`.

refactor: [Dropdown] remove the usage of a ramdom string

---

src/components/DropZone/DropZone.stories.tsx
src/components/DropZone/DropZone.tsx
src/components/DropZone/README.md
src/components/DropZone/index.tsx
src/index.ts

DropZone component accepts files drop and files select via the button.
It takes props below:
- `children`: `ReactNode`
- child components that will appear inside the droppable area.
- `onSelectFiles`: `(e: DragEvent<HTMLElement> | ChangeEvent<HTMLInputElement>, files: FileList | null) => void`
- the callback function called when you drop files or select files via the button
- `accept`: `string`
- file types that `<input type='file' />` accepts (no effect to file drop)

feat: add DropZone component

---

src/components/Dropdown/DropdownScrollArea.tsx

IE11にて DropdownScrollAreaの高さが0になってしまうバグが見つかったため対応します。

fix: dropdown scroll area height for ie

---

src/components/Dropdown/Dropdown.stories.tsx

**[SHRUI-30]**
- ulの上下paddingを10px→8pxに変更
- dropdown内のfont-sizeを14pxに変更
- dropdown内のcolorを#333333に変更

fix: change storybook dropdown style

---

src/components/Balloon/Balloon.tsx
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/index.ts
src/index.ts

feat: add tooltip component

---

src/components/Dialog/DialogContentInner.tsx

In #776 , I used React-transition-group to set the fade-out animation to Dialog component.
Because of #776 , "opened" Dialog's appear-animation no longer works.
"opened" Dialog doesn't fade-in anymore like the above.
This PR fixes it.

fix: set appear animation for Dialog

---

src/components/Dialog/DialogContentInner.tsx

`nodeRef` prop has been added to stop using `findDOMNode` in CSSTransitionGroup because the function is deprecated and produces a warning for the usage.
https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#440-2020-05-05
You can test this at a Dialog component on the storybook.

refactor: use nodeRef prop in CSSTransitionGroup for Dialog

---

src/components/InformationPanel/InformationPanel.stories.tsx
src/components/InformationPanel/InformationPanel.tsx

Adding option that can choose showing a toggle button or not in `InformationPanel`.

feat: add togglable option in InformationPanel

---

.circleci/config.yml

use `checksum package.json` and `checksum yarn.lock` as circleci cache key.

chore: use package.json's checksum for circleci

---

src/components/Table/Table.tsx

`table` 内 `th` の詳細度が高すぎるため、スタイルのオーバーライドが面倒になってる。
厳密に `table > thead > tr > th` である必要はまったくない。
これが | `table > thead > tr > th`
--- | ---
こうなる | `table th`

fix: table 内 th の詳細度が高すぎる

---

src/components/Button/TextButton.tsx

`border-top` が `white` だと白背景以外では浮いてしまう。
`background-color` に合わせて `transparent` に変更する。

fix: improve TextButton broder-color to transparent

---

src/components/AppNavi/AppNavi.stories.tsx
src/components/AppNavi/AppNavi.test.tsx
src/components/AppNavi/AppNavi.tsx
src/components/AppNavi/AppNaviAnchor.tsx
src/components/AppNavi/AppNaviButton.tsx
src/components/AppNavi/AppNaviCustomTag.tsx
src/components/AppNavi/AppNaviDropdown.tsx
src/components/AppNavi/README.md
src/components/AppNavi/appNaviHelper.tsx
src/components/Icon/Icon.tsx
src/components/Icon/index.ts

Enabled to display the following elements in addition to buttons in AppNavi.
- anchor tag
- Dropdown Component
- Custom Component
- If there is `href`, it becomes an anchor
- If there is `dropdownContent`, it becomes dropdown
- If there is `tag`, it becomes custom tag
- In the case of conditions other than the above three, it becomes button
Added `disabled` props for button props array.
With this change, it is no longer disabled by default when passing true for `current` props.

feat: add buttons props types for AppNavi component

---

src/components/AppNavi/AppNaviCustomTag.tsx
src/components/AppNavi/README.md

Modified type to accommodate custom components like `react-router-dom`'s `Link`.
- AnyStyledComponent -> ComponentType<any>
- {} -> { [key: string]: any }

fix: fix props type for AppNavi

---

src/components/AppNavi/AppNaviCustomTag.tsx

When using custom tag, props additionally passed when `current: true` is reflected.

fix: pass other props to AppNaviCustomTag

---

.circleci/config.yml

異なるdocker間で同一のcache keyを共有すると、あるdocker上で作られたcacheの場所によっては他のdockerからアクセスできないことがあるので、testとreg-suitで異なるcache keyになるように修正しました。
参考：https://support.circleci.com/hc/ja/articles/360004250693-%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%81%AE%E5%BE%A9%E5%85%83%E3%81%8C-Permission-Denied-%E3%81%A7%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B

fix: change cache key for circleci

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

Add `thousandsSeparated` props into `Input` that enable to control currency data.
When `type` is "number" and `thousandsSeparated` is true, the `Input` become currency mode.
In currency mode,
* add comma to integer part every 3 digits.
* remove no-numeric characters.
* convert full-width characters to half-width.

feat: add currency mode into Input

---

src/components/Calendar/Calendar.stories.tsx

`Calender`のstorybookが実行日によって描画内容が変動してreg-suitに引っかかってしまうため、初期`value`値を過去の日付にすることで表示上の差分が出ないように変更。

fix: calendar date in storybook

---

src/components/Dialog/DialogContentInner.tsx

When we extend `Dialog` by `styled-components`, there is a problem to display background like this.
```ts
const extendedDialog = styled(Dialog)`
width: 200px;
`
```
This problem is caused by passing `className`  to `Background`. So I exclude it.

fix: change not to pass className to Background in Dialog

---

src/components/Table/Table.stories.tsx

In IE11 and Edge, `rowSpan=0` is not working correctly. So I change it not to use `rowSpan=0`.
* before
* after

fix: change not to use rowSpan=0

---

src/components/Input/CurrencyInput.tsx
src/components/Input/CurrencyInput/CurrencyInput.stories.tsx
src/components/Input/CurrencyInput/CurrencyInput.tsx
src/components/Input/CurrencyInput/README.md
src/components/Input/CurrencyInput/index.ts
src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx
src/components/Input/index.ts
src/index.ts

https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99?selectedIssue=SHRUI-136
現状、通貨用Inputの整形タイミングがblur時だけになっていますが、それではアプリケーションで使用するにあたっては不十分であるため、親側からのvalue, defaultValueが渡ってくることを考慮した整形タイミングに変更します。
また、役割の明確化のため通貨用機能を`Input`コンポーネントから別コンポーネントへの切り出しも行います。
* 通貨用整形機能を`CurrencyInput`コンポーネントとして切り出し
* READMEを分離するため、ディレクトリも変更
* 整形を掛けるタイミングを追加
* 初回描画時
* value, defaultValue値を参照
* `value` propsの値が親側で変更された時
* ただし自身がフォーカスされている時（つまり入力中）は整形しない
* `onFormatValue`ハンドラを追加
* 自動整形による変更をハンドリングできるようにするため独自のハンドラを追加
* `Input` コンポーネントに[ref forwarding](https://ja.reactjs.org/docs/forwarding-refs.html)を追加
* [非制御コンポーネント](https://ja.reactjs.org/docs/uncontrolled-components.html)のままvalueを制御するためには`Input`にrefを通す必要があったため追加
* 使用側で制御 / 非制御を選択できるようにするために、`CurrencyInput`は非制御コンポーネントとして実装する必要がある

BREAKING CHANGE: segment and modify currency input

---

src/components/Textarea/Textarea.stories.tsx
src/components/Textarea/Textarea.tsx

An update to the TextArea component. 
* add 'maxlength' attribute
* show character counter if the maxlength attribute is enabled
|  default  |  character overload  |
| ---- | ---- |
| ![スクリーンショット 2020-07-08 17 53 08](https://user-images.githubusercontent.com/4032232/86898821-23c0db80-c144-11ea-81f3-00ba6a2a843f.png) | ![スクリーンショット 2020-07-08 17 53 24](https://user-images.githubusercontent.com/4032232/86898851-2b808000-c144-11ea-95bf-ecc660bc37f4.png)|

feat: add maxlength attribute and text counter to textarea

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

`Input`コンポーネントにおける`className`適用位置が間違っており、これによりextending styleが正しく行えなくなっている問題を修正します。
* `Input`に渡された`className`が外側のwrapperに適用されるように修正
* before
* after

fix: applying className in Input

---

src/components/Header/Header.tsx
src/components/Header/README.md

https://smarthr.atlassian.net/browse/SHRUI-143?atlOrigin=eyJpIjoiM2JmZDgyMjRkMmI0NDkyODg5YWNjMTViMGI4ODBlZTkiLCJwIjoiaiJ9
- テナント名領域に ReactNode が入るようにしたい
- 現状は string しか入らず、ドロップダウンなどを差し込めないので
- ついでにスタイル拡張できるようにしたい
- Header に `displayTenantName` props を追加
- optional な props で、入力なければ `currentTenantName` をそのまま表示
- 同 Header に `className` props を追加

Header コンポーネントのテナント名領域に node が入るようにしたいんじゃー

---

src/components/Input/Input.tsx

When setting small width to `Input` component, the actual input element exceeds the given width.
Added `width: 100%;` to input element.
When setting `width={75}`
before | after
-- | --

fix: width for input element in Input

---

src/components/Input/CurrencyInput/CurrencyInput.tsx

#878 
Adding dependencies of hooks, or suppressing `react-hooks/exhaustive-deps` rule
* add normal deps of hooks
* add comment to disable eslint rule

fix: add necessary dependencies of hooks in CurrencyInput

---

src/components/Calendar/CalendarTable.tsx

When using reset CSS like [styled-reset](https://github.com/zacanger/styled-reset), there is a problem of design collapse.
It needs to be modified to work fine with reset CSS.
* Set `vertical-align: middle;` to every table cell
* Change from `padding` to `margin` of table because `padding` is not working when `border-collapse: collapse;` is set.
| --- | --- |
| ![スクリーンショット 2020-08-31 17 38 11](https://user-images.githubusercontent.com/270422/91701111-cb411400-ebb1-11ea-8fe7-dc9ec38c88a9.png) | ![スクリーンショット 2020-08-31 17 37 48](https://user-images.githubusercontent.com/270422/91701133-d1cf8b80-ebb1-11ea-9440-da98e2d1d58b.png) |

fix: fix styles of Calendar when using reset style (SHRUI-160)

---

src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/hooks/useId.tsx
src/index.ts

#900 
Tooltipをportal化する際に、`aria-labelledby`に用いるための`id`を必須propsとして追加しましたが、idは外から渡さずにTooltip内で自動生成して完結させたほうが便利かつ合理的だったため、idの自動生成機能を作成しTooltipに適用・`id` propertyを削除します。
* `useId`hookを作成
* 生成されるidの形式は`id-[prefix]-[counter]`
* `prefix`, `counter`はcontextで管理
* `SequencePrefixIdProvider`を作成
* SSRする際に、生成したidの値をserverとclientで一貫させるために、prefixを連番にしてcounterをリセットするcontext provider
- id生成に関して[@react-aria/util](https://www.npmjs.com/package/@react-aria/utils)の導入を検討しましたが、ES5互換ではないため自前で実装を持つことにしました。

feat!: add useId hook and remove id property from Tooltip

---

src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
src/components/Icon/Icon.tsx

https://smarthr.atlassian.net/browse/SHRUI-148
When the Icon is a visual decoration, it may want to be set `aria-hidden=true` and `focasable=false`.
In `Icon` component
* set `focusable` **false** by default
* set `aria-hidden` **true** when the `Icon` has no settings of `visuallyHiddenText`, `aria-label` and `aria-labelledby`.

fix: enable to ignore Icon what has no labels (SHRUI-148)

---

src/components/DatePicker/DatePicker.stories.tsx
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/README.md
src/components/DatePicker/useOuterClick.ts

https://smarthr.atlassian.net/browse/SHRUI-178
`DatePicker`を全体的に修正します
* valueの指定の仕方を`Date`から`string`に変更
* 非Date formattableな文字列も受け取れるようにするため
* `onChangeDate`で、inputのvalueも受け取れるように変更
* `name`, `disabled`, `error` propsの追加
* invalid date error表示の削除
* アプリケーションによって様々なバリデーションが有り得、そのメッセージを表示する場合`DatePicker`自体のエラー表示とバッティングしてしまう。そこで`DatePicker`の役割を「parseできない場合はinvalid dateで扱う」ように限定し、そのハンドリングはアプリケーション側に任せるように変更する
* `Calendar`の表示位置がスクロール量を考慮できていなかったので修正
* custom hook内のrefの扱い方がまずかったので修正

fix!: DatePicker (SHRUI-178)

---

src/components/Tooltip/TooltipPortal.tsx

https://smarthr.atlassian.net/browse/SHRUI-172
Tooltipを晴眼者しか見ることができず、[達成基準 1.3.1 情報及び関係性](https://waic.jp/docs/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)に不適合なので対応しました。
- Tooltipのコンテナ要素に、 `role=tooltip` を追加
- https://waic.jp/docs/2019/NOTE-wai-aria-practices-1.1-20190207/#tooltip
- (トリガーとなる要素に `aria-describedby` の記述があり、Tooltip要素を参照するようになっていたので `aria-describedby` は追加していません)

fix: add role attribute to tooltip

---

.storybook/addons.js
.storybook/webpack.config.js
package.json
yarn.lock

[addon-storysource](https://github.com/storybookjs/storybook/tree/master/addons/storysource) を入れ Story のソースを見られるようにした。
- `@storybook/addon-storysource` を追加
- config 修正

Story のソースを見られるようにする

---

src/components/BottomFixedArea/TertiaryLink.tsx

https://smarthr.atlassian.net/browse/SHRUI-188
`BottomFixedArea` の `TertiaryLink` ですが、`button` の中に `p` がありHTML エラーなので対応しました。
- `button` の中にある `p` を `span` に変更
- [Nu Html Checker](https://validator.w3.org/nu/) でエラーにならないこと

fix: change tertiary link in Bottom Fixed Area to correct HTML

---

src/components/DatePicker/DatePicker.stories.tsx
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/Portal.tsx
src/components/DatePicker/datePickerHelper.ts

https://smarthr.atlassian.net/browse/SHRUI-212
`body`にスクロール制限がかかっている時、`DatePicker`の`Calendar`がページ下方にはみ出した時にスクロールして表示することができなくなる問題を解消する。
- 特定の条件下で、`Calendar`をinputの上側に表示するように変更
- input下側に`Calendar`を表示するための十分なスペースがなく、且つ、input下側のスペースより上側のスペースのほうが大きい場合

fix: calculate Calendar position in DatePicker (SHRUI-212)

---

yarn.lock

I've updated the version of `eslint-config-smarthr` to v5 and fixed some errors.
To fix the errors, I've changed the type of `{}` to `Record<string, unknown>`.

chore: bump eslint-config-smarthr to v5

---

src/components/BackgroundJobsPanel/BackgroundJobsPanel.tsx
src/components/BackgroundJobsPanel/JobIcon.tsx
src/components/BackgroundJobsPanel/OmittableJobText.tsx

https://smarthr.atlassian.net/browse/SHRUI-213
Modify styles of `BackgroundJobsPanel` not to collapse styles with reset css 
- Adjust `line-height` and `align-items` of Job row.
- Set `display: block` to Tooltip to ignore own line-height.

fix: consider reset css in BackgroundJobsPanel (SHRUI-213)

---

src/components/MessageScreen/MessageScreen.tsx

https://smarthr.atlassian.net/browse/SHRUI-223
`MessageScreen` コンポーネントの `aria-label = "別タブで開く"` がアイコンではなくリンク自体についているので修正しました。
- リンクではなくアイコンに `aria-label = "別タブで開く"` を付与。

fix: change to add aria-label to icon

---

src/components/Calendar/calendarHelper.test.ts
src/components/Calendar/calendarHelper.ts

なし
Calendar コンポーネントの用途として生年月日の選択などがあるが、現状だと最低値が1970年1月1日なので、これを1900年1月1日まで下げたい。
1900年1月1日という値は特に明確な理由はなく、 SmartHR のユースケースにおいてはこれより下の年月日を選択したい時はなさそうという感じです。
from props を渡さなかった場合のデフォルトの値は変わらず1970年1月1日のままです。
- from props の min の値を変更
なし

fix: change the value of min props in the calendar component

---

src/components/FieldSet/FieldSet.tsx
src/components/Input/Input.tsx

https://smarthr.atlassian.net/browse/SHRUI-194
- htmlにinvalidなwidth属性が指定される場合があったため対応したい
以下のコンポーネントで不正なwidth属性を取り除いた
- FieldSet
- Input
- MessageScreen
widthをTransient propsに変更しています

fix:  invalid html width attribute

---

src/components/DatePicker/DatePicker.stories.tsx
src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/README.md

なし
DatePicker コンポーネントでは生年月日などを選択することがあるが、現状だと1970年~現在から50年後の間しか選択できないので、 from, to という props を渡すことで上限と下限を変更できるようにしたい。
- from, to props の追加
- なお、 from, to の下限、上限は Calendar コンポーネントに依存する
なし

feat: add "from" and "to" props to DatePicker component

---

src/components/DatePicker/DatePicker.tsx
src/components/DatePicker/Portal.tsx

`DatePicker`のバグを2点修正します
* `Calendar`が上側表示される際の input との重なり具合を修正
* `value`propに`null`を設定した時、正しく input に値が反映されない不具合を修正
* `value`propに`null`が入ったときもinputへの反映用の`useEffect`が発火するように修正
* 同時に、適切に`selectedDate`が更新されるように修正
* `Calendar`の portal の位置及び外側クリック判定対象を修正
| --- | --- |
| ![スクリーンショット 2020-10-22 18 08 15](https://user-images.githubusercontent.com/270422/96850317-a0788b00-1491-11eb-957f-323e9600e016.png) | ![スクリーンショット 2020-10-22 18 07 21](https://user-images.githubusercontent.com/270422/96850328-a53d3f00-1491-11eb-8630-f3a92d0b48a3.png) |

fix: DatePicker bugs

---

src/components/DropZone/DropZone.tsx

- https://smarthr.atlassian.net/browse/SHRUI-191
- passing `''` to accept field is invalid on [Nu Html Checker](https://validator.w3.org/nu/)
- fixed to pass `undefined` to accept instead of `''`

fix: pass undefined to accept instead of blank string

---

src/components/Footer/Footer.tsx
src/themes/createPalette.ts

- change Footer color to BRAND Color
- remove HEADER_GREEN from palette
- update snapshots
before | ![image](https://user-images.githubusercontent.com/19403400/82002245-45e43300-9698-11ea-91a2-4e3cc04dbc18.png)
--- | ---
after | ![image](https://user-images.githubusercontent.com/19403400/82001898-3f08f080-9697-11ea-8897-ed686e72a4e6.png)
For the BRAND TEAM

Fix footer color to brand color 

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

- https://smarthr.atlassian.net/browse/SHRUI-121
- add `hasBlank` and `blankLabel` props to Select component so users do not have to inject a blank option manually.
- add `hasBlank` and `blankLabel` props to Select component
- default:
- `hasBlank`: `false`
- `blankLabel`: `'選択してください'`

feat: add hasBlank and blankLabel props to Select

---

.circleci/config.yml

https://smarthr-inc.docbase.io/posts/1585443#docker-hub-%E3%81%AE%E4%BB%B6-tknzk
- Docker Hub の無料プランにおける image の pull の回数制限が始まりました
- これを受けて弊社で Docker Hub への課金が始まりました
- https://smarthr-inc.docbase.io/posts/1585443#docker-hub-%E3%81%AE%E4%BB%B6-tknzk
- CircleCI の設定で docker pull するところで認証を通さなきゃいけなくなりました
- CircleCI の `config.yml` で認証情報を追加
🍐

chore: authenticate docker hub

---

src/components/AccordionPanel/AccordionPanelContent.tsx

アコーディオンパネルの開閉に `overflow: hidden` を利用しているが、`hidden` のままだと展開時に内部コンテンツが見切れる可能性がある。
例えばラジオボタンやチェックボックスを配置した場合に「アウトラインだけ見切れる」という事象が発生する。
アコーディオンパネルのコンテナ要素の展開時 `.enterd` に対して `overflow` の既定値 `visible` を設定した。
見た目の変更はないのでありません。

fix: アコーディオンパネルの展開時に overflow を既定値に戻す

---

package.json
yarn.lock

This is a retake PR of #1049 
React has released v17, so I'd like to test the version with `smarthr-ui`.
I've updated `peerDependencies` and `devDependencies` to allow React v17.
The `peerDependencies` still includes `v16.13.0` so this is not a breaking change.

feat: support React v17

---

.storybook/config.js
src/components/BottomFixedArea/TertiaryLink.tsx
src/components/Calendar/CalendarTable.tsx
src/components/Calendar/YearPicker.tsx
src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
src/components/Loader/Loader.stories.tsx
src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
src/index.ts
src/themes/createPalette.ts

https://smarthr.atlassian.net/browse/SHRUI-232
v10に新カラーをバックポートする
タグ`v10.0.0`から切った`v10-release`ブランチにマージする
- cherry-pick 1c8063ac92543f54b4046efc7d9f12a177cb891b
- update snapshot

feat: backport Shin Color to v10 (SHRUI-232)

---

.storybook/config.js
src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
src/components/Select/Select.tsx
src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
src/index.ts
src/themes/createPalette.ts

https://smarthr.atlassian.net/browse/SHRUI-232
v6に新カラーをバックポートする
タグ`v6.2.0`から切った`v6-release`ブランチにマージする
- cherry-pick 1c8063a
- `Loader`のstoryの変更はコンフリクトが多かったので落としました（機能に影響はありません）
- update snapshot
- lintに引っかかった部分を修正

feat: backport Shin Color to v6 (SHRUI-232)

---

.storybook/config.js
src/components/BottomFixedArea/TertiaryLink.tsx
src/components/Calendar/CalendarTable.tsx
src/components/Calendar/YearPicker.tsx
src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
src/components/Loader/Loader.stories.tsx
src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
src/index.ts
src/themes/createPalette.ts

https://smarthr.atlassian.net/browse/SHRUI-232
v9に新カラーをバックポートする
タグ`v9.3.0`から切った`v9-release`ブランチにマージする
- cherry-pick 1c8063ac92543f54b4046efc7d9f12a177cb891b
- update snapshot

feat: backport Shin Color to v9 (SHRUI-232)

---

.storybook/preview.js
src/components/BottomFixedArea/TertiaryLink.tsx
src/components/Calendar/CalendarTable.tsx
src/components/Calendar/YearPicker.tsx
src/components/Loader/Loader.stories.tsx
src/components/Select/Select.tsx
src/index.ts
src/themes/createPalette.ts

https://smarthr.atlassian.net/browse/SHRUI-232
v11に新カラーをバックポートする
タグ`v11.1.0`から切った`v11-release`ブランチにマージする
- cherry-pick 1c8063ac92543f54b4046efc7d9f12a177cb891b

feat: backport Shin Color to v11 (SHRUI-232)

---

src/components/Select/Select.tsx
src/libs/ua.ts

The blank <optgroup> is displayed for IE. 👇 
So, add the blank <optogroup> only on Safari Mobile
- Add mobile safari detection flag to is libs/ua.ts
- Add blank <optgroup> only on mobile safari by above flag

fix: remove that blank optgroup is displayed for IE

---

.github/workflows/e2e.yml

🍐 
IE 向けの E2E テストの動作が不安定なので、安定するまでは一旦 GitHub Actions のトリガーを master ブランチへの PR ではなく、 ie ブランチへの PR にしたい
- GitHub Actions の設定ファイルの修正
- `master` -> `ie`
🍐

chore: change e2e test trigger

---

src/components/Select/Select.tsx

- https://smarthr.atlassian.net/browse/SHRUI-225
- select の disabled のborder カラーに #f9f9f9 を使っている。
- 背景色でも領域を分けるために#f9f9f9 を使っているので、その上に select を載せて disabled にすると border が消えたように見えしまうのでカイゼンしたい
- select の disabled 状態時にも border を付ける
- アイコンの色が disabled になってなかったので修正（disabled用カラーを設定）

feat: fix style of disabling selectbox

---

package.json
src/components/Dialog/Dialog.opened.stories.tsx
src/components/Dialog/Dialog.uncontrollable.stories.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/README.md
yarn.lock

resolve #886 
1. `<Dialog>` を起動したら `<DialogContentInner>` 内のフォーカス用ダミー要素にフォーカスする
2. `<Dialog>` を閉じたら `<Dialog>` を開いたトリガーの要素にフォーカスする
3. `<Dialog>` をフォーカストラップとする（フォーカスを `<Dialog>` の外に出ないようにする） 
- `createFocusTrap` を利用して、 `isOpen` をトリガーにし `<DialogContentInner>` にてフォーカストラップを発動
- `<Dialog>` を起動するトリガーボタンに `aria-haspopup` を付与
- README.md に Accessibility の章を追加し、利用時の推奨事項とキーボードインタラクションについて追加
Storybook: https://deploy-preview-889--smarthr-ui.netlify.app/?path=/story/dialog--controllable
WHY: モーダルの後ろにあるコンテンツにアクセスできてしまうと、混乱を招いてしまうため
バンドルサイズと依存の少なさから `focus-trap/focus-trap` とした。
他のコンポーネントでも色々使う & React 依存で問題ないなら `@react-aria/focus` が良さそう
個人のOSSでSEEKING CO-MAINTAINERS だったが、メンテナも集まり org 化された。もともと依存も少なく枯れているがやや記述量が多い。バンドルサイズが小さい。
**BUNDLE SIZE**
- MINIFIED: 6.2kB
- MINIFIED + GZIPPED: 2.3kB …

fix: dialog focus management

---

src/hooks/usePortal.tsx

Fixed a potential bug in `usePortal`.
Add optional chaining (`?`) to `element.dataset.portalChildOf` since `dataset` can be undefined.

fix: add optional chaining to _isChildPortal

---

src/hooks/usePortal.tsx

IEにおいて`SVGElement.parentElement`が`undefined`であるという問題があるので、`parentNode`でフォールバックを行う
- `instanceof`で型ガードしつつフォールバック

fix: fallback parentElement of svg element for IE

---

src/components/Input/Input.tsx

こちらの PR の向き先を変えたものです。
すでに LGTM いただいているので CI 通り次第マージします。
v12.0.0-0 で発生するようになった表示崩れなので v12.0.0 で直るように hotfix します。
FireFox でのみ再現する表示バグです。
以下の条件を満たす場合に Input コンポーネントの表示が添付したキャプチャのように崩れます。
- Flex ボックスの子要素として Input が置かれている
- Input に width props が number で渡されている
Input コンポーネントの input タグに `box-sizing: border-box` をあてることで解決。
**Before**
**After**

fix: fix input width for firefox

---

src/components/SideNav/SideNav.stories.tsx
src/components/SideNav/SideNav.tsx
src/components/SideNav/SideNavItem.tsx
src/components/SideNav/useClassNames.ts
src/hooks/useClassNameGenerator.ts

https://smarthr.atlassian.net/browse/SHRUI-320
このPRはプレリリース`v12.0.0-0`に対する hotfix です
`SideNav`コンポーネントに対して以下の修正を行います。
- 外側から各アイテム、アイテムタイトルを特定できるようにする
- prefix - title 間のマージン設定の責務をprefix側で担保
- 各ボタンに`cursor: pointer`スタイルを付与
- 特定用のclass名を付与
- 共用hookとして`useClassNameGenerator`を追加
- コンポーネント名とパーツ名からclass名を生成する関数
- 命名ルールとしては、`smarthr-ui-SideNav-itemTitle` という風になる想定としました
- ケバブケースとキャメルケースが混じってやや違和感がありますが、`{コンポーネント名}-{パーツ名}`を明確に表現するためにはこれが良いのではないかと判断しました
- `SideNav`用のhookとして`useClassNames`を追加
- 意図としては、同コンポーネント内におけるコンポーネント名指定の揺れを防ぐためと、コンポーネント内で使っているclass名を一覧できるようにしたほうが良さそうだと思ったからです
- もしこれが冗長であれば消すことも可能です
- wrapper, 各アイテム, 各アイテムのタイトルにclass名を付与
- prefix に `margin-right` を設定
- ボタンに `cursor: pointer` を設定

fix: reflect feedback of SideNav (SHRUI-320)

---

src/components/StatusLabel/StatusLabel.stories.tsx
src/components/StatusLabel/StatusLabel.tsx
src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap

🍐 
v12.0.0-0 にて StatusLabel に白背景がつかなくなってしまったので追加したい
- `background-color: #fff` を追加
- story を見やすくするために padding を追加
(わかりやすくするためにキャプチャ撮る時だけグレー背景を敷いています)

fix: add background-color white

---

src/components/Dialog/Dialog.controllable.stories.tsx

Replace old color code in storybook to use theme
- Replace
- border style => frame.border.default

docs: replace old color code of storybook to theme in Dialog

---

src/components/ProgressBar/ProgressBar.stories.tsx

Replace old color code in storybook to use theme
- Replace 
- `#333` => `palette.TEXT_BLACK`

docs: replace old color code of storybook to theme in ProgressBar

---

src/components/SegmentedControl/README.md
src/components/SegmentedControl/SegmentedControl.stories.tsx
src/components/SegmentedControl/SegmentedControl.tsx

https://smarthr.atlassian.net/browse/SHRUI-242
This PR adds ARIA attributes and keyboard navigation into `SegmentedControl` component.
* Add ARIA attributes
* `role=toolbar`, `role=radiogroup`, `role=radio`, `aria-checked`
* Add keyboard navigation
* `Tab` : focus on / blur the `radiogroup`
* If the `radiogroup` includes an active radio button, focus the active radio button. If not, focus the first radio button in `radiogroup`.
* `→`, `↓` : move focus to next radio button
* `←`, `↑` : move focus to previous radio button
* The focus movement by arrow keys loops within `radiogruop`.
* Update README

fix: add Segmented control ARIA (SHRUI-242)

---

src/components/InputFile/InputFile.tsx

This PR migrates the Icon component in the InputFile component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in InputFile

---

src/components/InformationPanel/InformationPanel.tsx

This PR migrates the Icon component in the InformationPanel component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in InformationPanel

---

src/components/RadioButtonLabel/README.md

Escaping is needed for README.md for RadioButtonLabel.
Add escape character.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14817308/102038683-40f08900-3e0b-11eb-8a7c-770fa5717310.png) | <img width="553" alt="スクリーンショット 2020-12-14 12 46 46" src="https://user-images.githubusercontent.com/14817308/102038700-4948c400-3e0b-11eb-92bc-70545bdd85e5.png">|

add escape character to README.md for RadioButtonLabel

---

src/components/Header/HeaderCrewDropdown.tsx
src/components/Header/HeaderUserDropdown.tsx

This PR migrates the Icon component in the Header component, which does not affect anyone, just a refactoring.
HeaderButton is also using Icon components, but it receives an icon name as props, so we have to change I/F to migrate the usage. I'll work on that as another issue.

refactor: migrate Icon in Header

---

src/components/DropZone/DropZone.tsx

This PR migrates the Icon component in the DropZone component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in DropZone

---

src/components/MultiComboBox/MultiComboBox.tsx

This PR migrates the Icon component in the MultiComboBox component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in MultiComboBox

---

src/components/Downloader/Downloader.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-308
- Replace old color code in storybook to use `theme`
- Replace
- `#007bc2` => `palette.TEXT_LINK`
- `#333` => `palette.TEXT_BLACK`
- `font-size: 14px` => `size.font.TALL`

docs: replace old color code of storybook to theme in Downloader (SHRUI-308)

---

src/components/FieldSet/FieldSet.tsx

This PR migrates the Icon component in the FieldSet component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in FieldSet

---

src/components/AccordionPanel/AccordionPanelTrigger.tsx
src/components/BackgroundJobsPanel/BackgroundJobsPanel.tsx
src/components/BackgroundJobsPanel/JobIcon.tsx

A part of SHRUI-238.
This PR migrates the Icon component in AccordionPanel and BackgroundJobsPanel, which does not affect anyone, just a refactoring.
I've replaced the Icon component with each Icon components like `FaCaretDownIcon`.

refactor: migrate Icon in AccordionPanel and BackgroundJobsPanel

---

src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-304
- Replace old color code in storybook to use `theme`
- Replace
- `#333` => `palette.TEXT_BLACK`
- background-color in `:hover` => `palette.hoverColor()`
- border style => `frame.border.default`

docs: replace old color code of storybook to theme in Dropdown (SHRUI-304)

---

src/components/Dropdown/FilterDropdown/FilterDropdown.tsx

This PR migrates the Icon component in the FilterDropdown component, which does not affect anyone, just a refactoring.
I've replaced the Icon component with Fa* components.

refactor: migrate Icon in FilterDropdown

---

src/components/FlashMessage/FlashMessage.tsx

This PR migrates the Icon component in the FlashMessage component, which does not affect anyone, just a refactoring.

refactor: migrate Icon in FlashMessage

---

src/components/CheckBox/CheckBox.tsx

This PR migrates the Icon component in the Checkbox component, which does not affect anyone, just a refactoring.
I've replaced the Icon component with Fa***Icon components.

refactor: migrate Icon in Checkbox

---

src/components/Dropdown/DropdownContentInner.tsx

https://smarthr.atlassian.net/browse/SHRUI-236
IEで `Dropdown` コンポーネント内にスクロールが必要になった場合に正しくスクロールできない問題を解消する
- `max-height` を設定している要素が `display: flex` でwrapされるように構造を変更
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/101316254-80652580-389f-11eb-8768-1b1f2ec8e08b.png) | ![image](https://user-images.githubusercontent.com/270422/101316289-91159b80-389f-11eb-9094-66277d784bd3.png) |

fix: modify to be able to scroll Dropdown in IE (SHRUI-236)

---

src/components/Button/BaseButton.tsx
src/components/Button/PrimaryButton.tsx
src/components/Button/SecondaryButton.tsx
src/components/Button/SkeletonButton.tsx
src/components/Button/TextButton.tsx

https://smarthr.atlassian.net/browse/SHRUI-244
`Button`コンポーネントに対して、別ライブラリなどで指定されたaタグに対するホバーやフォーカスのスタイルが当たらないように修正する
- `Button`コンポーネントの`:hover`, `:focus`に対して`text-decoration`, `color` のスタイルを明示しておく

fix: modify not to apply hover or focus style from other css to Button (SHRUI-244)

---

src/components/FieldSet/FieldSet.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-314
FieldSetのstorybookのカラーをシン・カラーに変更しました。
- theme参照に変更
- シン・カラーに変更

docs: change the color of FieldSet in storybook to shin color

---

src/components/RadioButton/RadioButton.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-295
storybook 上の `RadioButton` のキーボード操作が不自然になっているのを修正する
実装云々ではなく story の書き方に起因する問題だったので以下の修正で対応
* 現状 `RadioButotn` は制御コンポーネントとしての利用のみを想定しているので、story 上の記述を制御コンポーネントに変更
* ひとつのラジオグループ内にチェック済み input がひとつになるように input name を変更

docs: improve radioButton story (SHRUI-295)

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

- https://smarthr.atlassian.net/browse/KOBAN-4970
- https://smarthr.atlassian.net/browse/SHRUI-327
- Input コンポーネントで error と disabled 双方の props が指定されている場合は、disabled の style を当てたい
- Input error の style は !disabled のときのみ適用するようにした
|Before|After|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5195381/105024803-dd075300-5a8f-11eb-830b-abdf3c7c2e7d.png) | ![image](https://user-images.githubusercontent.com/5195381/105024325-4f2b6800-5a8f-11eb-859f-d915a2813295.png) |

fix: change input error style (SHRUI-327)

---

src/constants.ts

https://smarthr.atlassian.net/browse/SHRUI-317
`VISUALLY_HIDDEN_STYLE` の位置が直近の祖先の相対位置になることに起因して意図しないスクロールが発生してしまう問題に対応する。
* `top`, `left` 位置を指定して基準座標付近（1px上）に配することで、このスタイルを持った要素の表示に伴うスクロールが生じないように修正
* ページ上の特定の箇所に 1px の absolute 表示の要素が存在しうることになるが、`clip` スタイルを用いていることによりその領域はクリック等のマウス操作に影響を及ぼさないことを確認したので、特に支障は無いと思われる

fix: fix position of visually hidden text (SHRUI-317)

---

src/components/InputFile/InputFile.tsx

- https://smarthr.atlassian.net/browse/SHRUI-316
Hanicaなどではinputのfont-sizeに!importantがついており、上書きされてしまう。
InputFileのfont-sizeが上書きされると、マウスポインターの切り替え位置がずれるため、デフォで !important つける

fix: add "!important" to font-size of InputFile

---

.gitignore
package.json

CI の reg-suit でタイムアウトが頻発する問題に対処します。
`storycap` がスクリーンショットを撮るために storybook を起動しアクセスするが、その初回アクセス時に storybook のコンテンツがロードされるまでに30秒以上掛かると `pupeteer` がタイムアウトする。
`start-storybook` コマンドによって storybook を起動した時、初回アクセス時にモジュールビルドが行われ余計に時間がかかってしまう。
そこで、 `build-storybook` コマンドによって予め storybook の静的ファイルを生成してから http サーバを立ち上げることで初回アクセス時の処理時間を短縮し、タイムアウトを回避させる。
* `pretest-visual` スクリプト内における storybook の起動を、`start-storybook` から `build-storybook` + `npx http-server` に変更

test: avoid timeout during reg-suit

---

src/components/DatePicker/DatePicker.tsx

https://smarthr.atlassian.net/browse/SHRUI-329
This PR makes `DatePicker` component can be set [default attributes of input element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attributes).
* Add default input attributes by using intersection types.

fix: enable to set attributes of input element in DatePicker (SHRUI-329)

---

src/components/InputFile/InputFile.tsx

<InputFile> は input[type=”file'] と <button>で実装されているが、隠している input にもフォーカスがあたってしまい、一度フォーカスインジケーターが表示されなくなる。
キーボードで操作している場合には混乱する可能性があるため修正したい

fix: input[file] の不要なfocusを削除する

---

src/components/Balloon/Balloon.tsx
src/components/Balloon/useClassNames.ts

hooks の叩き方に起因して警告及びエラーが発生する問題に対処します。
`Balloon` にて、render 時に警告
`Tooltip` にて、キーボードフォーカスしたトリガにマウスホバーするとエラー発生
* hooks の書き方を修正
* className を生成するファイルを分割

fix: modify not to call hooks in useMemo in Balloon

---

.circleci/config.yml

CI の jest でメモリを使い切っている雰囲気があるので、 maxWorkers の制限を入れる
* https://jestjs.io/docs/ja/cli#--maxworkersnumstring
* CI の jest に `-w 1` を設定

test: add maxWorkers option in CI

---

src/components/CheckBoxLabel/CheckBoxLabel.tsx

Replace from `FC` to `VFC` in `CheckBoxLabel`.
* replace `FC`

chore: replace from FC to VFC in CheckBoxLabel (SHRUI-321)

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContent.tsx
src/components/Dialog/ActionDialogContentInner.tsx
src/components/Dialog/Dialog.controllable.stories.tsx
src/components/Dialog/Dialog.tsx
src/components/Dialog/Dialog.uncontrollable.stories.tsx
src/components/Dialog/DialogCloser.tsx
src/components/Dialog/DialogContent.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/DialogPositionProvider.tsx
src/components/Dialog/DialogTrigger.tsx
src/components/Dialog/DialogWrapper.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContent.tsx
src/components/Dialog/MessageDialogContentInner.tsx

Replace from `FC` to `VFC` in `Dialog`.
- replace `FC`
- fix type error
- check presence of `children` props in exported components
- necessary
- `Dialog`
- `ActionDialog`
- `DialogWrapper`
- `DialogTrigger`
- `DialogCloser`
- `DialogContent`
- `ActionDialogContent`
- unnecessary
- `MessageDialog`
- `MessageDialogContent`

chore: replace from FC to VFC in Dialog (SHRUI-321)

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownCloser.tsx
src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownContentInner.tsx
src/components/Dropdown/DropdownScrollArea.tsx
src/components/Dropdown/DropdownTrigger.tsx
src/components/Dropdown/FilterDropdown/FilterDropdown.tsx

Replace from `FC` to `VFC` in `Dropdown`.
- replace `FC`
- fix type error
- check all exported components have `children` props
- `Dropdown`
- `DropdownTrigger`
- `DropdownContent`
- `DropdownCloser`
- `DropdownScrollArea`
- `FilterDropdown`

chore: replace from FC to VFC in Dropdown (SHRUI-321)

---

src/components/Loader/Loader.tsx
src/components/Loader/useClassNames.ts

https://smarthr.atlassian.net/browse/SHRUI-275
improve attributes of  Loader
- Enable to set [default attributes of div element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#attributes) to `Loader` component.
- Add preset className (`'smarthr-ui-Loader'`).

fix: improve attributes of  Loader SHRUI-275

---

src/components/InformationPanel/InformationPanel.tsx

https://smarthr.atlassian.net/browse/SHRUI-222
`InformationPanel` の ARIA を改善します。
- `role=region` に変更
- `role=region` からタイトルを `aria-labelledby` で参照
- 開閉ボタンからコンテンツを `aria-controls` で参照
- コンテンツ部分の `aria-hidden` が表示と乖離しているのを修正
- コンテンツ部分が非表示時にDOMから除去されないように変更

fix: improve ARIA of InformationPanel (SHRUI-222)

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContentInner.tsx
src/components/Dialog/Dialog.stories.tsx

ActoinDialog のボタン上部にレスポンスメッセージを表示したい。
プライマリボタンを押したあとのフィードバックをボタンのすぐ近くで行いたい。
入力要素ごとのメッセージは各入力要素の近くで見ればよい。
https://user-images.githubusercontent.com/19403400/110281694-8beff600-8020-11eb-9fde-eb5c64bf74ee.mp4
レスポンスメッセージを表示するときに「ガタン」が発生する。
以下の代案が考えられるが、一旦このままプロダクトに適用して調整したい。
- プライマリボタンの右横に吹き出し的な UI で表現
- ボタンを中央や左に寄せ、プライマリボタンの右横に構成
- レスポンスメッセージ表示時のみ上部にマイナス margin して調整
- あらかじめメッセージ分余白を取っておく

feat: ActionDialog にレスポンスメッセージエリアを追加

---

src/components/CheckBoxLabel/CheckBoxLabel.stories.tsx
src/components/CheckBoxLabel/CheckBoxLabel.tsx
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap

https://smarthr.atlassian.net/browse/SHRUI-354
Added support for align the opening when multiline text are position in ChekboxLabel.

feat: support multiline text of CheckboxLabel

---

src/components/TabBar/TabItem.tsx
src/components/TabBar/__snapshots__/TabBar.test.tsx.snap

- TabBarのアイテムにfocusしてもoutlineが表示されず、状態がわからないため修正したい
- `outline: none` を削除

fix: TabBar outline style

---

src/components/Textarea/Textarea.tsx

- Textareaにfocusしてもoutlineが表示されず、状態がわからないため修正したい
- `outline: none` を削除

fix: Textarea outline style

---

src/components/Pagination/PaginationItem.tsx

https://smarthr.atlassian.net/browse/SHRUI-299
Currently, the current button of pagenation can be pressed by clicking. So I want to add a disabled attribute so that it cannot be pressed.
Added `disabled` attribute to the current button of pagenation.

fix: add disabled to the current button of pagenation

---

src/components/Table/Cell.tsx
src/components/Table/Row.tsx

- E2E の自動テストを実施する際、独自のデータ属性（ `data-spec` など）を埋め込みたかったのですが、props として受け取れるようになっていなかったので、受け取れるようにし、受け取ったものを return する要素に渡すようにしました。
- 対応したコンポーネント
- `Row`
- `Cell`

chore: pass props to Row and Cell components

---

src/themes/__tests__/createTheme.ts
src/themes/createBreakpoint.ts
src/themes/createFrame.ts
src/themes/createRadius.ts
src/themes/createSize.ts
src/themes/createTheme.ts

この PR では、theme 構造の見直し (#1256) に起因して発生している `createTheme` の問題を修正する。
問題を例示すると、
```typescript
const theme = createTheme({
size: {
space: {
XXS: 10,
},
},
spacing: {
XXS: 20,
},
})
```
とした時、`theme.size.space.XXS` は `10` になるが `theme.spacing.XXS` は `20` となり、どちらを参照しているかによってズレが生じてしまう問題がある。
これを解消するには、上記の例で言えば、`createTheme` 内で引数の `size.space` と `spacing` をマージ（新規の方を優先）して扱う必要があると思われる。そうした場合、 `theme.size.space.XXS` と `theme.spacing.XXS` はどちらも `20` になりズレは発生しなくなる。
- `createTheme` 時に新旧 theme の設定値をマージするように修正
- `lodash` の `merge` によってオブジェクトが破壊されることで既定値が変わってしまう問題を修正
- `createTheme` のテストを追加

fix: fix problem with createTheme

---

.github/workflows/publishRelease.yml
.github/workflows/startRelease.yml
scripts/getLatestChangelog.ts

#1446 
Actions からプレリリースが行えるように、ワークフローを修正します
- リリースモード選択のための入力フィールド追加
- リリースモードによって各処理の分岐
- `getLatestChangelog` 内でプレリリースのヘッダにマッチするように正規表現を修正

chore: enable to prerelease from actions

---

src/components/FlashMessage/FlashMessage.stories.tsx

`FlashMessage` の Story において、画面端に接している部分の影のグラデーションが回帰テストで差分検出されがちなので、コンポーネントが画面端に到達しないように修正。
- Story におけるスタイルの上書き方法を修正

docs: modify overwriting styles in Story of FlashMessage

---

src/components/AccordionPanel/AccordionPanel.stories.tsx
src/components/AccordionPanel/AccordionPanel.tsx
src/components/AccordionPanel/AccordionPanelContent.tsx
src/components/AccordionPanel/AccordionPanelTrigger.tsx
src/components/AccordionPanel/accordionPanelHelper.ts

[WAI-ARIA プラクティス](https://waic.jp/docs/2019/NOTE-wai-aria-practices-1.1-20190207/#accordion)にならい、AccordionPanel のキーボード操作ができるようにした。
- パネルヘッダーボタン（Trigger）を `Heading` で囲い、`headingType` や `headingTag` は外から渡せるようにした
- スペースやエンターでパネルを開閉
- タブでパネルヘッダーおよび開いたパネル内のコントロールにフォーカス
- 矢印キーで同 AccordionPanel 内でヘッダーのフォーカスを移動
- Home / End で最初 / 最後のヘッダーにフォーカスを移動
- `outline: none` をやめる
- `focus` 時にも `hover` と同じスタイルを追加
- `transition` が lazy だったので `0.2s` に変更
- 閉じているパネルは `aria-hidden` ではなく `hidden` にしてキーボード操作不可にした
- Storybook のサンプルでフォーカスの挙動を確認するため FieldSet を追加

AccordionPanel をキーボード操作可能にする

---

src/components/Button/BaseButton.tsx
src/components/CheckBox/CheckBox.tsx
src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
src/components/RadioButton/RadioButton.tsx
src/themes/createColor.ts
src/themes/createPalette.ts
src/themes/createShadow.ts

https://smarthr.atlassian.net/browse/SHRUI-386
[WCAG 2.2の達成基準](https://www.w3.org/TR/WCAG22/#focus-appearance-minimum)を満たしたフォーカスの見た目を新しく作成した。
Create the appearance of a focus that meets the [WCAG 2.2 achievement criteria](https://www.w3.org/TR/WCAG22/#focus-appearance-minimum)
- テーマに定義されている `OUTLINE` の色が淡く、背景色とのコントラスト比が WCAG 2.2 の 2.4.11, 2.4.12 で提案されているフォーカスの見た目の達成基準（ `3:1` OR `4.5:1` ）を満たせていない。
- Google Chrome のデフォルトフォーカスインジケータの青色とテーマの `MAIN` が類似しており、フォーカスインジケータが視認しにくい。
----
- The color of the `OUTLINE` defined in the theme is pale and the contrast ratio with the background color does not meet the criteria for achieving the focus appearance (`3:1` OR `4.5:1`) proposed in WCAG 2.2, 2.4.11 and 2.4.12.
- The blue color of the default focus indicator in Google Chrome and the theme `MAIN` …

New focus appearance

---

src/components/FormGroup/FormGroup.tsx

FormGroup の label が `display: block` なため親要素いっぱいまで影響してしまっていた。
`display: inline-block` を指定して回避する。
また FormGroup の利用状況からコンポーネントは `display: block` の方が扱いやすいため `Wrapper` を噛ませた。

FormGroup における label の影響範囲を狭める

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

https://smarthr.atlassian.net/browse/SHRUI-392
Mobile Safari で Select コンポーネントのアイテム名が表示されない問題を修正したい
- Select.stories.tsx
- label と value の判別がつくように異なる名称にした
- Select.tsx
- option 要素の children にも label を渡すようにした
|Before|After|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5195381/114871469-451dc900-9e34-11eb-93c1-8f8058bcffad.png) | ![image](https://user-images.githubusercontent.com/5195381/114871413-39320700-9e34-11eb-892a-06faa724eb74.png)|

Fix mobile Safari not showing all options for Select component  (SHRUI-392)

---

.github/workflows/publishRelease.yml

自動リリースで PR を作成する際に、 `cherry-pick` でコンフリクトが発生してワークフローが中断する可能性があるため、残作業を最小限にするために PR 作成の step を job の最後尾に移動する
- `cherry-pick` および `create-pull-request` の step を最後尾に移動

chore: move PR creation to the end of publishRelease job

---

src/components/AccordionPanel/AccordionPanelTrigger.tsx
src/components/Base/Base.tsx
src/components/Base/index.ts

The rules for icons representing expansion and collapse are now as follows.
- Put an icon to the left of the trigger's text label.
- Use the caret right icon when target is expanded, and the caret down icon when target is collapsed.
- It is also acceptable to place the icon to the right of the trigger's text label, but in that case, use caret down when the target is open and caret up when it is closed so that the icon does not indicate transition.
- Do not mix icons with different positions in the same page.
展開・折りたたみを表すアイコンのルールは以下の通りとなりました。
- トリガーのテキストラベルの左にアイコンを置いてください。
- ターゲットが展開されているときはcaret_rightを、ターゲットが折りたたまれているときはcaret_downアイコンを使用します。
- アイコンをラベルの右におくこともできますが、その場合はアイコンが遷移を示唆しないようにターゲットが開いているときは caret_down を、閉じているときは caret_up アイコンを利用してください。
- 同じページ内でアイコンの位置が違うものを混在させないでください。
- …

Change caret direction of `<AccordionPanel>`

---

src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
src/components/Dropdown/FilterDropdown/FilterDropdown.tsx

https://smarthr.atlassian.net/browse/SHRUI-366?atlOrigin=eyJpIjoiNzBlMzNjY2QxNjEwNDQ1MTliY2RiYzMzY2NkNjkwZGMiLCJwIjoiaiJ9
FilterDropdown is indicate filtered status with only border color. So users that can’t percept difference color can’t percept FilterDropdown status.
絞り込みされている状態 `isFiltered` を示すのが border の色変更のみとなっており、色が知覚できないユーザーには絞り込み状態を知覚することができない。
- Set `FaFilterIcon` with `FaCheckIcon` when FilterDropdown is filtered.
- Add `hasStatusLabel` for indicate status with text
- Change color that indicate filtered to MAIN color.

Fix indicate `<FilterDropdown>` isFiltered state without color

---

src/components/Button/BaseButton.tsx
src/components/Button/Button.stories.tsx
src/components/Button/DangerButton.tsx
src/components/Button/PrimaryButton.tsx
src/components/Button/SecondaryButton.tsx
src/components/Button/SkeletonButton.tsx
src/components/Button/TextButton.tsx

https://smarthr.atlassian.net/browse/SHRUI-363
Each anchor button in `Button` can not be `disabled`, but it is useful that we can, so this PR enables to be able to make anchor button disabled.
- Make to be able to set `disable` prop to anchor button.
- Modify `href` and `onClick` of `BaseButtonAnchor` not to button operate when button is disabled.
- Add disabled anchor button in Story.

feat: enable to be able to make anchor button disabled (SHRUI-363)

---

src/components/DatePicker/DatePicker.tsx

https://smarthr.atlassian.net/browse/SHRUI-391
The `DatePicker` component is not working on IE11. The reason is that `new DOMRect()` is not supported for IE11.
This PR will modify not to do `new DOMRect()`, and make `DatePicker` can work on IE11.
- Replace blank `DOMRect` to `null`

fix: fix DatePicker for IE11 (SHRUI-391)

---

src/components/Dialog/BodyScrollSuppressor.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/DialogContentInner.tsx

https://smarthr.atlassian.net/browse/SHRUI-380
`Dialog` を開いたとき body のスクロールを抑制するために `overflow: hidden` を設定していますが、 mac などでスクロールバーを常に表示する設定にしている場合、 `overflow: hidden` によりスクロールバーが非表示になることで body の幅が変わり、内側のコンテンツにガタツキが発生してしまいます。
この PR では、スクロールバーが非表示なった分のスペースを `padding` で埋めることで、ガタツキを抑制するように変更します。
修正後の動作については、動作環境の OS で「常にスクロールバーを表示する」設定を行った上で、 `Dialog` の story 内の `Docs` タブにて任意のダイアログを開いたときにガタつかないことで確認できる。
- `Dialog` 表示時に以下の処理を行う `BodyScrollSuppresscor` を追加
- 垂直方向のスクロールバーの幅を検出する
- body の `padding-right` に対して、元々の値と上記の幅を加算した値を設定

fix: improve scroll suppression in Dialog (SHRUI-380)

---

package.json

https://storybook.js.org/docs/react/api/cli-options#build-storybook
SmartHR Team の Netlify の Build budget を使い切りそう。一番 build しているのが smarthr-ui だった。
This month, we will be almost using up the SmartHR Team's Netlify build budget.
smarthr-ui was the project that took the most time to build.
build 時間の短縮化のために `--quiet` オプションを追加
Add `--quiet` option to speed up build time.
```
build-storybook
yarn build-storybook  87.00s user 11.16s system 151% cpu 1:04.99 total
```
```
build-storybook --quiet
yarn build-storybook  44.67s user 7.73s system 151% cpu 34.573 total
```
```
Production: master@fd76aee
4m18s
```
```
Deploy Preview #1548: chore/build-storybook-quiet@98bfd89
1m45s
```

Add quiet option for build storybook

---

src/components/CompactInformationPanel/CompactInformationPanel.tsx

- https://smarthr.atlassian.net/browse/SHRUI-400
- CompactInformationPanelのbox-shadowをDIALOG（`rgba(51, 51, 51, 0.3) 0 4px 10px 0`）に設定します。
- CompactInformationPanelのbox-shadowが適切ではなかったため、正しい値を設定した。
- 修正前：設定なし（デフォルトの`BASE`）
- 修正後：`DIALOG`

fix: set DIALOG shadow to CompactInformationPanel (SHRUI-400)

---

src/components/BackgroundJobsPanel/BackgroundJobsPanel.tsx
src/components/FlashMessage/FlashMessage.tsx
src/components/RightFixedNote/RightFixedNote.stories.tsx

- https://smarthr.atlassian.net/browse/SHRUI-408
- https://smarthr.atlassian.net/browse/SHRUI-402
- https://waic.jp/docs/UNDERSTANDING-WCAG20/text-equiv-all.html
- https://waic.jp/docs/WCAG21/Understanding/name-role-value.html
- Add alternative text to Icon in button
- Change alternative text of BackgroundJobPanel to Japanese

Add accessible name [SHRUI-402] [SHRUI-408]

---

src/components/Dialog/ActionDialogContentInner.tsx

ActionButton の下に余計な余白が入っていた。
これが | こう
--- | ---

fix: ActionDialog のレスポンスメッセージがない時に余計な余白が出ている

---

src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.test.tsx
src/components/Icon/Icon.tsx
src/components/Icon/__snapshots__/Icon.test.tsx.snap

- `<svg>` should have `aria-hidden` when has alternative text by `visuallyHiddenText` props.
- Add snapshot testing for Icon component
- If the icon has visuallyHiddenText, set true to aria-hidden.

Fix Icon components aria

---

src/themes/__tests__/createFontSize.ts
src/themes/__tests__/createTheme.ts
src/themes/createFontSize.ts

調和数列を元にした新フォントサイズを追加しました。
SHORT / TALL / GRANDE / VENTI を `@deprecated` にしました。
このプルリクでは既存コンポーネントの修正は行なっていないため、影響はありません。
#1545 のマージ後に作業予定です。

新フォントサイズを定義

---

src/components/Icon/Icon.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-397
I want to change Icon's storybook from `div> div` to `dl > dt + dd`
- Change Icon's storybook from `div> div` to `dl > dt + dd`
| BEFORE  | AFTER  |
| ---- | ---- |
|  ![image](https://user-images.githubusercontent.com/23610884/118248634-81018800-b4df-11eb-8951-a1e695e82118.png) |![image](https://user-images.githubusercontent.com/23610884/118252920-464e1e80-b4e4-11eb-8184-067bb8e003cb.png)|

fix: change icon storybook from div to dl

---

src/components/Text/README.md
src/components/Text/Text.stories.tsx
src/components/Text/Text.tsx
src/components/Text/index.ts
src/index.ts
src/themes/__tests__/createLeading.ts
src/themes/__tests__/createTheme.ts
src/themes/createColor.ts
src/themes/createFontSize.ts
src/themes/createLeading.ts
src/themes/createTheme.ts

文字にまつわるスタイリングを管理するテキストコンポーネントを作成。
渡せるプロパティは下記の通り。
プロパティ | 対象 CSS プロパティ | 備考
--- | --- | ---
size | font-size | XXS / XS / S / M / L / XL / XXL
weight | font-weight | normal / bold
italic | font-style: italic | -
color | color | TEXT_BLACK / TEXT_GREY / TEXT_LINK / TEXT_DISABLED / inherit
leading | line-height | NORMAL / TIGHT / RELAXED / NONE
emphasis | - | em 要素として出力
as | - | 渡した要素として出力
as に渡せる要素
---
Text コンポーネントとして使う可能性があるものをフローコンテンツと記述コンテンツから選択肢、ホワイトリストとしました。
- `<address>`
- `<b>`
- `<em>`
- `<i>`
- `<mark>`
- `<p>`
- `<q>`
- `<small>`
- `<span>`
- `<strong>`
- `<time>`
as に渡せてもよさそうだけど除外した要素
---
局所的なマークアップであってり、代替コンポーネントが存在するため以下の要素は除外しました。
- `<abbr>`
- `<bdi>`
- `<blockquote>`
- `<button>`
- `<cite>`
- `<code>`
- `<data>`
- `<del>`
- `<dfn>`
- `<h1>`
- `<h2>`
- `<h3>`
- `<h4>`
- …

テキストコンポーネントを追加

---

src/components/FlashMessage/FlashMessage.stories.tsx
src/components/FlashMessage/FlashMessage.tsx
src/components/FlashMessage/FlashMessageList/FlashMessageList.tsx
src/components/FlashMessage/FlashMessageList/FlashMessageListProvider.tsx
src/components/FlashMessage/FlashMessageList/Item.tsx
src/components/FlashMessage/FlashMessageList/README.md
src/components/FlashMessage/FlashMessageList/useFlashMessageList.tsx
src/components/FlashMessage/index.ts
src/index.ts

https://smarthr.atlassian.net/browse/SHRUI-374
`FlashMeesage` の複数表示を制御する `FlashMessageList` を追加します。
使い方は、まず複数 `FlashMessage` を表示させたい場所の上層を `FlashMessageListProvider` で wrap します。
```tsx
import { FlashMessageListProvider } from 'smarthr-ui'
<FlashMessageListProvider>
<MyComponent />
</FlashMessageListProvider>
```
次に、 wrap した配下で `useFlashMessageList` hook を用いてメッセージを追加すると、メッセージが順次スタック表示されます。
```ts
import { useFlashMessageList } from 'smarthr-ui'
const MyComponent = () => {
const { enqueueMessage } = useFlashMessageList()
const handleClick = () => {
enqueueMessage({
type: 'success',
text: `success`,
})
}
return <button onClick={handleClick}>Add message</button>
}
```
表示されたあとのメッセージを消す処理は内部で完結させていて、組み込み時に改めて制御を記述する必要はありません。
- `FlashMessageList` の構成要素の追加
- `FlashMessage` が timeoutID …

feat: add FlashMessageList

---

src/components/ComboBox/SingleComboBox.tsx

master への反映: #1585 
プレリリース v12.4.0-1 に対する hotfix です。
`SingleComboBox` の `width` prop に `100%` を指定するとその値は内部の input 要素の`width` にセットされますが、 wrapper が `inline-block` かつ `width: auto` であることに起因して幅が正しく広がらない問題を解消します。
修正によって `width` prop の値は wrapper の `width` に作用するようになり、内部の input 要素のサイズは常に wrapper に合わせることで正しく幅が制御できるようになります。

fix (hotfix): modify SingleComboBox to be expected width when set percentage width

---

src/components/ComboBox/ComboBox.stories.tsx
src/components/ComboBox/MultiComboBox.tsx

https://smarthr.atlassian.net/browse/SHRUI-390
- Disable selected items when MultiComboBox is disabled.

fix: Disable selected items when MultiComboBox is disabled

---

src/components/MessageScreen/MessageScreen.tsx

Replace from `FC` to `VFC` in `MessageScreen`
- Replace `FC`
- Add necessary `children` props

chore: replace from VFC to FC in MessageScreen

---

src/components/Select/Select.tsx

Replace from `FC` to `VFC` in `Select`
- Remove `children` from `Select` props because this component should not be passed children and `SelectHTMLAttributes<HTMLSelectElement>` type contains `children`.

chore: replace from FC to VFC in `Select`

---

src/components/TabBar/TabBar.tsx
src/components/TabBar/TabItem.tsx

Replace from `FC` to `VFC` in `TabBar`

chore: replace from FC to VFC in `TabBar`

---

src/components/Table/Body.tsx
src/components/Table/Cell.tsx
src/components/Table/Head.tsx
src/components/Table/Row.tsx
src/components/Table/Table.tsx

Replace from `FC` to `VFC` in `Table`
- Modify `Body` props to `HTMLTableSectionElement`.

chore: replace from FC to VFC in `Table`

---

src/hooks/useId.tsx
src/hooks/usePortal.tsx

Replace from `FC` to `VFC` in hooks.
- Replace to `VFC` in:
- `useId` hook
- `usePortal` hook

chore: replace from FC to VFC in hooks

---

src/components/FieldSet/FieldSet.tsx

https://smarthr.atlassian.net/browse/SHRUI-396
Now use FormGroup component instead of FieldSet component.
So deprecate FieldSet component.
deprecate FieldSet component.
🍐

feat: deprecate FieldSet component

---

src/components/Input/Input.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-425
- Inputで使われているprefix,suffixアイコンの色が実際のプロダクトで使う色と合ってない
- BORDERからTEXT_GREYに変更する

feat: fix input prefix/suffix icons color in storybook

---

src/components/RadioButton/RadioButton.tsx
src/components/RadioButtonLabel/RadioButtonLabel.tsx

- https://smarthr.atlassian.net/browse/SHRUI-378
- https://github.com/kufu/smarthr-ui/pull/1592
- ☝️ これを今後 RadioButton と RadioButtonLabel の代わりに使う
詳細は上記 PR をご確認ください 🙏

feat: deprecate RadioButton and RadioButtonLabel

---

src/components/MessageScreen/MessageScreen.tsx
src/components/MessageScreen/useClassNames.ts

https://smarthr.atlassian.net/browse/SHRUI-276
`MessageScreen` の属性に関する改善を行います。
- 各パーツ
- logo
- title
- content
- linkList
- footer
- このコンポーネントの最外の要素である div のデフォルト属性を渡せるように修正

feat: `MessageScreen` の属性の改善 (SHRUI-276)

---

src/components/CompactInformationPanel/CompactInformationPanel.tsx

https://smarthr.atlassian.net/browse/SHRUI-416
CompactInformationPanel が className props を公開しておらず、 styled-components による拡張ができない状態だったので追加したい。
className props を追加
🍐

fix: CompactInformationPanel に className を渡せるようにする

---

src/components/Icon/Icon.stories.tsx

アイコン一覧 story の DOM 構造が
```html
<dl>
<dt>アイコン名</dt>
<dd>アイコン</dd>
</dl>
<dl>
<dt>アイコン名</dt>
<dd>アイコン</dd>
</dl>
...
```
となっていたので、以下のように修正します。
```html
<dl>
<div>
<dt>アイコン名</dt>
<dd>アイコン</dd>
</div>
<div>
<dt>アイコン名</dt>
<dd>アイコン</dd>
</div>
...
</dl>
```
- アイコン一覧 story の DOM 構造変更

docs: アイコン一覧 story の DOM 構造修正

---

src/components/ComboBox/MultiComboBox.tsx

https://smarthr.atlassian.net/browse/SHRUI-410
MultiCombobox の項目削除ボタンのラベルが delete のみで、どの項目を削除するかがわかりにくい。（特に入力後に、DOM 順をさかのぼった場合） 
ラベルに項目名を含むことで対象を明確にしたい。
項目削除のボタンのラベルを `${項目名}を削除` に変更。
なし

fix: MultiComboBox の項目削除ボタンのアイコンの visuallyHiddenText に項目名を含める

---

src/components/Dialog/DialogContentInner.tsx

#1514 で Inner にあたっていた `className` が Wrapper に移動し、既存アプリケーションに影響を与えていたので修正。
コンポーネントとして Dialog の実態は Wrapper ではなく Inner なので想像する使用感とも合致しそう。
https://github.com/kufu/smarthr-ui/commit/93a345d5dcb2a00e0b65cd5281cfff47147031f2#diff-23541497bd86a5f30d84af5daeff6522a804e0dab196d2ce0d3742002742011aR128-R142
Story で ```const MessageDiaglo = styled(shrMessageDialog)`` ``` として確認済み。

fix: DialogContentInner の className が Wrraper にあたっていたのを Inner に戻す

---

src/components/LineClamp/LineClamp.stories.tsx
src/components/LineClamp/LineClamp.tsx
src/components/LineClamp/README.md
src/components/LineClamp/index.ts
src/components/LineClamp/useClassNames.ts
src/components/MessageScreen/README.md
src/index.ts

- https://smarthr.atlassian.net/browse/SHRUI-413
- 複数行を省略表示しつつ、省略されたテキストをToolTipで表示できるコンポーネント
- Tooltipがdivタグで生成されるため、テキストが h*タグ及びpタグの場合、p > div の構造となり、warning が出力されますが、別チケットでの対応とします
- LineClamp コンポーネントの追加

`LineClamp` Component SHRUI-413

---

src/components/Text/Text.stories.tsx
src/components/Text/Text.tsx

Text コンポーネントで `white-space` を扱えるようにしました。

feat: Text コンポーネントに whiteSpace を追加 | SHRUI-429

---

.github/workflows/e2e.yml

Github Actions で設定している e2e は storybook が正しく起動できなかった場合などに最大6時間回ってしまうので、30分でタイムアウトするように変更します。
- `timeout-minutes` を設定

chore: e2e にタイムアウトを追加

---

src/components/Tooltip/Tooltip.tsx

tabIndex が固定で 0、かつ `{...props}` より後ろに記述があるため、利用側で上書きできない。

fix: Tooltip の tabIndex を利用側で上書きできないので修正

---

src/components/Dialog/ActionDialogContentInner.tsx

`ActionDialog` にて、 `styled-components` を動的に作成することによる warning が発生しているのを解消します。
- `styled-components` を動的に生成している部分を外出ししました
- `ResponseMessage` の部分がコンポーネントである必要があまりなかったので JSX に展開しました

fix: `ActionDialog` の warning 解消

---

src/components/Balloon/Balloon.tsx

Ballon の Wrapper に対して `as` で `span` を渡せるように修正。

Baloon に span を渡せるように修正 | SHRUI-433

---

src/components/SegmentedControl/SegmentedControl.tsx

https://smarthr.atlassian.net/browse/SHRUI-426
`SegmentedControl` のフォーカスインジケータが兄弟要素によって隠れないように修正します。
- `theme.shadow.focusIndicatorStyles` を適用
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/124545844-ae760c80-de64-11eb-8e00-b487f416ba1f.png) | ![image](https://user-images.githubusercontent.com/270422/124545805-9ef6c380-de64-11eb-875f-f9916a03b09b.png) |

fix: `SegmentedControl` のフォーカスインジケータが兄弟要素に隠れないように修正 (SHRUI-426)

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

https://smarthr.atlassian.net/browse/SHRUI-425
`Input` の prefix / suffix にアイコンを配置する場合のデフォルトカラーを規定します。
- prefix / suffix の wrapper に `color` スタイルに `TEXT_GREY` を設定

fix: `Input` の affix にデフォルトカラーを設定 (SHRUI-425)

---

src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/SingleComboBox.tsx

https://smarthr.atlassian.net/browse/SHRUI-432
コンボボックスが持っている `onChange` ハンドラは、意味としては「テキストボックスの変更のハンドラ」であり誤解を招きやすいので、 `onChangeInput` にリネームして `onChange` は deprecated にする
- `onChangeInput` を追加
- `onChange` を deprecated に

fix: コンボボックスの `onChange` ハンドラをリネーム (SHRUI-432)

---

src/components/TextLink/TextLink.tsx

LineUp を使って
- inline で inline-flex に
- vAlign で align-items: center
- as で span
にしている。
また、SmartHR Design System を参考に余白を変更した。
https://smarthr.design/products/design-guide/spacing-layout-pattern/#%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%EF%BC%88Icon%EF%BC%89%E3%82%84%E3%83%A9%E3%83%99%E3%83%AB%EF%BC%88Label%EF%BC%89%E3%81%AA%E3%81%A9%E3%81%AE%E5%B0%8F%E3%81%95%E3%81%84%E8%A6%81%E7%B4%A0%E9%96%93

TextLink の縦位置を中央合わせに修正

---

.circleci/config.yml

https://smarthr.atlassian.net/browse/SHRUI-418
CI で node のバージョンごとに行っている処理の内、 lint と yarn audit はバージョンごとに実行する必要がないため、一度だけ実行されるように変更します。実行する node バージョンは `.node-version` 似合わせて v14 としました。
この変更で CI 内の  node v10 の処理時間が約20秒短縮されますが、並列で実行されるジョブの中で最も時間のかかる reg-suit の処理時間は変わらないため、 CI 全体が完了するまでの時間に変化はほぼ無いと思われます。
- lint と yarn audit が node v14 でだけ実行されるように変更

test: CI のタスク最適化 (SHRUI-418)

---

src/components/Layout/Stack/Stack.tsx

インライン要素として振る舞いたい時もあるため、inline を渡せば inline-flex になるようにしました。
as に依って切り替えることも考えましたが、要素の種類とブロック / インライン要素の振る舞いは別なため inline を明示的に渡す形になっています。
LineUp と同じ I/F です。

Stack をインライン要素のように振る舞えるように inline を追加｜SHRUI-448

---

.circleci/config.yml

org レベルで環境変数を管理できるようになったらしいので、そちらに移行します。
[この記事のリンク](https://smarthr-inc.docbase.io/posts/1986993#circleci-%E3%81%AE-contexts-%E3%81%AE%E3%82%B9%E3%82%B9%E3%83%A1-tknzk) (社内のみ)
現在、リポジトリの範囲で CIrcleCI の環境変数を設定しているが、 org の値を使うようにする。
Context を追加。
この PR をマージ後、 CircleCI 上の smarthr-ui リポジトリの環境変数を削除します。

test: use circleci contexts

---

.storybook/main.js
.storybook/preview.js

storybook において controls addon を `controls: { disable: true }` で無効化していると hooks の呼び出し順序に関する warning が出るバグが発生しているので、 controls addon の無効化の指定方法を変更します。
- controls addon の無効化方法を変更

chore: storybook 起因の warning の解消

---

src/components/DatePicker/README.md

DatePickerのREADMEを読んでいたらtypoを発見しました。
* DatePickerのREADME内、 `formatDate` オプションの `Description` で、 `displa` → `display` に変更。

docs: DatePickerのREADMEのtypo修正

---

src/components/Layout/Stack/Stack.tsx

Stack したいけど flex アイテムを `stretch` にはしたくない場合があるので、align-items を align として渡せるようにしました。
（display: flex 時の align-items のデフォルトは normal で、これは内部的に stretch 扱いになります）
align の名前は LineUp と I/F を合わせています。

Stack に align を追加

---

src/components/TextLink/TextLink.tsx

別プロジェクトでアイコンにも下線を引くため `box-shadow` に依る装飾を試している。
折返しの発生する文字列がきた場合に、LineUp が `inline-flex` なため下線が一部にしか適用されないため、prefix / suffix を含まない場合は LineUp で囲むのをやめたい。
参考： https://codepen.io/uknmr/pen/yLboRwV

TextLink に prefix/suffix を含まない場合はレイアウトコンポーネントを使わない

---

src/components/Calendar/Calendar.tsx

年選択ボタンの位置に依ってイベントが伝播し、予期しない動作を生む。
Event. stopPropagation() でイベントの伝播を阻止する。

Calendar の年選択ボタンのイベント伝播を阻止する

---

src/components/Base/Base.stories.tsx
src/components/Base/Base.tsx
src/components/Base/DialogBase.tsx

https://smarthr.atlassian.net/browse/SHRUI-431
- Baseコンポーネントのbox-shadowをオーバーライド可能にする
- DialogBaseをdeprecated化する

Baseのbox-shadowをオーバーライド可能にする SHRUI-431

---

src/components/FloatArea/FloatArea.tsx

reg-suit の差分が今回の修正分です。エラーメッセージの margin を消し込みました。

fix: FloatArea エラーメッセージの余分な余白を取り除く

---

src/components/AccordionPanel/AccordionPanelTrigger.tsx

https://smarthr.atlassian.net/browse/SHRUI-443
`AccordionPanel` はこのコンポーネント自体を角丸にする責務を負っていないので、アウトラインを角丸にする処理を外します。
- アウトラインを角丸にするスタイルを削除

chore: `AccordionPanel` のアウトラインを角丸にしないように変更

---

src/themes/__tests__/createSpacing.ts
src/themes/createSpacing.ts

Layout コンポーネントで 0 を利用したことがあるので、余白トークンに 0 を追加しました。
プリミティブトークンは 0、抽象トークンは `ZERO: 0` にしました。

余白トークンに 0 を追加

---

.github/workflows/e2e.yml

`node_modules` をキャッシュするのは推奨されないようなので、 yarn のキャッシュをキャッシュするように変更します。
参考: https://github.com/actions/cache/blob/main/examples.md#node---npm
- e2e ワークフローのキャッシュ対象を変更

chore: e2e ワークフローのキャッシュ対象を変更

---

scripts/e2e.ts

現状、e2e テスト実行時に storybook のビルドに失敗してもプロセスが終了せず残り続けるため、プロセスがエラー終了するように修正します。
- ビルド失敗時に `exit(1)` するように修正

chore: e2e で storybook のビルドに失敗した時にプロセスが終了するように変更

---

src/components/ComboBox/ComboBox.stories.tsx
src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/SingleComboBox.tsx

https://smarthr.atlassian.net/browse/SHRUI-436
`SingleComboBox`, `MultiComboBox` に対して、選択値の変更を監視するハンドラとして `onChangeSelected` を追加します。また同時に、組み込み側でハンドリング方法を選べるようにするために、既存の `onSelect`, `onDelete` ハンドラを optional に変更します。
- `SingleComboBox`
- `onChangeSelected` を追加
- `onSelect` を optional に変更
- `MultiComboBox`
- `onChangeSelected` を追加
- `onSelect`, `onDelete` を optional に変更

feat: コンボボックスに `onChangeSelected` を追加 (SHRUI-436)

---

src/components/Layout/Cluster/Cluster.stories.tsx
src/components/Layout/Cluster/Cluster.tsx

- [Clusterに水平方向と垂直方向で別々の余白を定義したい - SmartHR JIRA](https://smarthr.atlassian.net/browse/SHRUI-470)
Make Cluster component possible to set the vertical and horizontal margins.
- add `rowGap`/`columnGap` property to `<Cluster>` component.
- prioritize rowGap or columnGap over gap if available.

`<Cluster>` に水平方向と垂直方向で別々の余白を定義できるようにする

---

src/components/AccordionPanel/AccordionPanel.stories.tsx

`AccordionPanel` の story 内で `storyOf` と CSF を併用してしまっていることでエラーが発生しているので、 CSF 方式に統一します。
- `AccordionPanel` の story を `storyOf` から CSF に変更

docs: `AccordionPanel` の story を CSF に変更

---

.github/CODEOWNERS

なし
- レビューが滞る問題があった
- 現状のレビュワーはフロントエンドエンジニアの中からランダムでアサインされる状態
- 特にメンバーに確認なく、フロントエンドとして入社するとレビュワーになっちゃっている
- 実装と同じでレビュワーも有志の方が良いよね
レビュワーにアサインされる対象をグループから人に変更。
この記述で動くか若干の不安があるのですがまあ一度入れてみてからで…。
なし

chore: レビュワーにアサインされる対象をグループから人指定に変更

---

.github/CODEOWNERS

なし
- この PR https://github.com/kufu/smarthr-ui/pull/1862 で人指定に変更したが、このやり方だと 2 assign で round robin という設定ができない
- なので新しいグループを作って運用という形にしたい
- 2人とか round robin みたいなのはグループに紐づく設定
- グループに @wmoai san を追加するのは権限的にできない
- ここは一旦置いておいてもう少し考えます
- 試しに CODEOWNERS に @wmoai san を追加してみました
- こうなるとレビュワーがどうアサインされるかは試してみないとわからない…
設定変更しました。
メンバー
設定
なし

chore: レビュワーにアサインされる対象を人からグループ指定に変更

---

src/components/Icon/Icon.tsx

非推奨だった `Icon` コンポーネントは既に削除されているため、 `Icon` コンポーネントのために処理を分割していた `IconComponent` を `createIcon` 内にインライン化します。
- `IconComponent` の処理を `createIcon` 内にインライン化
- diff が分かりにくいですが、`IconComponent` の VFC を `createIcon` 内で定義している `Icon` に移動させ、 VFC 内で `Component` を参照している部分を `SvgIcon` に置き換えただけです。

refactor: IconComponent の処理をインライン化

---

src/components/ComboBox/SingleComboBox.tsx

`clear`ボタンに`type`がないので`submit`が動いてしまいます。`submit`しないように`type`を`button`で追加します
`SIngleComboBox`の`clear`ボタンに`type`を追加しました。

SIngleComboBoxのclearボタンにtypeを追加したい

---

src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/DialogOverlap.tsx
src/components/Dialog/DialogTransition.tsx
src/components/Dialog/ModelessDialog.tsx

`v14.3.0` において、ダイアログの開閉アニメーション時にダイアログの後ろ側に表示されるべき要素が前側に表示されることによりチラつきが発生する問題が生じています。
<details>
<summary>再現</summary>
</details>
ダイアログのアニメーション部分の DOM 構造を変更したことに起因して、ダイアログの z-index を設定する層より `CSSTransition` を設定する層の方が親に変わっていました。 `CSSTransition` の層では `opacity` の設定によりダイアログ開閉時のアニメーションを表現していますが、アニメーション時に `opacity` が設定されることにより低いスタッキングコンテキストが発生しそちらが優先されてしまうため、結果として他の `z-index: 1` 以上を持つ要素のスタッキングコンテキストに負けてしまうことにより、アニメーションの間だけそれらの要素が前面に表示されるためチラつきが発生するようでした。
`CSSTransition` を設定する要素に `z-index` を設定し、 `opacity` 設定により低いスタッキングコンテキストが生成されないように変更します。
- `DialogTransition` コンポーネントに z-index: OVERLAP_BASE を設定
- `DialogTransition` コンポーネントが重なりの責務を持つのは違和感があるため、命名を `DialogOverlap` に変更し、重なりの責務を主にしつつアニメーションの責務を兼務させる意味合いに変更
- 一部 deprecated なコンポーネントを使用している部分を修正
<details>
<summary>修正後</summary>
</details>

fix: ダイアログがアニメーション中に低いスタッキングコンテキストにならないように修正

---

src/components/Layout/Cluster/Cluster.tsx
src/components/Layout/Sidebar/README.md
src/components/Layout/Sidebar/Sidebar.stories.tsx
src/components/Layout/Sidebar/Sidebar.tsx
src/components/Layout/Sidebar/index.ts
src/components/Layout/index.ts
src/components/Layout/type.ts

- [The Sidebar: Every Layout](https://every-layout.dev/layouts/sidebar/)
add `<Sidebar>` component via Every Layout The Sidebar
- add Layout `Gap` type
- add `<Sidebar>` component
[📕 Sidebar Story](https://deploy-preview-1888--smarthr-ui.netlify.app/?path=/story/sidebar--default)

add `<Sidebar>` Component

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/Dialog.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/ModelessDialog.tsx

決め打ちで `document.body` に生える各種ダイアログにポータルの親要素として `portalParent: HTMLElement` を渡せるようにしました。
デフォルトは `document.body` なので、今までと挙動は変わりません。
ちなみに [Fullscreen API](https://developer.mozilla.org/ja/docs/Web/API/Fullscreen_API) を使うにあたって、特定の要素をフルスクリーンにし、かつフルスクリーン内でダイアログを出したい場合に、`body` 直下では実現が面倒なのが発端です。

feat: 各種 Dialog を body 直下以外からも生成できるようにする｜SHRUI-474

---

.circleci/config.yml
package.json
scripts/e2e.ts
yarn.lock

#1808 
#1853 
`reg-suit` を CI で実行するための docker image `regviz/node-xcb` の node のバージョンが古い問題に対処します。
docker image を新しく作って docker hub に上げることは出来ますが、そうするとその image を保守する必要が出てきてしまいます。そこで、 image は Circle CI 公式の `circleci/node:14` ものを使いつつ、ジョブ内で必要な依存を追加する方法を試しました。
インストール分だけ実行時間が増えてしまうと予想していましたが、結果として image を準備する時間が `circleci/node:14` の方が早いため、掛かる時間は差し引きゼロという感じで、問題なさそうです。
`wait-for-localhost` のバージョンが上がると ESM になるため発生しますが、そもそも `wait-for-localhost` が無くても e2e は動くようなので削除しました。おそらく、 `testcafe` がいい感じに待ってくれているものと思われます。
- e2e の CI の image を `circleci/node:14` に変更して、必要な依存をインストールするように変更
- e2e の CI のキャッシュ対象を変更
- e2e のスクリプトから `wait-for-localhost` を削除

chore: reg と e2e の CI 改善

---

src/components/Button/BaseButton.tsx
src/components/Button/Button.stories.tsx
src/components/Button/DangerButton.tsx
src/components/Button/PrimaryButton.tsx
src/components/Button/SecondaryButton.tsx
src/components/Button/SkeletonButton.tsx
src/components/Button/TextButton.tsx
src/components/Pagination/PaginationItem.tsx

https://smarthr.atlassian.net/browse/SHRUI-427
ボタンの height が固定指定になっていたので、font-size * line-height + padding + border の積み上げでサイズが定まるようにしました。
[SmartHR のデザイン基本原則](https://smarthr.design/foundations/) と照らし合わせたときに、無駄なアニメーションはない方が SmartHR らしいと判断しました。
参考： https://kufuinc.slack.com/archives/CGC58MW01/p1632449933127300
- Primary / Secondary に border 分の高さがなかったので追加
- Button は複数行を想定しないため `line-height: 1` としました
- 全体的に CSS を見直しました
以下は Chrome でのサイズです。ブラウザに依って計算値の丸め方が異なるので誤差あります。
（Chrome は 2021-09-25 現在 line-height 計算後の高さにおいて小数点を切り捨てるため、小サイズの Button でアイコンのあるなしで高さが異なります）
\- | 既存 | 修正後
--- | --- | ---
`.default` | 40px or 42px | 42px
`.s` | 27px | 31.7px
`.square` | 40px or 42px | 42px
`.square.s` | 27px | 31.7px

feat!: Button の width / height の固定値をやめる｜SHRUI-427 

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/MessageDialog.tsx

Dialogのaria-labelがsubtitleとtitleから自動生成されているが、subtilte未指定の場合、`undefined タイトル` のように崩れてしまう。
falsyの場合の条件分岐を追加したい

fix: Dialogのsubtitle未指定の場合のaria-labelを調整する

---

src/components/Input/Input.tsx

申し訳ない!
Input の改修に依ってずれていました。
before | after
--- | ---

fix: SingleCombobox の削除ボタンが Input の suffix を使っていたため、縦位置がずれていたので修正

---

src/components/ComboBox/SingleComboBox.tsx

- https://smarthr.atlassian.net/browse/SHRUI-477
SingleComboboxの値を変更しようとするとき、オプションが現在の値でフィルタリングされ、他のオプションが表示されない問題があった。編集中の状態を追加し、編集している時のみオプションのフィルタリングをするようにした。
When trying to change the value of a SingleCombobox, the options would be filtered by the current value and other options would not be displayed. Added editing state, so that options are filtered only when editing.
- add `isEditing` state
- return all items when is not editing
- start isEditing when fire `onChange`
- end isEditing, when fire `onSelect` and `onBlur`
https://deploy-preview-1922--smarthr-ui.netlify.app/?path=/story/combobox--single
<details open>
<summary>Demo animation gif</summary>
</details>

fix: display all items when refocus SingleCombobox 

---

.github/workflows/titleCheck.yml

PR タイトルが Conventional Commits 形式になっているかをチェックする GitHub Actions ワークフローを追加しました。
チェックする内容は
- 規定された接頭辞
- BREAKING CHANGE を表す `!` の有無を許容
- `(deps)` のような括弧書きの許容
- コロン + スペース + タイトル本文
- `titleCheck` ワークフローを追加

chore: PR タイトル形式をチェックするワークフローを追加

---

src/components/SegmentedControl/SegmentedControl.tsx

ボタン同士を重ねるために border を消していたので、negative margin で対応。
合わせて冗長な記述を消しました。
reg-suit の差分出ているが、問題はなさそう。

fix: SegmentedControl の border が消えているので修正

---

src/components/ComboBox/MultiSelectedItemInner.tsx

IE において、`MultiComboBox` の選択済みアイテムが flex ショートハンド起因でスタイル崩れを起こしていたので修正します。
- flex ショートハンドを省略せずに記述
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/135587476-c01c3666-6163-49dc-b0f3-9a25a34e9875.png) | ![image](https://user-images.githubusercontent.com/270422/135587369-39c7b892-122d-4351-8309-4ac1b0090ca2.png) |

fix: `MultiComboBox` のスタイル崩れ修正

---

src/components/TextLink/TextLink.stories.tsx
src/components/TextLink/TextLink.tsx

https://smarthr.atlassian.net/browse/SHRUI-481
LineUp つかった flexbox にしたため発生した :bug: でした:pray:
ついでに下線を box-shadow に変え、アイコンの下にも引かれるようにしました。
（`text-decoration: none` のリセットしてるプロジェクトは `box-shadow: none` に変える必要があります）

feat: TextLink の折返しに対応し、Affix にも下線を引く｜SHRUI-481

---

src/components/AppNavi/AppNavi.stories.tsx
src/components/AppNavi/AppNavi.tsx
src/components/AppNavi/AppNaviAnchor.tsx
src/components/AppNavi/AppNaviButton.tsx
src/components/AppNavi/AppNaviCustomTag.tsx
src/components/AppNavi/AppNaviDropdown.tsx

`AppNavi` の storybook の形式を CSF に変更し、 DocPage を有効にします。
- story を CSF 形式に変更
- Props の説明を追加
- 一部外側に晒す必要のない props を InnerProps に移動

docs: `AppNavi` の story 整備 (SHRUI-464)

---

src/components/FormGroup/FormGroup.stories.tsx
src/components/FormGroup/FormGroup.tsx

https://smarthr.atlassian.net/browse/SHRUI-482
`FormGroup` コンポーネントは子の状態によってはグループとして表現したい場合があるため、グループとして表現できる手段を提供します。
- `FormGroup` に対して、要素のデフォルトの属性を渡せるように変更
- `role` を渡せるようになるので、 `role=group` でグループとして表現できるようになる
- デフォルト属性の内 `aria-labelledby` だけは下記との兼ね合いで対象外とした
- `role=group` が設定された時、タイトル部分の要素を `aria-labelledby` で参照するように変更

fix: `FormGroup` がグループであることを示せるように変更 (SHRUI-482)

---

src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/SingleComboBox.tsx
src/components/DatePicker/DatePicker.tsx
src/components/Select/Select.tsx

- https://kufuinc.slack.com/archives/CGC58MW01/p1634686160240700
- プロポーザル的なPR
- Comboboxのキャレットが、デフォルト`BORDER`カラーとなっており、`disabled`とも取れる色になっていた
- 有効であるということを、もっと視覚的にわかるようにしたい
- DatePicker, Selectも同じようなスタイルに合わせたい
- ComboBoxのキャレットのデフォルトカラーを`TEXT_GRAY`に変更
- active、disabled時のカラーは据え置き
| Before | After |
|:------:|:------:|
| <img width="431" alt="CleanShot 2021-10-20 at 13 47 04@2x" src="https://user-images.githubusercontent.com/4032232/138029909-44bd225a-fc80-4b52-86ea-c9040a45e835.png"> | <img width="425" alt="CleanShot 2021-10-20 at 13 46 10@2x" src="https://user-images.githubusercontent.com/4032232/138029817-96fa0d8e-aee8-41b9-b417-c36636270263.png"> |
| Before | After |
|:------:|:------:|
| <img width="354" alt="CleanShot 2021-10-20 at 18 36 27@2x" …

feat: ComboBox・DatePicker・Selectのキャレットの色を変更・統一

---

src/components/ComboBox/SingleComboBox.tsx

- `onBlur` で `isEditing` を `false` にしていた
- Listboxをクリックしたタイミングで、`<StyledInput>` の `onBlur` が走り、`state` が変わり再レンダリングされるため意図しない挙動を起こしていた
- `useOuterClick` 時の `blur()` で `state` をセット
<details open>
<summary>before</summary>
</details>
<details open>
<summary>after</summary>
</details>

fix: SingleComboboxで絞り込んだアイテムが選択できないのを修正

---

src/components/MessageScreen/MessageScreen.stories.tsx
src/components/MessageScreen/MessageScreen.tsx

https://smarthr.atlassian.net/browse/SHRUI-368
MessageScreen のリンクがリンクであることが文字色でしか判別できないため、下線を引きます。
背景色（BACKGROUND）の上にある青文字はコントラスト比 4.5:1 を担保できないが周囲の文字とのコントラスト比や下線に依る資格示唆で判別できるため、色はそのままとした。
SmartHR UI の TextLink で置き換えました。
これが | こう
--- | ---

fix: MessageScreen のリンクに下線を引く｜SHRUI-368

---

.github/workflows/startRelease.yml

GitHub Actions の手動トリガの入力フォームに新しいタイプが追加されたので、適用します。
- リリース開始ワークフローの入力フォームをチェックボックスに置き換え

chore: 自動リリースに新しい入力タイプを適用

---

src/components/Calendar/CalendarTable.tsx
src/components/Calendar/YearPicker.tsx

https://smarthr.atlassian.net/browse/SHRUI-466
`Calendar` コンポーネントにおいて、特にブラウザのフォントサイズを大きくした時にスタイル崩れが発生しているため、ブラウザのフォントサイズ指定にも追従できるように修正を行います。
- 各スタイル指定で px 値を固定で指定しているところなどを全体的にテーマ値を使うように変更
- 年選択のスクロール処理を同期に変更してチラつきを防止
※ chrome にてフォントサイズ「極大」指定時
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/140891241-c7b0edd1-d18d-4f8c-b4b5-8db2130f3511.png) | ![image](https://user-images.githubusercontent.com/270422/140890933-d24fea54-90ca-4f87-a5ee-9c40633c6370.png) |
| ![image](https://user-images.githubusercontent.com/270422/140891281-d63ede93-6925-4ae5-9ab0-fecb3f0805a5.png) | ![image](https://user-images.githubusercontent.com/270422/140891134-a0e07bbf-30d8-4274-a4b5-c3b50cafd2a0.png) |

fix: `Calendar` がブラウザのフォントサイズによってスタイル崩れを起こさないように修正 (SHRUI-466)

---

src/components/LineClamp/LineClamp.tsx
src/components/Tooltip/README.md
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipPortal.tsx

https://smarthr.atlassian.net/browse/SHRUI-483
現状、 `LineClamp` コンポーネントのツールチップは常に上側に表示されるため、画面上上側のスペースが小さいと見切れてしまいます。
これを解消するにはツールチップを表示する方向を上下のスペースに応じて出し分けるロジックが必要になりますが、そもそもこの機能は `Tooltip` コンポーネントが持っていたほうが良いので、`Tooltip` に自動位置決め機能を実装し、 `LineClamp` でそれを使うことでツールチップが見切れないように対応します。
- `Tooltip` コンポーネントの `vertical`, `horizontal` に `auto` オプションを追加
- `auto` を指定した時自動で表示位置が決まる
- `LineClamp` コンポーネント内の `Tooltip` に上記 `auto` オプションを適用
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/140694479-49651c51-780d-4b96-927b-a66126551856.png) | ![image](https://user-images.githubusercontent.com/270422/140694353-df2cbac1-c9b8-4a2e-a056-ba983e074f78.png) |

feat: `Tooltip` に自動位置決め機能を追加し、`LineClamp` のツールチップが見切れないようにする (SHRUI-483)

---

src/components/InputFile/InputFile.tsx

IE は DataTransfer() constructor をサポートしていなかったためクラッシュが発生する。
https://caniuse.com/mdn-api_datatransfer_datatransfer
IE の場合は input の value の書き換えを行わないようにすることでクラッシュを防ぐように修正する。
- 該当の処理を try catch で囲い、 catch した場合は何もしない

fix: `InputFile` が IE でクラッシュしないように修正

---

src/components/Layout/Cluster/Cluster.stories.tsx
src/components/Layout/Layout.stories.tsx
src/components/Layout/LineUp/LineUp.stories.tsx
src/components/Layout/Sidebar/Sidebar.stories.tsx
src/components/Layout/Stack/Stack.stories.tsx

Layout 配下のコンポーネントの story の構成を変更したことに起因して、 story のタイトルが重複しているという警告が発生するようになった。
タイトルの重複が発生しないように story の export 方法を変更する。
- Layout 配下の story を `Layout.stories.tsx` で export し直す形に変更

chore: Layout story の export 方法を変更

---

src/components/SegmentedControl/SegmentedControl.tsx

Safari において、 `SegmentedControl` のボタン間に隙間が生じてしまっているため、 UA スタイルを打ち消して隙間ができないように修正します。
- 該当箇所の button に対する margin を 0 に上書き
※ Safari にてキャプチャ
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/142342163-fc0e2466-47a3-4886-9aa5-295fa7045134.png) | ![image](https://user-images.githubusercontent.com/270422/142342214-881ad482-2f95-4f27-82c8-ac9f46ae6982.png) |

fix: Safari で `SegmentedControl` の隙間ができないようにする

---

src/components/Tooltip/Tooltip.tsx

LineClampは複数行になる長文を渡した際に、任意の行数で文を切り詰めて、代わりにフォーカス時にTooltipで全文を表示するcomponentである。
このcomponentをsafariで表示すると、切り詰める前の要素の高さを維持する不具合があったため、これを修正した。
なお、chromeではこの不具合は発生しない。
LineClamp内部で使用しているdiv要素(Tooltip)にて、切り詰めて見えなくなっている要素がある場合は親要素でも見えないようにoverflowを適用するようにした。
|before|after|
|-|-
|<img width="992" alt="スクリーンショット 2021-11-24 17 23 16" src="https://user-images.githubusercontent.com/1688137/143203959-51241992-a28c-4999-99fe-cbbf1eb552a1.png">|<img width="991" alt="スクリーンショット 2021-11-24 17 23 34" src="https://user-images.githubusercontent.com/1688137/143203969-1de93331-6b5f-45e4-95b8-26b8c2a3d9a9.png">|

fix: safariで表示されるLineClampのheightが折り畳み前の高さを維持する不具合を修正

---

src/components/ComboBox/MultiComboBox.tsx

`MultiComboBox` において、アイテムを選択してコンポーネントの高さが変わった時、リストボックスの座標が再計算されないバグが生じているため、修正します。
- 選択済みアイテムが変更された時にリストボックスの座標を再計算するように修正
以下の例では、3つ目のアイテムとして `option 4` を選択した時、コンボボックス内のコンテンツに改行が発生してコンポーネントの高さが変わる操作を行っています。この時、
- before では、リストボックスが1行目基準の位置のまま表示されている
- after では、リストボックスは2行目基準の位置に再計算されて表示されている
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/143530977-689debb1-6190-4d8b-b4d4-c506c8b55039.png) | ![image](https://user-images.githubusercontent.com/270422/143530832-34c9ba0a-58da-4942-ba33-8f9b3d26f544.png) |

fix: `MultiComboBox` においてフォーカス中に高さが変わった時にリストボックスの位置を再計算するように修正

---

e2e/components/Dialog/ModelessDialog.test.ts
src/components/Dialog/ModelessDialog.tsx

https://smarthr.atlassian.net/browse/SHRUI-479
`ModelessDialog` は開いている間も外側の要素を操作できるので、 `ModelessDialog` を閉じた時にトリガにフォーカスが戻るのは不自然な動作と言えるので、 `ModlessDialog` を閉じたときはフォーカスを移動させないように変更します。
- `ModlessDialog`を閉じたときのフォーカス移動処理を削除
- 閉じたときのフォーカス移動を担保するテストを削除

fix: `ModelessDialog` を閉じた時にトリガにフォーカスを戻さないように変更 (SHRUI-479)

---

src/components/SegmentedControl/SegmentedControl.stories.tsx

https://smarthr.atlassian.net/browse/SHRUI-487
現状の `SegmentedControl` の story においては、各ボタンの内部テキストと `aria-label` が一致しない問題があるため、 story の見た目を実際にサービスで用いられるような形にした上で、適切に内部テキストと `aria-label` を使い分けるものに変更します。
- story の修正

chore: `SegmentedControl` の story を実態に近い見た目に変更 (SHRUI-487)

---

src/components/FlashMessage/FlashMessage.tsx

https://smarthr.atlassian.net/browse/SHRUI-502
現状、 `FlashMessage` に div のデフォルト属性を渡しても DOM に反映されていないので、反映されるように修正します。
- `ElementProps` が Wrapper に渡されるように修正

fix:`FlashMessage` の Wrapper に ElementProps が渡るように修正 (SHRUI-502)

---

src/components/LineClamp/LineClamp.tsx
src/components/Tooltip/Tooltip.tsx

#2074 で LineClamp や Tooltip の wrapper に overflow が追加したが、[CSS の仕様](https://www.w3.org/TR/CSS2/visudet.html#:~:text=the%20baseline%20is%20the%20bottom%20margin%20edge0)により inline-block 要素に overflow: visible 以外を充てると baseline が bottom margin の端に揃うらしい。
参考： https://codepen.io/uknmr/pen/OJxXMWg
影響範囲はわからないが、特段問題はなさそうなので vertical-align: bottom を指定した。

fix: LineClamp と Tooltip の baseline ズレを修正

---

src/components/SideNav/SideNavItem.tsx

#2099 
#2099 で指摘いただいたフォーカスインジケーターを修正しました。
- SideNavItem の `focus-within` に `theme.shadow.focusIndicatorStyles` を追加
- 実態であるボタンのフォーカスインジケーターを削除
before | after
--- |---

fix: SideNav のフォーカスインジケーターを新しい装飾に置き換える

---

src/components/Input/Input.stories.tsx
src/components/Input/Input.tsx

プロダクト側でのsmarthr-uiの14.4.0 -> 15.3.0のアップデート対応で表示崩れが発生していることに気づいたので修正しました 🙏 
`Input`の`width`属性に184px以下の値を設定した場合、下記のcaptureに記載のスクショの通りinputタグの幅がwrapperのspanタグの幅を超えてしまいます。
おそらく#1909 のデグレだと思われます。
inputタグに`width: 100%`を設定し、親のwrapperのspanタグのwidthに追従するように修正しました。
| - | - |
| ![スクリーンショット 2021-12-09 10 44 36](https://user-images.githubusercontent.com/32166731/145320775-39660389-6ba9-45e1-b95d-10bf7d472c15.png) | ![スクリーンショット 2021-12-09 10 45 00](https://user-images.githubusercontent.com/32166731/145320724-8be50463-52b9-42e1-bff2-7475fe85e164.png) |

fix: `Input`のwidthをデフォルト値より小さく設定すると表示が崩れる不具合の修正

---

src/components/TextLink/TextLink.stories.tsx
src/components/TextLink/TextLink.tsx

https://smarthr.atlassian.net/browse/SHRUI-501
`TextLink` コンポーネントでは、 `target="_blank"` の場合 suffix にアイコンが付く制御がされていますが、アイコンを表示したくないケースも考えられるため、アイコンを非表示にする手段を追加します。
- `suffix` に `null` を与えた時、 `target="_blank"` でもアイコンが表示されないように変更

fix: `TextLink` の suffix に null を指定することで外部リンクアイコン表示を抑止できるように変更 (SHRUI-501)

---

src/components/TextLink/TextLink.tsx

TextLink のアイコンと文字の縦位置がずれていて気になるので、テキストの縦位置中央で揃えたい。
TextLink 内のアイコン（実際には wrapper）に `vertical-align: middle` を指定。
before | after
--- | ---

fix: TextLink のアイコン縦位置を正す

---

.circleci/config.yml
package.json

- 派生元ブランチ
- https://github.com/kufu/smarthr-ui/pull/2091
- cimg/node
- https://circleci.com/developer/ja/images/image/cimg/node
- CircleCI上のdocker imageを `circleci/node` から `cimg/node` に変更します
- node v14系を `14.18.2` にアップデートします
- package.jsonのnode versionを更新
- circleciのconfigを更新

chore: CircleCI上の使用イメージを `cimg/node` に変更する

---

src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/SingleComboBox.tsx
src/components/ComboBox/comboBoxHelper.ts

https://smarthr.atlassian.net/browse/SHRUI-504
現在のコンボボックスは入力によってリストをフィルタリングする際に、全角半角・大文字小文字を区別した部分一致で判定していますが、これらを区別せずマッチしてフィルタリングするように変更します。
- 文字列を半角・小文字に変換してからマッチングするように変更
- 英数と記号を対象とする
- 半角カナには触れていません
- 全角
- 大文字

feat: コンボボックスが全半角大小文字を区別せずマッチするように変更

---

src/components/AppNavi/AppNavi.tsx
src/components/StatusLabel/StatusLabel.tsx

https://smarthr.atlassian.net/browse/SHRUI-514
For internationalization, change string props to ReactNode
- Change `<AppNavi>` label props
- Change `<StatusLabel>` children props

feat: Change `<StatusLabel>`, `<AppNavi>`'s string props to ReactNode

---

.github/workflows/e2e.yml
scripts/build-test.ts
tsconfig.json

https://smarthr.atlassian.net/browse/SHRUI-505
プロダクト側の IE サポート終了に合わせて UI も IE のサポートを終了します。
※: 念の為 BREAKING CHANGE にしています
- IE の e2e テストを削除
- build-test のターゲットを es5 から es2020 に変更
- tsc の target と lib を es2020 に変更
各フォールバックの削除は別途行います

chore!: IE のサポートを終了する (SHRUI-505)

---

src/components/Tooltip/README.md

Delete deprecated component from Tooltip README
Replace `<LightTooltip>`, `<DarkTooltip>` to `<Tooltip>`

docs: delete deperecated Component

---

src/components/FloatArea/FloatArea.tsx

https://smarthr.atlassian.net/browse/SHRUI-381
`FloatArea` コンポーネントをモバイル端末で表示するとレイアウトが崩れるのを修正します。
※ この PR では表示崩れに対する暫定的な対応のみ行い、モバイル表示に対する本質的な対応は別チケットで行うことを想定しています。
- 表示領域が狭い場合は改行して表示するように変更
- 以下の3つの領域単位で改行されるように、 Cluster を3層追加
- Tertiary ボタン
- エラーメッセージ
- Primary と Secondary ボタン
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/148025433-99aaef1f-9afa-4899-8898-563c88fdadb1.png) | ![image](https://user-images.githubusercontent.com/270422/148025332-b445b3c8-3d47-4fb8-a5aa-834077e6ce91.png) |
| ![image](https://user-images.githubusercontent.com/270422/148025407-44f9cb89-7edb-4be0-8a1e-9e0ae19ec811.png) | ![image](https://user-images.githubusercontent.com/270422/148025371-a65e8068-6ab7-4c8a-b72a-cc6ed6751b18.png) |

fix: `FloatArea` のモバイルでのレイアウト崩れを修正 (SHRUI-381)

---

src/components/InputFile/InputFile.tsx

Safari にて、 `InputFile` コンポーネントでファイル選択を行うと更新処理がループして動作不能になる問題に対処します。
同一の `InputFile` に対して、2回ファイル選択を行うと発生します。
Safari においてのみ、 input[type=file] 要素の files プロパティに代入を行ったときに onChange が発火する動作をするため、 ファイル選択 → onChange → onAdd → useEffect で代入 → onChange → onAdd  → useEffect で代入... とループしてしまう。
まずは暫定対応として、代入時に onAdd が発火することを抑止する方針で問題を回避します。
- input.files への代入時には onAdd が発火しないように変更
- 代入中かどうかをフラグで管理

fix: Safari にて `InputFile` の onAdd がループしないように修正

---

src/components/Footer/Footer.tsx

#2129 
`Footer` コンポーネント内のレイアウトが float で行われていたので flex に変更します。
- レイアウトを flex に変更

fix: `Footer` のレイアウト修正

---

src/index.test.ts

https://smarthr.atlassian.net/browse/SHRUI-503
現状、 `src/components` 配下にあるコンポーネントが `index.ts` から export されているかどうかはテストで担保されています。
また、 `src/components/Layout` 配下の `Cluster` や `LineUp` などのような多重のディレクトリ構成に対するテストも用意されていますが、こちらはブラックリスト形式になっており、新たに子ディレクトリを切った時そのディレクトリを検証対象として追加しなければテストされず、作業者がそのことに気付けないという課題感がありました。
この PR では、その多重ディレクトリに対する export 確認テストをホワイトリスト形式に変更し、ディレクトリを切った段階で検証対象に追加され、検証したくないディレクトリを IGNORE で管理する形にすることで export 漏れを回避しやすくなるように変更します。
- `src/components` 配下の各コンポーネントディレクトリ内の子コンポーネントを探索して、export と突き合わせる形に変更
- 無視したい子ディレクトリは `IGNORE_INNER_DIRS` で管理
- ディレクトリ取得ロジックを改善

test: export テストをホワイトリスト形式に変更 (SHRUI-503)

---

src/components/Dialog/ActionDialogContentInner.tsx

- ActionDialogのローダーのアイコン部分が崩れていたので修正しました。
- サイズを `1rem` -> `18px` に修正
|before|after|
|:---|:---|
|![image](https://user-images.githubusercontent.com/5885283/147033751-d85b994a-eaa9-40f0-a975-d0422c051c74.png)|![image](https://user-images.githubusercontent.com/5885283/149459641-0e1df748-b0c8-4cc0-9401-5a72acd5708c.png)|

fix: actionDialogのLoaderの表示崩れを修正

---

src/components/FlashMessage/FlashMessage.stories.tsx
src/components/FlashMessage/FlashMessage.tsx

https://smarthr.atlassian.net/browse/SHRUI-512
現状、 `FlashMessage` コンポーネントは表示8秒後に自動で閉じることを抑止できませんが、これを抑止できるようにオプションを追加します。
- `autoClose` オプションを追加
- `true` のとき、表示8秒後に `onClose` を発火（デフォルト）
- `false` のとき、時間経過での `onClose` 発火を行わない

feat: `FlashMessage` に autoClose オプションを追加 (SHRUI-512)

---

src/components/Layout/Cluster/Cluster.tsx
src/components/Layout/Cluster/useClassNames.ts
src/components/NotificationBar/NotificationBar.stories.tsx
src/components/NotificationBar/NotificationBar.tsx
src/components/NotificationBar/README.md
src/components/NotificationBar/index.ts
src/components/NotificationBar/useClassNames.ts
src/index.ts

https://smarthr.atlassian.net/browse/SHRUI-508
FlashMessage の代替として NotificationBar を作成しました。
表示制御は各アプリケーションに委ねます。
- コンポーネントの新規作成
- Cluster に HTML 属性や className を渡すように修正
コンテンツ量と幅に依ってレイアウトが変わります。
メッセー欄の幅がアクション群よりも狭くなる場合は、アクション群が折り返されます。

feat: NotificationBar を作成｜SHRUI-508

---

e2e/components/Dialog/ActionDialog.test.ts
e2e/components/Dialog/Dialog.test.ts
e2e/components/Dialog/DialogWrapper.test.ts
e2e/components/Dialog/MessageDialog.test.ts
src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContent.tsx
src/components/Dialog/ActionDialogContentInner.tsx
src/components/Dialog/DialogContentInner.tsx

https://smarthr.atlassian.net/browse/SHRUI-516
For internationalization, change string props to ReactNode.
ActionDialog accessibility name ware named by `title` and `subTitle` strings.
Change ActionDialog to be named by `aria-labelledby`.
and fix role, aria-label, aria-labelledby attribute position

feat: Change <ActionDialog>'s string props to ReactNode

---

src/components/NotificationBar/NotificationBar.tsx

NotificationBar の className が `smarthr-ui-NotificationBarundefined` となっていた。
className のデフォルト値を空文字とし、`undefined` が文字列として表示されないようにした。

fix: NotificationBar の className に undefined が混じるバグを修正

---

src/components/BottomFixedArea/BottomFixedArea.tsx

- shadow を定数にしたことにより、BottomFixedArea の shadow が見えなくなってしまったので修正
- BottomFixedArea の Base の shadow の値を変更
- Theme のルールに含められなかったので一旦コンポーネント内にハードコーディング
- 同 Base の border-radius を削除
- BottomFixedArea では不要のため
- 同 Base に `box-sizing: border-box` を追加
- padding の分幅が伸び、中央がずれていたので

fix: BottomFixedArea のシャドウを調整する

---

src/components/Input/Input.tsx

input[type=number] にフォーカスがある状態でポインティングデバイスに依るホイールイベントが発生すると数値が変化してしまう。
これを防ぐために input[type=number] の場合に限り、wheel イベントが発生したら Blur する※。
※ これは wheel イベントに preventDefault がないため

fix: Input[type=number] のスクロールで数値が変更されるのを防ぐ

---

src/components/Input/Input.tsx

`useMemo` の dependency に対象のオブジェクトを追加しました。
#2233 の対応で漏れてました。

fix: Input の useMemo 記述漏れ依存配列を追記

---

src/components/NotificationBar/NotificationBar.tsx

fix: NotificationBar の useMemo dependency 漏れを追記

---

src/components/CheckBox/CheckBoxInput.tsx
src/components/RadioButton/RadioButton.stories.tsx
src/components/RadioButton/RadioButtonInput.tsx

[非制御コンポーネント – React](https://ja.reactjs.org/docs/uncontrolled-components.html)
`<RadioButton>` と `<Checkbox>` で React の `defaultChecked` が `true` のときにチェックが入っているスタイルになってなかったのを修正しました。
Fixed that `<RadioButton>` and `<Checkbox>` were not styled to be checked when React's `defaultChecked` was `true`.
チェックが入っているスタイルは `.active` によって適用されていた。ただし `.active` は `checked` が `true` のときのみしか適用されない（ defaultChecked では適用されていなかった）。
チェックされた時のスタイルに `:checked` 擬似クラスを利用した。
----
checked styles was applied by `.active` class. However, `.active` is only applied when `checked` props is `true` (defaultChecked was not).
I used `:checked` pseudo-class for the style when checked.
- refactor RadioButton Story to CSF.
- I will write Story that contain defaultChecked RadioButton by another PR

fix: style of `defaultChecked`

---

src/components/Text/Text.stories.tsx
src/components/Text/Text.tsx

`<Text>` 要素の `as` で指定できる要素に限りをなくしました。
- `as` props の型を styled-components の as と同じにしました。
- `weight` propsもCSSProperties を参照するようにしました。
---
- change type of `as` props to the same type as `as` in styled-components.
- `weight` props refers to CSSProperties.

fix: make `<Text>` as props like a styled-components

---

src/components/FlashMessage/FlashMessage.tsx
src/components/FlashMessage/FlashMessageList/FlashMessageListProvider.tsx
src/components/FlashMessage/FlashMessageList/useFlashMessageList.tsx

https://smarthr.atlassian.net/browse/SHRUI-511
`FlashMessage` の安易な使用を避けるため、非推奨にします。
- `FlashMessage`, `useFlashMessageList`, `FlashMessageListProvider` を非推奨に変更

chore: `FlashMessage` を非推奨にする

---

src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx

https://smarthr.atlassian.net/browse/SHRUI-529
`Tooltip` コンポーネントは、disabled なボタンに対して設定すると、hover 時に表示されるが leave 時に非表示ならない不具合が発生するため、修正します。
- 表示制御のイベントを変更
- `onMouseEnter` → `onPointerEnter`
- `onMouseLeave` → `onPointerLeave`

fix: disabled なボタンに表示するツールチップが正常に動作するように修正 (SHRUI-529)

---

src/components/AppNavi/AppNavi.stories.tsx
src/components/AppNavi/AppNavi.tsx
src/components/AppNavi/AppNaviButton.tsx
src/components/AppNavi/AppNaviDropdown.tsx
src/components/AppNavi/appNaviHelper.tsx

https://smarthr.atlassian.net/browse/SHRUI-532
`AppNavi` コンポーネントにおいて、モバイルなど表示幅が狭い場合にアイテムのテキストが折り返されて表示されているのを、折り返さないように修正します。
- アイテム内のテキストを折り返さないように変更
- コンテナが内容に応じて伸びるように `max-content` スタイルを追加
- 各 story に横スクロール表示対応
- 各アイテムの高さが、コンテナの高さいっぱいまで広がるように修正

fix: `AppNavi` のアイテムのテキストが折り返されないように修正

---

src/components/BottomFixedArea/BottomFixedArea.stories.tsx
src/components/BottomFixedArea/BottomFixedArea.tsx

https://smarthr.atlassian.net/browse/SHRUI-534
`BottomFixedArea` コンポーネントでは、モバイルなどで表示可能幅が狭い場合にコンテンツが隠れてしまう問題があるので、修正します。
- ボタン類を折り返して表示するように変更
- モバイル viewport の story 追加は、 #2286 で行います
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/154626384-aed1ef53-4d4f-411b-9a1a-5393871b2a83.png) | ![image](https://user-images.githubusercontent.com/270422/154626275-dcbeb16e-091d-410f-9e2e-dac1aef69f2b.png) |

fix: `BottomFixedArea` のモバイル表示調整

---

src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/MultiSelectedItemInner.tsx
src/components/ComboBox/SingleComboBox.tsx
src/components/ComboBox/types.ts
src/components/ComboBox/useListBox.tsx

SmartHR Design System から抽出する際により具体的な名前である必要があったため。
名前以外の変更はありません。

fix: ComboBox の Item 型名を明示的に ComboBoxItem とする

---

src/components/Layout/Cluster/Cluster.tsx
src/components/Layout/LineUp/LineUp.tsx
src/components/Layout/Sidebar/Sidebar.tsx

- https://bugs.chromium.org/p/chromium/issues/detail?id=1161709
add Workaround for chromium bug that empty element has flex gap break layout.
Add `:empty { gap: 0 }` workaround to Component has possible empty element and has gap property. and remove gap fallback from `<LineUp>`.

fix: workaround empty flex gap bug

---

src/components/FormGroup/FormGroup.tsx

FormGroupの `title` が `string` のみを受け付けており属性を自由に付与しにくいため ReactNode へ変更しました。
FormGroup title props changed to ReactNode because `title` of FormGroup only accepts `string` and it's hard to give attributes freely.

feat: change to ReactNode for i18n

---

src/components/TextLink/TextLink.stories.tsx
src/types.ts

`preview.js` の `addDecorator` で `theme` 自体は渡っていたので型定義を足しました。

fix: Story 内の styled-component に theme の型を効かせる

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContent.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/DialogContent.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContent.tsx
src/components/Dialog/ModelessDialog.tsx

https://smarthr.atlassian.net/browse/SHRUI-535
現状、モーダルダイアログ系のコンポーネントは、中央寄せの時のダイアログの幅が viewport の50%になっています。
これは特にモバイルにおいて表示幅が非常に狭くなってしまう問題をはらんでいるため、デフォルトの表示幅を
- ダイアログ内のコンテンツの幅
- viewport から左右の spacing を引いた幅
- `800px`
のうちから最小のもので表示するように変更します。
**[BREAKING CHANGE] ダイアログの幅を指定するとき Extending Styles ではなく `width` props で行うように変更します。引き続き Extending Styles で指定する場合は、デフォルトで設定される `max-width` を考慮して設定する必要があります。**
中央寄せのために `left: 50%` のスタイルを指定していることによって、表示領域が残りの右側50%になってしまうため
- 中央寄せのためのスタイル指定を `left: 50%` を使わないものに変更
- 幅の拡張を行いやすくするために `width` Props を追加
- `max-width` の指定が加わることによって extending styles による拡張が煩雑になるため
- extending styles の方法が変わるので BREAKING CHANGE にすべきかどうか
- ダイアログの幅指定が切り替わるように変更
- `ModelessDialog` の最大幅も併せて変更
- Story を追加
| --- | --- |
| …

feat!: ダイアログのデフォルト幅を変更 (SHRUI-535)

---

.storybook/preview.js

以前の対応で、reg-suit でモバイルの viewport でも比較する設定を追加しましたが、モバイル viewport の比較のうちアニメーションをもつコンポーネントで毎回差分が検出される状態になってしまっています。
原因としては、スクリーンショットを行う storycap にて、初回以降の variants には CSS アニメーションが無効化されない問題が存在していて、スクリーンショットを行うタイミングのズレによってアニメーション中の表示差分が生まれているようです。
この問題の対処を行います。
- ワークアラウンドとして、モバイル viewport のキャプチャ前に CSS アニメーション無効のスタイルを差し込むことで、アニメーションが起きないようにします
- [storycap の waitFor](https://github.com/reg-viz/storycap#type-screenshotoptions)

test: reg-suit の variants で CSS アニメーションが有効にならないようにする

---

src/components/Balloon/Balloon.tsx

Bolloon コンポーネントの三角形部分のスタイルを改善しました。
具体的には、下記の2つを実施しました。
- 三角形の描画は border ではなく clip-path を使って描画するように変更
- border による三角形の描画はややハック寄りの書き方であるため
- 影は box-shadow ではなく filter の drop-shadow を使って描画するように変更
- drop-shadow であれば、三角形部分を含めた影も正しく描画できるため
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14817308/157377766-129a3ea3-482a-4681-8783-082dee4d124a.png) | ![image](https://user-images.githubusercontent.com/14817308/157377816-b195741c-dd39-45c7-bb1f-c1e20b4be8f6.png) |

fix: Balloon の三角形関連のスタイルを改善

---

e2e/components/Dropdown.test.ts
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/FocusTrap.tsx
src/components/Dialog/ModelessDialog.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/DropdownContentInner.tsx
src/components/Dropdown/dropdownHelper.test.ts
src/components/Dropdown/dropdownHelper.ts
src/libs/tabbable.ts

https://smarthr.atlassian.net/browse/SHRUI-536
`Dropdown` コンポーネントのパネル部分の幅がウィンドウサイズを超えるとページに横スクロールが発生するため、折り返して表示するように変更します。
- トリガが右寄りの場合、 `position: absolute` の `right` で位置を決定するように変更
- `max-width` でウィンドウサイズを超えないように制限
- Story 側に、ドロップダウン内のコンテンツが折り返される記述を追加
- ドロップダウンを開いた時に、コンテンツ内先頭に配置したダミー要素をフォーカスするように変更
- 関連して、`tabindex="-1"` の要素が tabbale に補足されないように修正（本来 tabindex="-1" はタブ移動可能ではないはずなのでこれが正しそう）
- また、↑の変更によりモーダルダイアログの開いたときのフォーカス移動がおかしくなったので、フォーカス用ダミー要素を `FocusTrap` 内に内包させ、フォーカスされた要素がダイアログ内のコンテンツだと認識されるように `FocusTrap` が `role=dialog` の配下になるように構造を変更
ドロップダウン部分の ARIA における role や名前付けは変更前からされておらず、本 PR で追加もしていません。
[Disclosure パターン](https://www.w3.org/TR/wai-aria-practices-1.2/#disclosure) に則れば、トリガとなるボタンとドロップダウンのパネルが `aria-controls` で結ばれていれば良く、その制御は既に入っているので問題ないと判断しました。
| --- | --- …

fix: `Dropdown` のモバイル表示調整 (SHRUI-536)

---

src/components/Pagination/Pagination.tsx

https://smarthr.atlassian.net/browse/SHRUI-538
現状、`Pagination` コンポーネントの幅がウィンドウサイズを超えるとき、はみ出して横スクロールが発生してしまうため、その影響を限定的にする対応を行います。
- `Reel` を用い、単体で横スクロールするように変更

fix: `Pagination` のモバイル表示調整 (SHRUI-538)

---

src/components/TabBar/TabBar.tsx
src/components/TabBar/__snapshots__/TabBar.test.tsx.snap

https://smarthr.atlassian.net/browse/SHRUI-539
`TabBar` のモバイル表示を想定した微調整を行います。
- `Reel` で囲って、幅がウィンドウサイズを超える時に単体で横スクロールするように変更

fix: `TabBar` のモバイル表示調整 (SHRUI-539)

---

.circleci/config.yml

なし
ブラウザ動作に必要なパッケージが入っているイメージを使うことで手動で reg-suit に必要なパッケージを入れる処理を消したい。
プロダクト側で @f440 さんがやってくれた対応を輸入しています。
- reg-suit を実行する docker イメージの変更
- 手動でインストールしていた処理を削除
reg-suit が動いていれば問題ないです。
なし

test: reg-suit を実行する docker イメージを変更

---

src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/ModelessDialog.tsx

style 内のコメントが出力されてしまう場合があるようなので、出力されないように対応します。
- style 内のコメントをテンプレートリテラル外に移動

chore: スタイル内のコメントが出力されないように修正

---

src/components/Balloon/Balloon.tsx

- ballonのtriangle部分がRetinaディスプレイで表示崩れ場合がある
- 詳細な条件までは調べきれていませんが、画面幅などが影響しており、おそらく計算結果の小数点以下の数値が影響していそう
- triangle部分を1pxほど大きくしてballonのbody部分をかぶらせておくことで途切れないようにしたい

fix: ballonのtriangleがretinaディスプレイなどで条件が揃うと表示崩れするバグを修正

---

src/components/Dialog/useDialogPortal.tsx

- 現状、 react-router の `Route` 下などでダイアログコンポーネントを使うと、mount/unmount のタイミングの関係でエラーが発生するので、修正します。
- `appendChild` を `setTimeout` で遅らせるのではなく、`useEffect` から `useLayoutEffect` に変更し、子である FocusTrap のフォーカス処理（`useEffect`）より先に解決するように変更

fix: ダイアログの portal を追加するタイミングを修正

---

src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContent.tsx
src/components/Dialog/MessageDialogContentInner.tsx

similar pull request:
feat: Change <ActionDialog>'s string props to ReactNode #2117
- Changed UI label props from string to ReactNode to make `MessageDialog` multilingual.
- Change `MessageDialog` Accessibility name from aria-label to `aria-labelledby` to refer to the title.
----
- `MessageDialog` を多言語対応するためにUIラベルのPropsをstringからReactNodeに変更
- `MessageDialog` の Accessibility name を `aria-label` から `aria-labelledby` で title を参照する形に変更

feat: use ReactNode for i18n

---

src/components/AccordionPanel/AccordionPanelTrigger.tsx
src/components/Button/BaseButton.tsx
src/components/Button/DangerButton.tsx
src/components/Button/PrimaryButton.tsx
src/components/Button/SecondaryButton.tsx
src/components/Button/SkeletonButton.tsx
src/components/Button/TextButton.tsx
src/components/CheckBox/CheckBoxInput.tsx
src/components/Input/Input.tsx
src/components/NotificationBar/NotificationBar.stories.tsx
src/components/NotificationBar/NotificationBar.tsx
src/components/RadioButton/RadioButtonInput.tsx
src/components/SegmentedControl/SegmentedControl.tsx
src/components/Select/Select.tsx
src/components/SideNav/SideNavItem.tsx
src/components/Textarea/Textarea.tsx

https://smarthr.atlassian.net/browse/SHRUI-553
`:focus` を `:focus-visible` に置き換えました。
- Input はスタイリングの都合上 `focus-visible-within` 的なものがないと対応できないため保留
- MultiComboBox は #2427 で大きく手が入りそうなため保留
- Select のスタイリングを見直したので reg 差分が出ています
ほか AccordionPanel の `:focus:not(:focus-visible)` なスタイルは UA に任せる方針とし、`:focus-visible` に寄せました。

feat: :focus を :focus-visible に置き換える｜SHRUI-553

---

src/components/AppNavi/AppNavi.stories.tsx
src/components/AppNavi/AppNavi.tsx

無し
`AppNavi` コンポーネントの props である `displayDrodownCaret` が typo でした。
正しくは `displayDropdownCaret` なので直したい。
**BREAKING CHANGE: props 名が変わるのでこれまで `displayDrodownCaret` を使っていたプロダクトには影響があります。**
typo 修正
なし

fix!: `AppNavi` の props 名の typo を修正

---

src/components/Button/AnchorButton.tsx
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/Button/ButtonInner.tsx
src/components/Button/ButtonWrapper.tsx
src/components/Button/DangerButton.tsx
src/components/Button/PrimaryButton.tsx
src/components/Button/SecondaryButton.tsx
src/components/Button/SkeletonButton.tsx
src/components/Button/TextButton.tsx
src/components/Button/index.ts
src/components/Button/style.tsx
src/components/Button/types.ts
src/components/Button/useClassNames.ts
src/index.ts

https://smarthr.atlassian.net/browse/SHRUI-545
既存のボタンコンポーネントは `PrimaryButton`, `SecondaryButton` など種類毎に別コンポーネントになっていますが、コンポーネントを `Button` と `AnchorButton` に統一し、`variant` Props で種類を選べるように変更します。
- `Button`, `AnchorButton` を追加
- `variant?: 'primary' | 'secondary' | 'danger' | 'skeleton' | 'text'` 、デフォルトは `secondary`
- 既存のボタンを非推奨化
- `PrimaryButton`
- `PrimaryButtonAnchor`
- `SecondaryButton`
- `SecondaryButtonAnchor`
- `DangerButton`
- `DangerButtonAnchor`
- `SkeletonButton`
- `SkeletonButtonAnchor`
- `TextButton`
- `TextButtonAnchor`
- テキストボタンの disabled 時の文字色が `color.disableColor(color.TEXT_DISABLED)` で二重に色が薄くなっていたので、単に `TEXT_DISABLED` になるように修正

feat: `Button`, `AnchorButton` コンポーネントを追加 (SHRUI-545)

---

src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
src/themes/createColor.ts
src/themes/createPalette.ts
src/themes/createShadow.ts

https://smarthr.atlassian.net/browse/SHRUI-560
灰色のプリミティブトークンをプロダクトでも使用したかったが、現状抽象値しかなかったためプリミティブトークンを用意し公開することにした。
合わせて既存の色についてもプリミティブトークンを作成した。
また、影の定義も算出した最も暗い灰色を参照するように変更した。
reg-suit に差があるので要確認。
※ プロデザ確認済み

feat: 色のデザイントークンを整理｜SHRUI-560

---

e2e/components/Dialog/Dialog.test.ts
src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContent.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/Dialog.tsx
src/components/Dialog/DialogContent.tsx
src/components/Dialog/DialogContentInner.tsx
src/components/Dialog/DialogWrapper.tsx
src/components/Dialog/FocusTrap.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContent.tsx
src/components/Dialog/types.ts

https://smarthr.atlassian.net/browse/SHRUI-562
現状ダイアログコンポーネントは、開いた時にダイアログ内の先頭にあるダミー要素をフォーカスする挙動をしますが、オプションとして特定の要素を指定できるように機能追加します。
- `firstFocusTarget?: RefObject<HTMLElement>` Props を追加
- 同じ意味の型定義が散在していたのを集約
- `firstFocusTarget` は `RefObject` のみを許容し、`HTMLElement` は許容しませんでした
- 現状のダイアログの実装では、ダイアログ非表示時にはダイアログコンテンツの DOM は追加されいない関係で、コンテンツ内の特定のフォームの `ref.current` を指定できるようにしても適切に動作しないことと、`RefObejct` を渡せるようにしておけば問題は無さそうに思えたので `RefObject` のみを許容する形にしています。
- `ActionDialog` におけるアクションボタン・閉じるボタンなど、コンポーネント内に閉じている要素を指定できるオプションの追加はしませんでした
- つまり `firstFocusTarget?: RefObject | 'actionButton' | 'closeButton'` みたいな形にはしなかった
- 現状では考慮し過ぎ感があり、必要になれば跡から型変更で追加できるので現状での実装は見送りました

feat: ダイアログにおいて最初にフォーカスする要素を指定できるようにする (SHRUI-562)

---

e2e/components/Dialog/ActionDialog.test.ts
src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContentInner.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContentInner.tsx

デザインシステムに則り、ActionDialog と MessageDialog に良いデフォルトを作ります。
ダイアログの挙動をプロダクト間で少しでも近づけたいと考えています。
https://smarthr.design/products/components/dialog/
- ActionDialog も MessageDialog も共に Escape キーを押した場合はデフォルトで閉じるボタンと同等にします
- ActionDialog のデフォルト theme は `primary` にします
- ActionDialog の閉じるボタンラベルはデフォルト「キャンセル」にします
- MessageDialog の閉じるボタンラベルはデフォルト「閉じる」にします

feat: ActionDialog と MessageDialog の良いデフォルトを実装

---

package.json

- #2466
SmartHR UI v20 から v21 にあげたところ、テスト関連のライブラリまでインストールされるようになりました。
#2466 で `jest-environment-jsodom` を `dependencies` に追加したのが原因のようです。ライブラリを動かすためには必要のないパッケージなので、 `devDependencies` に配置するのが適切かと思いました。
- `jest-environment-jsdom` を `dependencies` から `devDependencies` に移動
N/A

fix: ライブラリの動作に必要ない jest-environment-jsdom を devDependencies に移動

---

.storybook/main.js
src/components/Button/Button.stories.tsx

Storybook上でpropsを変更しながら挙動を確認できる、controls addonを有効化しました。
#2443 にてButtonコンポーネントのインターフェースが変わったということなので、まずButtonコンポーネントに試験実装しています。
controlsタブで`variant` Propsを動的に変更できるようになるため、表示されるコンポーネントは1つだけにしています。
- controls addonを有効にすると、すべてのストーリーでControlsタブが表示され、何も設定がない場合には"This story is not configured to handle controls."という黄色いwarningが表示されてしまうようです。各ストーリーに`hideNoControlsWarning: true`というオプションを設定する必要があるかもしれません。
- `ReactNode` typeのPropsの場合、controlsにはデフォルトでJSONエディタが表示されてしまい、Storybookがエラーを表示するという問題があるため、`children` `suffix` `prefix`の3つについては、`{ control: 'text' }`を明示的に指定しています。
- 関連するissue
- https://github.com/storybookjs/storybook/issues/11428
- https://github.com/storybookjs/storybook/issues/13551
https://deploy-preview-2488--smarthr-ui.netlify.app/?path=/story/button--button

feat: Storybookにcontrols addonを追加

---

src/components/Heading/Heading.tsx
src/components/Text/Text.tsx

Heading の実装を Text で置き換えました。
`line-height: 1` から `leading.TIGHT` に変わっています。デフォルト `leading.TIGHT` は `line-height: 1.25` と同等です（reg-suit の差分はすべてこれ）。
また `<fieldset />` 内の `<legend />` として使いたいこともあるので `HeadingTagTypes` に `legend` を追加しました。
- `TextProps` が必要だったので `Text` から export
- `type` と styled-components で書いていたスタイリングを `Text` に置き換え

refactor: Heading の内部実装を Text で置き換え

---

src/components/CheckBox/CheckBoxInput.tsx
src/components/RadioButton/RadioButtonInput.tsx

CheckBox と RadioButton の一部スタイルが dynamic className ではなく static className があたってしまっていたので応急処置。
`&` を `&&` に変更（なぜか dynamic className）になってくれる。

fix: CheckBox と RadioButton で static className があたってしまうのを修正

---

package.json
yarn.lock

https://smarthr.atlassian.net/browse/SHRUI-566
Storybookがv6.5.x系にアップグレードされ、React v18対応のために指定していたemotionのバージョン固定が不要になったため除去します。
- `package.json`の`resolutions`から以下のライブラリを除去
- `"@emotion/core": "^10.3.1"`
- `"@emotion/styled-base"`
- `"emotion-theming"`

refactor: 不要になったresolutions指定の削除

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownContentInner.tsx
src/components/Dropdown/useKeyboardNavigation.ts

ドロップダウンのフォーカス制御で確認されている以下の問題を解決します。
- ダイアログを開く処理とドロップダウンを閉じる処理を同時に行うと、ドロップダウンのトリガにフォーカスを戻す処理が勝ってフォーカスがダイアログ内に移動しない
- ドロップダウンを開いた直後ダミー要素がフォーカスされている状態で Shift + Tab を押下したとき、フォーカスがトリガに戻らない
- ドロップダウンのトリガにフォーカスを戻す処理を `requestAnimationFrame` で遅らせていたのを削除
- フォーカス制御において、ダミー要素のフォーカス考慮を追加

fix: ドロップダウンのフォーカス制御の修正

---

src/components/Button/Button.tsx
src/components/Button/ButtonWrapper.tsx

`Button` コンポーネント追加時に、`type` のデフォルトが `button` になっていなかったのを修正します。
- `Button` の `type` のデフォルト値を `button` に修正
- 適切な型に修正

fix: `Button` コンポーネントをデフォルトで `type=button` にする

---

jest.config.js
src/components/Base/__test__/index.test.tsx
src/components/FlashMessage/FlashMessage.test.tsx
src/components/StatusLabel/StatusLabel.test.tsx

React 18 以降は `ReactDOM.reander()` は `createRoot()` への置き換えが推奨されるため、テストで使っている部分を置き換えます。
- `ReactDOM.reander()` を `createRoot` に置き換え
- `act()` を使うためにテスト環境のフラグを有効化（[参考](https://ja.reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#configuring-your-testing-environment)）

test: ReactDOM.reander を createRoot に切り替え

---

e2e/components/ComboBox/MultiComboBox.test.ts
e2e/components/ComboBox/SingleComboBox.test.ts
e2e/components/DatePicker.test.ts
src/hooks/useId.tsx

id 生成用のフックとして独自で実装を持っている `useId` は、React 18 以降の環境では適切に動作しないと思われるほか、Strict モード時の SSR においてサーバとクライアントの id がずれる問題があるため、可能であれば `React.useId` を使うように変更します。
- React 18 以降なら `React.userId` を使うように変更

fix: React 18 以降であれば ID 生成に `React.useId` を使うように変更

---

src/components/Dropdown/DropdownContent.tsx
src/components/Dropdown/DropdownContentInner.tsx
src/components/FormGroup/FormGroup.tsx
src/components/FormGroup/useClassNames.ts
src/components/InputFile/InputFile.tsx
src/components/SideNav/SideNav.tsx

https://smarthr.atlassian.net/browse/SHRUI-510
各コンポーネントのうち、wrapper の要素のデフォルト属性を渡せないものについて、渡せるように変更します。
また、エスケープハッチが付いていないコンポーネントにエスケープハッチを付与します。
- デフォルト属性を渡せるようにする
- Dropdown
- InputFile
- SideNav
- エスケープハッチ追加
- FormGroup

chore: 要素のデフォルト属性を渡せるようにする (SHRUI-510)

---

src/components/Select/Select.tsx

https://smarthr.atlassian.net/browse/SHRUI-569
`Select` コンポーネント内部のテキストの上端（特に半濁点）が見切れてしまうのを修正します。
- select 要素に対する padding 指定だと内部テキストが見切れてしまうため、wrapper 側でコンポーネントの高さを制御するように変更
| --- | --- |
| ![image](https://user-images.githubusercontent.com/270422/172762845-7aee602f-5a90-42c1-816c-0c0683730771.png) | ![image](https://user-images.githubusercontent.com/270422/172762802-3f80e6a3-1d69-429e-9126-7fbcce5017b5.png) |

fix: `Select` 内部のテキスト上端が見きれないように修正 (SHRUI-569)

---

src/components/Header/Header.tsx

Header が `className` を受け付けていなかったため `styled-components` で覆うことができなかった。

fix: Header に className を渡す

---

src/themes/__tests__/createTheme.ts
src/themes/createTheme.ts

https://smarthr.atlassian.net/browse/SHRUI-568
- 新フォントサイズを利用している場合 `spacing` では余白の表現が足りない
- `spacingByChar` の利用を推奨しているが、頻繁に使う値の割に長く可読性が悪い
- `theme.space()` の形で使えるように alias を追加

feat: spacingByChar の alias として space を追加｜SHRUI-568

---

src/components/Dropdown/DropdownButton/DropdownButton.tsx

関連: #2547
`v21.2.0` から特定条件下で発生しているエラーの解消を行います。
参考: https://github.com/styled-components/styled-components/issues/1449
推測ですが、コンポーネントの import の仕方によって循環参照が生じて、解決順が不正になることで特定のコンポーネントが undefined になってエラー、みたいな流れなのではと思います。
- `DropdownButtton` 内で 他のコンポーネントを `src/index` から参照している部分を、個別に import するように変更

fix: コンポーネント内の import 記述の変更

---

src/components/Button/AnchorButton.tsx
src/components/Button/Button.tsx

`BottomFixedArea` の Props 判定に用いるボタンコンポーネントの `displayName` の設定が漏れていたので、設定します。
- `Button`, `AnchorButton` コンポーネントの `displayName` を明示的に設定

fix: ボタンの displayName を明示的に設定

---

src/components/ComboBox/useListBox.tsx

現状、コンボボックスのリストボックスにおける、アイテム数が多い場合の部分的レンダリングが動かなくなっているのを修正します。
原因は、useEffect 外の document の参照を廃した（#2539）ことで、該当箇所のレンダリングが遅れて IntersectionObserver の登録がうまく行かなくなっているためだと思われます。
コンボボックスの両ストーリーの下の方にある「アイテムが多い時」のコンボボックスで、スクロールにより100個目以上のアイテムが表示できること
- IntersectionObserver の登録タイミングを遅らせる

fix: コンボボックスの部分的レンダリングが効かなくなっているのを修正

---

src/components/SmartHRLogo/SmartHRLogo.tsx

ThemeProvider がある前提で書かれていたので useTheme の戻り値を引き回すように修正。

fix: SmartHRLogo の Wrapper が ThemeProvider 前提で書かれていたので修正

---

src/components/Header/Header.tsx

現象としてはこちらと同じです。
https://github.com/kufu/smarthr-ui/pull/2593
Header コンポーネントの内部実装が、使うプロダクト側で styled-components の ThemeProvider を使用していることに依存している実装になっているため、それを使っていないプロダクトで Header を使用するとランタイムエラーが発生してしまう。
ので ThemeProvider に依存しない実装に変更したい。
useTheme を使用してスタイルを実装

fix: ヘッダーが ThemeProvider 前提で書かれている箇所を useTheme を使うように修正

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx
src/components/Select/useClassNames.ts

複数のプロダクトで独自実装を始めていたので作成。
select 要素に size 要素があるが、SmartHR UI では機能していないため潰す選択を取りました。
small など別のプロパティも検討しましたが、Button[size=s] などと合わせるためでもあります。
Select[size=s] は Button[size=s] と高さが揃います。
- `size === 's'` の時、class に `--small` を足す
- `--small` の時のスタイルを追加
- styled-components の記述と不要なスタイリングを見直し
- Story を更新

feat: Select にサイズ小を追加

---

src/components/Textarea/Textarea.stories.tsx
src/components/Textarea/Textarea.tsx

Textarea がコンテンツの量に依って、縦方向に自動的に広がると良さそうだったので機能を加えました。
- autoGrowable を追加
- autoGrowable がある場合は rows や maxRows に依って高さを動的に変える
- rows の初期値は 2（HTML 仕様に則る
- maxRows の初期値は Infinity
- アクセシビリティ観点でも問題がないことを確認
- rows を直接編集しているが HTML の仕様的に特に問題はない
- macOS の VoiceOver で確認したが問題なし
- アクセシビリティエキスパートによるレビューも問題なし

feat: Textarea が自動で広がるように機能追加

---

src/components/ComboBox/useListBox.tsx
src/components/ComboBox/usePartialRendering.tsx

コンボボックスにおいて、`IntersectionObserver` の登録の方法に起因して不要な `setTimeout` が存在していたため、`IntersectionObserver` の紐付け方法を変更します。
- `IntersectionObserver` を張る要素を `usePartialRendering` 内で 管理するように変更

chore: コンボボックスの IntersectionObserver の紐付け方法を修正

---

src/themes/createRadius.ts

https://smarthr.atlassian.net/browse/SHRUI-581
- radiusのセマンティクストークンには`L`と`FULL`が存在していますが、現状は`S`と`M`のみになっているため対応させたいです。
- [角丸 | デザイントークン | SmartHR Design System](https://smarthr.design/products/design-tokens/radius/#h2-2)
`createRadius`にDesign Systemに沿った値を追加しました。

feat: createRadiusに'L'と'FULL'を追加する

---

package.json
yarn.lock

Reverts kufu/smarthr-ui#2633
e2e が落ちるようになったので一旦 revert します。
エラーログ
```
$ testcafe chrome e2e/**/*.test.ts --host localhost --skip-js-errors
ERROR Cannot prepare tests due to the following error:
Error: TypeScript compilation failed.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (416, 62): ']' expected.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (416, 65): ';' expected.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (416, 70): ';' expected.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (416, 94): ';' expected.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (416, 95): Declaration or statement expected.
D:/a/smarthr-ui/smarthr-ui/node_modules/@types/jest/index.d.ts (420, 50): ']' expected. …
```

chore: return dependency version @types/jest to ^28.1.4

---

src/components/Button/ButtonWrapper.tsx
src/components/Input/Input.stories.tsx

`Button[variant=secondary]` の背景色が `disabledColor(WHITE)` となり、WHITE のままになっていた。
以前はベタ書きで別の色が当たっていたらしい。
`Input[disabled]` の背景色と合わせて `hoverColor(WHITE)` を適用した。

fix: Button[variant=secondary] の disabled に背景色を追加

---

src/components/ComboBox/MultiComboBox.tsx
src/components/Input/Input.tsx
src/components/Select/Select.tsx

以下のコンポーネントの disabeld 装飾を Button[variant=secondary] に合わせました。
- Input
- Select
- SingleComboBox
- 内部的には Input のため修正なし
- MultiComboBox
- DatePicker
- 内部的には Input のため修正なし

fix: 入力要素の disabled 装飾を Button に合わせる

---

src/components/Dropdown/DropdownButton/DropdownButton.stories.tsx
src/components/Dropdown/DropdownButton/DropdownButton.tsx

[SHRUI-586](https://smarthr.atlassian.net/browse/SHRUI-586)
DropDownButtonのchildrenはReactElementだけが許可されているため、条件分岐でnullを返したい場合などは使用することができません。
`null | boolean` を追加して、「条件によってボタンを表示しない」などの選択肢を取れるようにしたいです。
`type ActionItem` に `null | boolean` を追加しました。

feat: DropDownButtonのchildrenの型に `null | boolean` を追加する   SHRUI-586

---

src/components/DropZone/DropZone.stories.tsx
src/components/DropZone/DropZone.tsx

https://smarthr.atlassian.net/browse/SHRUI-588
DropZone の `input[type=file]` が `multiple` 固定になっている。

feat: DropZone を単一ファイル選択でも使えるようにする｜SHRUI-588

---

src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx
src/components/Icon/useClassNames.ts

- https://smarthr.atlassian.net/browse/SHRUI-567
- https://github.com/kufu/smarthr-ui/pull/2657
`<Text />` の拡張ではなく、`<Icon />` を拡張して可視テキストを渡せるようにしました。
アイコンとテキストを並べたいが、折り返されたくないときに利用します。

feat: Icon に可視テキストを渡せるようにする

---

src/components/Button/AnchorButton.tsx
src/components/Button/Button.tsx
src/components/Button/ButtonWrapper.tsx

Button と AnchorButton から `useImperativeHandle` を利用した ref の詰め替えが不要そうなので消しました。

fix: Button と AnchorButton から不要な ref の詰め替えを消す

---

.circleci/config.yml
yarn.lock

先日のフロントMTGで紹介されていた yarn-deduplicate を導入し、yarn.lock の最適化を行いました。
導入前後の効果は以下のとおりです。CIやローカルの初回構築時の速度がかなり上がりそう。
| | before | after |
| - | - | - |
| yarn.lock の行数 | 19591 | 17559 |
| node_modules のサイズ | 6.5 GB | 1.2 GB |
| 初回の yarn install にかかる時間 | 491.30s | 43.53s |

chore: 依存関係最適化のために yarn-deduplicate を導入

---

src/components/FloatArea/FloatArea.stories.tsx
src/components/FloatArea/FloatArea.tsx

https://smarthr.atlassian.net/browse/SHRUI-574
- FloatAreaのpositionのデフォルト値を`fixed`から`sticky`に変更
- fixedのpropsを用意した
- widthのデフォルト値(`80%`)を廃止
- stickyで利用しにくいため

fix!: FloatAreaにfixed propsを追加 | SHRUI-574

---

src/components/DefinitionList/DefinitionList.stories.tsx
src/components/DefinitionList/DefinitionList.tsx
src/components/DefinitionList/DefinitionListItem.tsx

https://smarthr.atlassian.net/browse/SHRUI-601
- DefinitionListItems の description は存在しない場合もあるため optional にしました
- DefinitionListItem の termTag は invalid な HTML なため削除しました
- description は空文字の場合も見た目が崩れないようにしました
- 全体的にスタイリングを見直しました
- reg-suit の差分が出ていますが、変更後のスタイルが正です
- コンテンツは標準で折り返されるため、折り返されたくない場合の対処方法を Story に追記しました
- resolve #2597

feat!: DefinitionList の description に空文字を許容させる｜SHRUI-601

---

.circleci/config.yml
renovate.json

届出書類チームで実施されていた改善を取り込みました。
これまでは CircleCI で yarn-deduplicate が実行されつつ、手動で push する必要がありましたが、今後は renovate が自動的にやってくれるようになります。

chore: renovate で yarn-deduplicate が自動実行されるようにする

---

src/components/DefinitionList/DefinitionListItem.tsx

dd に対してあてていた破線を、dt + dd の親 div にあてました。
一方の dd に改行があった場合も破線が揃う仕様になります。
改行を許さない場合は nowrap を使います。
https://deploy-preview-2758--smarthr-ui.netlify.app/?path=/story/definitionlist--all

fix: DefinitionListItem の破線を折返しがあっても下端で揃える

---

src/components/Icon/Icon.tsx

Icon に以下のアイコンを追加したい。
- FaCompressAlt
- FaExpandAlt
Icon に以下のアイコンを追加。
- FaCompressAlt
- FaExpandAlt

feat: add compressalt icon and expandalt icon

---

src/components/Dialog/ActionDialog.tsx
src/components/Dialog/ActionDialogContentInner.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/MessageDialog.tsx
src/components/Dialog/MessageDialogContentInner.tsx

https://smarthr.atlassian.net/browse/SHRUI-572
より適切なマークアップをするため、ダイアログタイトルのデフォルトを p から h2 に変えます。
ダイアログを呼び出すドキュメントに h1 があるはずなので、ダイアログは h2 以降になると考えています。
参考： [Modal Dialog Example | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/dialog.html)
また、デフォルトは h2 ですが、利用者が適宜指定できるようにしています。
- ActionDialog の title / subtitle 領域をまとめて h2 で囲みました
- MessageDialog の title / subtitle 領域をまとめて h2 で囲みました
- Dialog および ModelessDialog の Story を修正しました

feat: Dialog タイトルのデフォルトを h2 に統一｜SHRUI-572

---

src/components/FieldSet/FieldSet.tsx
src/components/Input/CurrencyInput/CurrencyInput.tsx
src/components/Input/Input.tsx
src/components/Textarea/Textarea.tsx

- placeholder属性を非推奨にします
- 基本的にテキストノードでヒントを表示、その領域がない場合はTooltipコンポーネントを使用することを促します

chore: deprecate placeholder attributes

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx

https://smarthr.atlassian.net/browse/SHRUI-577
Select の width に初期値 16.25em（260px）が指定されていたが、デザイン意図ではなくデザインデータをそのまま実装に落とし込んだだけだったため、あるべき姿に修正しました。
input や select などの要素幅のデフォルトは auto なため、合わせて auto としました。

fix: Select の width を初期値 auto に変更｜SHRUI-577

---

package.json

https://smarthr.atlassian.net/browse/SHRUI-628
https://kufuinc.slack.com/archives/CGC58MW01/p1665539082777099
- `react-innertext`がdevDependenciesに定義されていたことでSmartHR-UIを利用するプロダクト側で当該ライブラリが不足することによるエラーで正常にビルドできない状態になっていたためこれを修正したい
- `react-innertext`をdevDependenciesからdependenciesに移動

chore: react-innertextをdependenciesに移動 | SHRUI-628

---

src/components/Dropdown/DropdownButton/DropdownButton.stories.tsx

`color: red` を指定しなくても ReactNode を渡せる確認はできるので消しました @hndrr

docs: 意図せず DropdownButton の文字色が赤くなっていたので修正

---

src/components/Loader/Loader.tsx

Loader の代替テキストが固定されていたため、`alt` を渡せるようにしました。

feat: Loader に alt を追加

---

src/components/Header/Header.stories.tsx
src/components/MessageScreen/Footer.tsx

https://smarthr.jp/news/42544
SmartHRのヘルプセンターのURLが古いものだったので、最新のものに変更した。
合わせて、お知らせやプライバシーポリシーポリシーのURLも古いものだったので、最新のものに変更した。
- smarthr.jp/help が含まれるURLの置換
- knowledge.smarthr.jpが含まれるURLの置換
- `Footer.txs` 内の古いURLの置換
🍐

fix: ヘルプページなどのURLを置き換え

---

src/components/Dialog/ModelessDialog.tsx

https://smarthr.atlassian.net/browse/SHRUI-584
`ModelessDialog` を画面外にドラッグ&ドロップできてしまい、マウス操作でダイアログを閉じたり、ダイアログの位置を戻したりできなくなることがあるため修正したい。
`react-draggable` の props に、`Draggable` の境界を指定する `bounds` props があるため、これを使用し、画面上部を超えてドラッグ&ドロップできないように調整しました。
https://github.com/react-grid-layout/react-draggable#draggable-props
https://user-images.githubusercontent.com/32166731/197096894-64a2e4a7-978f-4e6d-890c-213bcde50b44.mov

fix: `ModelessDialog` を画面上部の境界外にドラッグ&ドロップできないようにする

---

src/types/markdown/markdown.d.ts

https://github.com/kufu/smarthr-ui/pull/2707
I use it as a reference for the implementation of the UI library. Thank you.
UIライブラリを実装する際に参考にさせていただいております。ありがとうございます。
In this time, I deleted the type because I thought it is forgotten to delete in the above pull request.
上記PRで型を削除し忘れているのかなと思い、軽微なPRを出しました。
I deleted the markdown type.
マークダウンの型定義を削除しました。
I executed `yarn lint`, `yarn build` and `yarn test` in local and confirmed that there were no errors.
lintとbuildとtestをlocalで打って問題ないことを確認しました。
none.
なし。
If you don't use this [template](https://github.com/kufu/smarthr-ui/blob/master/CONTRIBUTING.md#template), I will also remove this from CONTRIBUTING.md. Should I do?
テンプレートを使っていないのであればあわせて削除しますが、いかがでしょうか？

chore: delete markdown type

---

src/components/AccordionPanel/AccordionPanel.stories.tsx
src/components/AppNavi/AppNavi.stories.tsx
src/components/DefinitionList/DefinitionList.stories.tsx
src/components/Dialog/Dialog.stories.tsx
src/components/Downloader/Downloader.stories.tsx
src/components/DropZone/DropZone.stories.tsx
src/components/Dropdown/Dropdown.stories.tsx
src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
src/components/FieldSet/FieldSet.stories.tsx
src/components/FormGroup/FormGroup.stories.tsx
src/components/Layout/Cluster/Cluster.stories.tsx
src/components/Layout/LineUp/LineUp.stories.tsx
src/components/Layout/Sidebar/Sidebar.stories.tsx
src/components/Layout/Stack/Stack.stories.tsx
src/components/Loader/Loader.stories.tsx
src/components/MessageScreen/MessageScreen.stories.tsx
src/components/ProgressBar/ProgressBar.stories.tsx

- https://github.com/kufu/smarthr-ui/pull/2793#discussion_r1000118459
上記リンク先のレビュー指摘を反映させたい。
Story の実装時に `useTheme` それぞれで使うのではなく `parameters: { withTheming: true }` を指定し、`ThemeProvider` から渡される `theme` 値を使うように変更しました。
`.stories.tsx` 以外のファイルには手を入れていないのと、reg-suit にも差分は出ていないので問題なさそうなことは確認済み。

refactor: story で useTheme を使わないようにする

---

src/components/Icon/Icon.tsx
src/components/InformationPanel/InformationPanel.stories.tsx
src/components/InformationPanel/InformationPanel.tsx

https://smarthr.atlassian.net/browse/SHRUI-626
InformationPanel の見出し縦位置のズレを直すついでに、スタイリングを見直しました。
- Icon の text に ReactNode を渡せるよう修正
- InformationPanel の Story を幅の狭い画面用に修正
- 見出し部分を Icon with Text で書き換え
- px 固定値を算出 ほか
#2818 の後にマージします

fix: InformationPanel のスタイリングを微調整

---

src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/Button/ButtonWrapper.tsx
src/components/Button/types.ts

処理中にボタン自体が処理の状態を表せるように変更
- 処理中の状態を表すBooleanを追加
- 処理中の時は強制的にLoaderがsuffixに入るようにした
- 処理中の時はボタン自体がdisabledになるようにした
- themeの各スタイルに合うようにLoaderのスタイルを変更
- 基本的に使うのは通信処理が発生するActionDialog周り、SmartHR本体のサーバーが死んでるとかじゃない限り通信処理は成功するので、表示するメッセージはerrorのメッセージだけにしたい。
- ダイアログがガクガクするのを極力減らしたい
- ガクガクしたときにはエラーメッセージが出てるという認知に変えていきたい
- このButtonを使用するのは主にActionDialog
- responseMessageがあるのでそれをそのまま使えば実装できそう
- processingは要らない
- successはメッセージの内容や状況によって必要
- utsuwaの評価テンプレート作成時の「作成しました」等のFB時はsuccessは要らない
1. プロデザにレビューしてもらう
2. そしてSmartHRUIチームからのレビュー

feat: Button に処理中の状態を追加

---

src/components/Icon/Icon.stories.tsx
src/components/Icon/Icon.tsx

https://smarthr.atlassian.net/browse/SHRUI-625
Icon with Text で複数行になる場合にアイコンが縦位置中央に揃ってしまっていたため、1行目の先頭に揃えました。
また、アイコンを右側に寄せる場合は flexbox ではなく inline のまま扱うようにしました。
Story で動きの確認もお願いします。
https://deploy-preview-2859--smarthr-ui.netlify.app/?path=/story/icon--with-text

fix: Icon with Text の複数行表示を修正

---

src/components/Text/Text.tsx

https://smarthr.atlassian.net/browse/SHRUI-619
https://styled-components.com/docs/api#transient-props
Text で color プロパティをそのまま渡していたため DOM に反映されていました。
`$` をつけ Transient props として扱うことで回避しました。
ついでに VFC → FC に変更。

fix: Text の color が DOM に反映されないように修正

---

src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx

Button with Loader のスタイリングに ThemeProvider ありきの記述があったため、ThemeProvider を利用していないプロダクトで一部プロパティが読めずエラーが発生していた。
- Story の `withTheming` を消した
- `useTheme` で theme を引き回すように修正

fix: Button with Loader が ThemeProvider 前提になっていたので修正

---

src/components/Button/Button.tsx
src/components/Button/ButtonWrapper.tsx

Next.js 環境で以下の Warning が発生していた。
```
Warning: Received `false` for a non-boolean attribute `loading`.
If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.
If you used to conditionally omit it with loading={condition && value}, pass loading={condition ? value : undefined} instead.
```
原因は定かではないが、button 要素に対して `loading` を流し込んだときに `loading` は boolean ではない、と怒られていると考え Transient Props を用いて修正した。
https://smarthr.atlassian.net/browse/SHRUI-639
- https://styled-components.com/docs/faqs#transient-props-since-51
- [HTMLImageElement.loading - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/HTMLImageElement/loading)
- img 要素には loading 属性が存在する

fix: ButtonWrapper に渡していた loading を Transient Props に変更

---

src/components/Button/Button.tsx
src/components/Button/types.ts
src/components/Button/useClassNames.ts
src/components/Dropdown/DropdownButton/DropdownButton.stories.tsx
src/components/Dropdown/DropdownButton/DropdownButton.tsx

https://smarthr.atlassian.net/browse/SHRUI-603
DropdownButton の children に Button[disabled] がある時、利用者は disabled な理由を知る術がない。
Button[disabled] の外で disabled な理由を伝えたいため、Button に disabled な理由（disabledDetail）を渡せるようにした。
- [Button に disabled な理由を渡せるようにする](https://github.com/kufu/smarthr-ui/commit/12205138aac6119d4056ebc03d184f42f42b9426)
- [DropdownButton 内の disabled な Button スタイリングを調整](https://github.com/kufu/smarthr-ui/commit/d502d5bcb61d5002ec136c40f754db4909aea196)
- [Story を修正](https://github.com/kufu/smarthr-ui/commit/5dd4b978ac9b46c3dd7cd94541b806d78600950e)

feat: DropdownButton に disabled な理由を渡せるようにする

---

src/components/Tooltip/Tooltip.tsx

Tooltip のフォーカスリングがデフォルトのままだったので SmartHR UI のフォーカススタイルをあてました。
Before | After
--- | ---

fix: Tooltip のフォーカスリングを SmartHR UI 化

---

src/components/ComboBox/SingleComboBox.tsx
src/hooks/useClick.ts

- SingleComboboxの defaultItem オプションが特定の操作時、バグってしまうため、調整した
- 再現手順
- comboboxにfocusする
- deleteキーなどでinputをclearする
- defaultItemに指定している以外の選択肢を選ぶ
- defaultItemが選ばれてしまう

fix: combobox default-item optionのバグを修正する

---

src/components/Tooltip/Tooltip.tsx

Tooltip の利用用途として、HTML の構文上 div だと困ることが多いため span としたい。
https://smarthr.atlassian.net/browse/SHRUI-623

fix: Tooltip を div から span に変更

---

src/components/CheckBox/CheckBox.tsx
src/components/CheckBox/CheckBoxInput.tsx
src/components/Input/InputWithTooltip/InputWithTooltip.tsx
src/components/Input/SearchInput/SearchInput.tsx
src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/RadioButtonInput.tsx

react-hook-form など ref の公開を必要とする外部ライブラリに対応したい。
下記コンポーネントを forwardRef で置き換えた。
- SearchInput（内部で TooltipWithMessage）
- CheckBox（内部で CheckBoxInput）
- RadioButton（内部で RadioButtonInput）
また、以下コンポーネントは内部で ref を利用していたため別途対応予定。
- ComboBox
- DatePicker
- Textarea
以下コンポーネントは generics を含む場合の forwardRef の書き方がわからなかったため別途対応予定。
- Select

feat: 一部の入力系コンポーネントに ref を渡せるよう修正

---

src/components/DatePicker/DatePicker.tsx
src/components/DropZone/DropZone.tsx
src/components/InputFile/InputFile.tsx
src/components/Select/Select.tsx
src/components/Select/useClassNames.ts
src/components/Textarea/Textarea.tsx

#2929 で対応できなかったコンポーネントにも ref を渡せるように修正した。
diff は多いが、
```tsx
const Hoge: React.FC<Props> = (props) => {
const innerRef = useRef<HTMLElement>(null)
return <some-element ref={innerRef} />
}
```
となっているものを
```tsx
const Hoge = forwardRef<HTMLElement, Props>((props, ref) => {
const innerRef = useRef<HTMLElement>(null)
useImperativeHandle<HTMLElement | null, HTMLElement | null>(ref, () => innerRef.current)
return <some-element ref={innerRef} />
})
```
としただけで、内部処理には一切手を加えていない。
- DatePicker
- DropZone
- InputFile
- Select
- Textarea

feat: 入力系コンポーネントに ref を渡せるよう修正

---

src/components/DatePicker/DatePicker.tsx

- DatePickerのplaceholderを非推奨にしたい
- input系の対応は完了しており、指定が漏れていた
- placeholder は
- 色調の問題により視認しづらい
- 初期値と勘違いする
- 入力中に閲覧出来ないため短期記憶に不可をかける
- などの問題があり、基本的に他の手段を用いれる場合は利用を控えてもらいたいため

chore: date pickerのplaceholder optionを非推奨に変更

---

src/components/ComboBox/ComboBox.stories.tsx
src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/useListBox.tsx

- SingleComboBox編：https://github.com/kufu/smarthr-ui/pull/2920
SingleComboBoxに引き続き、MultiComboBoxのドロップダウンリストの幅を指定できるようにしました。
- MultiComboBoxにdropdownWidth propsを追加
- ヘルプメッセージの区切り線をsolidに変更、長い場合に折り返されるようにした
- StoryのdropdownHelpMessageの文言を修正

feat: MultiComboBoxのドロップダウンリストの幅を指定可能にする

---

src/components/AppNavi/AppNavi.tsx

`AppNavi` に対して、
```tsx
<AppNavi
buttons={[
{ children: 'ボタン' },
{ children: 'アンカー', href: '/' },
{ children: 'カスタム', tag: Link, href: '/' },
]}
/>
```
のようにボタンを設定した場合、３つ目のボタンがカスタムタグではなくアンカーとして扱われてしまう問題に対応します。
`AppNavi` 内のボタン判定がアンカー → ドロップダウン → カスタムタグ → ボタン の順で行われているため、カスタムタグのデータに `href` のフィールドが含まれていると先にアンカーとして判定されてしまうため。
- カスタムタグの判定を最初に行うようにした。
- `tag` フィールドは他のボタンの型には含まれていないので問題にはならないはず

fix: AppNavi においてカスタムタグ判定を最初に行うように変更

---

src/components/Dialog/useDialogPortal.ts
src/hooks/usePortal.tsx

#2936 
`document` に対する typeof の比較方法が間違っていたので修正します。
- typeof の比較対象を文字列に修正

fix: window.document に対する typeof の比較を修正

---

src/components/ComboBox/SingleComboBox.tsx
src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx

- 選択肢クリック時の動作を遅延させることでdropdownが閉じないように修正した
- 分かりづらいバグであり、smarthr-ui同士の組み合わせで発生する問題なのでsmarthr-uiで解決すると良さそうだったので。

fix: Dropdown系コンポーネント内で SingleComboBoxの選択肢をclickすると Dropdownが閉じてしまうバグを修正する

---

src/components/ComboBox/MultiComboBox.tsx
src/components/ComboBox/SingleComboBox.tsx

- Comboboxの調整を行います
- caret down にマウスオーバーしてもしてもマウスカーソルがinput用のままだったため、クリック用に調整
- inputにfocusした状態でdropdownを閉じさせる操作を行ったあと、caret down をクリックしてもdropdownが開かない問題を修正
- 再現手順: 適当に選択肢を選んだあと、inputにfocusされたままの状態でcaret downをクリックする

fix: ComboBoxのstyle調整 & inputにfocusしたままdropdownが閉じた状態でcaret downをクリックしてもdropdownが開かない問題を修正

---

src/components/Header/AppLauncher/AppLauncher.tsx

なし
アプリランチャーの「すべて見る」のリンク先が、現状用意できるページがないので、一旦これを出さない選択肢をとれるようにしたい。
urlToShowAll を渡さなかった場合に「すべて見る」を含むランチャーのフッター部分を表示しないようにした

feat: アプリランチャーの urlToShowAll props を optional にする

---

src/components/Input/InputWithTooltip/InputWithTooltip.tsx

https://smarthr.atlassian.net/browse/SHRUI-648
- SearchInput で width に`100%`などの比率を適用する場合に正しく親コンポーネントの幅を評価できない問題を修正しました
- width を定義した場合に InputWithTooltip の Tooltip コンポーネントおよびその子コンポーネントとなる Input コンポーネントのそれぞれに width を適用するようにしました

fix: InputWithTooltip で width に比率を渡しても適用されるようにする

---

src/components/ComboBox/ComboBox.stories.tsx
src/components/ComboBox/SingleComboBox.tsx

https://smarthr.atlassian.net/browse/SHRUI-646
- SingleComboBox の onClear の引数に event を渡せるようにした
- コンポーネントの利用側で event オブジェクトを利用したいケースがあったので
- SingleComboBox の onClear の型定義を修正
- onClearを呼び出している箇所で event オブジェクトを渡すようにした

feat: SingleComboBox の onClear の引数に event を渡せるようにした

---

src/components/BottomFixedArea/BottomFixedArea.stories.tsx
src/components/BottomFixedArea/TertiaryLink.tsx

- https://smarthr.atlassian.net/browse/SHRUI-650
- (okeで利用されていた)BottomFixedArea内でTertiaryLink利用時に多言語対応のためReactNodeを渡せるようにする
- ボタンテキストにReactNodeを渡せるように修正。
- StoryBoardのBottomFixedArea内TertiaryLink利用箇所の４番目の文言をspanでラップ

fix: bottomFixedArea/TertiaryLinkのtextにReactNodeを渡せるよう修正

---

src/components/Dropdown/FilterDropdown/FilterDropdown.tsx

- FilterDropdownのメインアクションボタンがSecondaryになっていた
- `value="primary"`となっていたので、おそらく指定が漏れている
-  `value="primary"`を`variant="primary"`に変更修正した

fix: FilterDropdownのvalueをvariantに変更

---

src/index.ts

#2948
`import { EmptyTableBody } from 'smarthr-ui/lib/components/Table'` のような書き方は面倒。 `from 'smarthr-ui'` でインポートできるようにしたい。
- export が漏れていたので足しました。
N/A

fix: インポートしやすいよう、トップレベルで EmptyTableBody を export

---

src/components/Header/Header.stories.tsx
src/components/Header/Header.tsx

🍐 
現状 Header の tenants props の型が `Tenant[] | string` になっていて、マルチテナントの場合は Tenant 型の配列、シングルテナントの場合はテナント名を文字列で渡す形になっている。
Header コンポーネントを使う側でシングルテナントかマルチテナントかを判断して値を整形して Header に渡す必要があり、手間がかかる。
使う側ではシングルテナントかマルチテナントかを意識せず、同じ形で props を渡せるようにしたい。
tenants props の型を `Tenant[]` だけにした。
シングルテナントの場合は tenants に length が1つの配列を渡す形になる。
プロダクト側では基本的に tenants という配列を持っているのでそれをそのまま渡す形で良いはず。
🍐

fix!: ヘッダーの tenants props の型を変更

---

src/components/CheckBox/CheckBox.stories.tsx
src/components/CheckBox/CheckBoxInput.tsx

特に無し
`CheckBox`にエラーのステータスを追加したいです。
ユースケースとしては同意を求めるチェックボックスにチェックを入れずにSubmitした場合などを想定しています。
- `CheckBoxInput.tsx`に`error`propsを追加
- `error`が`true`の場合にチェックボックスの外枠が赤くなるようCSSを追加
- Storybookにエラー状態のチェックボックスを追加

feat: CheckBoxにエラーのステータスを追加する

---

src/components/Header/AppLauncher/AppLauncher.tsx
src/components/Header/Header.tsx

🍐 
以下の3点の問題に対応したい。
- Header の tenants props に空の配列が渡されたときランタイムエラーが起きてしまう
- AppLauncher の urlToShowAll に `string | undefined` の他に null も許容したい
- AppLauncher の apps の type に `base` 以外の文字列も渡せるようにしたい
下の2点はランチャー API のレスポンスに合わせてそうしたい感じです。
- Header の tenants props に空の配列が渡されたときランタイムエラーが起きてしまう
- 👉 tenants.length が1以上のときにしか currentTenant を取得しないようにした
- AppLauncher の urlToShowAll に `string | undefined` の他に null も許容したい
- 👉 null 追加した
- AppLauncher の apps の type に `base` 以外の文字列も渡せるようにしたい
- 👉 type を string にした
🍐

fix: Header, AppLauncher の props で入れられる値を広げる

---

src/components/Header/AppLauncher/AppLauncher.tsx

🍐 
AppLauncher のドロップダウンでスクロールが発生してしまうので修正したい
line-height をつけることでスクロールが消えるので付与。
また、それによって行間が詰まっていたのも少し広くなりました。

fix: add line-height to AppLauncher

---

src/constants.ts
src/index.ts

https://smarthr.atlassian.net/browse/SHRUI-642
グラフに使用している色がプロダクト間で揺れていたため SmartHR UI で提供し統一を図ります。
その他のグラフ色を使ってるプロダクトはまだありませんが、合わせて追加しています。

feat: グラフ色を追加

---

src/components/MessageScreen/Footer.tsx

SmartHR基本機能のフッター上から`特定商取引法に基づく表記`リンクが削除されたので、smarthr-uiをこれに追従させたい。
フッターの`特定商取引法に基づく表記`リンクを削除しました。

fix: フッターの特定商取引法に基づく表記リンクを削除

---

src/components/RightFixedNote/RightFixedNote.tsx
src/components/RightFixedNote/RightFixedNoteItem.tsx

- コンポーネント内で固定で持つ文言を変更する手段をdecoratorsに統一します
- decorators以外の手段は後ほど削除予定です

feat: RightFixedNote に decoratorsオプションを追加

---

src/components/Loader/Loader.tsx

現状の Loader コンポーネントは、特定の条件下でスクロールバーが出現してしまいます。
👇 他の要素にホバーしたときに一瞬だけスクロールバーが表示されてしまっている様子
https://user-images.githubusercontent.com/14817308/214229233-8c6423d0-e30e-4c80-a4b9-9dd3a97383b6.mov
Loader コンポーネントのスタイルに `overflow: hidden;` を追記
👇 今回の修正でスクロールバーが出現しなくなっている様子
https://user-images.githubusercontent.com/14817308/214229751-e4486212-868e-4e07-ad97-503379503d6f.mov

fix: 特定の条件下で Loader コンポーネント使用時にスクロールバーが出現してしまう不具合を修正

---

src/components/Loader/Loader.tsx

- Loader コンポーネントの alt, text を ReactNodeに変更し、翻訳用コンポーネントなどを差し込めるようにする

feat: Loader の alt, text オプションを ReactNode に変更

---

e2e/components/Dialog/Dialog.PortalParent.test.ts
src/components/Dialog/Dialog.stories.tsx
src/components/Dialog/useDialogPortal.ts

`Dialog` コンポーネントが `portalParent` を指定したときに動かなくなっていた問題に対応します。
- 要素の生成方法が間違っていたのを修正
- e2e テストを追加

fix: ダイアログが `portalParent` 指定時に動かなくなっていた問題の修正

---

src/constants.ts

基本10色をプロダクト側で30色まで増やす想定でしたが、SmartHR UI 側で増やせば良いことに気がついたので拡張しました。
自然な色合いになるように `tint / shade` を使っています。機械的に増やした色のためコントラスト比などの担保はできません。プロダクト側でできるだけ色に頼らない使い方をする必要があります。
また、利用ライブラリの都合で、出力される色は、基本色が RGB 値で拡張値が HEX 値になっていますが特に問題ないと判断しました。

fix: チャート色を30色に拡張

---

src/components/Icon/Icon.tsx

- Iconコンポーネントのalt属性をReactNodeに変更します
- これにより、alt属性に対して翻訳用コンポーネントなどを設定することが可能になります

feat: Icon の alt属性を ReactNode に変更する
