kufu/smarthr-ui

src/components/AppBar/AppBar.tsx
@nabeliwo 
I think this would make more clear what the style is created.
What do you think?
=> Refactor a media query style

src/components/Modal/ModalEraser.tsx, src/components/Modal/ModalTrigger.tsx
Eraser は迷いましたがボタンにするケースがなくはなさそうなので一緒に変更しました。
=> :recycle: modal の trigger を button から div に変更する

README.md
=> add Badges and Install section into README

src/components/Modal/Box.tsx, src/components/Modal/ModalContent.tsx
- モーダルの背景をクリックしてモーダルを非表示にしたい！
- Box の DOM を変更
- 背景とコンテンツエリアを分離した
- ModalContent で hideModal() を Box へ渡すように変更
- Box の背景の要素をクリックで hideModal() するように変更した
=> モーダルの背景をクリックでモーダルを閉じるようにした

package.json, yarn.lock
This PR adds to check `tsc --noEmit` as a lint.
=> :wrench: add lint:tsc

src/components/Checkbox/__test__/__snapshots__/index.test.tsx.snap, src/components/Checkbox/__test__/index.test.tsx
Add some testings for checkbox component.
=> Add some tests for checkbox component

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx, src/components/Base/__test__/index.test.tsx, src/components/Base/index.ts
This PR adds `Base`, container component. currently theme is not supported.
=> Create Base component

src/components/Flash/Flash.tsx, src/components/Flash/__test__/index.test.tsx
This adds two test cases for Flash component.
=> Testing Flash component

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/index.ts
This PR add Button component.
https://github.com/kufu/smarthr-ui/projects/2#card-22295198
=> Add Button component

src/components/Modal/Box.tsx, src/components/Modal/Modal.stories.tsx
Support autoFocus in Modal component.
=> Support autoFocus in Modal

src/components/Modal/Modal.stories.tsx
eslint-disable jsx-a11y/no-autofocus
=> Ignore autofocus warning

src/components/Loader/Loader.stories.tsx, src/components/Loader/Loader.tsx, src/components/Loader/index.ts
- size : 's' or 'm' or 'l' (default : m)
- color: string (default : white in palette theme)
=> Add loader component

src/components/Pagination/Pagination.tsx
- Reset default margin and padding
- Publish className props as optional
=> Update Pagination component

src/index.ts
Button コンポーネントを使おうと思って import したら、 export されてないよのエラーになってしまったので export しました。
=> export button component

src/index.ts
added an export for importing Tag component
=> :sparkles: export tag component

src/components/Field/Field.tsx
when changed number to using pxToRem it was broken. so fixed it 😭
=> :bug: added missing theme to Tag in Field component

src/components/Field/Field.tsx
when there's some components in a Field component, unexpected click will be happened. so i removed label tag in a Field component. if u wanna wrap heading and input component by label tag, u can wrap Field component by label tag.
=> :shower: remove label tag

CHANGELOG.md, package.json
=> chore(release): 3.9.1

src/components/Button/Button.tsx
- remove redundant borders
- fix button font styles
- fix border color
=> fix button styles

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx, src/index.ts
Currently, override style of Base component using styledComponent doesn't work. Because, Base component can't receive className.
After merge this PR, Base component receive className from parent component.
I also fixed the problem of Base component doesn't export.
=> Update Base Component

src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx, src/components/Heading/index.ts, src/components/HeadlineArea/HeadlineArea.stories.tsx, src/components/HeadlineArea/HeadlineArea.tsx, src/components/HeadlineArea/index.tsx, src/index.ts
https://github.com/kufu/smarthr-ui/issues/261
https://github.com/kufu/smarthr-ui/issues/262
=> Create Heading / HeadlineArea components

src/components/Image/Images.stories.tsx, src/components/TabBar/README.md, src/components/TabBar/TabBar.stories.tsx, src/components/TabBar/TabBar.test.tsx, src/components/TabBar/TabItem.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, src/components/Table/Table.stories.tsx
As tabItem props, `children` are more intuitive than `label`. What do you think?
before
```tsx
<TabBar>
<TabItem id="1" onClick={action('clicked')} label="Tab" />
<TabItem id="2" onClick={action('clicked')} selected label="Selected" />
<TabItem id="3" onClick={action('clicked')} disabled label="Disabled" />
</TabBar>
```
after
```tsx
<TabBar>
<TabItem id="1" onClick={action('clicked')}>Tab</TabItem>
<TabItem id="2" onClick={action('clicked')} selected>Selected</TabItem>
<TabItem id="3" onClick={action('clicked')} disabled>Disabled</TabItem>
</TabBar>
```
=> Change TabItem's props

src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/__test__/__snapshots__/index.test.tsx.snap, src/components/CheckboxLabel/CheckboxLabel.tsx, src/components/Field/Field.tsx, src/components/Flash/Flash.tsx, src/components/Heading/Heading.tsx, src/components/HeadlineArea/HeadlineArea.tsx, src/components/Icon/Icon.tsx, src/components/Input/Input.tsx, src/components/Loader/Loader.tsx, src/components/Radio/Radio.tsx, src/components/RadioLabel/RadioLabel.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__test__/__snapshots__/index.test.tsx.snap
Allow all components to receive className props.
=> Add className props

src/components/Tag/README.md
fix tag's props type of enum value.
=> fix: Fix typo

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/index.ts, src/index.ts
=> Add select component

src/components/Flash/Flash.tsx
- Add background-color style to Flash component
- `background-color: #fff;`
=> fix: add background-color to Flash component

src/components/Button/BaseButton.tsx, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Select/Select.tsx
Change primitive components (Button, Select, Checkbox) interface in order to use with inteface of the DOM elements.
=> Change interface of Button, Select and Checkbox to conform to the DOM interface

src/components/Button/BaseButton.tsx, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Select/Select.tsx
=> Revert "Merge pull request #395 from wmoai/fix-primitive-component-interface"

src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.tsx
=> feat: export undo icon

package.json, yarn.lock
Some vulnerabilities was found by yarn audit in this project. Added resolutions field to fix it.
**Before**
```shell
> yarn audit
19 vulnerabilities found - Packages audited: 930300
Severity: 2 Low | 2 Moderate | 15 High
```
**After**
```shell
> yarn audit
0 vulnerabilities found - Packages audited: 930484
```
=> fix: add resolutions field

src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/Dialog/Dialog.controllable.stories.tsx, src/components/Dialog/Dialog.uncontrollable.stories.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/Field/Field.stories.tsx, src/components/Field/Field.tsx, src/components/Input/Input.stories.tsx, src/components/Input/Input.tsx, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/index.ts, src/components/RadioButtonLabel/RadioButtonLabel.tsx, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
- Input
- Field
- CheckBox
- CheckBoxLabel
- Select
- RadioButton
- RadioButtonLabel
Update props and component structure.
=> Update form element component props and structure

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx, src/components/Base/README.md
- Add `ref` props
- Add `background-color: #fff` style
- Clean storybook
=>  Extend Base component

src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
=> update: add background-color to StatusLabel

src/components/Dropdown/README.md
=> Add miss quote

src/components/DefinitionList/DefinitionListItem.tsx
- Add `line-height: 1.5` to `dd` tag
- Adjust the upper and lower margins of `dd` tag to accommodate changes in `line-height`
=> Update DefinitionList style

package.json, src/components/Table/Cell.tsx, yarn.lock
- Upgrade `@types/styled-components`
- Fix the error that caused build error by upgrade of `@types/styled-components`
=> Upgrade @types/styled-components

README.md
Fixed the example code in README.md for the update of the `ThemeProvider ` component.
=> docs: fix example code in README.md

src/components/Select/Select.tsx
Fixed it because it was broken in Firefox.
|BEFORE|AFTER|
|---|---|
|![image](https://user-images.githubusercontent.com/23610884/70291202-cebf8e80-181d-11ea-89f3-f803c839bfa9.png)|![image](https://user-images.githubusercontent.com/23610884/70291229-e39c2200-181d-11ea-925b-8a99c8b53368.png)|
=> bugfix(select): fix selectbox css

src/components/AccordionPanel/AccordionPanel.stories.tsx, src/components/AccordionPanel/AccordionPanel.tsx
Change behavior of defaultExpanded props.
**before**
`defaultExpanded` is reflected only once the first time the component is rendered.
**after**
Reflected every time `defaultExpanded` is changed.
=> Update defaultExpanded's behavior of AccordionPanel

src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap, src/components/RadioButton/RadioButton.tsx
=> Change radio button size

commitlint.config.js, package.json, yarn.lock
- Add [commitlint](https://github.com/conventional-changelog/commitlint)
- Add commitlint settong file
=> Introduce commitlint

src/components/Dialog/ActionDialogContentInner.tsx, src/components/Dialog/DialogContentInner.tsx, src/components/Dialog/DialogPositionProvider.tsx, src/components/Dialog/MessageDialogContentInner.tsx, src/components/Dialog/dialogHelper.ts
- Set `max-height` to the dialog's content area dynamically to prevent it from being bigger than the height of the window
=> feat: max-height for ActionDialog and MessageDialog

src/components/Field/Field.stories.tsx, src/components/Field/Field.tsx, src/components/Heading/Heading.tsx, src/components/Heading/index.ts
- add `labelType` and `labelTagType` props to use Heading for form label
- and add `HeadingTypes` type into Heading
- change layouts of help message and error message.
=> Modify Field component

src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
fix line-height for bordered label to fit its height
that includes border line width ( top & bottom )
closes #551
=> fix: fix line-height for StatusLabel

yarn.lock
I upgraded the package related to storybook
```
@storybook/addon-a11y@5.3.6
@storybook/addon-actions@5.3.6
@storybook/addon-viewport@5.3.6
@storybook/addons@5.3.6
@storybook/cli@5.3.6
@storybook/react@5.3.6
@storybook/theming@5.3.6
```
=> chore(deps-dev): update storybook

src/components/InformationPanel/InformationPanel.tsx
=> Fix InformationPanel layout

.stylelintrc, package.json, src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, yarn.lock
Update dependencies.
- styled-components
- @types/styled-components
- stylelint-config-standard
and modified rules to match stylelint rules.
When this PR is merged, the following PRs will be closed.
- https://github.com/kufu/smarthr-ui/pull/637
- https://github.com/kufu/smarthr-ui/pull/649
- https://github.com/kufu/smarthr-ui/pull/659
=> chore(deps): update styled-components and stylelint

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
select コンポーネントを optgroup 対応させます。
=> fix: add optgroup option for select

.circleci/config.yml, package.json, yarn.lock
- resolve yarn audit error
- add `yarn audit` command to CI task
=> chore: add yarn audit command to CI task

src/components/Footer/Footer.tsx
=> fix: change Footer base color

src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap, src/components/Header/Header.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, src/themes/createPalette.ts
- Create `BRAND` color on `createPalette.ts`
- Change Header color to `BRAND` color
- For the BRAND TEAM, lord of our company.
before:
after:
=> fix: Change header color

src/components/Button/SecondaryButton.tsx
=> fix: change SecondaryButton disabled style

package.json, yarn.lock
=> chore: update resolutions

src/components/TabBar/TabBar.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
Removing background color from TabBar according to interpretation of the design.
=> fix: remove background color from TabBar

package.json, yarn.lock
#785 のビルドエラーを修正するのがひと手間かかりそうだったので、
手動でアップデートして PR を作成した！
=> chore(deps): update dependency stylelint to ^13.6.0

src/components/RightFixedNote/RightFixedNote.tsx, src/components/RightFixedNote/RightFixedNoteItem.tsx
RightFixedNote のスタイルが extend できなかったので、 `className` を渡してあげるようにしますた。
=> fix: add className props to RightFixedNote and RightFixedNoteItem

src/components/Loader/Loader.stories.tsx, src/components/Loader/README.md
=> chore: add Loader's README

src/components/HeadlineArea/HeadlineArea.stories.tsx, src/components/HeadlineArea/README.md
- Create readme docs for `HeadlineArea` Component
- Add readme docs to stories
=> Add README.md to HeadlineArea component

src/components/Header/Header.stories.tsx, src/components/Header/README.md
https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99?selectedIssue=SHRUI-99
Adding README for `Header` component.
=> docs: add README for Header

src/components/Textarea/README.md, src/components/Textarea/Textarea.stories.tsx
https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99?selectedIssue=SHRUI-110
Adding README for `Textarea` component.
=> docs: add README for Textarea

src/components/Footer/Footer.stories.tsx, src/components/Footer/README.md
I added README for Footer component.
=> docs: add readme for footer

src/components/Header/Header.stories.tsx, src/components/Header/Header.tsx, src/components/Header/README.md
- none
- make header components customizable
- add options to hide listed items of header components
=> make header components customizable

src/constants.ts
https://smarthr.atlassian.net/browse/SHRUI-114
- font-family の指定を変更します。
- 各ブラウザにて、可能な限りフォントを変更可能な指定に変更します
=> fix: update font-family

src/components/Textarea/README.md
Related URL
https://smarthr.atlassian.net/browse/SHRUI-142
What I did
Update README for TextArea component.
=> docs: Update README to TextArea

src/components/Pagination/Pagination.tsx, src/components/Pagination/PaginationItem.tsx
https://smarthr.atlassian.net/browse/SHRUI-154
Add ARIA attributes into `Pagination` component
* change wrapper tag from `div` to `nav`, and add `aria-label`
* add `aria-current=page` into current page item
=> fix: add ARIA attributes into Pagination

src/components/Calendar/Calendar.tsx, src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap, src/components/DatePicker/Portal.tsx, src/components/Dialog/DialogContentInner.tsx, src/components/Dropdown/DropdownContentInner.tsx, src/components/FlashMessage/FlashMessage.tsx, src/components/Input/Input.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, src/components/TabBar/TabBar.tsx, src/components/TabBar/TabItem.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, src/components/Tooltip/TooltipPortal.tsx, src/themes/createTheme.ts, src/themes/createZIndex.ts
* https://smarthr.atlassian.net/browse/SHRUI-179
* z-indexの値を新たなthemeで定義する
* 定義した値をz-indexを利用してるコンポーネントに反映する
* createZIndex.tsを作成して、新たなthemeを定義
* z-indexを使っているコンポーネントの値を置き換え
* z-index: 1という不要の値を使っているコンポーネントの修正（TabBar）
レビューをお願いします！
=> feat: create zIndex theme

src/components/Calendar/CalendarTable.tsx, src/components/Calendar/YearPicker.tsx
https://smarthr.atlassian.net/browse/SHRUI-189
Calendarコンポーネントの `button` の中に `div` があり HTML エラーになっているので対応しました。
- `button` の中にある `div` を `span` に変更
- [Nu Html Checker](https://validator.w3.org/nu/) でエラーが発生しないこと
=> fix: change tag of calendar component

src/components/RadioButtonLabel/README.md, src/components/RadioButtonLabel/RadioButtonLabel.stories.tsx
- RadioButtonLabelコンポーネントにREADMEを追加しました。
- RadioButtonLabelコンポーネントにREADMEを追加
=> docs: add readme for radio-button-label

src/components/Calendar/CalendarTable.tsx, src/components/Calendar/YearPicker.tsx
https://smarthr.atlassian.net/browse/SHRUI-187
- button中にdivが存在してしまうパターンがあったので修正する
- 達成基準4.1.1 に適合しないため修正したい
- https://waic.jp/docs/WCAG21/Understanding/parsing.html
=> fix: replace div in button with span

src/components/AppNavi/appNaviHelper.tsx, src/components/Header/HeaderButton.tsx
https://smarthr.atlassian.net/browse/SHRUI-187
- button中にfigureが存在してしまうパターンがあったので修正する
- 達成基準4.1.1 に適合しないため修正したい
- https://waic.jp/docs/WCAG21/Understanding/parsing.html
=> fix: Replace figure in button with span SHRUI-187

src/components/StatusLabel/StatusLabel.stories.tsx, src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
StatusLabel の文字縦位置を修正。
- InVision に合わせて line-height と padding、min-width を修正
- Storybook を縦位置の違和感がわかりやすい日本語に変更（これも InVision に合わせた）
- borderStyle / fillStyle の記述が不要だったので削除
- themes → theme
- スナップショット更新
before | after
--- | ---
=> Fix status label

src/components/Base/Base.tsx, src/components/Base/DialogBase.tsx
https://smarthr.atlassian.net/browse/SHRUI-182
* divに属性値 radius 属性がついて HTML エラーが起きる
* 該当コンポーネント
* Base
* DialogBase
* AccordionPanel
* BottomFixedArea
* DefinitionList
* InformationPanel
* MessageScreen
* RIghtFixedNote
* Table
- コンポーネントの元となる`Base, DialogBase`コンポーネントの属性値によるスタイル変更を、transient propsでの変更に修正
radiusの値が`s=6、m=8`になっており、themeと揃ってなかったのが気になったので、themeの値提供時に改めて整備する
=> feat: change the attribute of radius

src/components/Pagination/Pagination.tsx, src/components/Pagination/PaginationControllerItem.tsx, src/components/Pagination/PaginationItem.tsx
https://smarthr.atlassian.net/browse/SHRUI-171
* Pagination がナビゲーションであることが晴眼者にしかわからない
* Pagination を正しくマークアップする
* Wrapのaria-labelの修正
* Wrapにroleを追加
* ページ数カレント表示ボタンが`disabled`になって、ページ数の読み上げがされないので`disabled`を無効化
* ページ数ボタンに`aria-label`を設定
見た目は特に変更なし
=> fix: add aria and role attributes to Pagenation

src/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap
- remove size props.
- fix spec.
=> fix: update Checkbox & Checkboxlabel spec

.github/workflows/e2e.yml, package.json, scripts/e2e.ts, scripts/waitStorybook.ts
#1177
- merge `setup` job on GitHub Actions into `e2e-win-matrix` for performance improvements
- create `scripts/e2e.ts` to handle the process of the storybook properly.
=> fix: e2e test on GitHub Actions

.storybook/preview-head.html
storybook の style 内に全角スペースが挟まっている部分があったので半角スペースに修正します。
- 半角スペースに修正
=> fix: change full-width space to half-width

.github/workflows/e2e.yml, package.json, scripts/e2e.ts, yarn.lock
Fixes #1200 
The issue seems to happen due to the build time of webpack after starting a storybook server.
https://github.com/kufu/smarthr-ui/runs/1506806109?check_suite_focus=true
So I've changed to finish the webpack build ahead of time rather than runtime.
I don't have confidence for the change, but it worth trying.
- build storybook before testing
- run HTTP server using `http-server`
=> test: run e2e using static storybook build

src/components/Pagination/README.md
https://smarthr.atlassian.net/browse/SHRUI-106
=> docs: add README.md for Pagination component

src/components/Input/Input.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-306
I want to use the color specification in the Story of the Input component from the theme palette.
Update story of Input Component.
🍐
=> chore: change the color of Input Component in storybook

CHANGELOG.md, package.json
=> chore(release): 12.0.0-0

src/components/DefinitionList/DefinitionList.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-310
- Replace old color code in storybook to use theme
- Replace Color
- #333 => palette.TEXT_BLACK
- color in Icon => palette.DANGER
- Replace Component
- Icon -> FaExclamationCircleIcon
=> docs: replace old color code of storybook to theme in DefinitionList (SHRUI-310)

src/components/AccordionPanel/AccordionPanel.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-307
I want to use the color specification in the Story of the AccordionPanel component from the theme palette.
Update story of AccordionPanel Component.
🍐
=> chore: change the color of AccordionPanel Component in storybook

src/components/MessageScreen/MessageScreen.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-312
I want to use the color specification in the theme palette for the Story of the MessageScreen component.
Update story of MessageScreen Component.
🍐
=> docs: replace the color code of MessageScreen Component in storybook(SHRUI-312)

src/components/Calendar/Calendar.tsx
This PR migrates the Icon component in the Calendar component, which does not affect anyone, just a refactoring.
I've replaced the Icon component with Fa***Icon components.
=> refactor: migrate Icon in Calendar

package.json, yarn.lock
- 利用されていない fixpack module を削除します
=> chore: yarn remove fixpack

src/components/Pagination/PaginationControllerItem.tsx
This PR migrates the Icon component in the Pagination component, which does not affect anyone, just a refactoring.
I've replaced the Icon component with Fa***Icon components.
=> refactor: migrate Icon in Pagination

src/components/Select/Select.tsx
This PR migrates the Icon component in the Select component, which does not affect anyone, just a refactoring.
I've replaced the Icon component with Fa***Icon components.
=> refactor: migrate Icon in Select

src/components/Button/BaseButton.tsx
#1234
https://eslint.org/docs/rules/no-shadow
Fix `no-shadow` error
* remove shadowing of `Tag`
=> test: no shadow

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
https://smarthr.atlassian.net/browse/SHRUI-303
This PR modifies `option` and `optgroup` of `Select` component to be able to set disabled.
* Modify `option` and `optgroup` can be set default attributes of each element (also `disabled`).
=> fix: enable to set disabled in Option of Select (SHRUI-303)

src/components/AppNavi/AppNavi.stories.tsx, src/components/AppNavi/AppNavi.test.tsx, src/components/AppNavi/README.md, src/components/BottomFixedArea/README.md, src/components/MultiComboBox/useListBox.tsx
This is a following up PR for #1304.
I missed some usages of `fa-***`🙏 🙏 🙏 
I've replaced the usages of `fa-***` with `Fa***Icon`, which includes a test file and documentation.
=> Use fa icon component

src/components/AccordionPanel/AccordionPanel.stories.tsx, src/components/AccordionPanel/AccordionPanel.tsx, src/components/AccordionPanel/AccordionPanelContent.tsx, src/components/AccordionPanel/AccordionPanelItem.tsx, src/components/AccordionPanel/AccordionPanelTrigger.tsx
Replace from `FC` to `VFC` in 'AccordionPanel`.
* replace from `FC` to `VFC`
=> chore: replace from FC to VFC in AccordionPanel (SHRUI-321)

CHANGELOG.md, package.json
=> chore(release): 12.2.1

src/components/BottomFixedArea/BottomFixedArea.tsx, src/components/BottomFixedArea/TertiaryLink.tsx, src/components/BottomFixedArea/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-252
`BottomFixedArea` コンポーネントの attributes を改善し、各パーツを特定可能にすると同時に、各部位にエスケープハッチを設ける。
references: https://github.com/kufu/smarthr-ui/pull/1290
=> fix: improve attributes of BottomFixedArea (SHRUI-252)

src/components/AppNavi/AppNavi.tsx, src/components/AppNavi/AppNaviAnchor.tsx, src/components/AppNavi/AppNaviButton.tsx, src/components/AppNavi/AppNaviCustomTag.tsx, src/components/AppNavi/AppNaviDropdown.tsx, src/components/AppNavi/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-248
`AppNavi` コンポーネントの attributes を改善し、各パーツを特定可能にすると同時に、各部位にエスケープハッチを設ける。
references: https://github.com/kufu/smarthr-ui/pull/1290
=> fix: improve attributes of AppNavi (SHRUI-248)

src/components/DefinitionList/DefinitionList.tsx, src/components/DefinitionList/DefinitionListItem.tsx
Replace from `FC` to `VFC` in `DefinitionList`.
- replace `FC`
=> chore: replace from FC to VFC in DefinitionList (SHRUI-321)

src/components/CheckBox/CheckBox.tsx
Replace from `FC` to `VFC` in `CheckBox`
- replace `FC`
=> chore: replace from FC to VFC in CheckBox (SHRUI-321)

src/components/DatePicker/DatePicker.tsx
Replace from `FC` to `VFC` in `DatePicker`.
- replace `FC`
=> chore: replace from FC to VFC in DatePicker (SHRUI-321)

src/components/DropZone/DropZone.tsx
Replace from `FC` to `VFC` in `DropZone`.
- replace `FC`
- fix type error
=> chore: replace from FC to VFC in DropZone (SHRUI-321)

src/components/InformationPanel/README.md
- [InformationPanel \- all ⋅ Storybook](https://smarthr-ui.netlify.app/?path=/story/informationpanel--all)
- Add a description for the togglable prop of InformationPanel
=> docs: add description for togglable of InformationPanel

src/components/CheckBoxLabel/CheckBoxLabel.tsx, src/components/CheckBoxLabel/__snapshots__/CheckBoxLabel.test.tsx.snap, src/components/CheckBoxLabel/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-256
`CheckBoxLabel` コンポーネントの attributes の改善と、特定可能なクラス名を付与しました。
- `CheckBoxLabel` コンポーネントの attributes の改善
- 特定可能なクラス名を付与
ref. https://github.com/kufu/smarthr-ui/pull/1290
=> fix: improve attributes of CheckBoxLabel (SHRUI-256)

src/components/Footer/Footer.tsx
https://smarthr.atlassian.net/browse/SHRUI-294
- 画面幅が小さくなった場合、リンクなどが読みづらくなる & 押しづらくなる問題に対応したい
- リンク、テキストの改行を禁止する
- 全て固定文字列のため許容しました
- 画面幅に合わせて段組みが流れるように調整
- その他軽めのリファクタリングを実施
=> Fix footer style

src/components/Base/Base.tsx, src/components/Base/DialogBase.tsx, src/components/Base/useClassNames.ts
- Dialog and DIalogBase needed their attributes improved.
- DialogBase component needed default class name.
- make them accept props as a native HTML element.
- added class name generator for DialogBase component, and applied it.
=> feat: improve attributes for Base and DialogBase

src/components/DefinitionList/DefinitionList.tsx, src/components/DefinitionList/DefinitionListItem.tsx, src/components/DefinitionList/useClassNames.ts
- ラッパーにdivに設定可能な属性を追加できるように調整
- classNameを複数箇所に設定
=> feat: improve attributes for DefinitionList

CHANGELOG.md, package.json, src/themes/__tests__/createTheme.ts, src/themes/createBreakpoint.ts, src/themes/createFrame.ts, src/themes/createRadius.ts, src/themes/createSize.ts, src/themes/createTheme.ts
#1475
hotfix で行った修正と、リリースコミットを master に取り込みます。
修正部分については hotfix 時にレビュー済みです。
=> fix: Merge hotfix v12.3.0 to master

src/components/HeadlineArea/HeadlineArea.tsx
In `HeadlineArea`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in HeadlineArea (SHRUI-321)

src/components/Header/Header.tsx, src/components/Header/HeaderButton.tsx, src/components/Header/HeaderCrewDropdown.tsx, src/components/Header/HeaderNotification.tsx, src/components/Header/HeaderUserDropdown.tsx
In `Header`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in Header (SHRUI-321)

src/components/InformationPanel/InformationPanel.tsx
In `InformationPanel`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in InformationPanel (SHRUI-321)

src/components/Heading/Heading.tsx
In `Heading`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in Heading (SHRUI-321)

src/components/Button/DangerButton.tsx, src/components/Button/PrimaryButton.tsx, src/components/Button/SecondaryButton.tsx, src/components/Button/SkeletonButton.tsx, src/components/Button/TextButton.tsx, src/components/Button/useClassNames.ts
- https://smarthr.atlassian.net/browse/SHRUI-257
- added default class names to button components
- PrimayButton
- SecondaryButton
- DangerButton
- SkeletonButton
- TextButton
- create `useClassNames` and apply it to button components
- remove some unnecessary codes
=> feat: add default class names to button components

src/components/Icon/Icon.tsx
In `Icon`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in Icon (SHRUI-321)

src/components/Image/BlankImage.tsx
In `BlankImage`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in BlankImage (SHRUI-321)

src/components/FieldSet/FieldSet.tsx
In `FieldSet`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in FieldSet (SHRUI-321)

src/components/FlashMessage/FlashMessage.tsx, src/components/FlashMessage/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-264
- FlashMessage needed own attributes improved.
- FlashMessage component needed default class name.
- make them accept props as a native HTML element.
- added class name generator for FlashMessage component, and applied it.
=> feat: improve attributes for FlashMessage

src/components/ComboBox/MultiComboBox.tsx
https://smarthr.atlassian.net/browse/SHRUI-364
If `MultiComboBox` does not contain a break line, height of `MultiComboBox` is `42px` or `46px`.
This PR is modify the height to be `40px`.
- Remove unnecessary wrapper
- Modify spacing and layout considering border width
=> fix: modify height of MultiComboBox (SHRUI-364)

CHANGELOG.md
hotifix の CHANGELOG.md を master に反映します！！
=> chore(release): 12.3.2

src/components/CompactInformationPanel/CompactInformationPanel.stories.tsx, src/components/CompactInformationPanel/CompactInformationPanel.tsx, src/components/CompactInformationPanel/README.md, src/components/CompactInformationPanel/index.ts, src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-365
新しいコンポーネントを追加しました。
アイコンの縦位置を揃えるために、本文のデフォルト行間を `1.5` にしています。
=> CompactInformationPanel を追加

src/components/Calendar/Calendar.tsx, src/components/Calendar/CalendarTable.tsx, src/components/Calendar/YearPicker.tsx, src/components/Calendar/useClassNames.ts
- Calendar needed own attributes improved.
- Calendar component needed default class name.
- make them accept props as a native HTML element.
- added class name generator for Calendar component, and applied it.
=> feat: improve attributes for Calendar

src/components/IndexNav/IndexNav.tsx
In `IndexNav`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in IndexNav (SHRUI-321)

README.md
The current example in README.md doesn't work 😭
=> docs: fix invalid syntax in README

src/components/Dialog/ActionDialog.tsx, src/components/Dialog/ActionDialogContent.tsx, src/components/Dialog/ActionDialogContentInner.tsx, src/components/Dialog/Dialog.tsx, src/components/Dialog/DialogContentInner.tsx, src/components/Dialog/MessageDialog.tsx, src/components/Dialog/MessageDialogContent.tsx, src/components/Dialog/MessageDialogContentInner.tsx, src/components/Dialog/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-259
- Dialog needed own attributes improved.
- Dialog component needed default class name.
=> feat: improve attributes for Dialog

src/components/FlashMessage/FlashMessage.tsx
In `FlashMessage`, replace from `FC` to `VFC`.
=> chore: replace from FC to VFC in FlashMessage (SHRUI-321)

package.json, yarn.lock
- #1540 
- #1540 requires stylelint > 13.13.0, so I also update it.
- ☝️ 
- N/A
=> chore(deps): update dependency stylelint-config-standard to v22, stylelint to v13.13.0

src/components/Table/Table.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-407
- Checkbox in `<Table>` story has no label and alternative text
- `<ClickableCell>` can not click by keyboard
- Add label to Checkbox by visuallyHiddenText
- Add Header cell text by visuallyHiddenText
- Clickable cell can operable also keyboard 
No different
=> Fix `<Table>` all story accessible [SHRUI-407]

src/components/Layout/Cluster/Cluster.stories.tsx, src/components/Layout/Cluster/Cluster.tsx, src/components/Layout/Cluster/README.md, src/components/Layout/Cluster/index.ts, src/components/Layout/LineUp/LineUp.stories.tsx, src/components/Layout/LineUp/LineUp.tsx, src/components/Layout/LineUp/README.md, src/components/Layout/LineUp/index.ts, src/components/Layout/Stack/README.md, src/components/Layout/Stack/Stack.stories.tsx, src/components/Layout/Stack/Stack.tsx, src/components/Layout/Stack/index.ts, src/components/Layout/index.ts, src/hooks/useSpacing.ts, src/index.ts, src/themes/createSpacing.ts
新 `spacing` を使った余白を管理するレイアウトコンポーネントを追加しました。
=> Layout コンポーネントを追加

src/components/ComboBox/SingleComboBox.tsx
=> fix: modify SingleComboBox to be expected width when set percentage width

src/components/FormGroup/FormGroup.stories.tsx
Replace from `FC` to `VFC` in `FormGroup`
- Replace `FC`
=> chore: replace from FC to VFC in FormGroup

src/components/InputFile/InputFile.tsx
Replace from `FC` to `VFC` in `InputFile`
- Replace `FC`
=> chore: replace from FC to VFC in InputFile

src/components/Loader/Loader.tsx
Replace from `FC` to `VFC` in `Loader`
- Replace `FC`
=> chore: replace from FC to VFC in Loader

src/components/ComboBox/MultiComboBox.tsx
Replace from `FC` to `VFC` in `MultiComboBox`
=> chore: replace from FC to VFC in MultiComboBox

src/components/Pagination/Pagination.tsx, src/components/Pagination/PaginationControllerItem.tsx, src/components/Pagination/PaginationItem.tsx
Replace from `FC` to `VFC` in `Pagination`
=> chore: replace from FC to VFC in Pagination

src/components/RightFixedNote/RightFixedNote.tsx, src/components/RightFixedNote/RightFixedNoteItem.tsx
Replace from `FC` to `VFC` in `RightFixedNote`
=> chore: replace from FC to VFC in RightFixedNote

src/components/SegmentedControl/SegmentedControl.tsx
Replace from `FC` to `VFC` in `SegmentedControl`
=> chore: replace from FC to VFC in SegmentedControl

src/components/SideNav/SideNav.tsx, src/components/SideNav/SideNavItem.tsx
Replace from `FC` to `VFC` in `SideNav`
=> chore: replace from FC to VFC in `SideNav`

src/components/RadioButton/RadioButton.tsx
Replace from `FC` to `VFC` in `RadioButton`
=> chore: replace from FC to VFC in `RadioButton`

src/components/RadioButtonLabel/RadioButtonLabel.tsx
Replace from `FC` to `VFC` in `RadioButtonLabel`
=> chore: replace from FC to VFC in `RadioButtonLabel`

src/components/SmartHRLogo/SmartHRLogo.tsx
Replace from `FC` to `VFC` in `SmartHRLogo`
=> chore: replace from FC to VFC in `SmartHRLogo`

src/components/StatusLabel/StatusLabel.tsx
Replace from `FC` to `VFC` in `StatusLabel`
=> chore: replace from FC to VFC in `StatusLabel`

src/components/Textarea/Textarea.tsx
Replace from `FC` to `VFC` in `Textarea`
=> chore: replace from FC to VFC in `Textarea`

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipPortal.tsx
Replace from `FC` to `VFC` in `Tooltip`
=> chore: replace from FC to VFC in `Tooltip`

src/themes/ThemeProvider.tsx
Replace from `FC` to `VFC` in `ThemeProvider`
- Change props of `ThemeProvider` simple.
=> chore: replace from FC to VFC in `ThemeProvider`

package.json
Reverts kufu/smarthr-ui#1558
reg-suiteが必ずコケてしまう状態になったのでrevertします。
=> Revert "chore(deps): update node.js to >=v12.22.1"

src/components/CheckBox/CheckBox.tsx, src/components/CheckBoxLabel/CheckBoxLabel.tsx
- https://smarthr.atlassian.net/browse/SHRUI-378
- https://github.com/kufu/smarthr-ui/pull/1604
- ☝️ これを今後 CheckBox と CheckBoxLabel の代わりに使う
詳細は上記 PR をご確認ください 🙏
=> feat: deprecate CheckBox and CheckBoxLabel

src/index.ts
=> fix: Cluster のインポートを追加

src/components/SegmentedControl/SegmentedControl.tsx, src/components/SegmentedControl/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-283
`SegmentedControl` コンポーネントの属性に関する改善を行います。
- wrapper である div 要素のデフォルト属性を渡せるように変更
=> feat: `SegmentedControl` の属性の改善 (SHRUI-283)

src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, src/components/StatusLabel/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-286
`StatusLabel` コンポーネントの属性に関する改善を行います。
- wrapper である span 要素のデフォルト属性を渡せるように変更
=> feat: `StatusLabel` の属性の改善 (SHRUI-286)

src/components/TabBar/TabBar.tsx, src/components/TabBar/TabItem.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, src/components/TabBar/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-287
`TabBar` コンポーネントの属性に関する改善を行います。
- wrapper 要素のデフォルト属性を渡せるように変更
- デフォルト属性の内、コンポーネント内で指定するため外から上書きできない属性 (`role` など) も omit
=> feat: `TabBar` の属性の改善 (SHRUI-287)

src/components/CompactInformationPanel/CompactInformationPanel.tsx, src/components/CompactInformationPanel/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-435
`CompactInformationPanel` コンポーネントの属性に関する改善を行います。
- escape hatch 用のクラス追加
- wrapper である `Base` コンポーネントの、要素としてのデフォルト属性を渡せるように変更
=> feat: `CompactInformationPanel` の属性の改善 (SHRUI-435)

src/components/RightFixedNote/RightFixedNote.tsx, src/components/RightFixedNote/RightFixedNoteItem.tsx, src/components/RightFixedNote/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-282
`RightFixedNote` コンポーネントの属性に関する改善を行います。
- 各パーツ
- title
- item
- itemEditButton
- itemText
- itemDate
- itemAuthor
- textarea
- submitButton
- wrapper である form 要素のデフォルト属性を渡せるように変更
=> feat: `RightFixedNote` の属性の改善 (SHRUI-282)

src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx
className 入れてなかったので足した。
ほか
- HTML の基本的な属性をつけられるようにした
- Story 内の不要な記述を削除
=> fix: Text を styled-component で wrap できなかったので修正｜ SHRUI-439

src/components/LineClamp/LineClamp.stories.tsx
lint warning が発生していたので解消します。
- 複数回参照する長文は文字列変数に置き換え
- 直接 HTML に記述する部分は `'` を `&apos;` に置き換え
=> test: lint warning の解消

CHANGELOG.md, package.json
=> chore(release): 13.2.0

.circleci/config.yml, .github/workflows/e2e.yml, .github/workflows/publishRelease.yml, .github/workflows/startRelease.yml
#1746 
CI 上の `yarn install` で `yarn.lock` が変更されないように `--frozen-lockfile` オプションを追加
- `--frozen-lockfile` 追加
=> test: CI 上の yarn install に `--frozen-lockfile` を追加

src/components/FloatArea/FloatArea.stories.tsx, src/components/FloatArea/FloatArea.tsx
FloatArea で `p > div` になっている箇所があったので修正しました。
また primaryButton だけの場合にボタンが左に寄っていたため修正しました。
=> FloatArea で p > div になっていたので修正、ほか

CHANGELOG.md, package.json
Conventional Commit ではないログを反映させるための手動コミット
元： https://github.com/kufu/smarthr-ui/pull/1810
=> chore(release): 14.0.1

src/components/HeadlineArea/README.md
`HeadlineArea` の README 内の間違った記述を修正します。
- `heading.heading` になっていたので `heading.children` に修正
- 間違った defaultValue を修正
- テーブルのマークダウンが壊れているのを修正
=> docs: `HeadlineArea` の README を修正

CHANGELOG.md, package.json
=> chore(release): 14.1.0

.github/CODEOWNERS
=> chore: レビュワーを調整

.github/CODEOWNERS
@wmoai san をグループに入れられなかったのでこの方法でうまくいくか試してみます
=> chore: レビュワー追加

src/themes/createColor.ts
=> fix: TextColors に TEXT_WHITE を追加し忘れていた

src/components/Input/Input.tsx
- #1908
- https://smarthr.atlassian.net/browse/SHRUI-460
#1908 の修正に合わせて Input のスタイリングを見直しました。高さは Button のデフォルトと合います。
=> feat!: Input のスタイリングを見直す｜SHRUI-460

src/components/Select/Select.tsx
- #1908
- #1909
Button や Input の修正に合わせて Select のスタイリングを見直しました。Button や Input と同じ高さになります。
=> feat!: Select のスタイリングを見直す

CHANGELOG.md
- CHANGELOGに `<Sidebar>` を追加したことを追記
- BREAKING CHANGEの説明を追加
=> chore: fix change log version 15

CHANGELOG.md, package.json
=> chore(release): 15.0.1

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx
`Base` の story を CSF 形式に変更し、 DocsPage を有効にします。
- CSF 形式に変更
- props に説明を追加
=> docs: `Base` の story 整備 (SHRUI-464)

src/components/Button/BaseButton.tsx
ボタンコンポーネントの DocsPage に表示される各 Props の説明を日本語化します。
- Props の説明を日本語化
=> docs: Button の Props 説明を日本語化 (SHRUI-464)

src/index.ts
=> fix: Sidebar を export

src/index.test.ts
こういうことが起こりがち。
https://github.com/kufu/smarthr-ui/pull/2038
現状 src/components 直下のものであれば、 src/index.ts で export されていることをテストしているが、 src/components/Layout/** のように、ネストしたものを export するテストはない。
Layout は今後も増えそうなのでテストを追加したい。
src/components/Layout 内のコンポーネントが src/components/Layout/index.ts を経由して src/index.ts から export されることを保証するテストを追加した。
今後もこういうパターンのディレクトリが増えるのであれば、そのときに Layout に限らない汎用的に扱えるテストを追加するのが良さそう。
=> test: components/Layout のコンポーネントが export されていることを保証するテストを追加

src/components/Button/Button.stories.tsx, src/components/Calendar/calendarHelper.test.ts, src/components/FlashMessage/FlashMessageList/useFlashMessageList.tsx, src/components/Icon/Icon.tsx, src/themes/__tests__/createRadius.ts
=> fix: fix typos

src/components/Layout/Cluster/Cluster.stories.tsx, src/components/Layout/Layout.stories.tsx, src/components/Layout/LineUp/LineUp.stories.tsx, src/components/Layout/Sidebar/Sidebar.stories.tsx, src/components/Layout/Stack/Stack.stories.tsx, src/index.test.ts
https://smarthr.atlassian.net/browse/SHRUI-468
Layout 下の各コンポーネント
- Cluster
- LineUp
- Sidebar
- Stack
の story を `Layout` 配下にまとめます。
- Layout 下に story をまとめた
- テスト調整
=> docs: Layout コンポーネントの story をまとめる (SHRUI-468)

src/components/Button/BaseButton.tsx
fontSize.S を標準フォントサイズの場合に 14px になるようにした。
参考：
https://codepen.io/uknmr/pen/YzQmPVJ
=> fix: fontSize.S の影響で Button[size=s] の縦揃えに影響していたので修正

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/DropdownContent.tsx, src/components/Dropdown/DropdownTrigger.tsx
`Dropdown` の story のメンテナンスを行います。
- story 形式を CSF に変更
- Props 説明コメントを追加
=> chore: `Dropdown` の story のメンテナンス (SHRUI-464)

src/components/BottomFixedArea/BottomFixedArea.stories.tsx, src/components/BottomFixedArea/BottomFixedArea.tsx
`BottomFixedArea` の story のメンテナンスを行います。
- story 形式を CSF に変更
=> chore: `BottomFixedArea` の story メンテナンス (SHRUI-464)

src/components/DropZone/DropZone.stories.tsx, src/components/DropZone/DropZone.tsx
`DropZone` の story メンテナンスを行います。
- story 形式を CSF に変更
- 各 Props の説明コメントを追加
=> chore: `DropZone` の story メンテナンス (SHRUI-464)

src/components/Downloader/Downloader.stories.tsx
,https://smarthr.atlassian.net/browse/SHRUI-464
`Downloader` の story を CSF に変更します。
ただし、 `Downloader` は TBD なので story 自体にまだあまり意味はないです。
- story を CSF に変更
=> chore: `Downloader` の story を CSF に変更 (SHRUI-464)

src/components/FieldSet/FieldSet.stories.tsx, src/components/FieldSet/FieldSet.tsx
`FieldSet` の Story のメンテナンスを行います。
- Story 形式を CSF に変更
=> chore: `FieldSet` の Story メンテナンス (SHRUI-464)

src/components/FlashMessage/FlashMessage.stories.tsx, src/components/FlashMessage/FlashMessage.tsx
`FlashMessage` の Story をメンテナンスします。
- DocsPage に Props テーブルが表示されるように修正
=> chore: `FlashMessage` の Story メンテナンス (SHRUI-464)

src/components/BackgroundJobsPanel/OmittableJobText.tsx, src/components/Balloon/Balloon.stories.tsx, src/components/Balloon/Balloon.tsx, src/components/LineClamp/LineClamp.stories.tsx, src/components/LineClamp/LineClamp.tsx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/TooltipPortal.tsx, src/index.ts
以下の非推奨コンポーネントを削除します。
- `LightBalloon`
- `DarkBalloon`
- `LightTooltip`
- `DarkTooltip`
代替として `Balloon`, `Tooltip` コンポーネントを使うことを推奨しています。
- 当該非推奨コンポーネントを削除
- 削除した非推奨コンポーネントを使っている箇所を推奨コンポーネントに置き換え
=> chore!: Light/Dark Balloon, Light/Dark Tooltip の削除 (SHRUI-464)

src/components/FloatArea/FloatArea.stories.tsx, src/components/FloatArea/FloatArea.tsx
`FloatArea` の Story のメンテナンスを行います。
- Story 形式を CSF に変更
=> chore: `FloatArea` の Story メンテナンス (SHRUI-464)

src/components/Footer/Footer.stories.tsx
=> chore: `Footer` の Story を CSF に変更 (SHRUI-464)

src/components/FormGroup/FormGroup.stories.tsx, src/components/FormGroup/FormGroup.tsx
`FormGroup` コンポーネントの Story メンテナンスを行います。
- Story 形式を CSF に変更
=> chore: `FormGroup` の Story メンテナンス (SHRUI-464)

src/components/ComboBox/MultiComboBox.tsx, src/components/ComboBox/MultiSelectedItemInner.tsx, src/components/ComboBox/SingleComboBox.tsx, src/components/ComboBox/multiComboBoxHelper.ts, src/components/ComboBox/useListBox.tsx, src/components/Dropdown/DropdownScrollArea.tsx, src/components/Dropdown/dropdownHelper.ts, src/components/InputFile/InputFile.tsx, src/components/Select/Select.tsx, src/hooks/useOuterClick.ts, src/hooks/usePortal.tsx
https://smarthr.atlassian.net/browse/SHRUI-519
IE サポートを終了したので、 IE 用に入れていたコードを削除します。
- IE コメントのある部分を修正、削除
- `-ms` プレフィックスのついたスタイルを削除
=> chore: IE 対応のコードを削除 (SHRUI-519)

src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.tsx
`Icon` コンポーネントの Story のメンテナンスを行います。
- 不要な story parameter を削除
- 各 Props の説明を日本語化
=> docs: `Icon` の Story メンテナンス (SHRUI-464)

src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx
`Heading` コンポーネントの story のメンテナンスを行います。
- story を CSF に変更
- 各 Props にコメント追加
=> docs: `Heading` の story メンテナンス (SHRUI-464)

src/components/IndexNav/IndexNav.stories.tsx, src/components/IndexNav/IndexNav.tsx
`IndexNav` コンポーネントの Story のメンテナンスを行います。
- Props の説明コメントを追加
=> docs: `IndexNav` の Story メンテナンス (SHRUI-464)

src/components/InformationPanel/InformationPanel.stories.tsx, src/components/InformationPanel/InformationPanel.tsx
`InformationPanel` コンポーネントの Story のメンテナンスを行います。
- Props の説明コメントを追加
=> docs: `InformationPanel` の Story メンテナンス (SHRUI-464)

src/components/Layout/Cluster/Cluster.tsx, src/components/Layout/LineUp/LineUp.tsx, src/components/Layout/Sidebar/Sidebar.tsx, src/components/Layout/Stack/Stack.tsx
- Layout 下の各コンポーネントの Story のメンテナンスを行います。
- Props に説明コメントを追加
=> docs: Layout 関連コンポーネントの Story メンテナンス (SHRUI-464)

CONTRIBUTING.md
#2130 
マークダウン内のリンク記法の不備を修正します。
- 不要なスペースの削除
=> chore: CONTRIBUTING.md のリンク修正

src/components/InputFile/InputFile.stories.tsx, src/components/InputFile/InputFile.tsx
`InputFile` の Story メンテナンスを行います。
=> docs: `InputFile` の Story メンテナンス

src/components/LineClamp/LineClamp.stories.tsx, src/components/LineClamp/LineClamp.tsx
`LineClamp` の Story メンテナンスを行います。
=> docs: `LineClamp` の Story メンテナンス

src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx
`Pagination` の Story メンテナンスを行います。
- コンポーネントの Props が interface だと CSF 化できなかったので type に変更
=> docs: `Pagination` の Story メンテナンス

src/components/InformationPanel/InformationPanel.stories.tsx, src/components/InformationPanel/InformationPanel.tsx
Informationpanel の Story.all が all ではなかったので追記しつつ日本語化した。
ついでに内部処理のリファクタリングをしたが、それを PR タイトルにした。 cf17f2397fc14e45619e3e9f873cf526d96816fc
=> fix: InformationPanel の内部処理を memo 化

src/components/TextLink/TextLink.stories.tsx, src/types.ts
=> Revert "fix: Story 内の styled-component に theme の型を効かせる"

src/components/Dropdown/Dropdown.stories.tsx
Dropdown の Story を SmartHR のプロダクトでよく使われる形に修正しました。
また合わせて日本語化しました。
before | after
--- | ---
=> chore: Dropdown の Story をよく使われる実装に合わせる

src/components/Layout/Layout.stories.tsx, src/components/Layout/Reel/README.md, src/components/Layout/Reel/Reel.stories.tsx, src/components/Layout/Reel/Reel.tsx, src/components/Layout/Reel/index.ts, src/components/Layout/index.ts, src/index.ts
- https://smarthr.atlassian.net/browse/SHRUI-544
- https://every-layout.dev/layouts/reel/
add `<Reel>` Component
- add Reel Component
- make story has TabItems, Table
- set defaultViewport
=> feat: add Reel component

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
=> docs: `Select` の Story メンテナンス

src/components/SegmentedControl/SegmentedControl.stories.tsx, src/components/SegmentedControl/SegmentedControl.tsx
`SegmentedControl` の Story メンテナンスを行います。
=> docs: `SegmentedControl` の Story メンテナンス

src/components/SideNav/SideNav.stories.tsx, src/components/SideNav/SideNav.tsx, src/components/SideNav/SideNavItem.tsx
`SideNav` の Story メンテナンスを行います。
=> docs: `SideNav` の Story メンテナンス

src/components/SmartHRLogo/SmartHRLogo.stories.tsx, src/components/SmartHRLogo/SmartHRLogo.tsx
`SmartHRLogo` の Story メンテナンスを行います。
- 各 Props の説明コメントを追加
=> docs: `SmartHRLogo` の Story メンテンナス

src/components/StatusLabel/StatusLabel.stories.tsx, src/components/StatusLabel/StatusLabel.tsx
`StatusLabel` の Story メンテナンスを行います。
=> docs: `StatusLabel` の Story メンテナンス

src/components/InformationPanel/InformationPanel.tsx
Change props type to ReactNode from string for internationalization.
=> feat: string to ReactNode InformationPanel

src/components/Layout/LineUp/LineUp.tsx
https://smarthr.atlassian.net/browse/SHRUI-558
横並びのレイアウトは `Cluster` や `Sidebar` によって実現できるため、`LineUp` コンポーネントを非推奨にします。
- `LineUp` を deprecated に変更
=> chore: `LineUp` を非推奨にする (SHRUI-558)

src/components/Dialog/ActionDialogContent.tsx, src/components/Dialog/ActionDialogContentInner.tsx, src/components/Dialog/DialogContentInner.tsx, src/components/Dialog/MessageDialogContent.tsx, src/components/Dialog/MessageDialogContentInner.tsx
ダイアログコンポーネントの Props 説明を日本語に統一します。
- コメントを日本語化
- 一部の内部 Props の定義位置を改善
=> docs: ダイアログコンポーネントの Props 説明を日本語化 (SHRUI-464)

src/components/Select/Select.tsx
`Select` コンポーネント内で theme の参照が間違っているところを修正します。
- `theme` を `themes` に変更
=> fix: `Select` 内の theme の参照を修正

src/components/ComboBox/useListBox.tsx
#2588 をパッチリリースするために、パッチリリース用ブランチ `patch-v21.4.1` にバグ修正を取り込む PR です
=> fix: 部分的レンダリングの問題解消のバックポート

src/components/Header/Header.tsx
=> fix: ヘッダーが ThemeProvider 前提で書かれている箇所を useTheme を使うように修正

src/components/Header/Header.tsx, src/components/Header/HeaderDropdownButton.tsx, src/components/Header/HeaderLink.tsx
=> fix: `Header` の theme 参照修正のバックポート対応

src/components/Header/Header.tsx, src/components/Header/HeaderDropdownButton.tsx, src/components/Header/HeaderLink.tsx
=> fix: `Header` 関連コンポーネントの theme 参照の修正

package.json
=> chore: 他プロジェクトと合わせて dev コマンドを追加

src/components/StatusLabel/StatusLabel.stories.tsx, src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
色は Aqua04 を使っています。
https://smarthr.design/basics/colors/#h4-1
=> feat: StatusLabel に type=green を追加

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/DropdownButton/DropdownButton.stories.tsx, src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
https://github.com/kufu/smarthr-ui/pull/2516#discussion_r883176953
=> docs: DropdownButton と FilterDropdown の Story を Dropdown のサブコンポーネントとした

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx, src/components/Base/index.ts
Base の値は radius のデザイントークを参照するように変更しました。
DialogBase は deprecated で削除予定のため修正していません。
=> fix: Base の radius をデザイントークンに対応付け

src/components/Dropdown/DropdownButton/DropdownButton.stories.tsx
=> docs: DropdownButton の Story を修正

src/components/NotificationBar/NotificationBar.stories.tsx, src/components/NotificationBar/NotificationBar.tsx
NotificationBar のアテンションが低い課題を解決するためにスライドインアニメーションを追加しました。
プロデザ内で議論、すり合わせ済みです。
=> feat: NotificationBar にスライドインアニメーションを追加

.eslintrc.js, src/components/ComboBox/SingleComboBox.tsx, src/components/ComboBox/useListBox.tsx, src/components/FieldSet/FieldSet.stories.tsx, src/components/Input/Input.stories.tsx, src/components/NotificationBar/NotificationBar.stories.tsx, src/components/RightFixedNote/RightFixedNote.tsx, src/components/Table/Table.stories.tsx
- useCallback のdependencies array の設定漏れを修正する
- 他、eslintのwarnを修正する
=> fix: hooksの設定漏れを修正する

src/components/ComboBox/SingleComboBox.tsx
- SingleComboBoxにprefixを指定できるようにする
- レアケースだが、フィルターとしてcomboboxを利用するパターンが存在するため、対応可能にしたい
=> feat: single combo box に prefix optionを追加する

package.json, src/components/DatePicker/datePickerHelper.ts, yarn.lock
- @smarthr/wareki が 半角変換済みの文字列日付を返すようになったためロジックを調整したい
- datepickerの内部処理をwareki内で完結させるように修正
=> chore: Update smarthr wareki

src/components/Icon/Icon.tsx
プロダクトで必要になったので`FaRegClock`アイコン追加しました。
=> feat: faRegClockアイコンを追加

src/components/InputFile/InputFile.stories.tsx, src/components/InputFile/InputFile.tsx
- label に ReactNodeを渡せるようにします
- decorator optionを実装し、翻訳などを設定可能にします
=> feat: InputFileの文言を変更可能にする

src/components/PageCounter/PageCounter.stories.tsx, src/components/PageCounter/PageCounter.tsx, src/components/PageCounter/index.ts, src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-611
「5,000件中 1–50件」という表記で作りました。
=> feat: PageCounter を追加

src/components/ComboBox/ComboBox.stories.tsx, src/components/ComboBox/MultiComboBox.tsx, src/components/ComboBox/MultiSelectedItem.tsx, src/components/ComboBox/SingleComboBox.tsx, src/components/ComboBox/useListBox.tsx
- 多言語対応などを行う際、combobox内に固定で存在する文字列も対象にしたいのでdecoratorを実装する
=> feat: combo box に decorator option を追加する

src/components/Header/AppLauncher/AppLauncher.tsx
https://github.com/kufu/smarthr-ui/pull/2581 と全く同じ対応です。
=> fix: アプリランチャー内の import 記述の変更 

src/components/Textarea/Textarea.stories.tsx, src/components/Textarea/Textarea.tsx, src/types/props.ts
=> feat: textarea に decorators props を追加

src/components/InformationPanel/InformationPanel.stories.tsx, src/components/InformationPanel/InformationPanel.tsx
- コンポーネント内で固定で持つ文言を変更する手段をdecoratorsに統一します
- decorators以外の手段は後ほど削除予定です
=> feat: InformationPanel に decoratorsオプションを追加

src/components/InputFile/InputFile.tsx
- コンポーネント内で固定で持つ文言を変更する手段をdecoratorsに統一します
- decorators以外の手段は後ほど削除予定です
=> feat: InputFile に decoratorsオプションを追加

src/components/Table/EmptyTableBody.tsx
- `EmptyTableBody`にclassNameを追加
- `EmptyTableBody`にclassNameが渡ってなかったので追加した
=> feat: EmptyTableBodyにclassNameを追加

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
- コンポーネント内で固定で持つ文言を変更する手段をdecoratorsに統一します
- decorators以外の手段は後ほど削除予定です
=> feat: Select に decoratorsオプションを追加

src/components/Header/Header.stories.tsx, src/components/Header/Header.tsx
- 翻訳用コンポーネントなどを差し込めるよう、stringからReactNodeに変更します
=> feat: Header コンポーネントのtenants[number].name を string から ReactNode に変更

commitlint.config.js
=> chore: commitlintの設定を調整する

src/components/Experimental/SideMenu/SideMenuItem.tsx
実装都合で `li` につけていた`aria-current="page"` を `<a />` に付けました。
=> fix: SideMenu の current が iOS の VoiceOver で効いていなかったので修正

src/components/Header/Header.stories.tsx
=> chore: AppLauncher のアイテム名を抽象化

.storybook/main.js, package.json, yarn.lock
- Storybookにstoryのソースコードを直接表示するaddonを入れてみました。
- https://storybook.js.org/addons/@storybook/addon-storysource
- GitHubのコードを見ずに使い方を知りたいことが多かったため。
=> feat: storysourceを追加

src/components/Dialog/Dialog.stories.tsx, src/components/Dialog/MessageDialog.tsx, src/components/Dialog/MessageDialogContent.tsx, src/components/Dialog/MessageDialogContentInner.tsx
- 翻訳用コンポーネントなどを差し込めるよう、decoratorsオプションを追加します
=> feat: MessageDialog に decorators オプションを追加する

src/components/Dialog/ActionDialog.tsx, src/components/Dialog/ActionDialogContent.tsx, src/components/Dialog/ActionDialogContentInner.tsx, src/components/Dialog/Dialog.stories.tsx
- 翻訳用コンポーネントなどのために、コンポーネント内部の固定テキストを書き換えるため、decoratorsを追加します
=> feat: ActionDialog に decorators オプションを追加する

src/components/Experimental/SideMenu/SideMenu.stories.tsx, src/components/Experimental/SideMenu/SideMenuItem.tsx
=> fix: SideMenu の現在地色が背景色の上に載ると見えなかったので調整

src/components/Select/Select.tsx
=> chore: Selectの型が厳密すぎるため使いやすく調整する

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx
Base に Table を入れる場合など、overflow を処理するために styled-components でオーバーライドすることが多いので props として生やしました。
=> feat: Base に overflow を追加

src/components/ComboBox/SingleComboBox.tsx
=> fix: SingleComboBox 内の typo を修正

src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/CheckBoxInput.tsx, src/components/CheckBox/index.ts, src/components/Table/Table.stories.tsx, src/components/Table/Td.tsx, src/components/Table/TdCheckbox.tsx, src/components/Table/Th.tsx, src/components/Table/ThCheckbox.tsx
- https://smarthr.atlassian.net/browse/SHRUI-610
- #3131
#3131 でチェックボックスを入れる Th の幅調整だけ行う予定だったが、label や不可視テキストの扱いを考えるとすべてをまとめてコンポーネント化した方が良いと考え Th と Td それぞれ CheckBox と一体化したコンポーネントを作成した。
=> feat: ThCheckbox と TdCheckbox を追加

src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
誤ってmasterに直接コミットしてしまったのでrevertします。
=> chore: 誤ってmasterに直接pushしたコミットをrevert

src/components/ComboBox/ComboBox.stories.tsx, src/components/ComboBox/MultiComboBox.tsx, src/components/ComboBox/SingleComboBox.tsx, src/components/ComboBox/types.ts
- required属性を設定可能にした
- aria属性などをinputAttributesで設定可能にした
- comboboxのinput要素にrequired属性やaria属性を設定可能にしたい
=> feat: ComboBoxのinput要素にrequired属性と、それ以外の属性を設定できるinputAttributesを追加する

src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx, src/components/RadioButtonPanel/RadioButtonPanel.tsx, src/components/RadioButtonPanel/index.ts, src/components/RadioButtonPanel/useClassNames.ts, src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-687
パネル型の見た目を持つ RadioButtonPanel を実装しました。
=> feat: RadioButtonPanel を追加

src/components/FormGroup/FormGroup.stories.tsx, src/components/FormGroup/FormGroup.tsx, src/components/FormGroup/useClassNames.ts
- https://smarthr.atlassian.net/browse/SHRUI-595
- #3356
- #3357
一部プロダクトで実装されていた、入力例と補足文を取り入れました。
#3356 #3357 がマージされてからマージします。
=> feat: FormGroup に入力例と補足文を追加

src/components/SpreadsheetTable/SpreadsheetTable.stories.tsx, src/components/SpreadsheetTable/SpreadsheetTable.tsx, src/components/SpreadsheetTable/SpreadsheetTableCorner.tsx, src/components/SpreadsheetTable/index.ts, src/index.ts
CSV データの取り込みなど、スプレッドシート的な例を表現するためのコンポーネントです。
=> feat: SpreadsheetTable を追加

src/components/CompactInformationPanel/CompactInformationPanel.stories.tsx, src/components/CompactInformationPanel/CompactInformationPanel.tsx, src/components/CompactInformationPanel/useClassNames.ts, src/components/Dialog/ActionDialog/ActionDialog.tsx, src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx, src/components/Dialog/FormDialog/FormDialog.tsx, src/components/Dialog/FormDialog/FormDialogContentInner.tsx, src/components/Dropdown/FilterDropdown/FilterDropdown.tsx, src/components/FlashMessage/FlashMessage.tsx, src/components/FlashMessage/useClassNames.ts, src/components/InformationPanel/InformationPanel.tsx, src/components/ResponseMessage/ResponseMessage.stories.tsx, src/components/ResponseMessage/ResponseMessage.tsx, src/components/ResponseMessage/index.ts, src/index.ts
ResponseMessage を作りました。
- ResponseMessage を追加
- 既存の実装を書き換えました
- CompactInformationPanel
- ActionDialog
- FormDialog
- FilterDropdown
- FlashMessage
- InformationPanel
=> feat: ResponseMessage を追加

src/components/Button/Button.tsx, src/components/Loader/Loader.tsx
アクセシビリティ試験で発覚。
Button > Loader など button > div のように invalid な HTML になる可能性があったため修正。
=> fix: Button[loading] の invalid な HTML を修正

src/components/FormGroup/FormGroup.tsx
アクセシビリティ試験で発覚。
valid な HTML となるように修正。
=> fix: FormControl や Fieldset に不要な属性や値があたらないように修正

src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx
アクセシビリティ試験で発覚。
RadioButtonPanel 内に div が紛れているので修正。
=> fix: RadioButtonPanel の Story で HTML が valid になるよう修正

src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx
- HeadingにvisuallyHiddenオプションを追加します
- Navの中など、 `a11y的にHeadingを設置したいがUI上見せたくない` 場合などに利用できるようにします
=> feat: HeadingにvisuallyHiddenオプションを追加する

src/components/SectioningContent/SectioningContent.tsx
=> feat: SectioningContent系コンポーネントに対してdata-specなどの属性を設定可能にする

src/components/CheckBox/CheckBoxInput.tsx
=> fix: Checkboxのmixed属性が意図せず表示されてしまう問題を修正

src/components/AccordionPanel/AccordionPanelTrigger.tsx, src/components/AppNavi/AppNavi.tsx, src/components/Calendar/Calendar.tsx, src/components/DefinitionList/DefinitionList.stories.tsx, src/components/Dialog/Dialog.stories.tsx, src/components/FieldSet/FieldSet.tsx, src/components/FloatArea/FloatArea.stories.tsx, src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx, src/components/HeadlineArea/HeadlineArea.tsx, src/components/Layout/Center/Center.stories.tsx, src/components/Layout/Cluster/Cluster.stories.tsx, src/components/Layout/LineUp/LineUp.stories.tsx, src/components/Layout/Reel/Reel.stories.tsx, src/components/Layout/Sidebar/Sidebar.stories.tsx, src/components/Layout/Stack/Stack.stories.tsx, src/components/MessageScreen/MessageScreen.tsx, src/components/NotificationBar/NotificationBar.stories.tsx, src/components/Pagination/Pagination.tsx, src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx, src/components/RightFixedNote/RightFixedNote.tsx, src/components/SectioningContent/SectioningContent.stories.tsx, src/components/SectioningContent/SectioningContent.tsx, src/components/SideNav/SideNav.stories.tsx
=> chore: eslintのwarningを修正

src/index.ts
- PageHeadingコンポーネントが正しくexportされていなかった問題を解決します
=> fix: PageHeadingのexportミスを修正

src/components/Dialog/Dialog.stories.tsx, src/components/Dialog/RemoteTriggerActionDialog/RemoteTriggerActionDialog.tsx, src/components/Dialog/RemoteTriggerFormDialog/RemoteTriggerFormDialog.tsx, src/components/Dialog/RemoteTriggerMessageDialog/RemoteTriggerMessageDialog.tsx, src/components/Dialog/useRemoteTrigger.ts
- RemoteTriggerActionDialogなどRemoteDialogTriggerを利用するDialogにonToggle, onOpen, onCloseオプションを追加します
- hooksなどを利用している場合でTriggerとDialogそれぞれで開閉時に処理を差し込みたい事があるため、対応できるようにします
=> feat: RemoteTrigger系Dialogに onToggle, onOpen, onCloseオプションを追加する

src/components/SpreadsheetTable/SpreadsheetTable.stories.tsx, src/components/SpreadsheetTable/SpreadsheetTable.tsx
- styled-components でスタイリングを上書けるように className を追加
- Story を追加
=> fix: SpreadsheetTable に className を追加

src/components/SectioningContent/SectioningContent.tsx
=> feat: SectioningContent系コンポーネントに対してrefを設定可能にする

src/components/AccordionPanel/AccordionPanel.stories.tsx
T/O
Base コンポーネントに `overflow="hidden"` しました。
| --- |  --- |
| ![image](https://github.com/kufu/smarthr-ui/assets/14817308/758a0223-66bd-4fda-8963-19d293995744) | ![image](https://github.com/kufu/smarthr-ui/assets/14817308/aa002e42-dc67-4def-bdeb-ce4c1bf47e72) |
=> chore: AccordionPanel の story で角丸を突き破ってるところがあったので修正

src/components/AppNavi/AppNaviAnchor.tsx, src/components/AppNavi/AppNaviButton.tsx, src/components/AppNavi/AppNaviCustomTag.tsx, src/components/AppNavi/AppNaviDropdown.tsx, src/components/AppNavi/appNaviHelper.tsx
=> chore: AppNaviのローカルコンポーネント(styled-components)に対してhtmlとして存在しない要素を設定しwarningが出ていたため修正

src/components/Switch/Switch.stories.tsx, src/components/Switch/Switch.tsx, src/components/Switch/index.ts, src/index.ts, test-runner-jest.config.js
https://smarthr.atlassian.net/browse/SHRUI-723
I/F は [type=checkbox] をそのまま流用しました。
`:has` を使った実装をしているため、サポート外ブラウザではネイティブのチェックボックスを代替表示しています。
=> feat: Switch を追加

src/components/Base/Base.stories.tsx, src/components/Base/BaseColumn.stories.tsx
デザインシステムで Story が表示されない不具合を解消します。
https://smarthr.design/products/components/base-column/
=> docs: BaseColumn の Story を分離

.eslintrc.js, src/components/Icon/generateIcon.tsx, src/components/Pagination/PaginationItem.tsx, src/hooks/useId.tsx, src/hooks/usePortal.tsx, src/themes/ThemeProvider.tsx, src/themes/createBorder.ts, src/themes/createBreakpoint.ts, src/themes/createFontSize.ts, src/themes/createFrame.ts, src/themes/createInteraction.ts, src/themes/createLeading.ts, src/themes/createPalette.ts, src/themes/createRadius.ts, src/themes/createShadow.ts, src/themes/createSize.ts, src/themes/createSpacing.ts, src/themes/createTheme.ts, src/themes/createZIndex.ts
=> chore: interface を type に変更する

src/components/Dialog/FormDialog/FormDialog.tsx, src/components/Dialog/FormDialog/FormDialogContentInner.tsx
=> fix: FormDialogのonSubmit時に画面が更新されてしまう場合があるため、FormEventをpreventDefaultする

src/components/ComboBox/MultiComboBox.tsx, src/components/ComboBox/SingleComboBox.tsx, src/components/ComboBox/useClassNames.ts
SingleComboBoxとMultiComboBoxにpropsで`ref`を渡せるようにします。
* それぞれのコンポーネントに`forwardRef`で`ref`を渡せるようにしました
=> feat: ComboBoxにrefを渡せるようにする

src/components/PageCounter/PageCounter.tsx
[JIRA](https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99?selectedIssue=SHRUI-780)
- PageCounterをTailwindCSS化
- PageCounterをTailwindCSSで書き換える作業を実施
- Storybookを用いて、変化がないことを確認済み。
=> feat: PageCounterをTailwindCSS化

src/components/Button/ButtonWrapper.tsx
[tailwind-variants v0.1.17](https://github.com/nextui-org/tailwind-variants/releases/tag/v0.1.17) で Boolean value の欠陥が治っていたので追従しました。
=> fix: tailwind-variants の修正を取り込み Button に反映

e2e/components/ComboBox/MultiComboBox.test.ts, src/components/Button/UnstyledButton.tsx
=> feat: UnstyledButton を Tailwind CSS 化

src/components/PageCounter/PageCounter.tsx
=> feat: PageCounterにdecoratorsを追加する

src/components/Table/Table.tsx, src/components/Table/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-747
=> refactor: Table を Tailwind CSS 化

src/components/PageCounter/PageCounter.tsx
=> chore: run prettier

src/components/NotificationBar/NotificationBar.stories.tsx, src/components/NotificationBar/NotificationBar.tsx
2ペインなど一部の画面で利用しにくかったため、Base を敷いて利用できるように調整しました。
=> feat: NotificationBar に下地の概念を追加

src/components/Base/Base.stories.tsx, src/components/Base/Base.tsx, src/components/Base/useClassNames.ts
https://smarthr.atlassian.net/browse/SHRUI-744
=> refactor: Base を Tailwind CSS 化

src/components/Layout/Center/Center.stories.tsx, src/components/Layout/Center/Center.tsx, src/components/Table/TdCheckbox.tsx, src/components/Table/ThCheckbox.tsx
https://smarthr.atlassian.net/browse/SHRUI-762
=> refactor: Center を Tailwind CSS 化

src/components/Table/Table.stories.tsx
=> docs: Table の Story を最新化

src/components/InformationPanel/VRTInformationPanel.stories.tsx
InformationPanelコンポーネントにVRT用のStoryを追加しました。
- VRT Narrow
- 画面幅の狭い状態
InformationPanelのストーリーに対してVRT用のストーリーを追加しました。
=> chore: InformationPanelのVRT用Storyを追加

src/smarthr-ui-preset.ts
n/a
＿人人人人人人＿
＞　Firefoxx　＜
￣Y^Y^Y^Y^Y^Y^￣
`s/Firefoxx/Firefox/`
n/a
=> chore: Fix typo in comment

src/components/Badge/Badge.tsx
=> refactor: Badge を Tailwind CSS 化

src/components/Icon/Icon.tsx
- 開発機能でFaRobotアイコンを使いたいので追加しました
- https://fontawesome.com/icons/robot?f=classic&s=solid 
- FaRobotを追加
=> feat: Robotアイコンを追加

src/components/Experimental/SideMenu/SideMenu.tsx
実験的なコンポーネントとしていた SideMenu は 2024-01 に削除することに決まりました。
SideNav などの別コンポーネントで代替するか、UI を見直す必要があります。
SmartHR のプロダクトにおいては問題を共有済みで見直しに向けて動き始めています。
=> chore: SideMenu を非推奨に変更

src/components/Layout/Stack/Stack.stories.tsx
=> Fix typo Stack.stories.tsx

e2e/components/ComboBox/SingleComboBox.test.ts, src/components/ComboBox/ComboBox.stories.tsx, src/components/ComboBox/MultiComboBox.tsx, src/components/ComboBox/MultiSelectedItem.tsx, src/components/ComboBox/SingleComboBox.tsx
- form内にcomboboxを設置した状態でキーボード操作すると、高確率で発生するバグっぽい挙動のため、対応したい
=> fix: form内にcomboboxが存在する場合、アイテムの選択をEnterキーで行うとformがsubmitされてしまう問題に対応する

src/components/Input/Input.tsx, src/components/StatusLabel/StatusLabel.tsx
[JIRA](https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99/backlog?selectedIssue=SHRUI-790)
- 対象箇所にshr-bg-whiteを追加
=> fix: Input と StatusLabel に白背景を追加

src/components/TabBar/TabBar.tsx, src/components/TabBar/TabItem.tsx
=> refactor: 細かなレビュー指摘を修正

src/components/Dialog/ModelessDialog.tsx, src/components/Dialog/useClassNames.ts
=> refactor: ModelessDialog を Tailwind CSS 化

src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
=> fix: FilterDropdown[disabled] 時のアイコン色を修正

src/components/Table/TdCheckbox.tsx
https://smarthr.atlassian.net/browse/SHRUI-820
=> refactor: TdCheckbox を Tailwind 化する

src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
https://smarthr.atlassian.net/browse/SHRUI-806
=> refactor: FilterDropdown を Tailwind CSS 化

src/components/Icon/Icon.tsx
🍐 
プロダクトで必要なアイコンを追加したい
FaPaintBrush を追加
=> feat: Icon に FaPaintBrush を追加

src/components/Header/HeaderLink.tsx
https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99/backlog?selectedIssue=SHRUI-848
- HeaderLinkをTailwindCSS化する
=> refactor: HeaderLinkをTailwindCSS化する

src/components/Header/HeaderLink.tsx
=> fix: HeaderLink に className を渡せるように修正

src/components/TabBar/TabBar.stories.tsx, src/components/TabBar/TabItem.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
=> fix: TabItem の余白を調整

src/components/NotificationBar/NotificationBar.tsx, src/smarthr-ui-preset.ts
- 誤 notifiction
- 正 notification
notifiction → notification に置き換え。
通知領域のアニメーションを決定する箇所なので、変更前後で動作に問題がないことをStorybookを使って確認しています。
=> fix: NotificationBar の typo を修正

src/components/PageCounter/PageCounter.tsx
https://smarthr.atlassian.net/browse/SHRUI-814
=> refactor: PageCounter を Tailwind CSS 化

.storybook/preview.tsx, src/components/Pagination/Pagination.tsx
https://smarthr.atlassian.net/browse/SHRUI-907
=> fix: Pagination の reset css 依存を修正

.storybook/preview.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx, src/components/FormGroup/FormGroup.tsx, src/components/Input/Input.tsx, src/components/NewFieldset/Fieldset.stories.tsx
- https://smarthr.atlassian.net/browse/SHRUI-891
- https://smarthr.atlassian.net/browse/SHRUI-890
=> fix: Input と Fieldset の normazlize 依存を修正

.storybook/preview.tsx, src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx, src/components/RadioButtonPanel/RadioButtonPanel.tsx
=> fix: RadioButtonPanel の normazlize 依存を修正

.storybook/preview.tsx, src/components/Textarea/Textarea.stories.tsx, src/components/Textarea/Textarea.tsx
=> fix: Textarea の normalize 依存を修正する

.storybook/preview.tsx, src/components/Table/Th.tsx
https://smarthr.atlassian.net/browse/SHRUI-882
=> fix: Table の normazlize 依存を修正

src/components/SpreadsheetTable/SpreadsheetTable.tsx, src/components/SpreadsheetTable/SpreadsheetTableCorner.tsx
https://smarthr.atlassian.net/browse/SHRUI-817
https://smarthr.atlassian.net/browse/SHRUI-818
=> refactor: SpreadsheetTable を Tailwind CSS 化

src/components/DefinitionList/DefinitionList.stories.tsx, src/components/DefinitionList/DefinitionList.tsx, src/components/DefinitionList/DefinitionListItem.tsx
=> feat: DefiinitionList の用語の見た目を変える termStyleType を追加

src/components/AppNavi/AppNavi.stories.tsx, src/components/AppNavi/AppNaviDropdown.tsx, src/components/AppNavi/appNaviHelper.tsx
=> feat: AppNavi の normazlize 依存を修正

src/components/ComboBox/useListBox.tsx, src/components/Input/Input.tsx, src/smarthr-ui-preset.ts
https://smarthr.atlassian.net/browse/SHRUI-885
=> fix: コンボボックスの normalize 依存を修正

src/components/Experimental/SideMenu/SideMenu.tsx, src/components/Experimental/SideMenu/SideMenuGroup.tsx, src/smarthr-ui-preset.ts
=> fix: SideMenu の normalize 依存を修正

src/components/Dialog/ActionDialog/ActionDialog.tsx, src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
https://smarthr.atlassian.net/browse/SHRUI-826
=> refactor: ActionDialog を Tailwind CSS 化する

src/components/Table/TableReel.tsx, src/components/Table/useClassNames.ts, src/components/Table/useReelShadow.ts
https://smarthr.atlassian.net/browse/SHRUI-823
=> refactor: TableReel を Tailwind CSS 化

src/components/SectioningContent/SectioningContent.tsx
=> refactor: Section, Article, Aside, Nav, SectioningFragmentをTailwindCSS化

src/components/ErrorScreen/ErrorScreen.tsx
https://smarthr.atlassian.net/browse/SHRUI-910
=> fix: ErrorScreen の normalize 依存を修正

.storybook/preview.tsx, src/components/TabBar/TabItem.tsx, src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
https://smarthr.atlassian.net/browse/SHRUI-909
=> fix: TabBar の normalize 依存を修正

src/components/Calendar/CalendarTable.tsx
https://smarthr.atlassian.net/browse/SHRUI-879
Calendar の日付選択部分のスタイリングが適切にあたっていなかったため修正。
=> fix: Calendar の日付選択領域のスタイリングを修正

src/components/ComboBox/ComboBox.stories.tsx, src/components/DropZone/DropZone.tsx, src/components/FormControl/FormControl.stories.tsx, src/components/FormGroup/FormGroup.tsx, test-runner-jest.config.js
FormControl と紐づかない不具合を修正しました。
紐づかなかったコンポーネント：
- SingleComboBox
- MultiComboBox
- DropZone
=> fix: 一部のコンポーネントと FormControl が紐づかない不具合を修正

src/components/Table/EmptyTableBody.tsx, src/components/Table/Table.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-822
=> refactor: EmptyTableBody を Tailwind CSS 化

src/components/Header/AppLauncher/AppLauncher.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1711025190194169
=> fix: AppLauncherのホバー時の表示を修正

src/components/NotificationBar/NotificationBar.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1711026498409739?thread_ts=1711025190.194169&cid=CGC58MW01
=> fix: NotificationBarのホバー時とフォーカス時のデザインを修正

src/components/Header/HeaderDropdownMenuButton.tsx
https://smarthr.atlassian.net/browse/SHRUI-849
=> refactor: HeaderDropdownMenuButtonをTailwindCSS化

src/components/FloatArea/FloatArea.tsx
=> fix: 記述を整理

src/components/ResponseMessage/ResponseMessage.stories.tsx, src/components/ResponseMessage/ResponseMessage.tsx
https://smarthr.atlassian.net/browse/SHRUI-858
=> refactor: ResponseMessage を Tailwind CSS 化

src/components/ErrorScreen/Footer.tsx
=> refactor: Footer を Tailwind CSS 化

src/components/Icon/Icon.tsx
=> feat: FaChartColumnIcon を追加

src/components/Dropdown/SortDropdown/useSortDropdown.ts
smarthr の textlint によると並び替えではなく並べ替えらしいです。
=> fix: SortDropdown のラベルを修正

src/components/ComboBox/useListBox.tsx
**SmartHR UI　Combobox Multi「読込中」読込中であることがわからない　NVDA**
https://app.asana.com/0/1205448161364688/1206305498133144/f
問題の原因は #4558 と同じなので、それを参照してください。
Comboboxを展開するとlistbox自体が動的にマウントされるので、live regionがportalの外側に来るように変更しました。また、ローダーにaria-hiddenを追加しました。
N/A
=> fix: Combobox内のlistboxのlive regionが読み上げるよう修正

src/components/Icon/Icon.tsx
=> feat: Icon に FaStar を 追加

src/components/Fieldset/Fieldset.tsx, src/components/FormControl/index.ts
https://github.com/kufu/smarthr-ui/pull/4587#discussion_r1572049316
=> fix: FormControl から内部コンポーネントが export されないように修正

src/components/Table/BulkActionRow.tsx
=> fix: 強制カラーモードの時は一括操作領域に枠線を付ける

src/components/FormControl/FormControl.tsx
=> chore: fix typo in FormControl.tsx

src/components/Button/Button.tsx, src/components/ComboBox/useListBox.tsx, src/components/DatePicker/Portal.tsx, src/components/Dropdown/Dropdown.tsx, src/hooks/usePortal.tsx
https://smarthr.atlassian.net/browse/SHRUI-948
Next.js環境でhydration errorが発生する件について修正した
createPotalをマウント後に実施するようにした
（useEffectの引数を取っていないので、取る形に直した方が良さそうであればご指摘いただけると助かります）
=> fix: Next.js環境でhydration errorが発生する問題の修正

.github/workflows/publishRelease.yml, .github/workflows/startRelease.yml
モノレポ後のリリース、初手でコケました
https://github.com/kufu/smarthr-ui/actions/runs/8921624957/job/24502090469
上記のコケていた箇所と、コケそうな箇所を直しました。
=> refactor: リリースがコケるところを修正

packages/smarthr-ui/src/components/FormControl/FormControl.tsx
FormControlのエラーメッセージを読み上げ通知に対応させたい
https://smarthr.atlassian.net/browse/SHRUI-861?atlOrigin=eyJpIjoiZjY2MWI5ZmE5YWU5NDE0Zjg2MmM4N2YwZWJjNGEzNzQiLCJwIjoiaiJ9
これまで、 `FormControl` コンポーネントでは `errorMessages` として ReactNode を受け取っていましたが、これに支援技術からアクセスするのが困難でした。なぜなら、カーソルはページを上から下に移動するのにエラーメッセージは入力欄の上に表示されていて、ライブリージョンにも対応していなかったため、エラーメッセージが表示されても気づきにくいからです。
これを改善するため、`FormControl`の`errorMessages`が更新されたときに、支援技術に対して通知を行うようにしました。また、入力欄にフォーカスがあたっているときも値が無効であることが分かるようにしました。
エラーメッセージを表示する部分のDOM要素に`role=alert`属性を付与しました。これによって、`errorMessages`が更新されたときに自動的に支援技術に通知が行われます。具体的な挙動は、後述の動画を見るとわかりやすいと思います（音声あり）
また、`errorMessages`が空の配列ではないときに、FormControlの子要素のうち最初のInputコンポーネントに対して `error: true` propを付与することにしました。これは内部的に、入力欄の枠線を赤くし、`aria-invalid="true"`を付与しています。 …
=> fix: FormControlのエラーメッセージをlive regionに変更

packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx, packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
https://smarthr.atlassian.net/browse/SHRUI-998
=> feat!: FilterDropdownのhasStatusText propsをOmitする

.github/workflows/titleCheck.yml
script injection される可能性があったので修正
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
=> fix: titleCheck action の script injection 対策

packages/smarthr-ui/src/components/DatePicker/DatePicker.stories.tsx, packages/smarthr-ui/src/components/DatePicker/DatePicker.tsx
Nstock さんからの要望
onBlur を渡せないように omit していたため、外から渡せるように修正しました。
=> feat: DatePicker に onBlur を渡せるように修正

packages/smarthr-ui/.storybook/preview.tsx, packages/smarthr-ui/src/hooks/useDevice/index.ts, packages/smarthr-ui/src/hooks/useDevice/useDevice.stories.tsx, packages/smarthr-ui/src/hooks/useDevice/useDevice.ts, packages/smarthr-ui/src/index.ts, packages/smarthr-ui/src/themes/createBreakpoint.ts
https://smarthr.atlassian.net/browse/SHRUI-990
副作用を各コンポーネントで持たなくていいように、各プロダクト側で判別してもらうための hooks を追加する。
```jsx
const { isNarrowView } = useDevice()
```
=> feat: useDevice を追加

packages/smarthr-ui/src/components/Button/Button.tsx, packages/smarthr-ui/src/components/Loader/Loader.stories.tsx, packages/smarthr-ui/src/components/Loader/Loader.tsx
=> fix: 不要なスタイリングを消す

.husky/commit-msg
- [migration guide](https://github.com/typicode/husky/releases/tag/v9.0.1)
- https://github.com/kufu/smarthr-ui/pull/4330
- husky v9対応時の変更漏れに対応したい
- migration guideに沿ってスクリプトから不要になった記述を削除しました
- 🍐
=> chore: husky v9 スクリプト対応

packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx, packages/smarthr-ui/src/components/Button/UnstyledButton.tsx, packages/smarthr-ui/src/components/ComboBox/ListBoxItemButton.tsx, packages/smarthr-ui/src/components/FormControl/FormControl.tsx, packages/smarthr-ui/src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, packages/smarthr-ui/src/components/TabBar/__snapshots__/TabBar.test.tsx.snap, packages/smarthr-ui/src/components/Text/Text.tsx, packages/smarthr-ui/src/smarthr-ui-preset.ts
https://www.tailwind-variants.org/docs/config#global-config
prefix を指定しないと tailwind-merge が機能しないため修正。
=> fix: tailwind-merge に prefix を追加

packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
=> fix: AppNavi 内の StatusLabel が潰れないように修正

packages/smarthr-ui/src/themes/__tests__/createColor.ts, packages/smarthr-ui/src/themes/createColor.ts, packages/smarthr-ui/src/themes/createPalette.ts
=> refactor: hoverColor の未使用変数を消す

packages/smarthr-ui/src/components/AppNavi/style.ts
#4798 に依って直感的な書き方ができるようになった。たまたま目に入ったので修正してみました。
=> refactor: AppNaviItem の不要なスタイリングを見直し

packages/smarthr-ui/src/components/Stepper/HorizontalStepItem.tsx, packages/smarthr-ui/src/components/Stepper/StepCounter.tsx, packages/smarthr-ui/src/components/Stepper/StepStatusIcon.tsx, packages/smarthr-ui/src/components/Stepper/Stepper.stories.tsx, packages/smarthr-ui/src/components/Stepper/Stepper.tsx, packages/smarthr-ui/src/components/Stepper/VRTStepper.stories.tsx, packages/smarthr-ui/src/components/Stepper/VerticalStepItem.tsx, packages/smarthr-ui/src/components/Stepper/index.ts, packages/smarthr-ui/src/components/Stepper/types.ts, packages/smarthr-ui/src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-783
Stepper を追加しました。
=> feat: Stepper を追加

packages/smarthr-ui/src/components/UpwardLink/UpwardLink.stories.tsx, packages/smarthr-ui/src/components/UpwardLink/UpwardLink.tsx, packages/smarthr-ui/src/components/UpwardLink/index.ts, packages/smarthr-ui/src/index.ts
アイコンとインデントの距離を定めた UpwardLink を作りました。
negative margin で良いのかは少し悩んでいます（transformX を使ったほうが、影響を受けにくかもしれない）。
=> feat: UpwardLink を追加

packages/smarthr-ui/src/components/TextLink/TextLink.stories.tsx, packages/smarthr-ui/src/components/TextLink/VRTTextLink.stories.tsx, packages/smarthr-ui/src/components/UpwardLink/UpwardLink.stories.tsx
TextLink と UpwardLink の関連性を Story 上に落とし込みました。
- TextLink を Navigation の配下に移動しました
- TextLink と UpwardLink を親子関係にしました
- Input と SearchInput の関係と同じです
=> docs: UpwardLink の Story 構造を修正

packages/smarthr-ui/src/components/Icon/Icon.tsx
https://smarthr.atlassian.net/browse/YBM-117
- `FaEnvelopeOpen` が必要な箇所が発生したため追加
- `FaEnvelopeOpen` を追加
=> feat(Icon): `FaEnvelopeIcon` を追加

packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
https://github.com/kufu/smarthr-ui/pull/4823#discussion_r1721236989
#4823 の指摘を反映せずにマージしてしまったため。
=> chore: AppNavi[buttons] の depreacted コメントを修正

.github/PULL_REQUEST_TEMPLATE.md
https://smarthr.atlassian.net/browse/SHRUI-1008
PULL_REQUEST_TEMPLATE.md を刷新し、主にレビュアーや利用者が変更内容を確認しやすいことに重きを置いたテンプレに書き換えます。(詳細の課題感などは関連リンク参照)
主に以下の観点で書き直しています。
- 日本語の使用
- 既に README.md から日本語で書かれており、開発者・利用者の大多数が日本語話者であることからそっちに寄せる
- PRタイトルについても言及
- リリースノートやCHANGELOGにそのまま掲載される旨を強調してちゃんと書いてもらう
- 変更内容や確認方法について重点的に書くように案内
全体的な方向性や一言一句までご意見様々募集。
=> chore: PRテンプレートを刷新し、変更内容を把握しやすいPRを書きやすくする

packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx
[JIRA](https://smarthr.atlassian.net/browse/SHRUI-863)
- AccordionPanelのタイトルのline-heightをTIGHT(1.25)に修正
- `shr-leading-tight` の追加
- コードを確認いただいたうえで、Storybookで差分がでているので意図せぬリグレッションがないか確認をお願いします
=> fix: AccordionPanelのタイトルのline-heightをTIGHTに修正

packages/smarthr-ui/src/components/Dialog/ModelessDialog.stories.tsx, packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
https://smarthr.atlassian.net/browse/SHRUI-918
ModelessDialog をリサイズ可能にする `resizable` を追加します。
`right` や `bottom` に依る絶対位置指定をしている場合、resize が困難になる問題を認識していますが、本 PR では対応せず、別途チケットを切ります。
リサイズ可能にするための `resize: both` を指定しました。
また、`overflow: visible` では動作しないため `overflow: auto` を指定しました。
Story の確認をお願いします。
https://63d0ccabb5d2dd29825524ab-igwhkpgnnl.chromatic.com/?path=/story/dialog%EF%BC%88%E3%83%80%E3%82%A4%E3%82%A2%E3%83%AD%E3%82%B0%EF%BC%89-modelessdialog--modeless-dialog
- ModelessDialog の Story で中央に初期表示されるダイアログがサイズ可変になっていることを確認してください
- 座標位置指定したダイアログはサイズ可変でないことを確認してください
=> feat: ModelessDialog をリサイズ可能にするオプションを追加

packages/smarthr-ui/src/components/Icon/Icon.tsx
プロダクトで使用するため、ファイル系のアイコン6種類を追加しました。
以下のアイコンを追加
- `FaFileCode`
- `FaFileCsv`
- `FaFileExcel`
- `FaFilePdf`
- `FaFilePowerpoint`
- `FaFileWord`
=> feat: ファイル系アイコンを追加

packages/smarthr-ui/e2e/components/ComboBox/MultiComboBox.test.ts, packages/smarthr-ui/e2e/components/ComboBox/SingleComboBox.test.ts, packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx, packages/smarthr-ui/src/components/ComboBox/MultiCombobox.stories.tsx, packages/smarthr-ui/src/components/ComboBox/SingleComboBox.tsx, packages/smarthr-ui/src/components/ComboBox/SingleCombobox.stories.tsx, packages/smarthr-ui/src/components/FormControl/FormControl.tsx
Reverts kufu/smarthr-ui#4909
元 PR は #4842 です。
=> feat!: Revert "Revert "feat!: Combobox の inputAttributes を消し、input に直接渡すように修正""

.github/workflows/e2e.yml, .github/workflows/previewRelease.yml, .github/workflows/titleCheck.yml
- https://smarthr.atlassian.net/browse/SHRUI-965
リリース時に作られるPRでGitHub Actionsが動かなかった問題を修正
- リリースPRでPRをapproveするとGitHub Actionsが動き始めるように修正
多分動くと思うからリリースしようぜ！
=> chore: リリース時にGitHub Actionsが動くように修正

.eslintrc.js
=> chore: eslint-config-smarthrでdefault errorになっているため、設定を調整する

packages/smarthr-ui/scaffold/templates/stories/VRT{{ pascalCase name }}.stories.tsx.hbs, packages/smarthr-ui/scaffold/templates/stories/{{ pascalCase name }}.stories.tsx.hbs
Story の見直しを始めて気になった箇所を修正しました。
File changed に書きます!
コードを見てくれれば 👌
=> chore: Story の雛形を調整

packages/smarthr-ui/scripts/exportUIProps.ts, packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx, packages/smarthr-ui/src/components/CheckBox/CheckBox.tsx, packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx, packages/smarthr-ui/src/components/Dialog/ActionDialog.stories.tsx, packages/smarthr-ui/src/components/Dialog/Dialog.stories.tsx, packages/smarthr-ui/src/components/Dialog/Dialog.tsx, packages/smarthr-ui/src/components/Dialog/DialogContent.tsx, packages/smarthr-ui/src/components/Dialog/FocusTrap.tsx, packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx, packages/smarthr-ui/src/components/Dialog/types.ts, packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.tsx, packages/smarthr-ui/src/components/FormControl/FormControl.stories.tsx, packages/smarthr-ui/src/components/Input/Input.tsx, packages/smarthr-ui/src/components/Stepper/HorizontalStepItem.tsx
typo をまとめて修正しました。
BACKGROUND の typo は色のトークンとして I/F に影響があるため BREAKING CHANGE になります。
修正内容は以下の通りです。BACKGRUOND 以外は内部的な修正のため、プロダクト影響ありません。
Before | After | プロダクト影響
--- | --- | ---
BACKGRUOND | BACKGROUND | あり
actiion | action | 
Opended | Opened | 
deault | default | 
horizontall | horizontal | 
Direact | Direct | 
filetered |filtered | 
indeteminate | indeterminate | 
overflw | overflow | 
opend | opened | 
Stlye | Style | 
Potals | Portale | 
Tabbale | Tabbable | 
Textaea | Textarea |
=> fix!(typo): BACKGRUOND → BACKGROUND ほか

packages/smarthr-ui/.storybook/preview.tsx, packages/smarthr-ui/src/components/Base/stories/Base.stories.tsx, packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
Story の背景色が BACKGROUND となるように修正しました。
Chroamtic 環境では参照されないため VRT への影響はありません。
Before | After
--- | ---
=> chore: Story のデフォルト背景を BACKGROUND 色の light に変更

packages/smarthr-ui/src/components/ComboBox/useListBox.tsx
- 特定の条件を満たすとcomboboxの選択肢リストの表示が崩れてしまう問題を解決します
- 条件
- 選択肢が1~4個の場合
- helpMessageが存在すると発生しやすい
- combobox下にリストを表示する領域が存在しない
- 症状
- リスト下に余計な空白が生じてしまう
- 2回目以降の表示は正常になる
- 原因
- 選択肢リストの高さに応じて計算する処理が存在するが、その処理より前に選択肢リストのwidthを調整していないため、初回表示のみ表示崩れが起きる
- helpMessageなど成り行きで高さが変わる要素が含まれるため、幅が変われば高さも連動して変わる
- 選択肢の数が一定以上になるとmaxHeightによって上限に達するため問題は発生しなくなる
- 選択肢リストの位置、高さ、幅の計算を同時に行なっていたロジックを分解し、幅の計算のみを先んじて行うように修正
=> fix: Comboboxの選択肢表示位置がズレてしまう問題を修正

packages/smarthr-ui/scaffold/templates/stories/VRT{{ pascalCase name }}.stories.tsx.hbs, packages/smarthr-ui/scaffold/templates/stories/{{ pascalCase name }}.stories.tsx.hbs
Story の型定義を、より適切だと考えられる satisfies operator に変えました。
=> chore: Story 雛形の型指定を as から satisfies に変更

packages/smarthr-ui/src/components/FloatArea/FloatArea.tsx
https://smarthr.design/products/design-tokens/z-index/#h2-2
FloatArea の作成以来、z-index 値が 500 というマジックナンバーになっていたため見直しました。
レイヤー順序の BottomFixedArea や sticky する thead と同等で良いと考えました。
コードのみでも問題ありません。
=> fix: FloatArea の z-index を見直し

packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx, packages/smarthr-ui/src/components/AccordionPanel/stories/AccordionPanelTrigger.stories.tsx, packages/smarthr-ui/src/components/AccordionPanel/stories/VRTAccordionPanel.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-1193
AccordionPanelTrigger に disabled を渡せるが装飾が存在しなかったため追加しました。
disabled 時の装飾は Button に寄せています。
- AccordionPanelTrigger が disabled の時の装飾を追加
- Story を追加
=> fix(AccordionPanelTrigger): disabled な装飾を追加

packages/smarthr-ui/src/components/BottomFixedArea/BottomFixedArea.tsx, packages/smarthr-ui/src/components/BottomFixedArea/stories/BottomFixedArea.stories.tsx, packages/smarthr-ui/src/components/BottomFixedArea/stories/VRTBottomFixedArea.stories.tsx
- https://smarthr.atlassian.net/browse/SHRUI-1203
- https://smarthr.design/products/components/float-area/
BottomFixedArea と FloatArea の明確な使い分け方法がなく、開発判断を減らしていくために BottomFixedArea を非推奨とし、 FloatArea を使っていくことになった。
ノールックでも大丈夫です。
=> fix(BottomFixedArea): deprecated

.github/workflows/titleCheck.yml
https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope-and--to-draw-attention-to-breaking-change
CI で走らせている titleCheck の正規表現が間違っていたため修正。
=> chore(titleCheck.yml): 正規表現の誤りを修正

package.json, pnpm-lock.yaml
=> chore: pnpm audit --fix

packages/smarthr-ui/src/components/Button/AnchorButton.tsx, packages/smarthr-ui/src/components/Button/Button.tsx, packages/smarthr-ui/src/components/Button/DisabledDetail.tsx, packages/smarthr-ui/src/components/Button/stories/AnchorButton.stories.tsx, packages/smarthr-ui/src/components/Button/stories/VRTAnchorButton.stories.tsx, packages/smarthr-ui/src/components/Button/stories/anchor-button.txt
AnchorButton に渡した disabledDetail が表示されるに修正しました。
anchor に disabled はないため、href が存在しない場合に disabled と見なし表示しています。
- Button に使っていた disabledDetail を DisabledDetail として切り出し
- href が存在しない場合に、AnchorButton の disabledDetail を表示
- Story を見直し
=> feat: AnchorButton の disabledDetail 対応

packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
=> fix: FilterDropdownのonApplyがsubmitキャンセルされるバグを修正

packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuGroup.tsx
外からスタイルを上書きできなかったため修正しました。
- `.shr-ui-DropdownMenuGroup` を追加
- 外から class を渡せるように修正
=> fix(DropdownMenuGroup): オーバーライド用のクラス名を追加

packages/smarthr-ui/src/smarthr-ui-preset.ts
SearchInput の `type` を `search` にした場合、`input[type=search]` に UA スタイルがあたり表示が崩れる可能性があるので normalize しました。
`input[type=search]` の `box-sizing` と `appearance` を normalize しました。
=> fix: input[type=search] のスタイルを normalize

packages/smarthr-ui/src/components/Browser/Browser.test.tsx, packages/smarthr-ui/src/components/Browser/Browser.tsx, packages/smarthr-ui/src/components/Browser/BrowserColumn.tsx, packages/smarthr-ui/src/components/Browser/BrowserItem.tsx, packages/smarthr-ui/src/components/Browser/index.ts, packages/smarthr-ui/src/components/Browser/models/ItemNode.test.ts, packages/smarthr-ui/src/components/Browser/models/ItemNode.ts, packages/smarthr-ui/src/components/Browser/models/Node.ts, packages/smarthr-ui/src/components/Browser/models/NodeContext.ts, packages/smarthr-ui/src/components/Browser/models/RootNode.test.ts, packages/smarthr-ui/src/components/Browser/models/RootNode.ts, packages/smarthr-ui/src/components/Browser/models/index.ts, packages/smarthr-ui/src/components/Browser/stories/Browser.stories.tsx, packages/smarthr-ui/src/components/Browser/stories/VRTBrowser.stories.tsx, packages/smarthr-ui/src/components/Browser/utils.test.ts, packages/smarthr-ui/src/components/Browser/utils.ts, packages/smarthr-ui/src/index.test.ts, packages/smarthr-ui/src/index.ts, pnpm-lock.yaml
[SHRUI-1182] 階層ごとにカラムが分かれていて項目を選択できるコンポーネントを作る - SmartHR JIRA
HRアナリティクスにおいて、ツリー形式のデータをカラムビューで表示するUIが追加されました。アクセシビリティ本部にてこのコンポーネントのアクセシビリティ観点でのレビューを実施したところ、非常に参考になり、他のプロダクトで同じような実装が行われた際に案内したいという運びとなったため、SmartHR UIへ移植しようとしています。
このPRでは、上述のUIを実現するBrowserという新しいコンポーネントを追加しています。
`Browser` というコンポーネントを追加しています。命名は、macOSにおいて同様のUIを実現する [`NSBrowser`](https://developer.apple.com/documentation/appkit/nsbrowser)を参考にしました。
基本的にプロダクトからの実装をコピーしたものになっていますが、一部アプリケーション知識と密結合になっていた部分を剥がしたり、prop名などを他のコンポーネントと合わせたものにしています。
また、元実装では矢印キーで項目間を移動できるようにしていますが、これを簡単に記述できるようにするために内部向けのドメインモデルを実装しています（`Browser/models`）。
https://63d0ccabb5d2dd29825524ab-twtlyegojj.chromatic.com/?path=/docs/data-display%EF%BC%88%E3%83%87%E3%83%BC%E3%82%BF%E8%A1%A8%E7%A4%BA%EF%BC%89-browser--docs …
=> feat: Browserコンポーネントを実装

packages/smarthr-ui/src/components/Table/EmptyTableBody.tsx
https://smarthr.atlassian.net/browse/SD-897?atlOrigin=eyJpIjoiMDdkNmFiOTc4MDhiNDgzYTlkOTkyMzI4NDA5NmY3NDUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
- 文字列が中央揃えになるように修正
- 文字列が中央揃えになるように修正
| :-- | :-- |
| <img width="294" alt="image" src="https://github.com/user-attachments/assets/deb59052-1567-4035-97bf-d0161bb6c7c0"> | <img width="304" alt="image" src="https://github.com/user-attachments/assets/f2d867b9-0572-4cb8-b8ae-a1298cd42b4d"> |
=> fix(EmptyTableBody): 文字列が中央揃えになるよう修正

.github/workflows/publishRelease.yml, .github/workflows/startRelease.yml
- 足りない引数を追加
- [payload に channel を含めてみた](https://github.com/kufu/smarthr-ui-slack-release-bot/commit/96dbf9d3942be32d0eb45af0b4f096b2bcedf6b6#diff-c77b89ae7ba2627f28f4b8fe20ecbb5c169809193c3a3cfd404cd93f12750b83R66)ので、そのまま payload として送ってみる
=> chore: リリース用 GitHub Actions がコケていたので修正（再）

packages/smarthr-ui/src/components/FormControl/stories/FormControl.stories.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1735113706347939
Storybookの非推奨がdeprecatedと同じ日本語訳のため混乱するので、利用注意に修正
=> docs(FormControl): dangerouslyTitleHiddenを非推奨から利用注意に変更

packages/smarthr-ui/src/components/Switch/Switch.tsx
=> chore: Switchのstyle生成をmemo化する

packages/smarthr-ui/src/components/Text/RangeSeparator.tsx
- RangeSeparator内のdecoratorsの処理を一つのuseMemoにまとめることとで処理を最適化します
- テキスト毎にmemo化のチェックをせず、decorators全体で一つのmemo化を施すことで更新判定の回数を減らします
=> chore: RangeSeparatorのdecoratorsの処理をまとめる

packages/smarthr-ui/src/components/SegmentedControl/SegmentedControl.tsx
=> chore: SegmentedControl の内部処理をリファクタリング

packages/smarthr-ui/src/components/SideNav/SideNavItemButton.tsx
=> chore: SideNavItemButtonの内部処理をリファクタリングする

packages/smarthr-ui/src/components/Loader/Loader.tsx
=> chore: Loader全体をmemo化する

packages/smarthr-ui/src/components/Layout/Cluster/Cluster.tsx
=> chore: Clusterの内部処理をリファクタリングする

packages/smarthr-ui/src/components/StatusLabel/StatusLabel.tsx, packages/smarthr-ui/src/components/Stepper/StepCounter.tsx
=> chore: StatusLabelの内部ロジックを適切にmemo化する

packages/smarthr-ui/src/components/Text/Text.tsx
- ロジックを調整し、スッキリさせたい
- propsの不要な再展開を修正
- stylesの生成に必要な判定の数を削減
=> chore: Textコンポーネントの内部ロジックをリファクタリングする

packages/smarthr-ui/src/components/Stepper/HorizontalStepItem.tsx, packages/smarthr-ui/src/components/Stepper/Stepper.tsx, packages/smarthr-ui/src/components/Stepper/VerticalStepItem.tsx
=> chore: Stepperの内部ロジックを整理する

packages/smarthr-ui/src/components/NotificationBar/NotificationBar.tsx
=> chore: NotificationBarの内部ロジックをリファクタリング

packages/smarthr-ui/src/components/Tooltip/TooltipPortal.tsx
https://smarthr.atlassian.net/browse/SHRUI-1211
メッセージのマークアップをpタグからdivタグに変更
- pタグをdivタグに置き換え
- これによりulなどTooltip内にテキストに限らないリッチなコンテンツを設置できるようになる
=> fix(Tooltip): マークアップをpタグからdivタグに変更

packages/smarthr-ui/src/components/ResponseMessage/ResponseMessage.tsx
=> chore: ResponseMessageのIcon選択ロジックをMapper形式に変更

packages/smarthr-ui/src/components/Layout/Sidebar/Sidebar.tsx
=> chore: Sidebarの内部処理をリファクタリングする

packages/smarthr-ui/src/components/Input/Input.tsx
=> chore: Inputの内部処理をリファクタリングする

packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
=> chore: SearchInputの内部処理をリファクタリングする

packages/smarthr-ui/src/components/Input/CurrencyInput/CurrencyInput.tsx, packages/smarthr-ui/src/components/Input/CurrencyInput/useClassNames.ts
=> chore: CurrencyInputの内部ロジックをリファクタリングする

packages/smarthr-ui/src/components/FormControl/FormControl.tsx
- FormControl, FieldsetでUI崩れがないこと
- a11y nameなどがdangerouslyTitleHiddenの指定有り無し、どちらでも問題なく設定されること
- その他markupなどで問題のある箇所がないこと
=> fix: FieldsetコンポーネントにdangerouslyTitleHiddenを設定した場合、余計な余白が出力されてしまう問題を修正

packages/smarthr-ui/src/components/Select/Select.tsx
=> chore: Selectの内部ロジックをリファクタリング

packages/smarthr-ui/src/components/LineClamp/LineClamp.tsx
=> chore: LineClampの内部処理をリファクタリングする

packages/smarthr-ui/src/components/RadioButton/RadioButton.tsx
=> chore: RadioButtonの内部ロジックをリファクタリングする

packages/smarthr-ui/src/components/DropZone/DropZone.tsx
=> chore: DropZoneの内部処理をリファクタリング

packages/smarthr-ui/src/components/Dialog/FocusTrap.tsx, packages/smarthr-ui/src/components/Dialog/useBodyScrollLock.ts, packages/smarthr-ui/src/components/Dialog/useDialogPortal.ts, packages/smarthr-ui/src/components/Dialog/useRemoteTrigger.ts, packages/smarthr-ui/src/libs/tabbable.ts
=> chore: Dialog hooks周りを整理

packages/smarthr-ui/src/components/FormControl/FormControl.tsx
=> fix: FormControl、FieldsetでdangerouslyTitleHiddenを指定した場合、多くのtest用ライブラリで用意されているメソッドで対象にできなくなってしまう問題に対応したい

packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
=> chore: ModelessDialogの内部処理を整理する

packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx, packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx
https://smarthr.atlassian.net/browse/SHRUI-1220
=> fix(ActionDialog,FormDialog): スクロールできない問題を修正

packages/smarthr-ui/src/components/SideNav/SideNav.tsx, packages/smarthr-ui/src/components/SideNav/SideNavItemButton.tsx
=> chore: SideNavの内部ロジックを整理する

packages/smarthr-ui/src/components/Select/Select.tsx
=> chore: Selectコンポーネントの内部処理を調整する

eslint.config.mjs, packages/smarthr-ui/src/components/AppHeader/components/mobile/TenantSelector.tsx, packages/smarthr-ui/src/components/ComboBox/ListBoxItemButton.tsx, packages/smarthr-ui/src/components/ComboBox/MultiComboBox/MultiComboBox.tsx, packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx, packages/smarthr-ui/src/components/Dialog/StepFormDialog/StepFormDialogContentInner.tsx, packages/smarthr-ui/src/components/DropZone/DropZone.tsx, packages/smarthr-ui/src/components/Dropdown/Dropdown.tsx, packages/smarthr-ui/src/components/Icon/generateIcon.tsx
=> chore: eslintのエラーを解消する

packages/smarthr-ui/src/components/DatePicker/datePickerHelper.ts
=> chore: contentHeihgt => contentHeight

packages/smarthr-ui/src/components/Picker/DatetimeLocalPicker.tsx, packages/smarthr-ui/src/components/Picker/MonthPicker.tsx, packages/smarthr-ui/src/components/Picker/TimePicker.tsx, packages/smarthr-ui/src/components/Picker/style.ts
=> chore: Pickerの内部処理を整理

packages/smarthr-ui/src/components/NotificationBar/NotificationBar.tsx, packages/smarthr-ui/src/components/PageCounter/PageCounter.tsx, packages/smarthr-ui/src/components/Switch/Switch.tsx, packages/smarthr-ui/src/components/Table/TdCheckbox.tsx
=> chore: NotificationBar, PageCounter, Switch, Tableの内部処理を整理

packages/smarthr-ui/src/components/Header/AppLauncher/AppLauncher.tsx, packages/smarthr-ui/src/components/Header/Header.tsx, packages/smarthr-ui/src/components/Header/HeaderDropdownMenuButton.tsx, packages/smarthr-ui/src/components/Header/HeaderLink.tsx
=> chore: AppLauncher内のコンポーネントの内部ロジックを整理

packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelContent.tsx
=> fix: AccordionPanelが特定の状況でスクロール領域を不自然に伸ばしてしまう場合がある問題を修正する

packages/smarthr-ui/package.json, sandbox/next/e2e/import.test.ts, sandbox/next/src/app/import_test/page.tsx, sandbox/next/src/app/rsc_test/ActionDialogContent/page.tsx, sandbox/next/src/app/rsc_test/MessageDialogContent/page.tsx
https://kufuinc.slack.com/archives/C06KVP5PL23/p1741749216742719
libディレクトリからのimportが失敗する問題を解消
- libディレクトリからのimportがesmへの参照が切れていたのが原因であった
- これを解消した
- テストを追加して今後起きたらわかるようにした
e2eが通ってたらOK
=> fix: libディレクトリをexportできるように修正

packages/smarthr-ui/package.json
https://kufuinc.slack.com/archives/C018J0A6DCH/p1741934879711689?thread_ts=1741933891.641159&cid=C018J0A6DCH
Design System等でpackage.jsonをJSONとして扱っているとimportできないのを修正
package.json自体をexportするようにした
=> fix: package.jsonをexportsに含める

packages/smarthr-ui/src/components/TextLink/TextLink.tsx, packages/smarthr-ui/src/components/Textarea/Textarea.tsx, packages/smarthr-ui/src/components/Tooltip/TooltipPortal.tsx
=> chore: TextLink, Textarea, Tooltipの内部ロジックを整理する

packages/smarthr-ui/src/components/VisuallyHiddenText/stories/VRTVisuallyHiddenText.stories.tsx, packages/smarthr-ui/src/components/VisuallyHiddenText/stories/VisuallyHiddenText.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-1153
VisuallyHiddenTextのStoryを追加した
VisuallyHiddenTextのStoryを追加
=> docs(VisuallyHiddenText): Storyを追加

packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx, packages/smarthr-ui/src/components/FormControl/FormControl.tsx, packages/smarthr-ui/src/components/FormControl/stories/FormControl.stories.tsx
=> feat: FormControl, Fieldset コンポーネントに直接StatusLabelコンポーネントを渡せる属性、statusLabelsを追加する

packages/smarthr-ui/src/components/AppHeader/components/desktop/Navigation.tsx
https://kufuinc.slack.com/archives/CJEUZ4MS6/p1742209585259839
NavigationにelementAsを渡した際にaria-currentがpageにならない問題を修正
- NavigationにelementAsを渡した際にaria-currentがtrueではなくpageになるようにした
=> fix(AppHeader): Navigationのaria-currentがpageにならない修正漏れを改修

packages/smarthr-ui/src/components/Icon/Icon.tsx
Icons にアイコンを追加したい
- 以下アイコンを追加した
- FaGoogleDrive
- FaMicrosoft
| FaGoogleDrive |FaMicrosoft|
|---|---|
|<img width="111" alt="スクリーンショット 2025-03-24 13 51 25" src="https://github.com/user-attachments/assets/d071c9f4-e67c-47ad-a6e5-968b6c9ab856" />|<img width="112" alt="スクリーンショット 2025-03-24 13 57 53" src="https://github.com/user-attachments/assets/d3e97361-e9d0-43ee-a2e1-90c55dc4e41e" />|
=> feat: add FaGoogleDrive and FaMicrosoft icon

packages/smarthr-ui/src/components/Experimental/SideMenu/SideMenu.tsx, packages/smarthr-ui/src/components/Experimental/SideMenu/SideMenuGroup.tsx
https://github.com/kufu/smarthr-ui/pull/5435 から切り出し
=> chore: SideMenuのマークアップを調整する

packages/smarthr-ui/src/themes/createSize.ts
=> chore: theme.sizeの内部生成ロジックをリファクタリング

packages/smarthr-ui/src/components/Combobox/MultiCombobox/MultiCombobox.test.tsx, packages/smarthr-ui/src/components/Combobox/MultiCombobox/MultiCombobox.tsx, packages/smarthr-ui/src/components/Combobox/MultiCombobox/MultiSelectedItem.tsx
=> feat: MultiComboboxの選択済みアイテムの削除ボタンのaltを詳細化 SHRUI-1191

packages/smarthr-ui/src/components/Textarea/Textarea.tsx
=> fix: TextareaのmaxLettersを指定した場合の処理がエラーになるバグを修正する

packages/smarthr-ui/CHANGELOG.md
=> chore: Update CHANGELOG.md

.circleci/config.yml
https://kufuinc.slack.com/archives/C018J0A6DCH/p1743753872944129
tagsでChromaticで動いていないため、リリースノートからStorybookが追えなかったのを修正する
tagsでChromaticが動くようにする
=> fix: tagsでもChromaticを動くようにする

packages/smarthr-ui/src/components/Table/TableReel.tsx, packages/smarthr-ui/src/components/Table/Td.tsx, packages/smarthr-ui/src/components/Table/Th.tsx, packages/smarthr-ui/src/components/Table/reelShadowStyle.ts, packages/smarthr-ui/src/components/Table/useReelCells.ts
=> chore: Th, Td のstyleの記述位置を調整 SHRUI-785

packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx, packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuGroup.tsx, packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/useKeyboardNavigation.ts
=> fix: DropdownMenuGroupを利用した場合、キーボード移動がうまく行えない問題を修正する

packages/smarthr-ui/src/components/Button/stories/VRTAnchorButton.stories.tsx, packages/smarthr-ui/src/components/Button/stories/VRTButton.stories.tsx
SHRUI-1246
- Buttonからsquare属性を削除した際、差分を確認しやすくするため、VRTの修正はしませんでした
- 現在上記作業は完了しているため、VRTの修正のみ行います
- VRTの修正
- diffを見てテスト用の設定が変更されているのみであることを確認
- 表示差分を確認
=> chore: Buttonコンポーネントのsqure属性を削除したため、VRTのパターンを修正する SHRUI-1246

packages/smarthr-ui/package.json, packages/smarthr-ui/rollup.esm.config.js, pnpm-lock.yaml
ESM形式でimportした際にprocess.envがないと怒られてしまうので修正
- process.env.NODE_ENVを置き換え
- 本来はproduction, developmentにきちんと置き換えたいが、良い方法がないためproduction固定にしています。
Before:
After:
=> fix: process is not definedエラーを解消

packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
=> fix: AppNaviはh1より先に設置されることが多く、heading levelが崩れるため、aria-labelledbyで表現する

packages/smarthr-ui/.storybook/preview.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts, packages/smarthr-ui/src/intl/stories/Localizer.stories.tsx
Storybook上で翻訳結果を確認できるようにした
- Storybookに言語切替ボタンを追加
- LocalizerをStorybookに追加 (カテゴリ `Internal（内部）` を新設)
- VRTは必要ないと考え未追加
- localeファイルが不十分なときに型エラーになるように修正
=> chore: Storybookで翻訳結果を確認できるようにした

packages/smarthr-ui/src/components/TextLink/HelpLink.tsx, packages/smarthr-ui/src/components/TextLink/index.ts, packages/smarthr-ui/src/components/TextLink/stories/HelpLink.stories.tsx, packages/smarthr-ui/src/components/TextLink/stories/TextLink.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-1244
ヘルプ用のTextLinkを追加
- relとreferrerPolicyを使用側で意識しなくて良いように追加
- targetの値によってアイコンが変わるようにした
=> feat(HelpLink): HelpLinkを追加

packages/smarthr-ui/src/components/StatusLabel/RequiredLabel.tsx, packages/smarthr-ui/src/components/StatusLabel/stories/RequiredLabel.stories.tsx, packages/smarthr-ui/src/intl/Localizer.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts
RequiredLabelをintlで多言語化対応した
- localesの追加
- Storybook周りの微修正
- 型の微修正
**localesに存在する場合**: Storybookで言語を切り替え、該当箇所の翻訳が切り替わっていればOK
=> chore(RequiredLabel): intlで多言語化

packages/smarthr-ui/src/components/InputFile/InputFile.tsx
https://kufuinc.slack.com/archives/C06KVP5PL23/p1747024592714019
#5281 のmaster merge時にミスっていた条件分岐を修正
- Safariの直接代入時は早期リターンするように修正
=> fix(InputFile): onChangeが2度呼ばれてしまう問題を修正

packages/smarthr-ui/src/components/WarekiPicker/stories/VRTWarekiPicker.stories.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1747045863500089
- Comboboxなどのようにinputの外をクリックしてflakyになるのを回避するようにした
#5607 でcaretをtransparentにしてみたがうまくいかなかったのでComboboxなどのように、input外をクリックさせてcaretを消すように修正
- VRTの差分を見てよければapproveしてください。上記の変更により、focus ringがVRTからはなくなることになります。
=> test(WarekiPicker): flakyなtestを修正

packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialog.tsx, packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialog.tsx, packages/smarthr-ui/src/components/Dialog/StepFormDialog/StepFormDialog.tsx
=> fix: ActionDialog, FormDialogでcloseDisabledが指定されている場合、onPressEscapeも動作しないようにする SHRUI-1276

packages/smarthr-ui/src/components/Icon/Icon.tsx
プロダクトで使用するため、 `FaClipboardQuestion` を smarthr-ui で利用できるようにしました。
`FaClipboardQuestion` を `FaClipboardQuestionIcon` として re-export 。
Storybookで表示されていることを確認した。
=> feat: FaClipboardQuestionIconを追加した

packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
=> chore: role="menu"に対するlintエラーをignoreする

packages/smarthr-ui/src/components/Dialog/useRemoteTrigger.ts
=> chore: RemoteTrigger系DialogのonToggle, onOpen, onCloseが常に正しい値が参照されるようにする

packages/smarthr-ui/src/constants.ts, packages/smarthr-ui/src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-1294
デザインシステムサイトを参考に単色チャートカラーを追加しました。
https://smarthr.design/products/design-tokens/color/#h4-1
=> feat: 単色チャートの色を追加

packages/smarthr-ui/src/components/Header/AppLauncher/AppLauncher.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ja.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts, sandbox/next/e2e/rsc.test.ts
AppLauncherをintlで多言語化
- AppLauncherをintlで多言語化
=> chore(AppLauncher): intlで多言語化

packages/smarthr-ui/src/components/Disclosure/Disclosure.tsx
`useState` が使われているが `'use client'`がないことでエラーが発生していたので修正
- `'use client'` directive をつけた
=> fix(Disclosure): RSC環境でのエラーを修正

packages/smarthr-ui/src/components/DropZone/DropZone.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ja.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts
DropZoneをintlで多言語化
- DropZoneをintlで多言語化
=> chore(DropZone): intlで多言語化

packages/smarthr-ui/src/components/Dialog/StepFormDialog/StepFormDialogContentInner.tsx
https://smarthr.atlassian.net/browse/SHRUI-1293
「ウィザード」のパターンにならい、副題（subtitle）がある場合は副題にステップを表示するように修正しました。
https://smarthr.design/products/design-patterns/wizard/#h4-0
=> fix: 副題付き StepFormDialog のステップ表示を修正

packages/smarthr-ui/src/intl/IntlProvider.tsx, packages/smarthr-ui/src/intl/stories/Localizer.stories.tsx, packages/smarthr-ui/src/intl/useIntl.test.tsx, packages/smarthr-ui/src/intl/useIntl.ts
https://smarthr.atlassian.net/browse/SHRUI-1256
availableLocalesを指定できるようにする
- IntlProviderで翻訳可能なlocalesを指定できるようにした
- useIntlでavailableLocalesを取得できるようにした
- テストをfmfm
=> feat(intl): IntlProviderにavailableLocalesを指定できるようにする

packages/smarthr-ui/src/smarthr-ui-preset.ts, packages/smarthr-ui/src/themes/createZIndex.ts
消し漏れていた FlashMessage 用のレイヤー順序トークンを消しました。
=> fix(FlashMessage): 消し漏れていたトークンを削除

packages/smarthr-ui/src/components/Stepper/StepStatusIcon.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ja.ts, packages/smarthr-ui/src/intl/locales/ja_easy.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts
chore(Steppter): intlで多言語化
chore(Steppter): intlで多言語化
=> chore(Steppter): intlで多言語化

packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialog.test.tsx, packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ja.ts, packages/smarthr-ui/src/intl/locales/ja_easy.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts
chore(FormDialog): intlで多言語化
chore(FormDialog): intlで多言語化
=> chore(FormDialog): intlで多言語化

packages/smarthr-ui/src/components/Combobox/ItemButton.tsx, packages/smarthr-ui/src/intl/locales/en_us.ts, packages/smarthr-ui/src/intl/locales/id_id.ts, packages/smarthr-ui/src/intl/locales/ja.ts, packages/smarthr-ui/src/intl/locales/ja_easy.ts, packages/smarthr-ui/src/intl/locales/ko_kr.ts, packages/smarthr-ui/src/intl/locales/pt_br.ts, packages/smarthr-ui/src/intl/locales/vi_vn.ts, packages/smarthr-ui/src/intl/locales/zh_hans_cn.ts, packages/smarthr-ui/src/intl/locales/zh_hant_tw.ts
- アイテム追加ボタンの多言語化が漏れていたので追加修正
- アイテム追加ボタンの多言語化が漏れていたので追加修正
=> chore(Combobox): intlで多言語化 (2)

packages/smarthr-ui/src/components/Icon/Icon.tsx
経緯
- https://kufuinc.slack.com/archives/C08RAC0CFGC/p1751523843043799?thread_ts=1751522449.049289&cid=C08RAC0CFGC
プロダクトで使用するため、ファイル系のアイコンを追加しました。
以下のアイコンを追加
- FaFileCirclePlusIcon
=> feat(Icon): FaFileCirclePlusIconを追加

packages/smarthr-ui/src/components/TabBar/TabItem.tsx, packages/smarthr-ui/src/libs/ua.ts
https://smarthr.atlassian.net/browse/SHRUI-1309
=> fix(TabItem): 不要なスタイルを消す

pnpm-workspace.yaml
pnpmのminimumReleaseAgeを設定
https://pnpm.io/ja/settings#minimumreleaseage
`pnpm config set --location project minimumReleaseAge 4320`
pnpm-workspace.yamlにminimumReleaseAgeを3日で設定
以下のコマンドを実行し、minimumReleaseAgeが指定した数値で設定されている
```
pnpm config list --location=project
```
=> chore: add minimumReleaseAge to pnpm workspace config
