kufu/smarthr-ui

- src/components/MessageScreen/MessageScreen.tsx
- MessageScreen コンポーネントの links[number].label を string から ReactNode に変更します
- これにより、翻訳用のコンポーネントなどでラップすることが可能になります
> feat: MessageScreen の links[number]label を string から ReactNode に変更

- src/components/Input/SearchInput/SearchInput.stories.tsx
- src/components/Input/SearchInput/SearchInput.tsx
- 固定だったアイコンの `検索` という文言を差し替えられるようにdecoratorsオプションを追加します
> feat: SearchInput に decorators 属性を追加

- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- 多くの場合で `その他操作` という文言で問題ないが、例えばアイコンのみ表示するかつ、他操作がない場合、意図しない代替テキストが設定される可能性がる
- 上記場合、設定されている代替テキストに、表示上気づく手段が無い
- そのため、どんなテキストを設定するのか？を明確に利用者に選択してもらうよう、label属性を必須にし、デフォルト値を削除する
> refactor!: DropdownMenuButton の labelのデフォルト値を削除

- src/components/Base/Base.stories.tsx
- src/components/Base/Base.tsx
- src/themes/createColor.ts
Base に背景色を付けたいことが多いが、毎度 styled-components で wrap していて不便だった。
- 灰色以外の色を指定することは基本的にないため、グレースケールに絞っている
- セマンティクストークン名でもプリミティブトークン名でもどちらでも指定できる
- 初期値は WHITE
> feat: Base に背景色を指定するための color を追加

- src/components/Base/Base.stories.tsx
- src/components/Base/Base.tsx
- src/components/Base/BaseColumn.tsx
- src/components/Base/index.ts
- src/index.ts
- src/themes/createColor.ts
プロダクトデザイナーで検討したところ `Base` ではなく `BaseColumn` として実装しようとなったので Base に色を載せるのは revert して `BaseColumn` を追加します。
revert コミット付きなので、以下コミットを見てもらえると良さそうです。
- ef910c2765e070ed4afc74d0eec006b4a7c149c6
- b611db69e969f77c536022d908ba3add3ceb0bdc
Reverts kufu/smarthr-ui#3081
> feat: BaseColumn を追加

- src/components/DropZone/DropZone.stories.tsx
- src/components/DropZone/DropZone.tsx
- 固定だったボタンの文言を差し替えられるようにdecoratorsオプションを追加します
> feat: DropZone に decorators 属性を追加

- src/components/Button/Button.tsx
- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
`DropdownMenuButton` で `Button[disableDetail]` を使った時、`Tooltip` が見切れてしまう問題があった。
`Button[disableDetail]` の `Tooltip` を自動位置決めに変えることで対応した。
- `Button[disableDetail]` の `Tooltip[horizontal / vertical]` に `auto` を指定
- DropdownMenuButton は右端に配置されることが多いので、Story を修正
https://deploy-preview-3092--smarthr-ui.netlify.app/?path=/story/buttons%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89-dropdown--dropdown-menu-button
> fix: Button の無効理由が見きれないように Tooltip の位置を自動に変更

- src/components/Table/Table.stories.tsx
- src/components/Table/Th.tsx
- https://w3c.github.io/aria-practices/examples/table/sortable-table.html
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort
半端に `onClick` が付き、利用側で実装する形になっていたため、smarthr-ui としてあるべき並び替え機能を実装しました。
以下の状態に対して `sort?: 'ascending' | 'descending' | 'none'` という props を追加しました。
- sort できない列
- sort できるがしていない列
- 昇順で sort している
- 降順で sort している
この props は並び替え状態を見た目的に制御するだけでなく、`th[aria-sort]` としても使われます。
> feat!: Th に並び替え機能を追加

- src/components/HeadlineArea/HeadlineArea.stories.tsx
- src/components/HeadlineArea/HeadlineArea.tsx
https://smarthr.atlassian.net/browse/SHRUI-606
Stack が作られたため、HeadlineArea は不要になりました。
以下のように書き換えることを推奨します。
```tsx
<Stack>
<Heading>見出し</Heading>
<p>説明</p>
</Stack>
```
Stack であれば `gap` プロパティで間隔の調整もできます。
また `<p />` は `<Text />` を使っても良いです。
> fix: HeadlineArea を deprecated にする

- src/components/InputFile/InputFile.tsx
- InputFileの非hover時の背景が未指定だったため追加します
> fix: InputFileの背景色指定漏れに対応する

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
https://smarthr.atlassian.net/browse/SHRUI-643
DatePicker に width props で幅指定ができなかったため修正しました。
> fix: DatePicker の width を指定できるように修正

- src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
#3042 
FilterDropdown が幅の狭い画面で機能しないことがわかったので修正。
- Cluster を使い、適切にレスポンシブするように修正
- 不要に幅指定している Story の記述を修正
iPhone SE など 320px を想定してキャプチャ。
before | after
--- | ---
> fix: FilterDropdown が狭い画面幅でも使えるように修正

- src/components/DatePicker/DatePicker.tsx
https://smarthr.atlassian.net/browse/SHRUI-585
和暦入力時、フォーカスを外すと変換されるが Enter を押しても変換されない問題が発生していた。
Enter 押下時に変換もかけるよう修正。
> fix: DatePicker の和暦入力後に Enter で変換されないバグを修正

- src/components/Table/Th.tsx
Th の onClick を onSort に変えた時に誤りがありました。
onSort は存在しないため button の onClick を使うよう修正しました。
sort と一緒にしか使えないのは変わっていません。
2023-02-24 13:07 追加
button にあたっていた `text-align: left` を th に当て直しました。
> fix: 存在しない onSort を使っていたため修正

- .storybook/main.js
Storybook の Composition という機能を使用し、SmartHR UI の Storybook 上でスマパタの Storybook も同時に見れるようにしてみました。
https://storybook.js.org/docs/react/sharing/storybook-composition
コンポーネントのStoryと、実際のパターン例のStoryが同時に見れるようになるのでめっちゃ良い気がしています。
> chore: スマパタのStorybookも同時に見れるようにする

- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/PaginationItem.tsx
- Pagination の aria-label の内容に `現在のページ` と表示されるパターンが存在するがその場合 `aria-current="page"` がもれなく設定されている
- 意味合いが同じであるため、 aria-label の内容を調整し、冗長な部分をなくしたい
> fix: Pagination の aria-label の内容が aria-current とダブっているため調整する

- src/components/Dialog/ActionDialogContentInner.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/useClassNames.ts
Button に loading は追加されたため、ActionDialog の processing を置き換えました。
I/F に変更はありません。
また、内部的なレイアウトも見た目はそのままに SmartHR UI で置き換えました。
before | after
--- | ---
> feat!: ActionDialog の processing を Button の loading で置き換え

- src/components/Table/ThCheckbox.tsx
alias import になってる箇所があったため修正。
念の為、他に alias import になってる箇所がないか調べてないことを確認しました。
> fix: alias import を相対パスに置き換え

- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
ResetButtonLayoutにthemeが渡されていなかったため修正を加えました。
> fix: FilterDropdownのResetButtonLayoutにthemeを渡すようにする

- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
#3180 の修正以前にスタイリングの指定が間違っていたので修正。
Close #3184
デグレでした。
https://github.com/kufu/smarthr-ui/commit/beb0776a1f63aded4068392708c797f5a087b9b2#diff-606f422820a68705fd17c0c15e836ec13efbb4644897c5fc1f33a956e1d96c69L143
> fix: FilterDropdown の効いていないスタイリングを修正

- tsconfig.build.json
N/A
一部のテストファイルがパッケージに含まれているようでした。不要なので除外したいです。
`*.test.*` のようなファイル名のテストファイルはビルド対象から除外されているのですが、 `__tests__/*` にあるテストファイルはビルドされていました。こちらもビルド対象から除外しました。
`npm build` 後、`npm pack --dry-run` した結果の比較：
> chore: ビルド対象からテストファイルを除外

- src/components/Calendar/YearPicker.tsx
- src/components/ComboBox/MultiComboBox.tsx
- src/components/ComboBox/SingleComboBox.tsx
- src/components/ComboBox/useListBox.tsx
- src/components/ComboBox/usePartialRendering.tsx
- src/components/DatePicker/Portal.tsx
- src/components/Dialog/ModelessDialog.tsx
- src/components/Dropdown/DropdownContentInner.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/TooltipPortal.tsx
- src/hooks/useEnhancedEffect.ts
- src/hooks/usePortal.tsx
https://smarthr.atlassian.net/browse/SHRUI-583
表題のとおりです、`useLayoutEffect` はSSRで使えず、大量に警告が出てしまうため、
- `useEffect` に置き換えられる箇所は置き換える
- 無理な箇所は SSR 時のみ `useEffect` を使うようにする
`useLayoutEffect` 利用箇所に対して一つずつ Storybook 上で動作確認し、上記の対応をしました。
動作確認をしてダメそうだったのは大雑把に以下のような箇所でした。
- portal 用の要素を `document.body.appendChild` している箇所
- その後に focus をしている箇所で e2e がコケたりした
- DOM 更新前の座標を計算し、Dropdown などを表示している箇所
- これは動作はするが、Dropdownがちらつくなどした
> fix: SSR を使用時に useLayoutEffect の警告が出ないようにする

- src/components/MessageScreen/MessageScreen.stories.tsx
- src/components/MessageScreen/MessageScreen.tsx
https://smarthr.atlassian.net/browse/SHRUI-594
MessageScreen のロゴを props で渡せるようにしました。未指定の場合は SmartHR ロゴが出ます。
ほか、以下の対応を行いました。
- footer も外から渡せるように変更
- footer はデフォルトなしに変更
- スタイリングを見直し
- Story を整理
> feat: MessageScreen のロゴを差し替えられるように修正

- src/components/BackgroundJobsPanel/BackgroundJobsPanel.tsx
- src/components/BackgroundJobsPanel/OmittableJobText.tsx
- src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- src/components/FloatArea/FloatArea.tsx
- src/components/FormGroup/FormGroup.tsx
- src/components/SideNav/SideNavItem.tsx
- 翻訳用コンポーネントなどを差し込めるようにstring型が指定されている箇所をReactNodeに変更します
> feat: 翻訳用コンポーネントなどを差し込み可能にするため string型 を ReactNode に変更する

- src/components/Calendar/Calendar.stories.tsx
- src/components/Calendar/Calendar.tsx
- src/components/Calendar/calendarHelper.ts
https://smarthr.atlassian.net/browse/SHRUI-607
DatePicker から Calendar を表示したとき、必ず現在月が表示されてしまい不便なため以下のように修正しました。
- from–toが過去の場合は、toを表示する
- from–toが未来の場合は、fromを表示する
- それ以外の場合は、現在の月を表示する
> fix: Calendar の初期表示を修正

- src/components/Table/ThCheckbox.tsx
- src/types/props.ts
現状の `DecoratorType` の型だと、`decorator` が複数ある場合に全ての `decorator` の指定が必須になっており、使いにくい。
例えば、以下のように一部の文言を変更したい場合でも、他の `decorator` も全て指定する必要があるのがつらい。
```TypeScript
<FilterDropdown
decorators={{
triggerButton: () => 'hogehoge',
applyButton: (txt) => txt,
cancelButton: (txt) => txt,
resetButton: (txt) => txt,
status: (txt) => txt,
}}
/>
```
以下のように、必要な項目だけ指定できるようにしたい。
```TypeScript
<FilterDropdown
decorators={{
triggerButton: () => 'hogehoge',
}}
/>
```
decorators内の各decoratorが任意になるように型を修正しました。
> fix: decorators内の個別のdecoratorの指定を任意にする

- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
FilterDropdownで「適用」ボタンを押した際にバリデーションを行い、バリデーションエラーがある場合はDropdownを閉じないような挙動を実現したいです。
利用イメージ
```TypeScript
const handleApply = (e) => {
const error = validate()
if (error) e.stopPropagation()
}
<FilterDropdown onApply={handleApply} />
```
現状だと、`onApply` は何の引数も受け取らず、`onApply` 内の処理に応じてDropdownを閉じないような実装は不可能だったため、`onApply` に `onClick` のイベントを渡しつつ、`onApply` 内で `e.stopPropagation()` をすることで今回実現したいことを実装できるようにしました。
`onApply`, `onCancel`, `onReset` の I/F を button の `onClick` と同じものにしました。
> feat: MouseEventを扱えるようにする

- src/components/Dialog/ModelessDialog.tsx
- https://smarthr.atlassian.net/browse/SHRUI-673
- ["overscroll-behavior" | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/?search=overscroll-behavior)
- [overscroll-behavior - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/overscroll-behavior)
ModelessDialog のスクロールが背後の要素に伝搬してしまうのを防ぐ。
> fix: ModelessDialog 内のスクロールが伝搬しないように制御

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
https://smarthr.atlassian.net/browse/SHRUI-602
フォームコントロールの変化しない値を表すための `readOnly` 機能を追加しました。
> feat: Input に read-only な視覚的表現を追加

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
- DatePicker の showAlternative のreturn型をReactNodeに変更することで、翻訳用コンポーネントなどを指定可能にした
> chore: DatePicker の showAlternative のreturnにReactNodeを渡せるように変更

- src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
FilterDropdown の trigger button を disabled にしたいケースがある
DropdownMenuButton を参考に、trigger button に任意の button props を渡せるようにした。
https://github.com/kufu/smarthr-ui/blob/9dfcbfd25fe051320ac8130d9c1097952e876ebc/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx#L39
> feat: FilterDropdown の trigger に任意の button props を渡せるようにする

- src/components/Header/AppLauncher/AppLauncher.tsx
🍐 
AppLauncher のトリガーとなる「アプリ」というボタンラベルや、中身のコンテンツが現在翻訳の対応ができていないため、対応したい。
- string で渡さなければいけない props を ReactNode に変更した
- decorators props を生やした
🍐
> feat: AppLauncher の多言語化対応

- src/components/Calendar/Calendar.stories.tsx
表題のとおりです。
Calendar の Story の内部で `new Date()` が使われており、ビルドの度にその日の日付の状態でスナップショットが取られてしまい、関係のないPRでも差分が出てしまっていました。
差分の例
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6445d467687d687ba00508dc
現在を 2023/04/01 とし、ビルドごとに Calendar の Story に差分が出ないようにしました。
> chore: Calendar の Story に毎回差分が出ないようにする

- src/components/Table/Th.tsx
https://smarthr.atlassian.net/browse/SHRUI-682
手元で以下のスタイルを充てて確認しました。
```tsx
const theme = createTheme({
fontSize: {
htmlFontSize: 10,
S: '1.1rem',
M: '1.4rem',
L: '1.8rem',
XL: '2.4rem',
},
})
const SmartHRGlobalStyle = createGlobalStyle`
${CssBaseLine}
html {
font-size: 62.5%;
}
`
```
> fix: Th のソートアイコンがフォントサイズに依って重なるバグを修正

- .github/workflows/publishRelease.yml
- .github/workflows/startRelease.yml
https://github.com/kufu/smarthr-ui/pull/3267
`public/exports/smarthr-ui-props.json`の更新がうまくリリースに反映できていたかったため、コミットを追加するタイミングを調整しました。
`release-candidate`ではなく、リリース処理の開始時点の`master`ブランチもしくは`merge-release-v...`ブランチにpushされている必要がありそうでしたので、`merge-release-v...`ブランチとPRが作られる直前にコミットを作成する（pushはしない）ように変更しました。
UIコンポーネント自体への影響はありません
> chore: smarthr-ui-props.jsonがリリースに含まれるようworkflowを調整

- src/components/Button/Button.tsx
- Button disabledDetail オプションで表示されるアイコンが表示崩れする場合があるため対応したい
> chore: ButtonのdisabledDetailオプション利用時に表示されるアイコンが小さくなってしまう場合に対処する

- src/components/Icon/generateIcon.tsx
https://smarthr.atlassian.net/browse/SHRUI-674
アイコンの名前が storybook 上で確認できなくなっていたので、見えるようにしたい
Icon を別コンポーネントでラップすることで displayName が消滅してしまっていたため、明示的に displayName を設定するようにした
> docs: Icon の story にアイコン名を表示させる

- src/components/Balloon/Balloon.tsx
- src/components/Base/Base.tsx
- src/components/Button/ButtonWrapper.tsx
- src/components/Calendar/CalendarTable.tsx
- src/components/CheckBox/CheckBoxInput.tsx
- src/components/ComboBox/MultiComboBox.tsx
- src/components/DefinitionList/DefinitionListItem.tsx
- src/components/Dialog/DialogContentInner.tsx
- src/components/Input/Input.tsx
- src/components/InputFile/InputFile.tsx
- src/components/Loader/Loader.tsx
- src/components/RadioButton/RadioButtonInput.tsx
- src/components/Select/Select.tsx
- src/components/StatusLabel/StatusLabel.tsx
- src/components/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
- src/components/Table/Table.tsx
- src/components/Textarea/Textarea.tsx
- src/themes/createBorder.ts
コントラスト比が高い視覚表現が必要なユーザーが、OSの高コントラスト設定をした時にUIも高コントラストにする
`prefers-contrast: more` の時に `border` を `color.GREY_100` にする
> feat: ハイコントラストモードに対応

- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- DropdownMenuButtonのchildrenの型を調整した
- DropdownMenuButtonのchildren内は `A && <Button />` のような判定が他用される
- Aにはbool以外にも `array.length` や `responseMessage` のようにnumberやstringなど、ほぼすべての型が利用される
- 実際にはfalsy or ReactElement以外になることは利用目的的には存在しないはず
- 利用実態に合わせた型に変更したい
> feat: DropdownMenuButton の childrenに型的に渡される可能性のあるfalsyな値を許容する

- src/components/ComboBox/ComboBox.stories.tsx
- src/components/ComboBox/types.ts
- src/components/ComboBox/useListBox.tsx
#3270 
上記に記載したPRの対応で `ComboBoxItem["label"]` の型が `ReactNode`に変更された。
この際、`onAdd`関数の引数として定義している label の型も同様に`ReactNode`に変更されているが、onAdd関数はユーザーが items に選択肢として存在しない label 名を selectedItems に新規追加する場合に発火する関数であり、文字列として処理をする想定になっている。（入力フォームに入力した値がReactNodeであるはずがない）
ComboBoxを利用する場合にonAddによって items に存在しない任意の文字を追加した場合、onAddの引数で受け取った label をもとに`{ label, value: label }`といった形でそれらしい要素を追加する関数を用意する必要があるが、onAddの引数の型が`string` → `ReactNode`になったことによって string 型である value に対して ReactNode を割り当てようとすることになって既存の実装を破壊してしまうケースがあった。
上述したとおりだが、ユーザーが ComboBox に任意で入力した新規の選択項目の値が ReactNode であるはずがないので文字列型としてよしなに要素を追加できるように修正した。
- `ComboBox["onAdd"]`の型を以下の様に変更
- ```diff
- onAdd?: (label: ReactNode) => void
+ onAdd?: (label: string) => void
```
- 関連箇所の修正
- `useListBox#handleAdd`などのユーザーから selectedItems …
> fix: onAdd の型を ReactNode から string に変更

- src/components/Experimental/SideMenu/SideMenuItem.tsx
- SideMenuItem に `:focus` が 指定されておりクリック時にフォーカスリングが表示されるのですが、 `:focus-visible` の方が自然な挙動に思えたので変更しました。
- SideMenuItem の `:focus` を `:focus-visible` に変更
SideMenuItem クリック時
| Before | After |
| --- | --- |
|![image](https://github.com/kufu/smarthr-ui/assets/16136015/000f6760-1eb9-4294-b76f-aa5eef342a2d)|![image](https://github.com/kufu/smarthr-ui/assets/16136015/0e0aa8e6-e5c6-43d9-8dcc-4f5980a2a383)|
> fix: SideMenuItem の :focusを :focus-visible に変更

- .circleci/config.yml
参考
https://uga-box.hatenablog.com/entry/2022/05/09/000000
Chromaticの差分が毎回出てしまう問題ですが、masterにマージする際にSquash Mergeを使っているのが原因っぽかったです。
コミットごとにChromaticでApproveをしていますが、Squash Mergeをすることでmasterブランチにマージ後に新規コミットとしてChromaticが検出するため、未確認の差分が毎回発生していたようです。
上記の記事を参考にしつつmasterブランチでのchromaticビルドは自動Acceptするようにしました。
> test: masterブランチマージ後のChromaticビルドを自動Acceptにし、Approve済みの差分が検出されないようにする

- src/components/AccordionPanel/AccordionPanel.stories.tsx
- src/components/FieldSet/FieldSet.tsx
- src/components/FormControl/FormControl.stories.tsx
- src/components/FormControl/FormControl.tsx
- src/components/FormControl/index.ts
- src/components/FormGroup/FormGroup.stories.tsx
- src/components/FormGroup/FormGroup.tsx
- src/components/FormGroup/useClassNames.ts
- src/components/MessageScreen/MessageScreen.stories.tsx
- src/components/NewFieldset/Fieldset.stories.tsx
- src/components/NewFieldset/Fieldset.tsx
- src/components/NewFieldset/index.ts
- src/index.ts
- https://smarthr.atlassian.net/browse/SHRUI-595
- #3232 
FormGroup が見た目に依った実装になっていたため見直しました。
`role="group"` を与えると `fieldset > legend` として振る舞います。
I/F こそ変わっていませんが、内部的に不要な `class` を消したため BREAKING CHANGE とします。
- role=group の場合は、fieldset > legend と振る舞うように修正
- fieldset[disabled] の場合の見た目を調整
- statusLabel を配列でなくても指定できるように修正
- StatusLabel を label に含めるように修正
- innerMargin の良いデフォルトを指定し、基本的に指定はいらないように修正
- titleType の良いデフォルトを指定
- 不要なマークアップを削除
- Story を見直し
別 PR で対応予定です。
- htmlFor を渡さなくても内部的に id を紐付けるように修正
- helpMessage や errorMessage が適切に紐付けられるように修正
- 入力例と補足文を追加
> feat!: FormGroup をセマンティックに扱えるよう修正

- package.json
- #3370
Storybook 起動時に警告が表示されます。
リポジトリルートの `public` を参照するためには `-s ../public` のようにすべきなのですが、そもそも開発時に `public` 内のディレクトリ参照する必要がなくなっています。(関連: #3370)
オプションを整理して良さそうです。
- Storybook 開発サーバー起動時の引数 `-s ./public` を削除
※ `storybook build` にも同様のオプション `-s ./public` が存在しているのですが、こちらは `-s ../public` に変更したり削除したりすると問題があるためそのままにしています。
N/A
> chore: 不必要な Storybook 起動オプションを削除

- .github/workflows/publishRelease.yml
- package.json
https://github.com/kufu/smarthr-ui/pull/3267
https://github.com/kufu/smarthr-ui/pull/3289
リリースのGitHub Actionsで更新した`smarthr-ui-props.json`が、次回のリリース時にコンフリクトする問題が起きたため、jsonの更新方法を見直しました。
- standard-versionが作るリリースコミット（直近ではv30.10.0のタグがついているこのコミット https://github.com/kufu/smarthr-ui/commit/d9bae7bada04b8e91ace47e3290e4a9f851ee709 ）には、CHANGELOG.mdとpackage.jsonの2つのファイルの変更が含まれている
- その後、上記のコミットを[masterからcherry-pick](https://github.com/kufu/smarthr-ui/blob/6f135710ffc15530b90a4623da8933f55daf31b4/.github/workflows/publishRelease.yml#L59-L61)し、さらに`smarthr-ui-props.json`の[更新コミット](https://github.com/kufu/smarthr-ui/pull/3361/commits/fed1a4dda0589c8550be6f2d15a2d0240945510d)を追加して、リリースのPRを作る
- リリースのPRにはコミットが2つ含まれている：https://github.com/kufu/smarthr-ui/pull/3361/commits …
> chore: smarthr-ui-props.jsonをstandard-versionで更新する方法に変更

- src/components/AccordionPanel/AccordionPanel.stories.tsx
- src/components/FormControl/FormControl.stories.tsx
- src/components/FormGroup/FormGroup.stories.tsx
- src/components/FormGroup/FormGroup.tsx
- src/components/MessageScreen/MessageScreen.stories.tsx
- src/components/NewFieldset/Fieldset.stories.tsx
- https://smarthr.atlassian.net/browse/SHRUI-595
- #3356 
FormGroup は内包するフォームコントロールを知っているので、内部的に id を生成して紐付けるように修正した。
#3356 のマージ後にマージします。
- htmlFor を渡さなくても内部的に id を紐付けるように修正
- helpMessage や errorMessage が適切に紐付けられるように修正
別 PR で対応予定です。
- 入力例と補足文を追加
> feat: FormGroup とフォームコントロールを内部的に id で紐づくように修正

- src/components/Dialog/DialogContentInner.tsx
https://smarthr.atlassian.net/browse/SHRUI-675
Dialog に width を与えると、max-width が消え、モバイルなどの横幅が狭い画面の場合に見切れる欠陥があった。
max-width は width の有無に限らず必ず指定した。
> fix: Dialog に width を指定した場合に max-width が効かなくなる欠陥を修正

- src/components/FormControl/FormControl.stories.tsx
- src/components/FormGroup/FormGroup.tsx
FormGroup の children を受ける wrapper が Stack で、`align-items: flex-start` を指定していたため、外から children への幅を指定しにくい状態になっていた。
元々、ラベルが横伸びしないように指定した `align-items: flex-start` だったため、ラベルのみ `align-self: start` を指定することで回避した。
> fix: FormControl の子要素に幅が指定できない欠陥を修正

- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
https://smarthr.atlassian.net/browse/SHRUI-690
before | after
--- | ---
> fix: DropdownMenuButton のフォーカスリングが見切れていたので修正

- src/components/DefinitionList/DefinitionList.stories.tsx
- src/components/DefinitionList/DefinitionList.tsx
- src/components/DefinitionList/DefinitionListItem.tsx
#3245 への別案 
DefinitionList の I/F と振る舞いを見直しました。
- 標準では画面幅に応じて列数が増減
- `maxColumns` を指定すると、`maxColumns` 以内の列数で増減
確認用 Story： https://63d0ccabb5d2dd29825524ab-isuyqpytba.chromatic.com/?path=/story/data-display%EF%BC%88%E3%83%87%E3%83%BC%E3%82%BF%E8%A1%A8%E7%A4%BA%EF%BC%89-definitionlist--all
- `layout` は削除
- 最大列数を指定する `macColumns` を追加
- 標準のデフォルト幅は 12em–30em とした
- 12em は日付が余裕を持って閲覧できる幅
- 30em は長すぎず短すぎず CJK における最適幅の min 値
- 不要な型定義の export を削除
- Story を整理
- nowrap を組みあせた時の段落ちがいまいち
- アイテム幅をはみ出てしまう場合に必ず段落ちさせつつ、余った領域は `flex-grow` する方法はないかしら
- item に `fill?: boolean` みたいな props を渡せてもいいかも?
- `fill = true` の時、`max-width` を消して、`flex-basis: 100%` とするイメージ
Close #3245
> feat!: DefinitionList を画面サイズに応じて列数を変化させる

- src/components/Table/Td.tsx
Td に`position: relative`が指定されていることによって、直上に DropDown や ComboBox のリストアイテムなどを表示した場合に Td に描画するコンテンツと被ってしまう場合がある。
Td では表示位置を制御する（top, left といったような位置指定）プロパティは提供されておらず、相対位置参照の指定は特段不要に見えるので削除したい。
Overview に記載した通りで、相対位置参照の指定を削除した。
> fix: Td の position: relative 指定を削除

- src/components/FloatArea/FloatArea.stories.tsx
- src/components/FloatArea/FloatArea.tsx
- src/components/FloatArea/useClassNames.ts
- https://smarthr.atlassian.net/browse/SHRUI-663
- https://smarthr.atlassian.net/browse/SHRUI-695
FloatArea の I/F が特殊だったため、ActionDialog や FilterDialog と合わせました。
差分を減らすために #3449 を base ブランチに指定しています。
- errorText / errorIcon を削除
- responseMessage を追加
- 内部的に ResponseMessage で書き換え
- Story を修正
> feat!: FloatArea の errorText / errorIcon を廃止し、フィードバックメッセージを表示する responseMessage を追加

- src/components/ComboBox/MultiSelectedItem.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
- src/components/FieldSet/FieldSet.stories.tsx
- src/components/Icon/Icon.stories.tsx
- src/components/Icon/generateIcon.tsx
https://smarthr.atlassian.net/browse/SHRUI-668
size は文字列・数値指定で px 単位を指定する非推奨なプロパティとして定義されていたが、デザイントークンによる指定で調整可能にしてサイズ変更を簡単かつ柔軟に指定できるようにしたい。
- size の型を `FontSizes`型に変更
- 指定されたトークンに応じて`rem`値を算出するロジックを追加
- テキストとアイコンを同等の扱いにするためText コンポーネントの実装に合わせている
- 既存コンポーネントの size に数値で px 指定している箇所の修正
> feat!: Icon の size をデザイントークンで指定するように変更

- src/components/Dialog/DialogContentInner.tsx
Dialog に幅が指定されている場合は最大幅もその幅に合わせる。
> fix: Dialog の max-width が固定値になっている欠陥を修正

- src/components/Textarea/Textarea.tsx
アクセシビリティ試験で発覚。
label > Textarea となる可能性があるため、wrapper を span として提供。
> fix: Textarea は label 内に含まれる可能性があるため span として提供

- src/components/CheckBox/CheckBox.tsx
アクセシビリティ試験で発覚。
Th/TdCheckbox などで label > CheckBox となる可能性があるため、wrappaer を span に変更。
> fix: CheckBox の wrapper を span に変える

- src/components/Select/Select.tsx
アクセシビリティ試験で発覚。
label > Select となる可能性を考慮して、wrapper 要素を span に変更。
> fix: Select は label 内に含まれる可能性があるため span として提供

- src/components/Table/BulkActionRow.tsx
- src/components/Table/EmptyTableBody.tsx
- src/components/Table/useTableHeadCellCount.ts
アクセシビリティ試験で発覚。
colspan="1000" は invalid な HTML だったため、hooks で算出するように変更。
> fix: BulkActionRow や EmptyTableBody の colspan を算出するように変更

- src/components/Dialog/ActionDialog/ActionDialog.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/FormDialog/FormDialog.tsx
- src/components/Dialog/MessageDialog/MessageDialog.tsx
- src/components/Dialog/ModelessDialog.tsx
- src/components/Dialog/useDialogPortal.ts
アクセシビリティ試験により発覚。
aria-controls が同一画面上に存在しないと valid な HTML にはならないため修正。
> fix: 各 Dialog の id が portal の親要素に設定されるように修正

- src/components/ComboBox/MultiComboBox.tsx
- src/components/ComboBox/useListBox.tsx
アクセシビリティ試験で発覚。
width / disabled な不要に渡されていたため、transient props を使って修正。
> fix: MultiComboBox の width / disabled が DOM に渡らないように修正

- src/components/Dialog/DialogContentInner.tsx
#3453
#3453 で width を指定していない Dialog の最大幅も `800px` になってしまっていたので修正。
width が指定されていない場合は vieport 幅から最低限の margin を除いた値が最大となるように修正。
> fix: Dialog に width が指定されていない場合の max-width を vieport からの計算に変更

- .storybook/main.ts
https://smarthr.atlassian.net/browse/SHRUI-709
Story ファイルで`@`エイリアスによるモジュールの参照ができていない状態になっていたためtsconfigと同様にエイリアスを利用できるように設定を追加したい
`.storybook/main.ts`で webpack のエイリアス設定を追加
> fix: Storybook関連ファイルでも @/ エイリアスを利用可能にする

- src/components/CheckBox/CheckBoxInput.tsx
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/checkbox#%E6%9C%AA%E6%B1%BA%E5%AE%9A%E7%8A%B6%E6%85%8B%E3%81%AE%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9
アクセシビリティ再試験で発覚。
input[type=checkbox] は標準で checked 状態を持つため、`aria-checked` を付けると invalid な HTML とみなされる。
JavaScript で node.indeterminate = true にするのが正解らしいので、`mixed` が渡された時は `indeterminate = true` となるように修正。
> fix: Checkbox の indeterminate に aria-checked を使わないように修正

- .eslintrc.js
- src/components/Icon/generateIcon.tsx
- tsconfig.json
tsconfig.json で `skipLibCheck: true` を設定していない環境では、ライブラリの型チェックをしにいきエラーが発生するそう。
根本解決方法が見つかるまでは alias は利用しない。
> fix: alias をやめる

- src/components/FormGroup/FormGroup.tsx
- src/hooks/useId.tsx
`FormControl` の `htmlFor` と `labelId` に渡した値が `label` タグに設定されない不具合を修正します。
現状だと以下のように、`htmlFor` を使って独自の `input` タグなどと紐づけたい場合に、
```html
<FormControl title="ラベル" htmlFor="hoge">
<MyInputComponent id="hoge" />
</FormControl>
```
レンダリング結果が以下のようになってしまい、`htmlFor` に渡したいはずの `hoge` が無視され、自動生成の ID が付与されてしまい、label と input を紐づけることができません。
```html
<label htmlFor=":r00">ラベル</label>
<input id="hoge" />
```
React18未満の場合は独自実装の `useId` を使うようになっていて、propsで渡した `htmlFor` と `labelId` の値がそのまま `label` タグに付与されるようになっていたんですが、
React18の場合は標準の `useId` が使われ、props `htmlFor` と `labelId` で渡した値が無視されていました。
https://github.com/kufu/smarthr-ui/blob/aceb775d89f90f8892fd5d90f549ae634fe89097/src/hooks/useId.tsx#L25
`htmlFor` と `labelId` が渡された場合はその値を直接 `label` タグに渡すように修正しました。
> fix: FormControlのhtmlForとlabelIdが使えなくなっていたのを修正

- src/components/AccordionPanel/AccordionPanelContent.tsx
- src/components/AccordionPanel/AccordionPanelItem.tsx
- AccordionPanelのマークアップを修正し、SectioningContentで自動レベリングされるようにします
- AccordionPanelのマークアップが以下の様になっていた
```
<div>
<heading />
<section>hoge</section>
</div>
```
- 関連性的には以下が正しいはず
```
<section>
<heading />
<div>hoge</div>
</section>
```
- また、Accordionの利用を想定した場合、自動的にSectionによってレベリングされても不自然ではなさそうなのでSectioningContentを利用するようにします
> fix: AccodionPanelのマークアップを修正し、Section内にHeadingが存在する状態にします

- src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- FormDialogのSectioningContent対応が漏れていたため、修正したい
- ActionDialog, MessageDialog同様、FormDialogにもHeadingの自動計算が有効になるように修正した
> fix: FormDialogのHeadingが自動計算されるようにマークアップを変更する

- src/components/Header/AppLauncher/AppLauncher.tsx
- AppLuncher内のHeadingがh3で固定だったものを、自動計算されるようにSectioningContentでマークアップします
> fix: AppLuncherのHeadingが自動計算されるようにマークアップを変更する

- src/components/InformationPanel/InformationPanel.stories.tsx
- src/components/InformationPanel/InformationPanel.tsx
- InformationPanelのHeadingが自動計算されるようにSectioningContentでマークアップします
> fix: InformationPanelのHeadingが自動計算されるようにマークアップを変更する

- src/components/Dialog/RemoteDialogTrigger.tsx
- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
> fix: DropdownMenuButton内にdisabledなButtonコンポーネントを設置するとstyle崩れが発生する場合がある問題を修正

- src/components/TabBar/TabItem.tsx
- src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
- 低コントラストモードなどで transparent指定のborderが表示されてしまう場合があり、selectedな場合と見分けがつきづらくなることがある
- border自体の有無を切り替えることで問題を解決したい
> fix: TabItemがselectedでない場合にもborderが表示されてしまう場合があるため、transparent指定ではなく、border有無を切り替えるstyleに変更

- package.json
- yarn.lock
stylelint の不具合に依って指定していた postcss のバージョン固定を解除。
> refactor: postcss のバージョン固定を解除

- src/components/TextLink/TextLink.tsx
視覚的な差の少ない :hover スタイルが指定されていた。
User Agent Stylesheet でも hover の指定はないため、smarthr-ui でも `:hover` は不要と判断した。
- [Chrome](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css)
- [Safari](https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css)
- [Firefox](https://searchfox.org/mozilla-central/source/layout/style/res/html.css)
> fix: TextLink から不要な hover スタイルを削除

- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/index.ts
- src/index.ts
通知や件数を表示するためのコンポーネントです。
NotificationBadge という命名も考えましたが、通知以外でも使われる可能性があるため Badge としました。
- 数字を表示するか、ドットを表示するか選択できます
- 今後テキストを表示したい要望が出る可能性がありますが、まずは数字のみを実装します
- count=0 の場合にコンポーネントを表示するかどうか選択できます。デフォルトでは0は表示しません
- 何件まで数えるかを指定できます。デフォルトは99件です
- children を与えると、その children の右肩に表示します
- 表示位置は、現状右肩だけですが、今後課題が見つかった時に対応予定です
- 色は blue | grey | yellow | red から選択できます。デフォルトは blue です。
> feat: Badge を追加

- src/components/ComboBox/MultiComboBox.tsx
* https://github.com/kufu/smarthr-ui/commit/0b2c3e06e61692109bb4b2c7254e448889a60fb0#diff-99591a6bd0570c02c5bf0202f232fa3976be1bb4d82ee52eea61c3f0fc5275c9R484
* 上記の修正にでスタイル属性に`pointer-events`を当てたが、スタイル属性はcamelケースで指定する必要があるためエラーになる
* `Warning: Unsupported style property pointer-events. Did you mean pointerEvents?`
* kebabケースからcamelケースに修正しエラーを解消した
> fix: style属性に渡すプロパティのため、camel caseに変更する

- src/components/CheckBox/CheckBoxInput.tsx
- src/components/RadioButton/RadioButtonInput.tsx
- https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99/backlog?selectedIssue=SHRUI-715
Windowsなどで提供されているカラーテーマによっては、ラジオボタンやチェックボックスがチェックされているかどうかがわからなかった。
`forced-colors: active` メディアクエリを利用し、カラーがOSなどによって矯正されている場合は、ラジオボタンやチェックボックスをブラウザデフォルトのUIを表示し、選択状態がわかるようにした。
Google Chromeの開発者ツールで、forced-colors: activeをEmulateしたときのキャプチャ
左の「RadioButton」ラベルがついたRadioButtonは選択されているにも関わらず、選択状態が分からない
> feat: 白黒反転などの強制カラーモードに対応する

- src/components/InputFile/InputFile.tsx
とくになし
ブラウザネイティブの`<input type="file" />` のUIとdecoratorで挿入可能なテキストの2つがスクリーンリーダーで読まれる。
1. <img width="870" alt="VoiceOverでInputFileを読み上げているスクリーンショット「ファイル選択: 選択されていません、ボタン、12の2」" src="https://github.com/kufu/smarthr-ui/assets/6724665/778ce12f-8ec1-4a29-925c-cd7d7b485b24">
2. <img width="849" alt="VoiceOverでInputFileを読み上げているスクリーンショット「ファイルを選択、12の2」" src="https://github.com/kufu/smarthr-ui/assets/6724665/0f8f70b6-8336-4d6d-bb2a-3dfe6a9bf0c6">
`<InputFile>` は視覚的な提示も、roleもbuttonであるためユーザーからは「ボタン」であると認識されうる。
スクリーンリーダーユーザーとしては `input[type=file]`のあとに追加で「ファイルを選択」と読まれるとそこも操作可能と勘違いしてしまう。
decoratorのテキストを`<InputFile>`の読み上げられるテキストとして統一、そこが操作可能な状態を目指す。
decorator のテキストは `aria-hidden` で隠しつつ、そのテキストの内容をinput[type=file]に関連付ければ良い。
`aria-hidden` & `aria-labelledby`
```html
<input type="file" aria-labelledby=":u1:" …
```
> feat: InputFileのラベルが2回スクリーンリーダーで読まれないように

- src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1694669568761429
FilterDropdownを他のボタン類と合わせて使用する際にサイズの調整が効かずデザイン調整ができないため、FilterDropdownにトリガーのボタンサイズを渡せるようにしました。
FilterDropdownに`triggerSize` propsを生やしました（DropdownMenuButtonと同じI/Fです）
> feat: FilterDropdown にサイズ小オプションを追加

- package.json
- yarn.lock
> chore: revert update dependency glob to 10.3.7

- package.json
- yarn.lock
https://github.com/kufu/smarthr-ui/pull/3758 のプルリクでの指定だと最終的なインストールバージョンが 3.10.6 にできていなかったので、それの修正です。
> chore: fix glob version

- src/components/FieldSet/FieldSet.tsx
- FieldSetは非推奨コンポーネントのため、FormControlに置き換えたい
- その際、メッセージやエラーメッセージの配置が変わってしまうため、UIの食い違いを防ぐため、大きな単位での作業になってしまいがちとなる
- なるべく小さな単位で置き換えすることができるよう、FieldSet非推奨コンポーネントのUIをFormControlによせることで置き換えしやすくしたい
> feat!: FieldSet非推奨コンポーネントのヒント、エラーメッセージの配置をFormControlと揃える

- src/components/Text/Text.tsx
color や leading といった props が DOM に流し込まれていたため明示的に絞った。
> fix: Text の color や leading などの属性を DOM から隠す

- src/components/Switch/Switch.tsx
幅や高さ指定に `1rem` が使われていたため、`:root { html: { font-size: '10px'; } }` などと書かれた環境で想定した表示にならない。
デザイントークンを参照するように修正する。
- rem を使っている箇所を `fontSize` のトークンで書き換え
- キーボード操作時にアウトラインが表示されないことに気がついたので修正
> fix: Switch がルートフォントサイズに依存していたので、theme を参照するように修正

- src/components/Select/Select.tsx
before | after
--- | ---
Chrome は VRT で確認。
- ブロック方向の padding を足しました
- 他フォーム要素と合わせて、display を `inline-block` にしました
- 不要な box-sizing の指定を消しました
- 他、細かな書き方を修正しました
> fix: Select の文字位置が Firefox でズレていたので修正

- .storybook/preview.tsx
どのタイミングかわからないが、いつの間にか消えて警告が出ていたので修正。
> chore: CSS Reset のツールバーにタイトルを設定

- .gitignore
- Editorの設定ファイルがgit管理されないように.gitignoreを更新する
- .gitignoreを更新
> chore: .ideaのディレクトリ配下をgit管理から排除

- src/components/Dialog/VRTDialog.stories.tsx
DialogコンポーネントにVRT用のStoryを追加しました。
- VRT Open Dialog Narrow
- スマートフォン環境を想定した、ウィンドウ幅の狭い状態でダイアログを開いた状態
- VRT Dialog Forced Colors
- `forcedColors: 'active'` を適用した状態
[ドキュメント](https://www.chromatic.com/docs/snapshots/#3-take-a-screenshot-and-crop-it-to-the-dimensions-of-the-ui)によるとChromaticは`#storybook-root`要素の範囲でスナップショットを撮るのですが、開いたダイアログはこの要素の外側に作られるため、画面幅が狭い状態ではダイアログの幅は`#storybook-root`より広くなり、Chromaticのスナップショットでは両側が欠けた状態になってしまいます。
これを回避するには、`.storybook/preview.ts`で、`body`の`padding`を`0`にする（そうすると`#storybook-root`が画面幅いっぱいまで広がるはずです）などの対応が必要そうですが、他のStoryにも影響するため、現時点では何もしていません。
Chromatic上のスナップショットは以下です↓
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=652cd9a4c187d7a433a24719
こちらもChromatic上のスナップショットは以下です↓
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=652cd9a4c187d7a …
> chore: DialogコンポーネントにVRT用のStoryを追加 

- tsconfig.build.json
- 他のプロジェクトでpresetを再利用したい
- npm packageとして公開するときのbuild対象ファイルとして `smarthr-ui-preset` を追加した
`npm publish --dry-run` するのはアカウント作らないとで手間だったので下記で確認しました
(1) smarthr-ui-presetがpackされてることを確認する
```sh
$ yarn prepublishOnly  && yarn pack && tar xvzf smarthr-ui-v37.0.0.tgz   
$ ls package/lib/
smarthr-ui-preset.d.ts    smarthr-ui-preset.js      smarthr-ui-preset.js.map  src/
```
(2) 他のプロジェクトでpackしたファイルを`dependencies` に入れる
```sh
$ pnpm add ../smarthr-ui/package 
$ git diff package.json
```
```diff
diff --git a/package.json b/package.json
index 0c41809..6988029 100644
--- a/package.json
+++ b/package.json
@@ -17,6 +17,7 @@
"next": "^13.5.4",
"react": "^18.2.0",
"react-dom": "^18.2.0",
+    "smarthr-ui": "link:../smarthr-ui/package",
"swagger-ui-react": "^5.9.0"
},
"devDependencies": {
```
(3) presetを読み込む …
> chore: tailwind用presetをpublishするようにした

- tsconfig.build.json
https://github.com/kufu/smarthr-ui/pull/3847
- `tsconfig.build.json` の1ファイル内で `include` を複数設定すると、その階層が反映された状態でビルドされてしまう
- そのため、今までのビルドでは `src/` 以下が `lib/` 以下にビルドされていたのに、前回の対応で `lib/src/` 以下にビルドされるようになってしまっていた
- その結果、エントリポイントとして指定されている `lib/index.js` が存在しないことになってしまい、コンポーネント群がimportできなくなってしまった
Reverts kufu/smarthr-ui#3847
nothing
> fix: Revert "tailwind用presetをpublishするようにした" (#3847)

- src/components/Button/VRTButton.stories.tsx
#3751 
ButtonコンポーネントのVRT用のStoryに、VRT用である旨の表示を追加しました。また、Story名に入っていた"Force Color"を"Forced Colors"に変更して他のコンポーネントと統一しました。
- VRT Button State
- VRT Button Anchor State
- VRT Button Forced Colors
- VRT Button Anchor Forced Colors
説明文用のInformationPanelの追加に伴い、インデントがずれたので、git上はコードの差分が多く発生していますが、メインのButtonコンポーネント群に関するところは変更していません。
> chore: ButtonのVRT用Storyに説明など追加

- smarthr-ui-preset.ts
- src/components/TextLink/TextLink.tsx
- src/themes/createShadow.ts
[Link](https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99/backlog?selectedIssue=SHRUI-777&text=textlink)
- TextLinkコンポーネントをTailwindで書き換え
1. TextLinkコンポーネントを対象に、Tailwindを利用した書き換えを実装
2. boxShadowのpresetにunderlineのスタイルを追加
> feat: TextLink を Tailwind CSS 化

- .storybook/preview.tsx
- src/components/Dropdown/DropdownContentInner.tsx
- src/hooks/useTailwindTheme.ts
- src/index.ts
- src/themes/index.ts
- src/themes/tailwind/TailwindThemeProvider.tsx
- src/themes/tailwind/index.ts
- src/themes/tailwindTheme.ts
- tailwind.config.ts
内部的に JavaScript から動的に theme 値を参照したい場合に、現状では利用者が設定した tailwindConfig の値を参照できていなかった。
Context を挟んでもらうことにより、利用者が実際に使っている tailwindConfig を参照できるようにした。
- tailwindcss 用の ThemeProvider を作成
- tailwindConfig を呼び出し、theme を返す hooks を作成
- smarthr-ui 自体に適用
- ローカルで tailwind.config.js を書き換えて動作確認
```jsx
export default {
...
theme: {
extend: {
spacing: {
'0.5': '10em',
},
},
},
}
```
> feat: tailwindcss 環境向けの ThemeProvider を追加

- src/components/Balloon/VRTBalloon.stories.tsx
BalloonコンポーネントにVRT用のStoryを追加しました。
> chore: BalloonのVRT用Storyを追加

- package.json
[Slack](https://kufuinc.slack.com/archives/CGC58MW01/p1698130887852489?thread_ts=1698125678.289769&cid=CGC58MW01)
- 削除してから生成しないと、意図していない状態を生成する事象が発生したため
- 提案レベルで出しておりますので、もし対応不要等とのことがあればCloseします！
- 生成されたディレクトリやファイルを一旦削除してから生成し直すようにコマンドを変更
- package.jsonのコマンドを編集
`yarn clean`  を実行した際に、`./lib`, `./esm`, `./smarthr-ui.css` が削除されていることを確認済み
> chore: cleanコマンドに `./esm` , `./smarthr-ui.css` を追加

- src/components/Button/AnchorButton.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Button/ButtonInner.tsx
- src/components/Button/ButtonWrapper.tsx
- src/components/Button/useClassNames.ts
- src/components/Loader/Loader.tsx
- src/smarthr-ui-preset.ts
https://smarthr.atlassian.net/browse/SHRUI-731
Button コンポーネントを Tailwind CSS 化します。
- ゴリッと preset を見直しました
- overflow に `inherit | initial | unset | revert` のグローバル値を生やしました
- spacing に `em: '1em'` を生やしました
- ほか
- Button を置き換えました
- ButtonWrapper を置き換えました
- ButtonInner を置き換えました
- クラスセレクタでスタイル指定していた箇所を置き換えました
> feat: Button を Tailwind CSS 化

- src/components/Base/BaseColumn/VRTBaseColumn.stories.tsx
BaseColumnコンポーネントにVRT用のStoryを追加しました。
> chore: BaseColumnのVRT用Storyを追加

- src/components/Base/VRTBase.stories.tsx
BaseコンポーネントにVRT用のStoryを追加しました。
- Narrow
- 画面幅が狭い状態
> chore: BaseのVRT用Storyを追加

- src/components/FieldSet/FieldSet.tsx
- src/components/FormGroup/FormGroup.tsx
- src/components/Heading/Heading.tsx
- src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx
- src/components/RightFixedNote/RightFixedNote.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.ts
- smarthr-ui/Headingは見出しを表現するためのコンポーネントであり、見出し出ない場合はTextコンポーネントで表現するべき、という思想
- Headingは内部的にはTextコンポーネントのaliasなので置き換えも簡単...と思っていたが、想像以上にtag="span"が利用されており、意図しない状態になっている
- a11y系チェックの誤検知なども引き起こしてしまう可能性があるため、Headingコンポーネントのtag属性にはspan, legendを設定出来ないようにしたい
> fix!: headingコンポーネントのtag属性にspan, legendを指定不可能にする

- src/components/Tooltip/VRTTooltip.stories.tsx
TooltipコンポーネントにVRT用のStoryを追加しました。
> chore: TooltipのVRT用Storyを追加

- e2e/components/Dialog/Dialog.test.ts
- e2e/components/Dialog/DialogWrapper.test.ts
- e2e/components/Dialog/MessageDialog.test.ts
- src/components/Dialog/ActionDialog/ActionDialogContent.tsx
- src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- src/components/Dialog/BodyScrollSuppressor.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Dialog/DialogCloser.tsx
- src/components/Dialog/DialogContent.tsx
- src/components/Dialog/DialogContentInner.tsx
- src/components/Dialog/DialogOverlap.tsx
- src/components/Dialog/DialogPositionProvider.tsx
- src/components/Dialog/DialogTrigger.tsx
- src/components/Dialog/DialogWrapper.tsx
- src/components/Dialog/FocusTrap.tsx
- src/components/Dialog/FormDialog/FormDialogContent.tsx
- src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- src/components/Dialog/MessageDialog/MessageDialogContent.tsx
- src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
- src/components/Dialog/ModelessDialog.tsx
Dialog の背景を押した時の挙動がまちまちだったため揃えました。
Dialog の背景は予期せずクリックした場合に閉じてしまうのを避けるため、デフォルトで閉じないようにしました。
- VFC を FC に置き換え
- `onClickOverlay` の初期値に `onClickClose` を渡している箇所を消去
- children を独自定義しているところを `PropsWithChildren` で置き換え
> fix: Dialog の背景を押した時の挙動をデフォルトで閉じないように揃える

- src/components/Button/ButtonWrapper.tsx
- src/components/Icon/__snapshots__/Icon.test.tsx.snap
- src/components/Icon/generateIcon.tsx
- src/components/Table/Th.tsx
- src/smarthr-ui-preset.ts
強制カラーモード時にシステム色を使うように修正しました。
normal | forced color mode (light) | forced color mode (dark)
--- | --- | ---
> fix: 強制カラーモード時に Icon の色が強制されない欠陥を修正

- src/components/ComboBox/VRTComboBox.stories.tsx
ComboboxコンポーネントにVRT用のStoryを追加しました。
- VRT Single
- Singleコンボボックスのリストを展開し、１つ目の項目をホバーした状態
- VRT Multi
- Multiコンボボックスのリストを展開した後に、１つ目と2つ目の項目を選択した状態
- VRT Single Forced Colors
- VRT Singleに、forcedColors: 'active' を適用した状態
- VRT Multi Forced Colors
- VRT MultiにforcedColors: 'active' を適用した状態
完全に網羅しようとするとあまりにも冗長になると判断し、リストを展開していくつかの操作をした状態をVRT用テストとして追加しました。他に必要なテストがありそうでしたらご指摘ください。
> chore: ComboboxのVRT用Storyを追加

- src/components/InputFile/VRTInputFile.stories.tsx
InputFileコンポーネントにVRT用のStoryを追加しました。
- VRT State
- hoverやfocusなどを適用した状態
- このコンポーネントにはフォーカスのスタイル当てにfocus-withinを利用していたため、focus-withinのstateを特別に追加してあります
> chore: InputFileのVRT用Storyを追加

- src/components/DatePicker/VRTDatePicker.stories.tsx
CalendarコンポーネントにVRT用のStoryを追加しました。
- Expanded
- カレンダーを展開した状態
- Expanded Forced Colors
- ExpandedのforcedColors: 'active' を適用した状態
- Expanded Years
- カレンダーを展開し、さらに年を選択する状態
- Expanded Years Forced Colors
- Expanded YearsのforcedColors: 'active' を適用した状態
- Bootm Expanded
- ページ下部でカレンダーを展開し、上部方向に表示されるか確認
一部抜粋
> chore: DatePickerのVRT用Storyを追加

- src/components/CheckBox/VRTCheckBox.stories.tsx
CheckboxコンポーネントにVRT用のStoryを追加しました。
- VRT State
- hoverやfocusなどを適用した状態
> chore: CheckboxのVRT用Storyを追加

- src/components/Input/SearchInput/VRTSearchInput.stories.tsx
- src/components/Input/VRTInput.stories.tsx
InputコンポーネントにVRT用のStoryを追加しました。
- InputのAllに対してforcedColors: 'active' を適用した状態
- Hover Search Input
- Search Input をホバーしてツールチップを表示した状態
- Hover Search Input Forced Colors
- Hover Search Inputに対してforcedColors: 'active' を適用した状態
> chore: InputのVRT用Storyを追加

- src/components/RadioButton/VRTRadioButton.stories.tsx
RadioButtonコンポーネントにVRT用のStoryを追加しました。
- VRT State
- hoverやfocusなどを適用した状態
- チェックされたラジオボタンも含む
> chore: RadioButtonのVRT用Storyを追加

- src/components/Select/VRTSelect.stories.tsx
RadioButtonコンポーネントにVRT用のStoryを追加しました。
- VRT State
- hoverやfocusなどを適用した状態
このSelectコンポーネントをクリックしたい際に表示されるリストはブラウザデフォルトのものであるため、そのリストのVRTテストは不要と判断しました。VRT用で他に必要そうなストーリーは思いつきませんでした。
> chore: SelectのVRT用Storyを追加

- src/components/Icon/VRTIcon.stories.tsx
IconコンポーネントにVRT用のStoryを追加しました。
- ColorとAllのStoryに対してforcedColors: 'active' を適用した状態
もともと、Size、Text、WithTextなどのストーリーがあり十分そうに思えたので、ForcedColorsだけ追加しました。
forcedColors: 'active' を適用した状態でVRTしたほうが良さそうなものはColorとAllの2つで十分と判断しました。
> chore: IconのVRT用Storyを追加

- src/components/CheckBox/CheckBoxInput.tsx
強制カラーモードの時、チェックマークが二重で表示されていた
`forced-colors: active` メディアクエリを利用し、カラーがOSなどによって矯正されている場合は、smarthr-ui 側で表示しているチェックアイコンを非表示にした。
Google Chromeの開発者ツールで、forced-colors: activeをEmulateしたときのキャプチャ
> fix: 強制カラーモードの時、チェックマークが二重で表示されていたのでブラウザ標準UIのみを表示するようにした

- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/VRTTextarea.stories.tsx
TextareaコンポーネントにVRT用のStoryを追加しました。
- State
- focus した状態
- InputのAllに対してforcedColors: 'active' を適用した状態
> chore: TextareaのVRT用Storyを追加

- src/components/AccordionPanel/VRTAccordionPanel.stories.tsx
AccordionPanelコンポーネントにVRT用のStoryを追加しました。
AccordionPanelコンポーネントに3つのVRT用Storyを追加
- VRT Open Accordion
- パネルを開いた状態
- VRT Open Accordion Narrow
- スマートフォン環境を想定した、ウィンドウ幅の狭い状態でパネルを開いた状態
- VRT Accordion Forced Colors
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6551acc208431a2092af5726
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6551acc208431a2092af5727
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6551acc208431a2092af5728
> chore: AccordionPanelのVRT用Storyを追加

- src/components/Pagination/VRTPagination.stories.tsx
PaginationコンポーネントにVRT用のStoryを追加しました。
- State
- active、hover 等した状態
- Scroll
- 画面幅を狭くしてスクロールした状態
> chore: PaginationのVRT用Storyを追加

- src/components/DatePicker/VRTDatePicker.stories.tsx
日付が固定されていないと Chromatic 上で DatePicker の VRT 用 story に毎日差分が発生してしまうので、日付を固定しました。
> fix: DatePicker の VRT 用 story の日付を固定

- src/components/Layout/Center/VRTCenter.stories.tsx
- src/components/Layout/Cluster/VRTCluster.stories.tsx
- src/components/Layout/LineUp/VRTLineUp.stories.tsx
- src/components/Layout/Reel/VRTReel.stories.tsx
- src/components/Layout/Sidebar/VRTSidebar.stories.tsx
- src/components/Layout/Stack/VRTStack.stories.tsx
Layout以下の各コンポーネントにVRT用のStoryを追加しました。
Layout以下の各コンポーネントに2つのVRT用Storyを追加
- スマートフォン環境を想定した、ウィンドウ幅の狭い状態でパネルを開いた状態
ただし、Reelに関しては、元から幅の狭い状態のStoryが存在しているため、forcedColorsのみ追加しました。
Center
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c1b
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c1c
Cluster
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c1e
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c1f
LineUp
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c21
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65530cf30b9752267eee2c22
Reel …
> chore: LayoutのVRT用Storyを追加

- src/components/Badge/VRTBadge.stories.tsx
BadgeコンポーネントにVRT用のStoryを追加しました。
画面幅は影響しないコンポーネントで、ボタンを押すなどの動作もないので、forcedColors: 'active' を適用したStoryのみ追加しています。
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=65544fb0dabe0867f26b9233
> chore: BadgeのVRT用Storyを追加

- src/components/Heading/VRTHeading.stories.tsx
HeadingコンポーネントにVRT用のStoryを追加しました。
単純に見出しだけなのでForced ColorsでさえもVRTが必要か悩ましかったので不要であればリジェクトでも構いません🙏
> chore: Heading、PageHeadingのVRT用Storyを追加

- src/components/Text/VRTText.stories.tsx
TextコンポーネントにVRT用のStoryを追加しました。
これもHeading同様に単純にテキストだけなのでForced ColorsでさえもVRTが必要か悩ましかったので、不要であればリジェクトでも構いません！🙏
> chore: TextのVRT用Storyを追加

- src/components/FormGroup/FormGroup.tsx
https://smarthr.atlassian.net/browse/KAT-999
https://kufuinc.slack.com/archives/CGC58MW01/p1699923068678449
- FormControl内のDatePickerをStyled-Componentとしてラップした際に、FormControl側で作成されたlabelのidやaria-describedbyがinputに紐づかない問題を解決したい
- 対象のコンポーネントがStyled-Componentだった場合に、Styled-Componentのターゲットに対して判定をかけるようにした
> fix: Input等がStyled-Componentでラップされている際にFormControlを使用してもラベルのid等が紐づかない問題を修正

- src/components/NotificationBar/NotificationBar.stories.tsx
- src/components/NotificationBar/NotificationBar.tsx
どこかのタイミングでデグレっていた。
- テキストに折り返しが発生した時、アイコンや閉じるボタンは baseline で揃える
- 操作群が横1列に収まらない時、テキストの右下にボタンは収まる
before | after
--- | ---
> fix: 画面幅が狭い時の NotificationBar の見た目を調整

- src/components/TextLink/VRTTextLink.stories.tsx
TextLinkコンポーネントにVRT用のStoryを追加しました。
- State
- hover、focus、focusVisible、activeで変化はないのですが、リンクであるため念のため追加しました
- UserFocus
- 上記のfocus、focusVisibleでは専用の装飾がないと変化がないため、ユーザー操作によるフォー明かすをシミュレートしてブラウザデフォルトのフォーカスのスタイルを表示しています
State、UserFocusのストーリーが必要か悩ましいところでした。不要ならお伝えください。
> chore: TextLinkのVRT用Storyを追加

- package.json
- src/components/ComboBox/__tests__/useActiveOption.test.ts
- src/components/ComboBox/__tests__/useOptions.test.tsx
- yarn.lock
- [testing\-library/react\-hooks\-testing\-library](https://github.com/testing-library/react-hooks-testing-library)
テストで利用しているライブラリ `@testing-library/react-hooks` の peerDependencies に React 18 は含まれておらず、`@testing-library/react-hooks` の README でも React 18 を使う際は `@testing-library/react` に移行するよう促されています。
[A Note about React 18 Support](https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support)
指示に従いライブラリの変更を行いました。
- package.json の変更
- テスト内での読み込み元ライブラリの変更
> test: @testing-library/react-hooks から @testing-library/react に移行

- src/components/Icon/Icon.tsx
Icons にアイコンを追加したい
以下の3つのアイコンを追加した。
- FaBabyCarriage
- FaTruck
- FaTruckLoading
> feat: add new icons: FaBabyCarriage, FaTruck, and FaTruckLoading

- src/components/CheckBox/CheckBoxInput.tsx
- src/components/RadioButton/RadioButtonInput.tsx
Close #3991 
before | after
--- | ---
> feat: CheckBox と RadioButton の disabled 色を見直す

- src/components/Badge/Badge.tsx
- src/components/Button/ButtonWrapper.tsx
- src/components/InformationPanel/InformationPanel.tsx
- src/components/NotificationBar/NotificationBar.tsx
- src/components/Tooltip/TooltipPortal.tsx
🍐 
いつからか SmartHR UI を読み込むと添付したキャプチャのような warning が多発するようになった。
これは、element に本来存在しない名前の props がそのまま DOM element に渡されてしまっているために warning になっているので、そういうのは渡されないようにしたい。
- styled-components の機能を使って、`$` をつけることで DOM に渡らないようにする
- ButtonWrapper の isAnchor に関しては styled-components じゃなかったのでスプレッド構文で渡しているところを isAnchor だけ取り出している
動作確認としては、
- この変更では UI は変わらないので、意図しない差分が出ていないこと
- 直したコンポーネントで warning が出ないようになっていること
とかを見てもらえると良さそうです。
🍐
> fix: props が DOM element に渡ってしまって warning になっている箇所を修正

- src/components/FormGroup/FormGroup.tsx
- https://github.com/kufu/smarthr-ui/pull/3908 の変更で、FormControl(FormGroup)のGroupLabelTextに `as` が 使われるようになったのですが、`styled(Text)` なので `forwardedAs` でないと正しく渡されないため修正しました
- as を forwardedAs に変更
- FormControlのstory
- before: labelにstyleが当たっていない
- after: labelにstyleが当たっている
| --- | --- |
| <img width="350" alt="image" src="https://github.com/kufu/smarthr-ui/assets/16136015/4ad77b75-2794-48f1-ae63-fdafcba8ab41"> | <img width="474" alt="image" src="https://github.com/kufu/smarthr-ui/assets/16136015/b018df94-815b-42ca-af79-8500d5875f0c"> |
> fix: FormGroupのGroupLabelTextでforwardedAsを使うように修正

- src/components/Layout/Center/Center.tsx
Center に className が渡っていなかったため styled-components が使えていなかった欠陥を修正
> fix: Center を styled-components で装飾することができない欠陥を修正

- src/components/BackgroundJobsPanel/VRTBackgroundJobsPanel.stories.tsx
BackgroundJobsPanelコンポーネントにVRT用のStoryを追加しました。
- VRT Panel State
- パネル内のボタンにhoverやfocusなどを適用した状態
- VRT Panel Hover Long
- 長いテキストにホバーしてツールチップを表示した状態
panelのストーリーに対してVRT用のストーリーを追加しました。
listはJavaScriptによる処理と見受けられましたのでTailwindへの移行のための追加テストは不要と判断しました。
> chore: BackgroundJobsPanelのVRT用Storyを追加

- src/components/NotificationBar/VRTNotificationBar.stories.tsx
NotificationBarコンポーネントにVRT用のStoryを追加しました。
以下の4つを追加しました
- 画面幅が狭いとき
- DemoでNotificationBarが表示された状態（アニメーション終了時点）
- 閉じるボタンにフォーカスした状態
- `forcedColors: 'active'` を適用した状態
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6556f539b8a3275b227ffbc1
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6556f539b8a3275b227ffbc2
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6556f539b8a3275b227ffbc3
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6556f539b8a3275b227ffbc4
> chore: NotificationBarのVRT用Storyを追加

- src/components/CompactInformationPanel/VRTCompactInformationPanel.stories.tsx
CompactInformationPanelコンポーネントにVRT用のStoryを追加しました。
- VRT Narrow
- 画面幅の狭い状態
CompactInformationPanelのストーリーに対してVRT用のストーリーを追加しました。
DefaultとTypeがありましたが、TypeがDefaultのケースも含め網羅的にコンポーネントの状態を用意していましたので、そちらを流用してVRT用のストーリーを作成しました。
> chore: CompactInformationPanelのVRT用Storyを追加

- src/components/DefinitionList/VRTDefinitionList.stories.tsx
DefinitionListコンポーネントにVRT用のStoryを追加しました。
- VRT Narrow
- 画面幅の狭い状態
DefinitionListのストーリーに対してVRT用のストーリーを追加しました。
> chore: DefinitionListのVRT用Storyを追加

- src/components/StatusLabel/VRTStatusLabel.stories.tsx
StatusLabelコンポーネントにVRT用のStoryを追加しました。
画面幅は影響しないコンポーネントで、ボタンを押すなどの動作もないので、forcedColors: 'active' を適用したStoryのみ追加しています。
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6556fb89421058594ad2d213
> chore: StatusLabelのVRT用Storyを追加

- src/components/ComboBox/MultiComboBox.tsx
- src/components/ComboBox/SingleComboBox.tsx
- src/components/Select/Select.tsx
Select、SingleCombBox、MultiComboBox のジェネリクス部分の型情報が壊れていたので修正しました。
forwardRef されたコンポーネントではジェネリクスの型情報を正しく扱えないので、何かしらの回避策が必要ということで、下記を参考にして検討をしました。
https://stackoverflow.com/a/58473012
今回は、対応の対象となるコンポーネントが3コンポーネントと限られていたので、やや力技ではありつつも影響範囲を小さくできる1つ目の方法 (1. Use type assertion("cast")) が良いかなと思い、修正をしています。
下記は tsc によって吐き出された Select コンポーネントの型情報の before/after のキャプチャです。
after では正しくジェネリクスを受け取ることができるようになっていることがわかります。
before
after
下記は実際にジェネリクスを渡したときの before/after のキャプチャです。
before ではそもそもジェネリクスを渡す部分でエラーが発生していて、コールバックの型は string 型になってしまっています。
after ではジェネリクスを渡せるようになり、コールバックの型もジェネリクスで指定した通りのものになっています。
before
after
> fix: forwardRef によって壊れていた型情報を直した

- src/components/Icon/generateIcon.tsx
Icon[right] の場合は CSS を使わない実装になっていたが、混乱を生みそうなため左右どちらにアイコンが来ても同じ実装になるよう修正した。
折返しが発生した場合、アイコンの下に文字は回り込まないが、親要素の幅で回避できるためそれで良しとする。
（回り込みが必要な場面の方が少ないと判断した。）
> fix: テキスト付き Icon における左右位置の実装を揃える

- src/components/PageCounter/VRTPageCounter.stories.tsx
PageCounterコンポーネントにVRT用のStoryを追加しました。
- forcedColors: 'active' を適用した状態。
PageCounterに関しては表示内容が単純なテキストだけのため、 VRT Forced Colorsのストーリーも不要ではと迷いましたが念のため追加しました。不要であれば、このPRをリジェクトいただければと思います。
> chore: PageCounterのVRT用Storyを追加

- src/components/RightFixedNote/VRTRightFixedNote.stories.tsx
RightFixedNoteコンポーネントにVRT用のStoryを追加しました。
- VRT Hover
- ボタン要素をhover
- VRT Focus Visible
- ボタン要素とテキストエリアをフォーカス
- forcedColors: 'active' を適用した状態。
他のコンポーネントではhoverとfocusVisibleはVRT Stateというストーリーでひとまとめにしていましたが、このコンポーネントが1画面に1つ配置される特殊なコンポーネントであるため別々のコンポーネントに分けました。
> chore: RightFixedNoteのVRT用Storyを追加

- src/components/LineClamp/VRTLineClamp.stories.tsx
LineClampコンポーネントにVRT用のStoryを追加しました。
- ~~VRT State~~
- ~~hover、activeを擬似的に指定した状態（その状態もスタイルによる装飾がないようなので、変化はありません）~~
- VRTUserHover
- ユーザー操作のhoverをシミュレートしてツールチップを表示した状態
- VRTUserFocus
- ユーザー操作のfocusをシミュレートしてツールチップを表示した状態
- forcedColors: 'active' を適用した状態。ツールチップが出ている状態が良いと考え、フォーカスしてツールチップが表示されている状態を対象にしています
LineClampのストーリーに対してVRT用のストーリーを追加しました。
> chore: LineClampのVRT用Storyを追加

- src/components/TabBar/VRTTabBar.stories.tsx
PaginationコンポーネントにVRT用のStoryを追加しました。
- Hover
- hover した状態
- UserFocus
- ユーザー操作のフォーカスをシミュレートした状態
- Scroll
- 画面幅を狭くしてスクロールした状態
> chore: TabBarのVRT用Storyを追加

- src/components/Dialog/DialogContentInner.tsx
- src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- portalなどで擬似的にform in form している場合でもsubmitイベントが親に到達してしまうため、stopPropagationを追加します
> fix: FormDialogのsubmit時、portal等で擬似的にネストしている親formをsubmitしてしまうためstopPropagationを追加する

- .circleci/config.yml
フロントのSlackで共有した件です。
Chromaticの利用料削減のため、turbosnapを有効にし、gitのコミットの差分に依存しないコンポーネントのスナップショットは取得しないように修正します。
詳細は以下のドキュメントをご確認ください。
https://www.chromatic.com/docs/turbosnap/#turbosnap-beta
> chore: turbosnapを有効にして無駄なスナップショットを減らす

- src/components/Layout/Sidebar/Sidebar.stories.tsx
- src/components/Layout/Sidebar/Sidebar.tsx
https://smarthr.atlassian.net/browse/SHRUI-765
tailwindcss では `* > :first-child` に対して動的な `min-width` を与えられないため、React 側で疑似的に `:first-child` と `:last-child` を再現しています。
> refactor: Sidebar を Tailwind CSS 化

- src/components/ErrorScreen/ErrorScreen.tsx
- src/components/Layout/Center/Center.tsx
- src/components/Layout/Cluster/Cluster.tsx
- src/components/Layout/Reel/Reel.tsx
- src/components/Layout/Sidebar/Sidebar.tsx
tailwindcss 化の際に、`styeld.div` では標準装備されていた `ref` を渡せなくなってしまっていた。
すべての Layout コンポーネントに `ref` が渡るように修正。
Hide whitespace でレビューをオススメします。
> fix: Layout コンポーネントに ref を渡せない不具合を修正

- src/components/Button/ButtonWrapper.tsx
#4073 の作業を進めている際に見つけたので修正。
軽微だったため #4073 に混ぜようとしたがChromaticのVRTで対象のコンポーネント以外に差分が出ていたため、原因を分けるためにPRを分けた。
[Chromatic](https://www.chromatic.com/build?appId=63d0ccabb5d2dd29825524ab&number=4701)
> chore: ButtonWrapper 内で `shr-` prefix の漏れを修正

- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
- src/components/Dropdown/DropdownMenuButton/VRTDropdownMenuButton.stories.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- src/components/Dropdown/FilterDropdown/VRTFilterDropdown.stories.tsx
DropdownMenuButton, FilterDropdownコンポーネントにVRT用のStoryを追加しました。
どちらも、
- 画面幅が狭くドロップダウンを開いた状態
- 強制カラーモードでドロップダウンを開いた状態
の2つを追加しています。
DropdownMenuButton
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6566d8b46540584f27f1c5b7
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6566d8b46540584f27f1c5b8
FilterDropddown
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6566d8b46540584f27f1c5ba
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6566d8b46540584f27f1c5bb
> chore: DropdownMenuButton, FilterDropdownのVRT用Storyを追加

- src/components/BottomFixedArea/VRTBottomFixedArea.stories.tsx
BottomFixedAreaコンポーネントにVRT用のStoryを追加しました。
- VRT Hover
- 通常のボタン、アンカー風のボタンすべてがhoverされた状態で表示されます
- VRTFocusVisibleButton
- 通常のボタンがfocusされた状態で表示されます
- VRTFocusVisibleAnchor
- アンカー風のボタンの1つ目がfocusされた状態で表示されます
- VRTNarrow
- 画面幅が狭い状態で表示されます
BottomFixedAreaには通常のボタンとアンカー風のボタンがあり、storybook-addon-pseudo-statesによるHoverはどちらにも適用できたので一つのStoryで済ませました。
アンカー風のボタンのフォーカスの状態はstorybook-addon-pseudo-statesで再現できないため、ユーザー操作のシミュレートによってフォーカスを当てています。
また、幅が狭い場合に意図したとおりに折り返すかの確認のため、画面幅の狭いStoryも用意しました。
> chore: BottomFixedAreaのVRT用Storyを追加

- src/components/AppNavi/VRTAppNavi.stories.tsx
AppNaviコンポーネントにVRT用のStoryを追加しました。
- VRT Hover
- hoverした状態で表示されます
- VRT Focus Button
- ボタンをフォーカスした状態で表示されます
- VRT Focus Anchor
- アンカーをフォーカスした状態で表示されます
- VRT Drop Down
- ドロップダウンを表示した状態で表示されます
AppNaviにはアンカーとボタンが混在させることができるため、ボタンとアンカーでそれぞれフォーカスをあてたストーリーを用意しました。独自の装飾がされていないのでstorybook-addon-pseudo-statesプラグインによってフォーカスの状態を再現できないため、ユーザー操作のシミュレートによってフォーカスを当てています。
> chore: AppNaviのVRT用Storyを追加

- src/components/Header/VRTHeader.stories.tsx
HeaderコンポーネントにVRT用のStoryを追加しました。
- VRT FocusVisibleButton
- ボタンやリンクがfocusされた状態で表示されます
- VRT DropDown
- ドロップダウンが表示された状態で表示されます
- VRT Launcher
- ランチャーが表示された状態で表示されます
- VRT NarrowTablet
- 画面幅がタブレットサイズで表示されます
- VRT NarrowMobile
- 画面幅がモバイルサイズで表示されます
> chore: HeaderのVRT用Storyを追加

- src/components/SideNav/VRTSideNav.stories.tsx
SideNavコンポーネントにVRT用のStoryを追加しました。
- VRT Hover
- hoverされた状態で表示されます
- VRT Focus
- focusされた状態で表示されます
> chore: SideNavのVRT用Storyを追加

- src/components/ComboBox/MultiComboBox.tsx
- MultiComboBoxの利用者の認知として `selectedItems.length > 0 の場合は値は入力済み` となる
- しかし、現在の仕様では `itemの検索用inputが未入力だったらrequired判定はfalse` になってしまう
- 認知とあうよう、required属性をon/offしたい
> fix: MultiComboBoxでアイテムを選択済みであるにも関わらず、requiredがhtml validationに引っかかってしまう問題を修正する

- src/components/Heading/Heading.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.ts
reset css があたっていない場合に、予期せず UA スタイルの `font-weight: 700` があたってしまうのを防ぎたい。
- bold ではない Heading には明示的に `font-weight: 400` が当たるように修正
- Text に Heading の情報を持っているのはおかしいため、Heading で持つように修正
- スタイリングの情報
- 見出しの種類
> fix: Heading のスタイリングが reset css に依存していたので修正

- src/components/RadioButtonPanel/RadioButtonPanel.tsx
smarthr-ui では押せる UI に box-shadow を使っていないため、border に変更。
> fix: RadioButtonPanel の装飾を見直し

- src/components/CheckBox/CheckBox.tsx
- src/components/CheckBox/CheckBoxInput.tsx
- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/RadioButtonInput.tsx
- src/components/RadioButton/useClassNames.ts
Reverts kufu/smarthr-ui#4122
Input と StatusLabel の背景色が指定されていない問題を先に修正してリリースしたほうが良さそうなので一旦 revert
> fix: Revert "RadioButtonをTailwindCSS化"

- src/components/DatePicker/DatePicker.tsx
reset css があたっていない場合に、border-left 以外も表示させるのを防ぐ
明示的にy(top,bottom)とr(right)に0を指定
|before|after|
|---|---|
|<img width="241" alt="before datepicker" src="https://github.com/kufu/smarthr-ui/assets/39780486/7d6663d6-6205-4e1c-862d-39d02e2faeb3">|  <img width="251" alt="after datepicker" src="https://github.com/kufu/smarthr-ui/assets/39780486/ffc3c643-15b8-4f01-a9e1-1c37e753ae0d">|
> fix: DatePicker の inputSuffixWrapper border が reset css に依存していたので修正

- src/components/TextLink/TextLink.tsx
TextLinkコンポーネントについて、ハイコントラストモード利用時に下線が表示されないため、リンクであることがわかりづらい問題を解決したいです。
CSSを修正して、強制カラーモード時にunderlineを表示するように修正しました。
| --- | --- |
| <img width="1028" alt="image" src="https://github.com/kufu/smarthr-ui/assets/60545096/46c48920-bbfd-402d-98ab-1c7f6167d023"> | <img width="1028" alt="image" src="https://github.com/kufu/smarthr-ui/assets/60545096/ff6737e9-a977-4286-b98d-013ac26f5262"> |
> fix: 強制カラーモード時、TextLinkにunderlineを表示する

- src/components/RightFixedNote/RightFixedNote.stories.tsx
- src/components/RightFixedNote/RightFixedNoteItem.tsx
RightFixedNoteのeditボタンは常に非表示になっているが、プロダクトや権限によってはコメントが編集不可の場合もあるため、editボタンの表示/非表示をpropsで制御したい。
itemの`isEditable`でボタンの表示/非表示を切り替えられるようにしました。
Chromaticから確認してください。
> feat: RightFixedNoteのeditボタンの表示/非表示を切り替えられるようにする

- src/components/Input/Input.tsx
> fix: Input[readOnly] の背景を正しい装飾に修正

- src/components/Dialog/ModelessDialog.tsx
> fix: ModelessDialog ヘッダを hover した時の装飾を修正

- src/components/Button/AnchorButton.tsx
- src/components/Button/Button.tsx
- src/components/Button/ButtonInner.tsx
N/A
`<Button>` コンポーネントにて、 `size="s"` と `prefix` または `suffix` にアイコンを指定した場合に、アイコンとテキストコンテンツの縦位置が揃わない問題を解消したいです。
`<Button>` の Tailwind 化にて、以下の箇所で `line-height` の設定を削除していますが、 `size="s"` の場合には引き続き必要に見えました。
https://github.com/kufu/smarthr-ui/pull/3899/files#r1375616072
Tailwind 化前のコードを参考に、 `line-height: 0` が設定されるようにしてみました。
→ その後不備が見つかったため、 @uknmr さんに影響範囲を最小にするようコミットいただいてます
|before|after|
|----|----|
|![スクリーンショット 2024-01-12 19 10 13](https://github.com/kufu/smarthr-ui/assets/16274215/fcd5fd94-5e0a-4230-8a94-0f9cba579812)|![スクリーンショット 2024-01-12 19 10 26](https://github.com/kufu/smarthr-ui/assets/16274215/432ce402-a7a3-4f6f-b149-cfdf946f4810)|
> fix: size="s" の Button でも、アイコンとテキストコンテントの縦位置が揃うようにする

- src/components/Chip/Chip.stories.tsx
- src/components/Chip/Chip.tsx
- src/components/ComboBox/ComboBox.stories.tsx
- src/components/ComboBox/ListBoxItemButton.tsx
- src/components/ComboBox/MultiComboBox.tsx
- src/components/ComboBox/MultiSelectedItem.tsx
- src/components/ComboBox/SingleComboBox.tsx
- src/components/ComboBox/useListBox.tsx
- src/smarthr-ui-preset.ts
Tailwind CSS 化の前に複雑なスタイリングを減らしたかったため、見直しました。
見直し自体は `refactor` でしたが、Chip や tailwind-preset に機能追加をしたため `feat` としています。
- Multi / Single で微妙にズレていた装飾を合わせました
- MultiCombobox の初期幅がマジックナンバーになっていたため、文字ベースの `20em` に変更しました
- MultiComboBox の選択済みアイテムを Chip に置き換えました
- Chip に disabled 状態を追加しました
- 不要な DOM を削りマークアップを見直しました
> feat: Combobox のスタイリングを見直し

- src/components/ComboBox/MultiComboBox.tsx
smarthr-uiのv41.1.0の更新時に表示崩れが発生したので直したい。
MultiComboboxにwidth: 100%を指定した場合に、親要素からはみ出るようになってしまいました。
参考: 発生した差分
https://www.chromatic.com/test?appId=652e2197db1cfed7fd55f831&id=65af72585b6d37d60f8ace6d
下記対応で削除された`box-sizing: border-box;`を復活させました。
- https://github.com/kufu/smarthr-ui/pull/4196/files#diff-99591a6bd0570c02c5bf0202f232fa3976be1bb4d82ee52eea61c3f0fc5275c9L475
> fix: MultiComboboxのwidth:100%が正常に動作しない不具合修正

- src/components/AccordionPanel/AccordionPanelContent.tsx
tailwindcss 化の際にアニメーション用スタイルを見直したが、不用意に `max-height: 100vh` があたっていたため削除した。
- `max-height: revert;` 相当となるスタイルを充てる
- ローカルでアニメーションに問題ないことを確認
> fix: AccordionPanel の max-height に余計なスタイルがあたっていたため削除

- src/components/Select/Select.tsx
`<Select>` コンポーネントのValueに英字などが来た場合、ディセンダーが見切れる
原因は、`<Select>` の `line-height` が `1` になっているため。
`<Select>` の `line-height` を `shr-leading-tight` （`1.25`）に変更し、`padding` を調整し高さを変えない。
Before
After
> feat: SelectのValueに英字などが来た場合、ディセンダー部分が見切れるのを修正

- src/components/ComboBox/MultiComboBox.tsx
#4196 
#4196 でMultiComboBoxの`min-width`のマジックナンバーを解消するために`20em`に指定が変更されていたが、比較的幅指定が狭い固定長のダイアログ上などで利用している場合に収まりきらず、既存のプロダクトの一部で表示崩れを誘発していた。
元々のマジックナンバー指定の頃と比較すると`20em`は約3倍大きく取っており、最小幅としては少し大きすぎる気もするので再調整をしたい。
コアメンバーと協議した結果、`15em`程度であればレイアウト崩れの心配もなさそう（仮に親要素のfont-sizeを8px程度まで小さくしても100px以上の幅は確保できる）なので、それを採用した。
> refactor: MultiComboBox の min-width を調整

- src/components/FormGroup/FormGroup.tsx
- 対象コンポーネントのerrorMessagesの表示ロジックを修正
- 利用側の都合で、常に配列としてerrorMessagesが渡されるパターンが存在し、その場合、不必要にerrorMessage用Stackがレンダリングされることにより余計な余白が生じてしまうため対応
> fix: FormControl, Fieldset の errorMessages に空配列が渡された場合、不必要な要素をレンダリングしないように修正

- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/MessageDialog/MessageDialog.tsx
- src/components/Dialog/MessageDialog/MessageDialogContent.tsx
- src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
- https://smarthr.atlassian.net/browse/SHRUI-824
- https://smarthr.atlassian.net/browse/SHRUI-825
ダイアログボディに垂直方向の padding を足したため、視覚差分が生まれています。
> refactor: MessageDialog を Tailwind CSS 化

- src/components/RightFixedNote/RightFixedNote.stories.tsx
- src/components/RightFixedNote/RightFixedNote.tsx
- src/components/RightFixedNote/RightFixedNoteItem.tsx
社内プロダクトで`RightFixedNote`を使うにあたり、`loading`(初期読み込み中)と`submitting`(送信中)の状態を追加し、`Loader`を表示するなどしたい
- Propsに`loading`と`submitting`を追加しました
- 割りとエイヤで実装したので、実装内容問題無さそうか確認お願いします！
> feat: RightFixedNoteにloadingとsubmittingの状態を追加

- src/components/ComboBox/ComboBox.stories.tsx
N/A
ストーリーブック内の文字が壊れているので解消したい。
- 文字の置き換え
> fix: ComboBox のストーリーブック内で文字が表示できていない問題を修正

- src/components/PageCounter/PageCounter.tsx
NVDAで「–」が読み上げられないため、修正したいです。
「–」に`role="img"`, `aria-label="から"`を付与しました。
`aria-label`を付与したい関係上なんらかの`role`を付与する必要があり、検討した結果`role="img"`に落ち着きました。
他には`role="paragraph"`なども候補にあがりましたが、`paragraph`は`aria-label`を付けることができないroleだったため候補から外しました。
[Accessible Rich Internet Applications (WAI-ARIA) 1.3](https://w3c.github.io/aria/#aria-label)
> fix: PageCounterの-がスクリーンリーダーで読み上げられない問題を修正

- .circleci/config.yml
N/A
pnpm化以降、Chromatic へのデプロイのビルドに失敗するようになっています。これを解消したい。
- 管理画面を見た限りOOMが濃厚なので、より強力なインスタンスサイズに変更します。
N/A
> chore: メモリー不足解消のため、Chromatic の実行インスタンスを medium+ に変更

- .husky/pre-commit
- package.json
- [Release v9\.0\.1 · typicode/husky](https://github.com/typicode/husky/releases/tag/v9.0.1)
> Removed husky install. Use husky or husky some/dir for the same functionality (deprecation notice to be added).
Husky のメジャーバージョンアップにより、警告が出る状態になっている。これを解消したい。
```
% pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date
> smarthr-ui@41.3.0 prepare /home/f440/go/src/github.com/f440/smarthr-ui
> husky install
install command is deprecated
Done in 1.6s
```
- [Release v9\.0\.1 · typicode/husky](https://github.com/typicode/husky/releases/tag/v9.0.1) の 「How to Migrate」を参考にスクリプトを修正
N/A
> chore: husky v9 対応

- package.json
- pnpm-lock.yaml
https://kufuinc.slack.com/archives/CGC58MW01/p1708387625302639
- yarn の頃は dependencies / peerDependencies でインストールしたmoduleを使っても問題なかった
- pnpm になったら厳格になってちゃんと package.json に書いてないとエラーになるようになったため、package.jsonに明記します
> chore: react-docgen-typescriptをpackage.jsonに追加

- package.json
- pnpm-lock.yaml
https://kufuinc.slack.com/archives/CGC58MW01/p1708387625302639
- yarn の頃は dependencies / peerDependencies でインストールしたmoduleを使っても問題なかった
- pnpm になったら厳格になってちゃんと package.json に書いてないとエラーになるようになったため、package.jsonに明記します
> chore: rimrafをpackage.jsonに追加

- src/components/FormGroup/FormGroup.tsx
🍐 
FormControl コンポーネントの innerMargin と dangerouslyTitleHidden prop が styled-components を通して DOM に表出しており、React の warning が出てしまっているので出ないようにしたい
styled-components にわたす際に props 名に $ をつけて回避
参考: [transient props](https://styled-components.com/docs/api#transient-props)
🍐
> fix: FormControl コンポーネントの props が DOM に表出しないようにする

- src/components/Pagination/Pagination.tsx
- Pagination の番号ボタン部分にでstyleが崩れてしまう場合があるため対応する
- reset.cssを利用していない、もしくは違うresetを行っている場合などに問題になる
> fix: Paginationコンポーネントの番号ボタンに不必要なlist-styleが表示されてしまう問題を修正

- src/components/Textarea/Textarea.tsx
- styled-componentsなどでTextareaに対してwidthを指定する場合、修正前の状態では常にstyle="width: auto;" が指定されてしまい、styled-componentsによるwidth指定が無視されてしまう
- widthの初期値はautoであるため、初期値として指定する意味も無いため調整する
> fix: Textareaでwidthを指定しない場合、style属性で"width=auto"が指定されないようにする

- src/components/Base/Base.tsx
強制カラーモードの時、Baseコンポーネントの枠が表示されなくなっていた。（強制カラーモードでは box-shadow が none に強制されるため、見えなくなっていた。）
強制カラーモードの場合、borderが表示されるように対応した。
CSSで表すと以下のようになる。
```
@media (forced-colors: active) {
border: 1px solid ButtonBorder;
}
```
Google Chromeの開発者ツールで、forced-colors: activeをEmulateしたときのキャプチャ
> fix: 強制カラーモードの時、borderのスタイルが適用されるようにした

- .circleci/config.yml
#4291 でメモリが不足してCIが落ちていたので、a11y-testのリソースクラスをmedium+へ上げました。
> test: a11y-testのリソースクラスをmedium+へ上げた

- src/smarthr-ui-preset.ts
なし
SmartHR UI を導入したプロジェクトをビルドしたところ以下のようなエラーが発生しました。
```
warnings when minifying css:
▲ [WARNING] Expected "," but found "100%" [css-syntax-error]
<stdin>:690:5:
690 │   0% 100% {
│      ~~~~
╵      ,
▲ [WARNING] Expected "," but found "100%" [css-syntax-error]
<stdin>:948:5:
948 │   0% 100% {
│      ~~~~
╵      ,
```
CSSの指定が間違っているようです。
Loaderコンポーネントの回転にあたっていたCSSが間違っていたので修正しました。
これにより今まで無効だった指定が効くようになったのですが、変化は体感できませんでした。
> fix: 無効なCSSアニメーションを修正

- src/smarthr-ui-preset.ts
- smarthr-normalize-cssが利用されていない場合、dottedのstyleを指定した時点で全方向にborderが設定されてしまう
- styleで基本のwidthを0にすることでnormalize cssを未使用でも表示崩れが起きない状態にしたい
> fix: DefinitionListのstyleがsmarthr-normalize-cssを利用していないプロダクトで崩れてしまう問題に対応する

- src/components/Badge/Badge.stories.tsx
- src/components/Base/Base.stories.tsx
- src/components/Base/BaseColumn/BaseColumn.stories.tsx
- src/components/Button/VRTButton.stories.tsx
- src/components/ComboBox/VRTComboBox.stories.tsx
- src/components/FormControl/FormControl.stories.tsx
- src/components/FormGroup/FormGroup.stories.tsx
- src/components/Heading/Heading.stories.tsx
- src/components/Icon/Icon.stories.tsx
- src/components/Input/Input.stories.tsx
- src/components/Pagination/Pagination.stories.tsx
- src/components/SpreadsheetTable/SpreadsheetTable.stories.tsx
- src/components/TabBar/TabBar.stories.tsx
- src/components/TextLink/TextLink.stories.tsx
- src/components/TextLink/VRTTextLink.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/smarthr-ui-preset.ts
smarthr-normalize-css がなくても機能する smarthr-ui を作りにいくための下準備です。
- smarthr-normalize-css で最低限必要な global css を Tailwind CSS の base layer として定義します
- Chroamtic で差分を洗い出すために smarthr-normalize-css を Story に当てている箇所を消します
- これは差分を洗い出し終わったら消します
> fix: smarthr-normalize-css への依存を剥がすための下準備

- .storybook/preview.tsx
- src/smarthr-ui-preset.ts
https://smarthr.atlassian.net/browse/SHRUI-876
AccordionPanel に差分がでていて気がついた。
button に UA style の `button { font-family: Arial; }` があたっていたため、`inherit` に変更。
input や textarea なども同様と考えられるため修正。
> fix: button と input, textarea, select の font-family を normalize

- src/smarthr-ui-preset.ts
radius が rem ベースだと、開発環境に依って `html: { font-size: 10px; }` などとしている環境で想定しない大きさになってしまうため修正。
> fix: 角丸のデザイントークンが rem ベースになっていたので修正

- src/components/Badge/Badge.stories.tsx
- src/components/Base/Base.stories.tsx
- src/components/Base/BaseColumn/BaseColumn.stories.tsx
- src/components/ComboBox/VRTComboBox.stories.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- src/components/FormControl/FormControl.stories.tsx
- src/components/Heading/Heading.stories.tsx
- src/components/Icon/Icon.stories.tsx
- src/components/Input/Input.stories.tsx
- src/components/NewFieldset/Fieldset.stories.tsx
- src/components/NotificationBar/NotificationBar.stories.tsx
- src/components/Pagination/Pagination.stories.tsx
- src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx
- src/components/SmartHRLogo/SmartHRLogo.stories.tsx
- src/components/SpreadsheetTable/SpreadsheetTable.stories.tsx
- src/components/StatusLabel/StatusLabel.stories.tsx
- src/components/TabBar/TabBar.stories.tsx
- src/components/TextLink/TextLink.stories.tsx
- src/components/TextLink/VRTTextLink.stories.tsx
- src/components/Textarea/Textarea.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/smarthr-ui-preset.ts
> fix: 順序なしリストと定義リストの余白を reset

- src/components/Dialog/ActionDialog/ActionDialog.tsx
- src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- src/components/Dialog/FormDialog/FormDialog.tsx
- src/components/Dialog/FormDialog/FormDialogContentInner.tsx
https://smarthr.atlassian.net/browse/SHRUI-872
任意のボタンなどを埋め込むことができます。
やや実験的な側面がありそうなので、裏メニュー的な取り扱いとして Story には追加していません。
手元の Story を修正するなどして動作確認していただけると嬉しいです。
> feat: Action / FormDialog のフッター左端に操作領域を追加

- src/components/CheckBox/CheckBox.tsx
- src/components/RadioButton/RadioButton.tsx
> fix: RadioButton, CheckBox の装飾用spanがスクリーンリーダーで読み上げられてしまう場合がある問題を修正

- src/components/AccordionPanel/AccordionPanelTrigger.tsx
右アイコンの AccordionPanel の開閉動作を見直しました。 
thx! @shinog
Before | After
--- | ---
> fix: AccodionPanel[iconPosition="right"] の開閉アイコン向きを調整

- src/components/Icon/WarningIcon.tsx
- src/smarthr-ui-preset.ts
WarningIcon を Fontawesome v6 対応しました。
> fix: WarningIcon を Fontawesome v6 に追従

- src/components/AccordionPanel/AccordionPanelTrigger.tsx
- src/components/Tooltip/Tooltip.tsx
- 他のアイテムを実装しているときに、classNameのtypoに気づいたので、typoを修正しようとしました。
- ですが、修正したらもともと正常に表示されていそうな部分が表示されなくなったりしたので、classNameごと削除する方針に切り替えました。
- 今のfocus周りの表示が正しい・正しくないの判断がつかなかったのでヘルプほしいです！（chromeとfirefoxで確認しましたが、目立った箇所はわからず...）
> chore: typoしているclassNameを削除する

- package.json
N/A
`pnpm e2e:dev` コマンドでエラーが発生することがある問題を修正する
- `--host` という存在しないオプションを指定していたので、`--hostname` に差し替える
- 開発用なので1回きりの実行よりも監視モードにしたほうが良いと思ったので `--live` オプションを付与する
`pnpm e2e:dev [filename]` で E2E テストをローカルで動かせることを確認。
> fix: 開発用E2Eテストコマンドのオプションを正しく指定する

- src/components/Header/Header.tsx
Hi I'm sorry, I'm new here!
Changed ElementProps type from `ComponentProps<'h1'>` to `ComponentProps<'header'>` since Header is rendered as a header element.
> fix: change `ElementProps` type

- src/components/ComboBox/VRTComboBox.stories.tsx
MultiComboBox の Chromatic の挙動が不安定だったので直しました。
MultiComboBox でアイテムが選択されたときのコールバック内では requestAnimationFrame が使用されていて、処理の実行がブラウザの次の描画タイミングまで遅延される実装になっています。 👉 https://github.com/kufu/smarthr-ui/blob/f25c4fc568bd507bec25b97a326b1600b87d996b/src/components/ComboBox/MultiComboBox.tsx#L237
storybook の play function 内ではこの遅延された処理の完了を待たずに後続の処理が走ってしまうので、ブラウザの表示が意図した状態になる前に chromatic のスナップショットが取られてしまう場合があり、ランダムに差分が発生してしまっていると思われます。
play function 内に、アイテムクリック後に 1 フレーム分待つ処理を入れました。
Chromatic で、すべてのキャプチャで option1 と option2 が正しく選択されている状態になっていることを確認してください 🙏
> fix: MultiComboBox の story でランダムに差分が出てしまう問題の解消

- src/components/Dialog/DialogContentInner.tsx
- src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
- src/components/Dialog/useDialogInnerStyle.ts
Dialog をスマホビューで表示した際に、ブラウザのアドレスバーによってボタンが隠れてしまっていたので、高さ指定で svh を使用するように変更した
Story で確認しています
ActionDialog
|before|after|
|:-:|:-:|
|![simulator_screenshot_01DF7664-DBA4-4420-9D0C-96A5976B6F07](https://github.com/kufu/smarthr-ui/assets/42249033/8cab0caf-81b5-4ac1-9cfe-665071db1fff)|![simulator_screenshot_34840D98-A121-44F1-872D-8CD046571B1D](https://github.com/kufu/smarthr-ui/assets/42249033/a4a43d4d-b831-4984-bf94-0dfe9a99e7c4)|
MessageDialog
|before|after|
|:-:|:-:|
|![simulator_screenshot_063C19D5-0CF5-4322-8622-7AEFDA6DB753](https://github.com/kufu/smarthr-ui/assets/42249033/1784d075-58f0-456c-8da7-49178b2f3020)|![simulator_screenshot_7E76C556-B741-4B7F-BA77-7C4062D325E7](https://github.com/kufu/smarthr-ui/assets/42249033/3787ead5-41b3-4d59-8d14-33c078717564)|
> fix: Dialog の maxHeight に svh を使用する

- src/components/AppNavi/AppNaviDropdown.tsx
AppNaviDrodpdown が current の場合に、ドロップダウンが開けない不具合を修正しました。
`isCurrentUnclickable` を消した影響ですが、ドロップダウンについては押せないと遷移できないリンクやボタンが発生するため `disabled` にはしません。
> fix: AppNaviDropdown が current の時に押せなくなる不具合を修正

- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.stories.tsx
- src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
基本的にアイコンのみの DropdownMenuButton の利用を減らしていたためアイコンを絞っていたが、視覚設計の一貫で必要になったため差し替えるための props `triggerIcon` を足しました。
> feat: DropdownMenuButton[onlyIconTrigger] は任意のアイコンに差し替えられるようにする

- src/components/Dialog/RemoteTriggerFormDialog/RemoteTriggerFormDialog.tsx
- 以前RemoteTriggerActionDialogで対応されたものがRemoteTriggerFormDialogに対しては修正が漏れていたため対応する
> fix: RemoteTriggerFormDialogのonPressEscapeにclose引数が渡されずとじることができないバグを修正する

- renovate.json
[提案スレ](https://kufuinc.slack.com/archives/CGC58MW01/p1712219406755239)
CIの実行回数を減らし、Storybookのsnapshot数を減らすのが目的。
minor, patchバージョンに関するPRの数を週に1度に限定して、手動でマージしていくことを想定している。
このPRで目指す状態
```
dependencies: 単体PR / 随時
devDependencies: 
1. majorは単体PR / 随時
2. minor || patch は おまとめ1PR/week
```
- renovate.jsonの更新
- renovate.jsonの更新
> chore: devDependenciesのnon-major updateを一つのグループにまとめる

- src/components/Header/AppLauncher/AppLauncher.tsx
`<AppLauncher>` 上で指定しているスタイルが、`<ButtonWrapper>` のスタイルを上書きできておらず、フォーカス時にボタンの背景色が変化せず、低いコントラスト比となっていた
`<AppLauncher>` 上のスタイルの詳細度を上げるように指定
Before
After
> fix: AppLauncherのスタイルが上書きされてない箇所の詳細度を修正

- src/components/Dropdown/SortDropdown/SortDropdown.tsx
- src/components/Dropdown/SortDropdown/useSortDropdown.ts
- src/components/Icon/Icon.tsx
- #4301 マージ時に最新に追従しなかったことによる不具合
- 削除したアイコンを読みにいきエラーが発生していた
- 不要な Section が挟まり、Heading がないと怒られていた
- 昇順・降順のアイコン向きが逆
> fix: lint エラーを修正

- src/components/Dialog/BodyScrollSuppressor.tsx
- src/components/Dialog/DialogContentInner.tsx
> fix: Revert "BodyScrollSuppressorをstyled-componentsに依存しない形で実装"

- src/components/Calendar/Calendar.tsx
**SmartHR UI　DatePicker「all」　カレンダーが展開されていることがわからない　NVDA、PC-Talker　VoiceOver**
https://app.asana.com/0/1205448161364688/1206305498133149/f
Calendarは `box-shadow` によってコンポーネントの内部と外部に視覚的な境界を作っていますが、CSS Color Adjustment Module Level 1によると、強制カラーモード下では `none`に上書きされると定義されています。
> `box-shadow` and `text-shadow` compute to `none`
> [3.1. Properties Affected by Forced Colors Mode - CSS Color Adjustment Module Level 1](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties)
また、Windowsのハイコントラストモードでも同様の振る舞いをします。
> To take a common example, `box-shadow` is a versatile property which web developers can use to achieve various different glow and nested border effects. However, this property is reverted in forced color modes.
> [Styling for Windows high contrast with new standards for forced …
> fix: forced-colors: active時のCalendarの表示を改善

- src/components/DatePicker/VRTDatePicker.stories.tsx
N/A
- https://github.com/kufu/smarthr-ui/pull/4563
の VRT 差分を確認した際に、`DatePicker` の VRT 結果スクリーンショットにカレンダーUIが表示されていなくて困ったのを解消する
スクリーンショットにカレンダーUIが収まるようにサイズを明示する
VRT 結果参照
https://www.chromatic.com/build?appId=63d0ccabb5d2dd29825524ab&number=7293
> fix: VRT にてスクリーンショットに要素が収まりきっていないストーリーを修正

- src/components/Button/Button.tsx
- src/components/Loader/Loader.tsx
**SmartHR UI　「Button」With Loading　読み込み中と読み上げない　NVDA**
https://app.asana.com/0/1205448161364688/1206247075014349/f
WAI-ARIAのLive Regionは、ある要素の**コンテンツ**に変更があった際にその変更をユーザーエージェントに通知する機能ですが、コンテンツではなく**要素自体**が動的に追加または削除されたとき、どのように振る舞うべきかは仕様中で言及されていないようです。
したがって、`role="status"`のような属性値を持った要素（今回の場合では `Loader`）が動的に追加されると、ユーザーエージェントの組み合わせによってはこの変更を検出できず、無視してしまいます。最初からLive Regionをもった要素を挿入しておいて、あとからその子要素を変更する、というほうが想定されている使い方のようです。
> The aria-live attribute provides a way for developers to announce such changes to AT based on event triggers set by the developer rather than by user initiated actions so they are made aware that **the content** has changed.
> [aria-live - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live#description)
> What I have …
> fix: Buttonのロード時のlive regionを読み上げるよう修正

- src/components/FormControl/FormControl.stories.tsx
- src/components/FormControl/FormControl.tsx
N/A
`FormGroup` や `Fieldset` では提供されている `dangerouslyTitleHidden` オプションを `FormControl` でも使えるようにします。
`FormControl` で入力要素の項目ラベルを非表示にするなんて言語道断という背景は理解しているつもりですが、実際に既存画面に対して `FormControl` を用いたアクセシビリティの底上げを狙うと、どうしても「FormControl 使うと可視ラベルが冗長に表示されちゃうから、このケースでは使えないなぁ」という判断になるケースがあります。
既存画面の構成上、可視ラベルは他のもので代用できているけど、アクセシブルネームや `helpMessage` `errorMessages` などの仕組みには乗っかりたいという場面のために、`dangerouslyTitleHidden` を使えるようにしました。
> feat: FormControl でも dangerouslyTitleHidden オプションを許容する

- src/components/Base/Base.stories.tsx
- src/components/Base/Base.tsx
- src/components/Base/BaseColumn/BaseColumn.stories.tsx
- Base, BaseColumnもas, forwardedAsでSectioningContentを指定した場合、見出しレベル自動計算を行うように修正します。
> feat: Base,BaseColumnのas属性にsection,aside,article,navを設定した場合、SectioningContent同様に見出しレベル自動計算を行うように修正

- src/components/Icon/Icon.tsx
https://smarthr.atlassian.net/browse/SHRUI-950
#4481 で消えてしまったがFigmaにはあるアイコンを復活させる
- FigmaのIcon群と実装にあるIcon群の集合の差分をとる
- [Slackに差分の一覧](https://kufuinc.slack.com/archives/CDG1XRPTP/p1713513309888609?thread_ts=1713510005.526079&cid=CDG1XRPTP)があります
- 差分のうち、Figmaにはあるが実装にないものを追加
量が多いので[Storybook](https://63d0ccabb5d2dd29825524ab-xdaqjuvfef.chromatic.com/?path=/docs/media%EF%BC%88%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%EF%BC%89-icon--docs)で見てください！
観点: 
- エラーなくすべて表示されているか
- [足すべきアイコン](https://kufuinc.slack.com/archives/CDG1XRPTP/p1713513309888609?thread_ts=1713510005.526079&cid=CDG1XRPTP)がすべて足されているか
> fix(Icon): Figmaにのみ存在するアイコンを復活

- src/components/Table/BulkActionRow.tsx
> fix: Tableの一括操作領域のborderがスクロール時にちらついてしまう場合があるためstyleを調整する

- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/FormDialog/FormDialog.tsx
- src/components/Dialog/FormDialog/FormDialogContent.tsx
- src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- react-hook-formなど、FormEventを受け取りたいモジュールが存在するため、onSubmit経由でFormEventを引き渡せるように修正します
> feat: FormDialogのonSubmitの第二引数にFormEventを渡すように修正

- src/components/CompactInformationPanel/CompactInformationPanel.stories.tsx
- src/components/CompactInformationPanel/CompactInformationPanel.tsx
`NotificationBar[base="base"]`で代替可能になったので、`CompactInformationPanel`を非推奨にします。
`CompactInformationPanel`をdeprecatedにしました。
> fix: CompactInformationPanelをdeprecatedにする

- .circleci/config.yml
- [monorepo build fails due to storybookBaseDir check in v11.3.1 · Issue #975 · chromaui/chromatic-cli](https://github.com/chromaui/chromatic-cli/issues/975)
- [Chromatic + TurboSnap cannot find the base directory · Issue #971 · chromaui/chromatic-cli](https://github.com/chromaui/chromatic-cli/issues/971)
モノレポ構成だと、storybookのbase directoryを設定する必要が出てきたので設定
[CLI • Chromatic docs](https://www.chromatic.com/docs/cli/#configuration-options)
> chore: set storybook-base-dir for Chromatic

- packages/smarthr-ui/src/components/DropZone/DropZone.stories.tsx
[用字用語：一覧 | 用字用語 | SmartHR Design System](https://smarthr.design/products/contents/idiomatic-usage/data/#%E3%81%9F%E8%A1%8C)
デザインシステムのライティングガイドラインとしては、「ドラッグ＆ドロップ」ではなく「ドラッグアンドドロップ」が推奨されているので、その形に合わせたい。
該当の文言を修正した。
> fix: DropZoneのstoryの文言をデザインシステムに準拠した内容に変更

- packages/smarthr-ui/src/components/Textarea/Textarea.stories.tsx
- packages/smarthr-ui/src/components/Textarea/Textarea.tsx
- TextareaにmaxLengthを設定しても、実際に出力されるhtmlにはmaxLength属性は設定されない
- maxLengthは実質あと何文字入力できるか表示するためだけの属性になっている
- そもそもsmarthrとしてmaxLength属性は非推奨にしているため、 `maxLength` を `maxLetters` に変更して利用者のメンタルモデルと合わせたい
> fix!: TextareaコンポーネントのmaxLength属性をmaxLetters属性に変更

- packages/smarthr-ui/src/components/Table/TdCheckbox.tsx
- packages/smarthr-ui/src/components/Table/ThCheckbox.tsx
`<Table>` 中のチェックボックスの位置がずれてたので直した
`<Checkbox>` の `display` を `block` に
> fix: `<Table>` 中のチェックボックスの位置を調整

- packages/smarthr-ui/src/components/DefinitionList/DefinitionList.stories.tsx
- packages/smarthr-ui/src/components/DefinitionList/DefinitionListItem.tsx
- tailwind 移行時の不具合がありました
- `min-h-` に `shr-` prefix が付いておらず、値が効いていませんでした
- 1文字分である `calc(1em * leading.NORMAL)`  となるように修正しました
- 再発しないよう Story を追加しました
リリースを待たずに修正したい場合は、`.smarthr-ui-DefinitionListItem-description` というクラスに対して `min-height: calc(1em * leading.NORMAL)` と同等のスタイルを充ててください。
> fix: DefinitionListItem が空の場合に高さが潰れる欠陥を修正

- packages/smarthr-ui/src/components/NotificationBar/NotificationBar.stories.tsx
- packages/smarthr-ui/src/components/NotificationBar/NotificationBar.tsx
読込中を NotificationBar で使いたいプロダクトが発生したため、`type=sync` を追加しました（InformationPanel と揃いました）。
読み込みが終われば消える想定で `role=state` が付与される実装にしました。
> feat: NotificationBar に読込中状態を追加

- packages/smarthr-ui/src/components/Dialog/Dialog.stories.tsx
- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- packages/smarthr-ui/src/components/Dialog/useDialogInnerStyle.ts
https://smarthr.atlassian.net/browse/SHRUI-937
- UI デザイン上はダイアログコンテンツ領域は天地左右1.5文字分の padding を設けていましたが、コンポーネントに反映されておらず各開発者が実装していたため統一しました
- おそらく全プロダクトが対応をしないといけなくなりますが、機械的な修正で済むので「今が一番早い」と判断します
- ダイアログコンテンツ内の table を幅いっぱいにしたい場合は、内包要素に何らかの方法で negative margin を与えるのが良いと考えます
- 背景色を与えたい場合にも上記の negative margin を余計に指定する必要があるため、Dialog 系コンポーネントに対して contentPadding や contentBgColor といった props を生やす検討を別途行います（本 PR では行いません）
> fix: すべてのダイアログコンテンツの padding を統一

- packages/smarthr-ui/src/components/Fieldset/Fieldset.stories.tsx
- packages/smarthr-ui/src/components/Heading/Heading.tsx
- packages/smarthr-ui/src/components/Text/Text.tsx
FormControl や Fieldset のラベルに line-height の指定がなく、継承された line-height があたっていたので修正。
Heading と同等のスタイルでは必ず `leading=TIGHT` となるとして修正した。
もし `leading=TIGHT` 以外を使いたい場合は、別途上書きすればよい。
例
```
<Text styleType="blockTitle" leading="NONE" />
```
`Text[styleType]` を利用しているところでは、別途 `leding="TIGHT"` を指定していない限り視覚差分が必ず出るため、周知すること。
> fix: Text[styleType] の時 Heading と同等とみなし leading="TIGHT" があたるように修正

- packages/smarthr-ui/src/components/DefinitionList/DefinitionList.stories.tsx
- https://github.com/kufu/smarthr-design-system/pull/1157 を見てて気になったので
DefinitionListのStory内の、値がない項目の表示を基準に合わせて修正
参考: https://smarthr.design/products/design-patterns/empty-data/
- DefinitionListのStory内の、値がない項目の表示を基準に合わせて `TEXT_DISABLED` で `-` を表示するように修正
- `-`だけだとスクリーンリーダーでの読み上げで問題があるのでVisuallyHiddenTextで対応
| Before | After |
| :-- | :-- |
| <img width="263" alt="image" src="https://github.com/kufu/smarthr-ui/assets/8467289/a18b498f-5985-44f4-9891-88c5352428e9"> |  <img width="222" alt="image" src="https://github.com/kufu/smarthr-ui/assets/8467289/7fda35b2-814a-4204-9b8c-f8c92fc536da"> |
> docs(DefinitionList): 値がない項目の表示のStoryを基準にあわせて修正

- packages/smarthr-ui/src/components/CheckBox/CheckBox.stories.tsx
- packages/smarthr-ui/src/components/CheckBox/CheckBox.tsx
https://smarthr.atlassian.net/browse/SHRUI-968
Checkbox が mixed かつ error の時、checkbox が mixed とならな不具合を修正。コンポーネントの実装に問題はなく、Story で checked が付いていないだけでした。
> chore: Checkbox[mixed error] の時 mxied とならない Story の不具合を修正

- packages/smarthr-ui/e2e/components/ComboBox/MultiComboBox.test.ts
- packages/smarthr-ui/e2e/components/ComboBox/SingleComboBox.test.ts
- packages/smarthr-ui/src/components/ComboBox/MultiCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/SingleCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/VRTMultiCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/VRTSingleCombobox.stories.tsx
デザインシステムサイトから参照する際に Combobox としてまとめて表示ではなく、それぞれ別コンポーネントとして表示したいため、Story を分解しました。
SingleCombobox  / MultiCombobox は同カテゴリだが別コンポーネントのため妥当だと考えます。
純粋にファイルを分解しただけで、中の処理には一切手を加えていません。
> docs: Comobobox の Story を分解

- packages/smarthr-ui/src/components/Button/Button.tsx
- packages/smarthr-ui/src/components/Loader/Loader.tsx
強制カラーモードの際、`<Loader>` のアニメーションが機能していなかったため、修正
- `<Loader>` に `forced-color-adjust: none` を設定し、transparentを有効に
- border-colorに system-color の `ButtonBorder` を付与し色を背景に依存しない色に
On emulate `forced-colors: active` and `prefers-colors-scheme: dark`
`<Loader>`
`<Button>`
`<Loader>`
`<Button>`
> feat: Loaderを強制カラーモードに対応

- packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
- https://smarthr.atlassian.net/browse/SHRUI-951
MultiComboboxで高さがガタつくのを修正
- `vertical-align: bottom` を追加
[StorybookのMultiCombobox](https://63d0ccabb5d2dd29825524ab-fhnwavzcgm.chromatic.com/?path=/story/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-multicombobox--multi-combobox)で、
- 未選択 → フォーカス
- 項目を選択済み → 削除
の2つを試し、高さがガタつかないことを確認してください。
レビュー担当の方へ: [FilterDropDownのVRTの差分](https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=664e85cc5451081b8a5d9633)が意図とあっているか (おそらく以前のものが崩れているのだとは思うが) 確認お願いしたいです！
> fix(MultiCombobox): 高さのガタツキを修正

- packages/smarthr-ui/src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx
- RadioButtonPanelのstoryのlist-styleを修正しました
- shr-list-noneを追加
| Before | After |
| --- | --- |
| ![image](https://github.com/kufu/smarthr-ui/assets/16136015/bc2a58a1-5c80-4bc0-9673-46054d3c73dd) | ![image](https://github.com/kufu/smarthr-ui/assets/16136015/fa11b32d-823a-423d-ae3c-758261738a89) |
> fix: RadioButtonPanel.storiesのlist-styleを修正

- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialog.tsx
- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContent.tsx
- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/Dialog.stories.tsx
- packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialog.tsx
- packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContent.tsx
- packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialog.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialogContent.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- packages/smarthr-ui/src/components/Dialog/useDialogInnerStyle.ts
https://smarthr.atlassian.net/browse/SHRUI-866
#4644 でダイアログコンテンツの padding を統一したが、背景色を敷きたい場合などに実装側でスタイリングを別途あてないと使えない状態だったため、`contentBgColor` と `contentPadding` を生やしました。
利用側が negative margin などを駆使しなくてもスタイリングできるようになります。
「Reg Opened Hoge」な Story で確認できるように Story を修正しました。
既存の構成に追記したため、同一の記述が3箇所に分かれてしまい煩雑化しましたが、リファクタリングは別途行ったほうが良いと考えたため行っていません。
> feat: ダイアログコンテンツに背景色とパディングを設定できるようにする

- packages/smarthr-ui/src/components/RadioButton/RadioButton.tsx
- packages/smarthr-ui/src/components/Select/Select.tsx
- packages/smarthr-ui/src/libs/ua.ts
- タイトルの通り、iOS系端末のブラウザ(safari, chrome, アプリ内ブラウザで確認)において、select, radioにrequired属性が設定されていると、submitの阻害は行われるがユーザーフィードバックがない、という状態になる問題を解決したい
- そのため、iOS系端末の場合、required属性を設定しないように修正します
- これによりフロントのvalidate自体が行われなくなりますが、そもそもhtml validate単体での実装は、実用上存在しないはずなのでこのような対応にしています
- 歴史的経緯により、required属性を正しく認識出来ないブラウザが存在する、そもそもhtmlでの記述なのでユーザーが突破しようと思えば突破できてしまうなど、単独での実装はそもそも問題が有るため
> fix: iOS系端末の場合、Select, Radio系入力要素にrequired属性を設定しないように変更

- packages/smarthr-ui/src/components/Base/BaseColumn/BaseColumn.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- packages/smarthr-ui/src/components/Dialog/useDialogInnerStyle.ts
- WCAG AA 1.4.11 の試験で発覚しました
- フォーカスインジケーターに `OUTLINE` の色を使っていますが、GREY_30 以上の濃さのグレースケールではコントラスト比 3:1 を担保できません
- プロダクトを作る中で GREY_30 以上の背景を使う可能性はないため、bgColor 関連の props からも消します
参考： [コントラストグリッド](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=%23ffffff%2C%20WHITE%0D%0A%23f8f7f6%2C%20GREY_5%2C%20BACKGROUND%2C%20COLUMN%0D%0A%23f5f4f3%2C%20GREY_6%0D%0A%23f2f1f0%2C%20GREY_7%2C%20OVER_BACKGROUND%0D%0A%23edebe8%2C%20GREY_9%2C%20HEAD%0D%0A%23d6d3d0%2C%20GREY_20%2C%20BORDER%0D%0A%23c1bdb7%2C%20GREY_30%0D%0A%23706d65%2C%20GREY_65%0D%0A%2323221e%2C%20GREY_100&foreground-colors=%230077c7%2C%20OUTLINE&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18)
> fix: 背景色として使う可能性のない色を bgColor 関連 props から消す

- packages/smarthr-ui/.storybook/preview.tsx
N/A
Chromatic の VRT にて、強制カラーモードを意図した Story でだけ有効化したいのに、ランダムに有効になったり無効になったりする事象があって解決したい。
根本原因は全然わかってないけど、とりあえずデフォルト設定を `none` に明示的に設定するのを試したい。
> chore: 強制カラーモード用のデフォルトのパラメータを設定する

- packages/smarthr-ui/src/components/Button/AnchorButton.tsx
- packages/smarthr-ui/src/components/TextLink/TextLink.stories.tsx
- packages/smarthr-ui/src/components/TextLink/TextLink.tsx
- anchorのrel属性はセキュリティに係るものであるため、可能な限り安全にしたい
- target=_blankの場合、自動でrel属性にnoopener, noreffererを設定する
- 明示的にrel属性が設定されている場合はそちらを優先する
> feat: anchor系コンポーネントがtarget属性を持つ場合、rel属性を自動設定する

- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx
- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
- packages/smarthr-ui/src/components/Heading/Heading.tsx
- packages/smarthr-ui/src/components/Heading/index.ts
- packages/smarthr-ui/src/components/Text/Text.tsx
- packages/smarthr-ui/src/components/Text/index.ts
🍐 
SmartHR UI を React Server Component で使用する際、ほぼ多くのコンポーネントが Server Component では使用できない現状になっている。
その原因の一つとして、ほとんどのコンポーネントが内部で使っている Text コンポーネントが Server Component で使えない実装になっているということがある。
ただ、Text の実装を見ると Server Component で使えない要因がなく、実際は Text が内部で変数を参照している Heading で context を使用していることが要因。
なので Text を Heading に依存させないようにしたい。
ついでに Text と Heading の実装をよく見ると、相互参照状態になっていて良くないので、それも一緒に解消したい。
Heading 内にある Text をスタイルを変更するための変数を Text 側に持たせるようにした。
これで Heading と Text の相互参照状態がなくなり、Heading が Text に依存するだけの状態になった。
また、Text が Server Component で使用できるようになった。はず。
🍐
> fix: Heading と Text の相互参照をなくして Text が Heading に依存しないようにする

- packages/smarthr-ui/src/components/ComboBox/VRTMultiCombobox.stories.tsx
N/A
MultiCombobox の VRT で発生する、以下のようなフレーキーな結果が生じないようにする
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=666b8d48fab7ae85ed175fce
Play 関数にてコンボボックスを操作した直後で、カーソルが点滅状態になっているため、撮影されるスクリーンショットにブレが生じてしまっていた。
操作後にテキストボックスからフォーカスを外すことでこれを修正する。
> chore: MultiCombobox の VRT はフレーキーな問題を修正する

- packages/smarthr-ui/src/components/Dropdown/Dropdown.tsx
- packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
- packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
N/A
Dropdown 及び FilterDropdown に onOpen/onClose オプションを追加し、ドロップダウンコンテンツの開閉をプロダクト側でフックできるようにします。
一度以下で提案した後、「あったら嬉しいけど無くてもよい」と結論付けて見送りましたが、やはりプロダクト側でドロップダウンコンテンツの開閉をフックに非同期処理を呼び出したいユースケースがあったため対応したいです。
https://kufuinc.slack.com/archives/C06KVP5PL23/p1711607266418609
調べてみると他のプロダクトでも潜在需要があるっぽい？
https://kufuinc.slack.com/archives/C05TN64KD1V/p1717059738348349
- `Dropdown` に `onOpen` / `onClose` オプションを追加
- `FilterDropdown` に `onOpen` / `onClose`  オプションを追加
- ドロップダウンコンテンツの開閉状態が変化するたびに `onOpen` / `onClose`  を発火する
> feat: Dropdown 及び FilterDropdown に onOpen/onClose オプションを追加する

- packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
> fix: aria-disabled なボタンの強制カラーモード時の色を指定

- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanel.tsx
https://github.com/kufu/smarthr-design-system/pull/1220
AccordionPanel のガイドライン追記による見直しで、expandableMultiply の初期値を true に変える。
> fix: AccordionPanel がデフォルトで複数パネル開く設定に変更

- packages/smarthr-ui/src/components/FormControl/FormControl.stories.tsx
- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
`Fieldset > (FormControl > Input) + (FormControl > Input)` の時、Fieldset に errorMessage を指定すると1つめの Input が予期せず error 表現の赤枠になってしまう不具合を修正。
`FormControl > Input` など、多くの場合では error を自前で設定する必要はないため良いデフォルト挙動だが、意図的に opt-out できるように `autoBindErrorInput` を追加した。`false` を渡すと無効にできる。
> feat: FormControl / Fieldset 内における入力要素の error 状態紐づけ制御用 props を足す

- packages/smarthr-ui/src/components/TextLink/TextLink.tsx
> fix: TextLink に color を指定できないように閉じる

- .gitignore
https://github.com/kufu/smarthr-ui/pull/3845
`.idea` ファイルと同様に、 `.vscode` もgit管理しないようにしたいです
> chore: .vscodeのディレクトリ配下をgit管理しない

- packages/smarthr-ui/src/components/Table/Table.stories.tsx
- packages/smarthr-ui/src/components/Table/Table.tsx
- packages/smarthr-ui/src/components/Table/Td.tsx
- packages/smarthr-ui/src/components/Table/Th.tsx
- packages/smarthr-ui/src/components/Table/type.ts
悪いクセで複数のチケットを混ぜました:pray:（コミットは分けたし、大きくはないので大丈夫だと判断）
- https://smarthr.atlassian.net/browse/SHRUI-993
- https://smarthr.atlassian.net/browse/SHRUI-963
- table-layout 相当の layout props を Table に追加
- Th / Td に contentWidth を追加
- number / string で指定できます
- number はフォントサイズの何文字分かで指定
- string は任意の文字列
- Th / Td に align を追加
- Story を整理
> feat: Table に table-layout 相当の props を追加 ほか

- packages/smarthr-ui/src/components/Icon/Icon.tsx
- なし
- Icon に FaTableColumns を追加したいです
- https://react-icons.github.io/react-icons/search/#q=FaTableColumns
- https://fontawesome.com/icons/table-columns?f=classic&s=solid
- FaTableColumns を追加
> feat: Icon に FaTableColumns を 追加

- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelContent.tsx
N/A
AccordionPanel を開いた際に、確定で以下のエラーがコンソール上に発生する (開発環境のみ)
> Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference.
これは [react-transition-group](https://github.com/reactjs/react-transition-group) の `<Transition>` コンポーネントにて `React.findDOMNode` を使用しているが、これは既に非推奨な関数で、次期バージョン (React 19) では廃止されるため、それを警告するメッセージが表示されている。
長期的には React 19 でも AccordionPanel を使用できるようにするため、短期的には余計なコンソールエラーを表示させないためにこの問題を解消したい。
以下 Issue を参考にすると、Transition コンポーネントは、トランジション対象の要素を取得するために `React.findDOMNode` を使用しているが、対象要素を `nodeRef` props で渡してあげることで、これの実行を回避することができる模様。
- https://github.com/reactjs/react-transition-group/issues/904
なので、現行では `React.findDOMNode` で取得される要素の ref を渡してあげることで、挙動を変えずにこの問題を修正する。
Storybook で AccordionPanel …
> fix: AccordionPanel 開閉時にコンソールエラーが発生する問題を修正

- packages/smarthr-ui/src/components/Table/Th.tsx
タイトルの通り
https://github.com/kufu/smarthr-ui/assets/40714517/7f361ae4-1091-48d3-8554-91563ab0811f
https://github.com/kufu/smarthr-ui/assets/40714517/54b72a14-7ac6-4120-ba88-11114347e0c9
> fix: ソートできる場合はクリッカブルなので Th に `cursor: pointer` を当てた

- packages/smarthr-ui/src/components/Button/Button.tsx
- packages/smarthr-ui/src/components/Loader/Loader.stories.tsx
- packages/smarthr-ui/src/components/Loader/Loader.tsx
- packages/smarthr-ui/src/smarthr-ui-preset.ts
[チケット](https://smarthr.atlassian.net/jira/software/projects/SHRUI/boards/99/backlog?selectedIssue=SHRUI-960)
- レスポンスが早い際にLoaderのちらつきが発生してしまう。それを抑制するために200ms経過後に表示するように変更する。
- 現状は各個別のプロダクトで対応している状況だが、SmartHR UIに変更を入れることで統一の仕様とする。
- props関係なく常に 200ms 固定で animation-delay する
https://github.com/kufu/smarthr-ui/assets/25091548/43f1ab11-654a-41ea-ad20-8276ad852962
> feat: Loaderを200ms経過後に表示する

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- [react-grid-layout/react-draggable: React draggable component](https://github.com/react-grid-layout/react-draggable?tab=readme-ov-file#draggable-props)
- ModelessDialogコンポーネントをマウントすると `findDOMNode` が非推奨である旨の警告が表示されました
- 内容は https://github.com/kufu/smarthr-ui/pull/4777 で起きていたものと同じです
- 原因はModelessDialogが依存している [react-draggable](https://github.com/react-grid-layout/react-draggable) の `Draggable` コンポーネントがDOMの直接操作を行なっていることでした
- READMEにも警告が発出される可能性について記載されていました
- > If running in React Strict mode, ReactDOM.findDOMNode() is deprecated. Unfortunately, in order for <Draggable> to work properly, we need raw access to the underlying DOM node. If you want to avoid the warning, pass a `nodeRef` ... (略) 
- 上記の記載に従い `Draggable` コンポーネントの操作対象となる要素の `ref` を渡して対処しています
- 元々あった `wrapperRef` …
> fix: ModelessDialogマウント時の警告を消したい

- packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
- packages/smarthr-ui/src/components/Tooltip/TooltipPortal.tsx
- Tooltipのアクセシビリティ問題を解決します
- 現状のtooltipはhoverしない限りmessageがhtml上に存在せず、triggerとなる要素もインタラクティブなものではないため、存在が理解出来ない場合がある状態でした
- 最低限、tooltipと理解できなくてもテキストを常に存在する状態にすることでtooltipと理解できなくても良い状態にします
> fix: Tooltipのmessageを常にhtml上に存在するように修正する

- packages/smarthr-ui/src/components/CompactInformationPanel/VRTCompactInformationPanel.stories.tsx
N/A
Storybook にて、CompactInformationPanel の Storybook が重複して表示されているのを修正する
対象コンポーネントを非推奨化した際に、通常の Story 側のタイトルをリネーム (`(非推奨)` を追加) したのに、VRT用の Story のリネームが漏れていたようなので、タイトルを揃える。
> chore: CompactInformationPanel の Storybook が重複表示される問題を修正

- packages/smarthr-ui/src/components/TabBar/TabItem.tsx
https://github.com/kufu/smarthr-ui/pull/4793#pullrequestreview-2200646627
上記 URI の指摘を修正。
> fix: TabBar 内の Tooltip 縦位置を自動調整に変更

- packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.stories.tsx
- packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
- packages/smarthr-ui/src/components/Input/SearchInput/VRTSearchInput.stories.tsx
revert 対象のPR
- https://github.com/kufu/smarthr-ui/pull/4635
`SearchInput` コンポーネントには、検索キーワードを削除するための `onClickClear` オプションが存在したが、削除ボタンの必要性や挙動の不十分さから、機能を削除することとした。
調べられる限りではこの機能は利用されていなかったので影響は限りなくありません。
元PRのスカッシュマージコミット(48be8b414a97dfd0d917ac6ace05a6f58d46af36)をリバート
> feat!: SearchInput コンポーネントから onClickClear オプションを削除

- packages/smarthr-ui/src/components/Button/Button.test.tsx
- packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
[報告スレッド(社内)](https://app.slack.com/client/T02FXTZ7A)
[調査スレッド(社内)](https://kufuinc.slack.com/archives/C06KVP5PL23/p1723010431280679)
以下PRの修正にて、Button コンポーネントに loading (あるいは disabled) を付与した場合、ボタンはネイティブの disabled 状態にはせずに、onClick イベントを破棄をすることで挙動を維持するようにした。
- https://github.com/kufu/smarthr-ui/pull/4684
しかし、以下のように form でラップして onSubmit を受け取るようにすると、 loading (あるいは disabled) 属性を付与しても、ボタンクリックによって submit イベントが発火してしまう問題が見つかったので、これを解決する。
```tsx
<form onSubmit={() => alert('submit')}>
<Button type="submit" loading>Loading...</Button>
</form>
```
Button コンポーネントへの onClick ハンドラを undefined で上書きすることで握りつぶす対応をしていたが、これだとイベントのバブリングが発生し、親要素 (たいていは form) にイベントが伝搬してしまっていた。
そこで、undefined で上書きするのではなく、ハンドラを定義の上、preventDefault / stopPropagation だけすることでイベントの伝播をブロックした。
> fix: Button コンポーネントが disabled/loading の場合も onClick イベントがバブリングしてしまう問題を修正

- packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
表示されていない Tooltip メッセージも DOM 上に表示されていたので、Tooltip が表示される時に絞りました。
> fix: Tooltip メッセージが機械側に過足提供していたので修正

- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
https://smarthr.atlassian.net/browse/SHRUI-928
FormControl に渡しても機能していなかった `disabled` props を消しました。
disabled にしたい場合は、FormControl ではなく内包する Input 系の要素やコンポーネントに `disabeld` を渡してください。
> fix!: FormControl から disabled を消す

- packages/smarthr-ui/src/components/TimePicker/TimePicker.stories.tsx
- packages/smarthr-ui/src/components/TimePicker/TimePicker.tsx
- N/A
- `TimePicker` コンポーネントに `Input` 等と同様のエラー時・読み取り専用時といった状態に応じたスタイリングをしたいです
- props型を拡張し、スタイルをvariant化しました
下の3つが今回追加したものです
> feat: TimePickerに様々な状態に応じたスタイルをあてたい

- packages/smarthr-ui/src/components/TabBar/TabItem.tsx
- packages/smarthr-ui/src/components/TabBar/__snapshots__/TabBar.test.tsx.snap
https://kufuinc.slack.com/archives/CDG1XRPTP/p1724204204068229?thread_ts=1723185002.816649&cid=CDG1XRPTP
suffixにテキストのスタイルが継承されないように修正
- TabItemのラベル部分の装飾をテキストのみに適用されるように修正
- spanで囲った
- Badgeの太字がregularになっていることをVRTで確認してapproveしてください
> fix(TabBar): suffixにテキストのスタイルが継承されないように修正

- package.json
- pnpm-lock.yaml
脆弱性が含まれていたパッケージの Issue
https://github.com/micromatch/micromatch/issues/264
使用している `micromatch` のバージョンに脆弱性が含まれることから `pnpm audit --prod` をパスできずにCIが通らない状態が続いている。
`micromatch` 自体は修正バージョンがリリースされたが、それを利用している依存パッケージ側にまで浸透するにはもう少し時間がかかりそうなので、取り急ぎバージョンの override によって解決を図る。 
`pnpm audit --prod --fix` による自動修正の適用
> chore: micromatch は脆弱性に対応したバージョンを使用する

- packages/smarthr-ui/src/components/TextLink/TextLink.tsx
- packages/smarthr-ui/src/components/UpwardLink/UpwardLink.tsx
- sandbox/next/src/app/about/page.tsx
- sandbox/next/src/app/page.tsx
https://smarthr.atlassian.net/browse/SHRUI-1018
`UpwardLink` をSPA対応するために、内部で使われている `TextLink`コンポーネントに`elementAs`プロパティを追加しました。この`elementAs`プロパティに要素を指定した場合、指定された要素に固有の`props`が自動的に引き継がれるようになります。
- `TextLink`コンポーネントにジェネリック型`T`を導入しました。
- この変更は、既存の`TextLink`コンポーネントの使用方法に影響を与えません。
- `elementAs`と定義したのはnext/linkが[`as`](https://github.com/vercel/next.js/blob/d588515c62b5058ff36df66308a2242dab6229b8/packages/next/src/client/link.tsx#L45)というpropsを持っていたので被りが発生しないようにしています。
next/linkを利用した場合
```tsx
import Link from 'next/link'
import { TextLink, UpwardLink } from 'smarthr-ui'
<TextLink elementAs={Link} href="/about" suffix={<FaArrowRightIcon />}>
smarthr-ui with next/link
</TextLink>
<UpwardLink elementAs={Link} href="/" indent={false}>
前へ戻る
</UpwardLink>
```
nextのSandbox環境での例
TextLinkのStyleを適用しつつ …
> feat: TextLinkをnext/linkなどのラップされたコンポーネントに対応

- packages/smarthr-ui/src/components/AppNavi/AppNavi.stories.tsx
- packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
- packages/smarthr-ui/src/components/AppNavi/AppNaviDropdown.tsx
- packages/smarthr-ui/src/components/AppNavi/AppNaviDropdownMenuButton.tsx
- packages/smarthr-ui/src/components/AppNavi/VRTAppNavi.stories.tsx
- packages/smarthr-ui/src/components/AppNavi/index.ts
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- packages/smarthr-ui/src/index.ts
- https://smarthr.atlassian.net/browse/SHRUI-949
- https://smarthr.atlassian.net/browse/SHRUI-917
AppNavi の buttons を deprecated に変え、Composite な作りに設計しなおしました。
また、ドロップダウンメニュー内の現在ページ（`aria-current="page"`）も表現できるように修正しました。
buttons を非推奨にしたため、各 AppNaviHoge コンポーネントを export しています。
また、AppNaviDropdown は上記課題に対応するため AppNaviDropdownMenu として作り直しています。
> feat: AppNavi を再設計

- renovate.json
関連JIRA
https://smarthr.atlassian.net/browse/SHRUI-1015
関連PR
https://github.com/kufu/smarthr-ui/pull/4878
関連スレ(社内)
https://kufuinc.slack.com/archives/CGC58MW01/p1724288220410419
本リポジトリでは、CircleCI で単体テストなどを動かしており、その際に使用する Node のバージョンとして、LTS バージョンと maintenance バージョンを指定して回している。
しかし、関連PRの通り、renovate がすべてひっくるめて最新版にバージョンアップしようとするため、うっかりマージしてしまって意図に反したバージョンでテストが実行されることが複数回あった。
CI で使用する Node のバージョンを正確に調整する必要性も無さそうなので、renovate 自体を無効化することにした。
renovate の設定ファイルを更新し、`cimg/node` はバージョンアップの対象外とする
> chore: Node のバージョンアップは renovate では行わないようにする

- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/useKeyboardNavigation.ts
[Slack](https://kufuinc.slack.com/archives/CGC58MW01/p1725857465544679?thread_ts=1725852045.876039&cid=CGC58MW01)
- DropdownMenuButton内のメニューにて、上下・左右キーでメニューアイテムのフォーカスを切り替えられるように変更
- バグとなっていたdisabledな要素をスキップするようにしました。
- 原因：disabledな要素と判断するロジックが不十分だったため、aria-disabledの値を確認するように変更。
- 過去はこれで機能していたが、変更したテストコードやコンポーネントの変更影響を受けていそう
- キーボード操作に関する処理をhooksとして切り出しました。(useKeyboardNavigation.ts)
- キーボード操作に関する処理の共通化したり、関数を作成したりすることで可読性をあげられるようリファクタリングしました。
- Storybookで動作確認した内容を記載します。
https://github.com/user-attachments/assets/0761c379-75b6-44d1-b80f-eafa084dab95
> fix: DropdownMenuButtonで矢印キーを押してフォーカスを移動できる

- packages/smarthr-ui/e2e/components/ComboBox/MultiComboBox.test.ts
- packages/smarthr-ui/e2e/components/ComboBox/SingleComboBox.test.ts
- packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
- packages/smarthr-ui/src/components/ComboBox/MultiCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/SingleComboBox.tsx
- packages/smarthr-ui/src/components/ComboBox/SingleCombobox.stories.tsx
- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
https://smarthr.atlassian.net/browse/SHRUI-700
他の入力系コンポーネントと合せて、Combobox の inputAttributes を消しました。
Combobox に渡した各種 attrs は内包する input に渡ります。
> feat!: Combobox の inputAttributes を消し、input に直接渡すように修正

- packages/smarthr-ui/src/components/TextLink/TextLink.tsx
- packages/smarthr-ui/src/libs/util.ts
https://github.com/kufu/smarthr-ui/pull/4885
@types/react 18.3.5で forwardRefの型定義が更新されたため
TextLinkとutil.tsでエラーが発生していた
forwardRef に期待される props の型にあうように修正
ローカルで@types/react 18.3.5で問題なくBuildが出来ることを確認済
> chore: types/reactの型定義更新に伴うエラーを修正

- packages/smarthr-ui/e2e/components/ComboBox/MultiComboBox.test.ts
- packages/smarthr-ui/e2e/components/ComboBox/SingleComboBox.test.ts
- packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
- packages/smarthr-ui/src/components/ComboBox/MultiCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/SingleComboBox.tsx
- packages/smarthr-ui/src/components/ComboBox/SingleCombobox.stories.tsx
- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
#4907 への fix をする際、変更が大きくなりすぎないように Reverts kufu/smarthr-ui#4842
> chore: Revert "feat!: Combobox の inputAttributes を消し、input に直接渡すように修正"

- packages/smarthr-ui/src/components/Dialog/ActionDialog.stories.tsx
- packages/smarthr-ui/src/components/Dialog/Dialog.stories.tsx
- packages/smarthr-ui/src/components/Dialog/DialogOverlap.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog.stories.tsx
一部環境においてスタッキングコンテキストの発生した特定要素がダイアログ背景よりも上に現れてしまう不具合を修正します。
ダイアログ背景の `shr-z-overlap-base` を消したのが原因だったため、戻しました。
https://github.com/kufu/smarthr-ui/pull/4848/files#diff-41a98e1c7f207238823888de15eee54e035b490d73a741f885cd1e7b834a15ebL20 
各ダイアログの Story にスタッキングコンテキストを追加したので、Chromatic に差分がでていなければ問題ありません。
> fix: Dialog 背景に z-index を追加

- packages/smarthr-ui/src/components/Experimental/SideMenu/SideMenu.tsx
https://github.com/kufu/smarthr-ui/pull/4895
SideMenuのPropsから`children`が消えており、子要素を受け付けることができなくなっているので追加したい。
`PropsWithChildren`を利用して`children`を追加した。
コードを読んで修正方法が正しそうか確認。
型定義のみの変更なので挙動に変化はありません。
> fix: SideMenuのPropsにchildrenを追加

- packages/smarthr-ui/src/components/Table/Table.tsx
なし
Table コンポーネントに使用されていないコードが残っていたので削除したい
- createContext でコンテキストを作っていた処理を削除
- 以前使っていた名残の消し忘れっぽい
- これがなくなると、Table コンポーネントが Server Component から使用できるようになります
- Th がまだ Server Component から使えないのでこの PR 単体だとあんまり意味ないけど…
Story で Table が以前同様動いていれば ok
> fix: Table コンポーネントの使われていない記述を削除

- packages/smarthr-ui/package.json
- packages/smarthr-ui/src/hooks/useId.test.ts
- packages/smarthr-ui/src/hooks/useId.tsx
- packages/smarthr-ui/src/index.ts
https://smarthr.atlassian.net/browse/SHRUI-1047
React 17 以下にも提供していた独自の `userId` の仕組みを廃止します。これによって事実上 React 18 未満のサポートを終了します。
SmartHR UI が提供する `useId` は、React 組み込みの `useId` をラップし、一部機能を拡張して提供しています。
その中で、useId が存在しない React 18 未満でも使用できるように、同等の機能を独自実装していました。
独自実装では `useContext` が使われていますが、これによって、 `useId` を使用している各種コンポーネントがサーバーコンポーネントとして利用できない問題が発生しています。
RSC 対応を進めたいという気持ちと、React 18 未満のサポートはぼちぼち終了しても良さそうという背景から、独自実装を廃止し、React 18 のみをサポートするように変更します。
React 18 を使用している場合には影響は一切ありません。
React 17 以下を使用している場合、SmartHR UI を使用することができなくなるため、SmartHR UI のバージョンアップを止めるか、React をバージョンアップしてください。
> feat!: useId の独自実装を削除し、React 18 未満のサポートを終了する

- packages/smarthr-ui/src/components/Dialog/DialogOverlap.tsx
画面をスクロールした状態でダイアログを開くとダイアログ背景がズレる不具合を修正しました。
ダイアログ背景の `position: absolute` を `position: fixed` に変更しました。
Dialog の With Scroll Story で確認できます。
https://63d0ccabb5d2dd29825524ab-qumxppnwwd.chromatic.com/?path=/story/dialog%EF%BC%88%E3%83%80%E3%82%A4%E3%82%A2%E3%83%AD%E3%82%B0%EF%BC%89-dialog--with-scroll
> fix: ダイアログの背景がスクロールに依ってズレる不具合を修正

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
https://smarthr.atlassian.net/browse/SHRUI-1026
ModelessDialog に幅や高さを指定すると、その指定以上に resize できない問題を修正しました。
resize のスタイリングを持っている Base の親要素に幅や高さを指定しているため、親要素以上に広げられないのが原因でした。
「幅や高さを指定している div > Base」という DOM を、Base に集約しました。tailwlind 上では layout > box となっていたのを wrapper としました。
また [no-unused-expressions](https://typescript-eslint.io/rules/no-unused-expressions/) でエラーが出ていたので合わせて修正しました。
> fix: ModelessDialog に指定した幅や高さを超えて resize できるように修正

- packages/smarthr-ui/src/components/RadioButton/RadioButton.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1727167147526389
- RadioButton: [このPR](https://github.com/kufu/smarthr-ui/pull/4926)で外部のidより内部のdefaultIdが優先されてしまっていたのを修正
- RadioButton: [このPR](https://github.com/kufu/smarthr-ui/pull/4926)で外部のidより内部のdefaultIdが優先されてしまっていたのを修正
- 当該PRの変更に含まれていた他のコンポーネントでは問題ないことを確認
> fix(RadioButton): 外部からのidをdefaultIdより優先するように修正

- packages/smarthr-ui/src/components/Experimental/SideMenu/SideMenu.stories.tsx
https://kufuinc.slack.com/archives/CDG1XRPTP/p1727146089496589?thread_ts=1726813803.339369&cid=CDG1XRPTP
- SideMenuのStorybookにSideMenuGroupを使わない例を追加した
- SideMenuのStorybookにSideMenuGroupを使わない例を追加した
- `Default` にSideMenuGroupを使わないシンプルなものを設置
- 今までのものを `Grouped` に改名
https://63d0ccabb5d2dd29825524ab-ymnkzwtxnh.chromatic.com/?path=/docs/experimental%EF%BC%88%E5%AE%9F%E9%A8%93%E7%9A%84%EF%BC%89-sidemenu--docs
> docs(SideMenu): SideMenuGroupを使用しないサンプルを追加

- packages/smarthr-ui/.storybook/main.ts
- packages/smarthr-ui/.storybook/preview.tsx
- packages/smarthr-ui/src/components/TabBar/TabBar-bordered.stories.tsx
- packages/smarthr-ui/src/components/TabBar/TabBar.stories.tsx
- packages/smarthr-ui/src/components/TabBar/TabItem.stories.tsx
- packages/smarthr-ui/src/components/TabBar/VRTTabBar.stories.tsx
- packages/smarthr-ui/test-runner-jest.config.js
https://smarthr.atlassian.net/browse/SHRUI-1040
Story のあり方を定義し直し、他の見本となる Story を作ろうとしています。
構成は次の通りです。
Story 名 | 説明 | Chromatic 対象
--- | --- | :-:
Default | デザインシステムサイト用。過渡期として用意 | -
Playground | コンポーネントごとに必ず設置する Control | -
props 系 | id や onClick など汎用的なものは省略 | -
VRT | ペアワイズ法で props の組み合わせを網羅する | ✓
TabBar / TabItem のようにサブコンポーネントを持つ場合、コンポーネントごとに作成。
VRT を除いて、Story ごとに表示する状態は一つとしました。
ペアワイズ法の組み合わせ作成は、[pict](https://github.com/microsoft/pict) を使いました。
> docs: TabBar の Story を見直し

- packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
- packages/smarthr-ui/src/components/AppNavi/AppNaviAnchor.tsx
https://smarthr.atlassian.net/browse/SHRUI-1062
他のLink Componentと同様に`elementAs`をサポートしました
`elementAs`で任意のnext/linkなどを渡せるようになっています
sandbox環境などで確認
```tsx
<AppNavi label="機能名">
<AppNaviAnchor elementAs={Link} href="/about" current>
アンカーボタン
</AppNaviAnchor>
</AppNavi>
```
`buttons`についてはdeprecatedなので最低限使えるレベルの対応になってます
```ts
const buttons: = [
{
onClick: () => console.log('click'),
children: 'ボタン',
},
{
elementAs: Link,
href: '/about',
current: true,
children: 'アンカーボタン',
},
]
```
> feat: AppNaviAnchorにelementAsのpropsを追加

- packages/smarthr-ui/src/components/DropZone/DropZone.tsx
`DropZone` コンポーネントで、ドラッグ＆ドロップで選択されたファイルが `input` タグのDOMに格納されず、 `form` で送信した際に意図したファイルが `FormData` オブジェクトに格納されない問題がありました。
`DropZone` コンポーネントで、ドラッグ＆ドロップで選択されたファイルが `input` タグのDOMにデータが格納されるようにした。
`pnpm add https://pkg.pr.new/kufu/smarthr-ui@4964` で変更したパッケージをインストールし、 `DropZone` でファイルをドラッグ＆ドロップしてから `form` を `submit` して正常に選択したファイルが送信されていること。
> fix(DropZone): ドラッグ＆ドロップ時に選択したファイルがFormDataに格納されるようにした

- packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.stories.tsx
- packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
- Clusterなどの中でSearchInputに対してwitdh propsを指定した場合、正常に幅指定がされない問題があったので修正したい
- SearchInput内にあるlabel要素に対してwidhtを指定、その場合、子要素となるinputなどにはwidth 100% を指定するように修正
- これは `width: 50%` などが指定された場合の対応
- diffとCIを確認する
> fix: SearchInputのwrapperであるlabel要素に対してwidthを指定する

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- packages/smarthr-ui/src/smarthr-ui-preset.ts
ModelessDialog の重なり順序を変えたいが、`z-index` 値が固定で上書けない問題を修正しました。
コンポーネントに渡した className をもう一つ外側の要素にあたるように修正しました。
styled-components を使った拡張をしている場合は見直しが必要になる可能性があります。
```jsx
// ## Before
const HogeModelessDialog = styled(ModelessDialog)`
display: block; // 1
> div {
display: block; // 2
}
.smarthr-ui-ModelessDialog-header {
display: block;  // 3
> span {
display: block; // 4
}
}
`
// ## After
const HogeModelessDialog = styled(ModelessDialog)`
// 直下に書いていたものは .smarthr-ui-ModelessDialog に当ててください。
.smarthr-ui-ModelessDialog {
display: block; // 1'
> div {
display: block; // 2'
}
}
// クラスセレクタなど、直下に書いていないスタイルへの影響はありません。
.smarthr-ui-ModelessDialog-header {
display: block;  // 3'
> span {
display: block; // 4'
}
}
`
```
> fix: ModelessDialog に渡した className が当たる場所を変更

- .eslintrc.js
- packages/smarthr-ui/src/components/AppNavi/AppNavi.stories.tsx
- packages/smarthr-ui/src/components/AppNavi/AppNavi.tsx
- packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
- packages/smarthr-ui/src/components/CheckBox/CheckBox.tsx
- packages/smarthr-ui/src/components/ComboBox/VRTMultiCombobox.stories.tsx
- packages/smarthr-ui/src/components/ComboBox/VRTSingleCombobox.stories.tsx
- packages/smarthr-ui/src/components/DropZone/DropZone.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- packages/smarthr-ui/src/components/Header/HeaderLink.tsx
- packages/smarthr-ui/src/components/Input/CurrencyInput/CurrencyInput.tsx
- packages/smarthr-ui/src/components/Input/Input.tsx
- packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
- packages/smarthr-ui/src/components/InputFile/InputFile.tsx
- packages/smarthr-ui/src/components/NotificationBar/NotificationBar.stories.tsx
- packages/smarthr-ui/src/components/RadioButton/RadioButton.tsx
- packages/smarthr-ui/src/components/RadioButtonPanel/RadioButtonPanel.tsx
- packages/smarthr-ui/src/components/Select/Select.tsx
- packages/smarthr-ui/src/components/Switch/Switch.tsx
- packages/smarthr-ui/src/components/Table/TdCheckbox.tsx
- packages/smarthr-ui/src/components/Table/ThCheckbox.tsx
- packages/smarthr-ui/src/components/TextLink/TextLink.stories.tsx
- packages/smarthr-ui/src/components/Textarea/Textarea.tsx
- packages/smarthr-ui/src/components/TimePicker/TimePicker.tsx
- packages/smarthr-ui/src/components/UpwardLink/UpwardLink.tsx
- eslintのignore commentが開発時にノイズになるため、必要最小限になるよう、調整
- その際、既に不要になっていた箇所もあったため削除なども実施
- 差分をみてロジックに影響がないことを確認する
> chore: eslintのignore commentを削除 or 不要なように調整する

- packages/smarthr-ui/src/components/Input/Input.stories.tsx
> chore: storybookのInputのerror表示にミスがあったため調整する

- packages/smarthr-ui/src/components/AppNavi/AppNaviDropdownMenuButton.tsx
https://kufuinc.slack.com/archives/C06KVP5PL23/p1727780133229749
AppNaviDropdownMenuButton に `aria-current="page"` を1度でも指定すると、再読み込みされるまで current 装飾がつき続けてしまう不具合の修正提案です。
既存ロジックは current をつけるだけで、外す処理がありませんでした。children として渡される要素の `aria-current="page"` を検知する方法できないため、本 PR では引き金ボタン内に hidden 付きの要素として複製し、CSS の `has()` でスタイリングしています。
- `React.Children.map` 内で `aria-current="page"` を探すのをやめる
- chlidren を引き金 button 内に複製し `hidden` 属性を付与
- `has()` に（tailwlind では `has-[[aria-current="page"]]` に）まかせてスタイリング
> fix: AppNaviDropdownMenuButton の current 装飾ロジックを見直し

- packages/smarthr-ui/src/components/SegmentedControl/stories/SegmentedControl.stories.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1728614020390679
SegmentedControl[isSquare=true]はアイコンのときにのみ使用されるので、Storybookもそうなるように修正
- SegmentedControl[isSquare=true]の箇所について、options propsにアイコンを使用したものが渡るように修正
> docs(SegmentedControl): [isSquare=true]のときにアイコンになるように修正

- packages/smarthr-ui/src/components/Table/ThCheckbox.tsx
`<Table>` のヘッダーセルにあるチェックボックスには、マシンリーダブルなラベルはあるが可視のラベルがなかったため追加。
参考: [フォーム: ウェブアクセシビリティ簡易チェックリスト | アクセシビリティ | SmartHR Design System](https://smarthr.design/accessibility/check-list/#h2-6)
関連チケット
https://smarthr.atlassian.net/browse/SHRUI-1066
> 入力する内容や、操作がラベルとして表示されている
テキストラベルを表示するスペースがセル内に無いため、マウスポインターがホバーした際、またはフォーカスした際に、「すべての行を選択」のツールチップを出した。
ヘッダーセルを固定した際に、`<Table>` コンポーネントの描画範囲外が描画されなくなるため、ツールチップは右側に出した。（右側の見出しセルが見えなくなるけど。。。）
`<ThCheckbox>` は `<th>` でレンダリングされ、内包するコンテンツが「すべての行を選択」になるので、チェックボックスがあるカラムの名前が「すべての行を選択」になってしまう。
そのことを回避するために `<th>` に `aria-label` を付与し、内包するコンテンツを無視して「選択」というカラム名に変更した。
> feat: 一括選択のチェックボックスに可視のラベルを追加

- packages/smarthr-ui/src/components/Header/LanguageSwitcher/LanguageSwitcher.stories.tsx
- packages/smarthr-ui/src/components/Header/LanguageSwitcher/LanguageSwitcher.tsx
https://smarthr.atlassian.net/browse/SHRUI-1177
[Storybook](https://story.smarthr-ui.dev/?path=/docs/navigation%EF%BC%88%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%EF%BC%89-header-languageswitcher--docs)
[WCAG Reference](https://waic.jp/translations/WCAG21/Understanding/language-of-parts.html)
言語切替メニューのリンクのテキストが各言語の言葉のため、pageに設定されている言語によってスクリーンリーダーで読み上げるときに発音がおかしかったり、読み上げられない場合がります
- スクリーンリーダーで各言語の発音で読み上げるために、LanguageSwitcherの各アイテム言語ごとにlang属性を追加
現在の状態の確認は
- ローカルのStorbookで確認したい場合一旦LanguageSwitcherで追加したlang属性を削除してから、スクリーンリーダーで各アイテムを読み上げる
- SmartHR上のヘッダーにあるLanguageSwitcherでスクリーンリーダーで各アイテムを読み上げる
- 一番わかりやすいのがポルトガル語やベトナム語を選択し、漢字、ハングルを読み上げると選択中の言語で読み方がないため何も読み上げられない
> fix(LanguageSwitcher): スクリーンリーダーで各言語のリンクを正しく読み上げられるようにlang属性を追加

- packages/smarthr-ui/src/components/SectioningContent/SectioningContent.test.tsx
- packages/smarthr-ui/src/components/SectioningContent/useSectioningWrapper.test.tsx
- packages/smarthr-ui/src/components/SectioningContent/useSectioningWrapper.ts
元は単体テストを書くぞってチケット
https://smarthr.atlassian.net/browse/SHRUI-1185
SectioningContent コンポーネント及び useSectioningWrapper の単体テスト作成し、RSCに向けた対応の下準備します。
その過程で、以下のような不具合を発見したのでついでに修正します。
```tsx
<Stack as={StyledSection}>
<Heading>heading</Heading>
</Stack>
// 中略
const StyledSection = styled.section``
```
上記のように、ネイティブの SectioningContent タグを拡張した StyledComponent を、Stack  (や Cluster, Base など) の  `as` オプションに指定した場合、内包される `Heading` タグの見出しレベルは自動計算されるべきですが、されずにすべて h1 になる不具合がありました。
- 単体テストを追加
- 軽微な不具合修正
テストコードに過不足ないかを確認の上、CIが通ればOKです。
```
✓ src/components/SectioningContent/SectioningContent.test.tsx (11)
✓ SectioningContent (11)
✓ <Section> を使用すると section 要素が描画されること
✓ <Article> を使用すると article 要素が描画されること
✓ <Aside> を使用すると aside 要素が描画されること
✓ <Nav> を使用すると nav 要素が描画されること
✓ SectioningContent 直下の見出しレベルはデフォルトで2になること
✓ …
```
> fix: レイアウトコンポーネントなどと StyledComponent を組み合わせた場合に、見出しレベルの自動設定が機能しない不具合を修正

- packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
- packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
SearchInput が inline なため幅があたらない不具合がありました。
flexitem や block になっていない場合、label に対して width があたっているため意図した幅を与えられませんでした。
- SearchInput の display を inline-block に変えました
- tailwind-variants 化しました
> fix: SearchInput に幅があたらない不具合を修正

- packages/smarthr-ui/src/components/Switch/Switch.tsx
https://smarthr.atlassian.net/browse/SHRUI-1072
- Switchは非テキストとして、未選択時のコントラスト比をミニマムでも3:1を確保したい
- 視覚障害を持つユーザーや色を見分けることが難しいユーザーが内容が見やすくなる
- borderもコントラスト比をミニマムでも3:1を確保したいけど、他のform control componentも影響があるため、まとめて別途検討する
- 未選択時のSwitchのコントラスト比をミニマムでも3:1を確保するために、つまみの部分のカラーを変更する
- #c1bdb7(TEXT_DISABLED) から #706d65(TEXT_GREY)
- コントラスト比：**1.87:1**　＝＞　**5.16:1**
BEFORE | AFTER
--- | ---
> fix(Switch): 未選択時のコントラスト比を 3:1 確保する

- packages/smarthr-ui/src/components/Picker/types.ts
- 無
- 従来の型定義だと `TimePicker` / `MonthPicker` は `input` 要素に付与可能なすべての属性をpropsとして受け取ります
- その結果 `<TimePicker type="date" />` といった意図のわからない指定が可能になっていました
- ランタイムでは内部的に指定されている `type=time` が勝つので当該指定をしても挙動は変わりません
- あくまで「型定義上は可能」という話
- `TimePicker` は既にコンポーネントとして提供されているため一応BREAKING CHANGEという扱いにしています
- `PickerProps` から `type` を除外しました
- ✅ `TimePicker` / `MonthPicker` に `type` 属性を指定すると型検査でエラーとなること
> fix!: TimePicker/MonthPickerにtypeを指定できないようにする

- packages/smarthr-ui/src/components/TabBar/TabBar.tsx
- packages/smarthr-ui/src/components/TabBar/TabItem.tsx
- packages/smarthr-ui/src/components/TabBar/stories/TabBar.stories.tsx
- packages/smarthr-ui/src/components/TabBar/stories/VRTTabBar.stories.tsx
- packages/smarthr-ui/src/smarthr-ui-preset.ts
https://smarthr.atlassian.net/browse/SHRUI-1190
Tabbar の実装が Reel > TabBar となっており、focus-ring が見切れてしまう対処として TabBar に margin が設定されていた。
レイアウト上の不都合や視覚的な違和感が強いため修正することにした。
- focus-ring を TabItem の外側ではなく内側にセットされるように修正
- Story をついでに見直し
> fix: TabBar が margin を持たないように修正

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
https://smarthr.atlassian.net/browse/SHRUI-1176
ModelessDialog のダイアログタイトル部ではドラッグできず、テキスト選択になってしまう不具合を修正。
既存のスタイルで何故かスタッキングコンテキストを発生させていたことが影響し、ドラッグ対象になっていなかった。
Storybook で確認してください。
> fix: ModelessDialog のグラブ領域を修正

- packages/smarthr-ui/src/components/TabBar/TabItem.tsx
#5054 
#5054 の修正漏れです。
TabItem が disabled かつ disabledDetail を持つ時に Tooltip > TabButton という構造になるが、Tooltip への focus ring が外側についているため見切れてしまう。
TabItem を囲う Tooltip の focus ring を内側につける。
> fix: TabItem に disabledDetail があるときのフォーカスリングを修正

- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
https://smarthr.atlassian.net/browse/SHRUI-1069
InputFile コンポーネントを `<label>` 要素などで紐づけた場合(FormControlで利用する時に)にアクセシブルネームに `<label>` 内のテキストが反映されないため、 `<label>` 内のテキストもInputFileのアクセシブルネームに含める
reference:
https://github.com/kufu/wcag-guide/wiki/SmartHR-UI#inputfile%E3%81%AEaccessible-name%E3%81%AF%E3%81%A9%E3%82%93%E3%81%AA%E5%86%85%E5%AE%B9%E3%81%8C%E9%81%A9%E5%88%87%E3%81%8B
FormControl内でInputFile利用する際には`<label>` 要素で可視ラベルとして紐づけるため、`<label>` 要素の可視ラベルをInputFileのアクセシブルネームに含める
メリット
https://smarthr.design/accessibility/check-list/accessible-name/#h2-2
> fix: FormControl内のInputFileのアクセシブルネームに可視ラベルを含める

- packages/smarthr-ui/src/components/Dropdown/Dropdown.test.tsx
- packages/smarthr-ui/src/components/Dropdown/useKeyboardNavigation.ts
- JIRA: https://smarthr.atlassian.net/browse/SHRUI-676
DropdownContent からフォーカスが外れても開いたままだった & Tabの逆順では DropdownContent には入らなかったため、[フォーカス順序が見た目と異なっていて](https://smarthr.design/accessibility/check-list/focus-order) 品質基準を満たせていませんでした！
そのため、フォーカスが外れたときは DropdownContent を閉じるように変更しました！
- DropdownContent の最後の要素で Tab を押したとき次の要素へフォーカスするロジックに、閉じる実行を追加
- storybook で確認可能ですが、確認するには dropdown trigger の他にフォーカス可能な要素を追加する必要があります。
テスト動画
https://github.com/user-attachments/assets/5a874faf-693e-4aa5-8324-c782cd18ff51
> fix: DropdownContentの最後の要素でTabを押したときDropdownを閉じる

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
ModelessDialog のヘッダー部にキーボードフォーカスすると文字列が消えてしまう不具合があったため修正しました。
ヘッダー部分にフォーカス中は、文字列部分でドラッグアンドドロップできなくなりますが、許容範囲と考えました。
> fix(ModelessDialog): ヘッダー部にキーボードフォーカスが当たると文字列が消えてしまう不具合を修正

- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx
AccordionPanelTrigger のキャレットアイコンが shrink してしまう不具合を修正しました。
なぜか aria-expanded に対して設定され、かつ `shr-` がついていないため機能していなかった。
> fix(AccordionPanelTrigger): キャレットが shrink してしまう不具合を修正

- packages/smarthr-ui/src/components/DefinitionList/DefinitionList.tsx
DefinitionList の maxColumns や termStyleType を DefinitionListItem に渡す時、cloneElement に null が渡ると壊れる不具合を修正。
```jsx
<DefinitionList>
{/* hoge=false の時、null が渡るため cloneElement(child) でエラーが発生する */}
{hoge && <DefinitionListItem />}
</DefinitionList>
```
> fix(DefinitionList): children に null が渡ってきた場合の不具合を修正

- packages/smarthr-ui/src/hooks/useDevice/DeviceProvider.tsx
- packages/smarthr-ui/src/hooks/useDevice/index.ts
- packages/smarthr-ui/src/hooks/useDevice/useDevice.stories.tsx
- packages/smarthr-ui/src/hooks/useDevice/useDevice.ts
- packages/smarthr-ui/src/index.ts
- https://smarthr.atlassian.net/browse/SHRUI-1204
下記問題に対応した。
- `useDevice` を使うたびにイベントリスナーが登録されてしまう。
-  `useState` の初期値に Web API を使っているため SSR 時にエラーになる。
-  `useDevice` ごとの利用ごとにイベントリスナーを登録するのではなく、Provider でイベントリスナーの登録をし、 `useDevice` で Context を通じて値を購読するようにした。
- サーバーサイドレンダリング時と、メディアクエリの判定ができていない初期描画時の `isNarrow` の初期値は `null` とした。
- `useState` と `useEffect` ではなく、 `useSyncExternalStore` でスマートに書けたのでリファクタ。
- Provider や hook は RSC でもラップせずにそのまま利用できるように `use client` を付与した。
①プロジェクトのルートのコンポーネントで `DeviceProvider` を囲ってください。
```jsx
function App() {
return <DeviceProvider><Main /></DeviceProvider>
}
```
② `useDevice` の `isNarrow` が `null` の場合の制御を追加してください。
`null` になるケースはサーバーサイドレンダリング時、もしくはクライアントサイドでの初期描画時のケースです。
```jsx
function Component() {
const { isNarrow } = useDevice()
// examples
// モバイル or …
```
> fix!: SSR対応や必要以上にイベントを登録しないように `useDevice` を変更した

- packages/smarthr-ui/src/components/Button/Button.tsx
disabledDetail で表示されるアイコンが幅によって折り返されないように修正しました。
合わせて、非推奨アイコンの置き換えや高すぎる詳細度を見直しています。
> fix(Button): disabled の説明が不用意に折り返されないように見直し

- packages/smarthr-ui/src/components/Header/Header.tsx
- packages/smarthr-ui/src/components/Header/stories/Header.stories.tsx
> fix(Header): enableNew を隠す

- packages/smarthr-ui/src/components/Dialog/RemoteDialogTrigger.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/stories/DropdownMenuButton.stories.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/stories/VRTDropdownMenuButton.stories.tsx
DropdownMenuButton の children に RemoteDialogTrigger を指定できることを考慮できていなかったので修正しました。
- DropdownMenuButton が Button / AnchorButton だけでなく RemoteDialogTrigger にも意図したスタイリングが当たるように修正
- RemoteDialogTrigger に与えた props が内包要素に引き継がれるように修正
- Story を拡充
> fix(DropdownMenuButton): RemoteDialogTrigger の考慮漏れを修正

- .github/workflows/publishRelease.yml
- .github/workflows/startRelease.yml
- https://github.com/kufu/smarthr-ui/actions/runs/12063086686/job/33637730278
- https://github.com/kufu/smarthr-ui/actions/runs/12063194282/job/33638001325
- https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0
リリース用の GitHub Actions が slackapi/slack-github-action の更新に追従できていなかったため修正しました。
[slack-github-action のリリースノート](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0)を参考に修正しましたが、しっかり読まず雰囲気で修正しています🙏
特記事項なし
ローカルで確認できないためマージする必要があります。
> chore: リリース用 GitHub Actions における利用ライブラリ更新に追従

- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
DropdownMenuButton に何らかの形で拡張した Button や AnchorButton を使っていると、装飾があたらない不具合を修正します。
- Button や AnchorButton、RemoteDialogTrigger 以外にも装飾があたるように条件を見直し
- DropdownMenuGroup には装飾があたらないように修正
> fix(DropdownMenuButton): ボタンリストの装飾適用条件を緩和

- .circleci/config.yml
CircleCI の不適切な設定を調整します
- 過剰なリソースクラスの使用を見直し、必要十分なクラスに変更します。
- Node18/20 を利用しているテストを Node20/22 に変更します。
CI が通ればOKです。
フレーキーでないことを確認するため10連続実行して問題ないことを確認済みです。
> chore: CircleCI の image/resource_class の調整

- packages/smarthr-ui/scripts/exportUIProps.ts
- リリースで `write: ui-props` を実行するとき発生するエラーに対応したい
- `exportUIProps` の中で、[後続の処理](https://github.com/kufu/smarthr-ui/blob/b1a1bc62e83d8bfa5b47cde6c4695405f362f00a/packages/smarthr-ui/scripts/exportUIProps.ts#L37) で参照する配列の中身が空でも進める状態になっていて、例外エラーが起きているので `propItem.declarations` が空配列を返す場合は後の処理をスキップするようにしました
> fix: declarationsが空配列の場合も後続の処理をスキップする

- packages/smarthr-ui/src/components/Table/Th.tsx
#5144 で紛れ込んでしまった不具合を修正します。ソート付き Th のアイコンが両端揃えではなく左に依ってしまっていました。
両端揃えになるように調整。
> fix(Th): ソートアイコンが左寄せになっていたのを修正

- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
https://smarthr.atlassian.net/browse/SHRUI-1067
ModelessDialogを閉じたときのフォーカスの処理が無いので、フォーカスをコンテンツに戻す処理を実装する
- ModelessDialog以外の最終フォーカスした要素にフォーカスを戻す
modeless dialogをボタンまたESCキーで閉じた際にmodeless dialog以外の最終フォーカスした要素にフォーカスを戻す
- ModelessDialogを開いた際にフォーカスイベントを検知してフォーカスされている要素をrefで管理する
- フォーカスがModelessDialog内の場合はフォーカスをrefに代入しない
- onClickCloseとおｎPressEscapeにmodeless dialog以外の最終フォーカスした要素にフォーカスを戻す処理を追加
https://github.com/user-attachments/assets/340f1aa3-1aa8-43c3-8560-7d4a32718c4c
> fix(ModelessDialog): modeless dialog閉じたときのフォーカス処理修正

- packages/smarthr-ui/src/components/DatePicker/DatePicker.tsx
- packages/smarthr-ui/src/components/DatePicker/stories/DatePicker.stories.tsx
- packages/smarthr-ui/src/components/DatePicker/stories/VRTDatePicker.stories.tsx
- packages/smarthr-ui/src/components/Input/stories/Input.stories.tsx
- packages/smarthr-ui/src/components/Picker/DatetimeLocalPicker.tsx
- packages/smarthr-ui/src/components/Picker/MonthPicker.tsx
- packages/smarthr-ui/src/components/Picker/TimePicker.tsx
- packages/smarthr-ui/src/components/WarekiPicker/WarekiPicker.tsx
- packages/smarthr-ui/src/components/WarekiPicker/index.ts
- packages/smarthr-ui/src/components/WarekiPicker/stories/VRTWarekiPicker.stories.tsx
- packages/smarthr-ui/src/components/WarekiPicker/stories/WarekiPicker.stories.tsx
- packages/smarthr-ui/src/index.ts
- packages/smarthr-ui/test-runner-jest.config.js
https://smarthr.atlassian.net/browse/SHRUI-1000
DatePicker を和暦に特化させた WarekiPicker を追加しました（厳密に言えば Wareki を pick するわけではない）。
合わせて DatePicker / DateTimeLocalPicker / MonthPicker / TimePicker などを非推奨とし、`<Input type="{date | datetime-local | month | time" />` を使うように促します。
- DatePicker を deprecated
- DatePicker の `showAlternative` で和暦を表示するコンポーネントを WarekiPicker として追加
- DateTimeLocalPicker / MonthPicker / TimePicker を deprecated
- Input の Story の type を拡充
> feat: WarekiPicker を追加

- .github/workflows/publishRelease.yml
`npm publish` で利用しているNPM AUTH TOKENをorganization管理のトークンに切り替えます。
`secrets.NPM_TOKEN` を `secrets.KUFU_NPM_RELEASE_TOKEN` に差し替えた
admin権限があれば、[Actions secrets and variables](https://github.com/kufu/smarthr-ui/settings/secrets/actions)からsecretsがあるか確認可能です。
> chore: npm publish用のNPM AUTH TOKENをorg管理のものに置き換える

- packages/smarthr-ui/package.json
- pnpm-lock.yaml
タイトルの通りです。 [npm-run-allは何年も前からメンテされておらず](https://github.com/mysticatea/npm-run-all) 、フォークでメンテされている [npm-run-all2](https://github.com/bcomnes/npm-run-all2) に変更しました。npm-run-allと同様にコマンド打てます。
タイトルや概要の通り。
`pnpm ui build` で `run-p` コマンドが実行されること。
> chore: npm-run-allはもうメンテされてないので、メンテされているnpm-run-all2に変更した

- packages/smarthr-ui/src/components/AppHeader/AppHeader.tsx
- packages/smarthr-ui/src/components/AppHeader/components/desktop/DesktopHeader.tsx
- sandbox/next/e2e/rsc.test.ts
- sandbox/next/src/app/rsc_test/AppHeader/page.tsx
🍐 
AppHeader を Server Component から呼び出すとエラーが発生してしまったので、`'use client'` をつけたい
- `'use client'` をつけた
- ドロップダウンの不要な suffix アイコンを削除
fmfm で大丈夫です
> fix: AppHeader を Server Component から呼べるようにする

- packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx
https://github.com/kufu/smarthr-ui/pull/5192#issuecomment-2550502047
#5192 で変更された構造をシンプル化しActionDialogに近づけた
- `form` を `display: contents` で囲うことでレイアウトが崩れてしまう問題を回避
> refactor(FormDialog): 構造をシンプル化

- pnpm-lock.yaml
- sandbox/next/package.json
N/A
sandbox 環境で使用している Next 14.2.20 に脆弱性が発見され、`pnpm audit` が通らなくなってしまったのでバージョンを上げます。
v14 にパッチバージョンが出てるけど、せっかくなのでついでに v15 にしてみます。テストで使ってるだけなのでCIが通ればOKなはず。
CIが通ればOK
> chore: sandbox で使用している Next のバージョンを 15 にする

- packages/smarthr-ui/src/components/Table/useReelCells.ts
TableのuseReelCellsのロジックを整理し、効率化、可読性の向上を試みます
> chore: TableコンポーネントのuseReelCells のロジックを整理する

- packages/smarthr-ui/src/components/Textarea/Textarea.tsx
- Textareaのdecoratorsの実行結果が意図しない文字列になる場合があるため調整したい
- decoratorsの実行結果が、ReactNodeになる場合を考慮し、Fragmentで結合するように修正する
- decoratorsは文字列に対してタグなどを差し込めるようにするための属性であるため、それを考慮したロジックに変更しました
> fix: Textareaの文字数カウントテキストの生成時、ReactComponentが利用される場合があることの考慮漏れを対応

- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanel.test.tsx
- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanel.tsx
- packages/smarthr-ui/src/components/AccordionPanel/AccordionPanelTrigger.tsx
- packages/smarthr-ui/src/components/AccordionPanel/accordionPanelHelper.ts
* [従業員サーベイアプリ「アクセシビリティ簡易チェックリスト」検証結果](https://docs.google.com/spreadsheets/d/1tLR0kGQNMFIKiF5cVCdbF76lHFtkOjouzFNwMupZ_js/edit?gid=0#gid=0&range=D3)
従業員サーベイアプリにおいて、 `AccordionPanel` のコンテンツとして `RadioButton` を利用している箇所がありましたが、 その場合に矢印キーで項目を選択できなくなっていました。このPRでは、AccordionPanel内にインタラクティブな要素が配置されていた場合にも、キーボード操作ができるようにしました。
TriggerとContentを包含する一番外側のラッパー要素に対して `keydown` イベントリスナーが設定されており、そのハンドラ内で `preventDefault()` が実行されていたことが原因でした。本来は、矢印キー上下で複数の `AccordionPanelItem` 間を移動できるようにしていたものでしたが、アコーディオンが開かれていてContent内の要素を操作しているときでも、このハンドラが作動していました。
代替手段として、イベントリスナーの監視対象を `Trigger` 側の要素に変更しました。これによって、 `Content` 内を操作している場合には、キーボード操作ができるようになりました。
また、 [`KeyboardEvent#keyCode`](https://developer.mozilla.org/ja/docs/Web/API/KeyboardEvent/keyCode) は非推奨となっていたため、 …
> fix: AccordionPanelのkeydownイベントリスナーをTriggerに移動

- packages/smarthr-ui/src/components/UpwardLink/UpwardLink.tsx
- 再レンダリングの度にtailwindのstyle生成が実行されるため、memo化するようにします
> chore: UpwardLinkのstyle生成をmemo化する

- packages/smarthr-ui/src/components/PageCounter/PageCounter.tsx
> chore: PageCounterの内部処理をリファクタリングする

- packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
> chore: InputWithTooltipの内部でのstyle属性の生成方法を整理

- packages/smarthr-ui/src/components/InputFile/InputFile.tsx
> chore: InputFileの内部処理をリファクタリングする

- packages/smarthr-ui/src/components/InformationPanel/InformationPanel.tsx
- useIdは1つにしてほしいと書いてあるので
- https://ja.legacy.reactjs.org/docs/hooks-reference.html#useid
- でも新しいドキュメント https://react.dev/reference/react/useId#generating-ids-for-several-related-elements だと書きっぷりが少し変わってて、実はそうでもないのか…？となってる
- 挙動としては複数書いても違うidが当たるようにはなってる
> refactor(InformationPanel): useIdを1つに統合

- packages/smarthr-ui/src/components/Button/Button.tsx
- packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
```tsx
<Button>
<FaHogeIcon alt="hoge" />
</Button>
```
のようなボタンを作る時に、 `square` を指定しなくてもsquareになるように修正
- ButtonWrapperの `$loading` を `loading` に修正
- `react-innertext` でchildrenを見て、ラベルが空 かつ square propsがundefinedなら自動的にsquareになるようにした
- VisuallyHiddenTextでの指定などもあるが、square propsは残してあるので概ね対応できれば、でいいと考えた
> fix(Button): テキストのラベルが存在しない場合に自動的にsquareにする

- packages/smarthr-ui/src/components/Button/Button.tsx
- packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
react-intlとの組み合わせで期待通りの動作をしないことがわかったのでRevert kufu/smarthr-ui#5294
https://kufuinc.slack.com/archives/CGC58MW01/p1738040458168459?thread_ts=1737541173.404369&cid=CGC58MW01
> chore: Revert "fix(Button): テキストのラベルが存在しない場合に自動的にsquareにする"

- packages/smarthr-ui/.storybook/preview-head.html
https://kufuinc.slack.com/archives/C079SGNTSGN/p1737529135300159?thread_ts=1737337547.918989&cid=C079SGNTSGN
https://kufuinc.slack.com/archives/C079SGNTSGN/p1737529430502409?thread_ts=1737337547.918989&cid=C079SGNTSGN
Storybookの高さが不十分なことで、Dropdown等の外をクリックしたら閉じる系のものの挙動が勘違いされやすいので修正
- Storybookのiframeのhtml, bodyをheight: 100%に修正
before
https://github.com/user-attachments/assets/2eae5818-a1c0-4d9a-8194-322ccf10a549
after
https://github.com/user-attachments/assets/b607a4bc-9774-42b7-9d9f-6cb3d1bf7d32
> docs: iframe内のコンテンツの高さを100%で表示できるように修正

- packages/smarthr-ui/src/components/Textarea/Textarea.tsx
https://kufuinc.slack.com/archives/C06KVP5PL23/p1737614015187009
autoResize時にvalue, defaultValueの初期値でも高さを反映するように修正
- autoResize時にvalue, defaultValueの初期値でも高さを反映するように修正
- 軽微なリファクタリング
- 複数行のvalue または defaultValue と autoResize を設定した状態で初期レンダリング時に高さが反映されていることを確認
> fix(Textarea): autoResize時にvalue, defaultValueの初期値でも高さを反映するように修正

- packages/smarthr-ui/src/components/ComboBox/usePartialRendering.tsx
> chore: ComboBoxのusePartialRenderingの処理を最適化する

- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
conformなどのフォームライブラリを使用している際、FormControlのaria-describedbyが紐づかず、エラー表示時にエラー内容がinput要素で読み取れなくなっていた。
input要素にすでにaria-describedbyが設定されている場合も、追加でaria-describedbyを設定するようにした。
Storybook等で、FormControl内にあるinput要素にaria-describedbyを手動で設定していた場合も、FormControlのerrorMessagesに指定したエラー内容が読み取れることを確認してください。
例：
```tsx
<FormControl title="some title" errorMessage={['some error']}>
<Input aria-describedby="some-id" />
</FormControl>
```
> fix: aria-describedbyがinputに紐づいている場合もFormControlのaria-describedbyを設定する

- packages/smarthr-ui/src/components/Header/AppLauncher/AppLauncher.tsx
- packages/smarthr-ui/src/components/Header/Header.tsx
- packages/smarthr-ui/src/components/Header/HeaderLink.tsx
- packages/smarthr-ui/src/components/Header/LanguageSwitcher/LanguageSwitcher.tsx
> chore: Headerの内部処理を最適化する

- packages/smarthr-ui/src/components/Dropdown/Dropdown.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownCloser.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownContentInner.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownTrigger.tsx
- packages/smarthr-ui/src/components/Dropdown/dropdownHelper.ts
- packages/smarthr-ui/src/components/Dropdown/useKeyboardNavigation.ts
> chore: Dropdownコンポーネント内のロジックを整理する

- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialogContent.tsx
- packages/smarthr-ui/src/components/Dialog/MessageDialog/MessageDialogContentInner.tsx
> chore: MessageDialogの内部ロジックを整理する

- packages/smarthr-ui/src/components/SegmentedControl/SegmentedControl.tsx
* https://smarthr.atlassian.net/browse/SHRUI-1218
`SegmentedControl` コンポーネントにおいて、チェック済みの項目をホバーしたときの背景色と前景色のカラーコントラスト比が不十分でした。そのため、選択済みの場合は、内部で利用されている `Button` コンポーネントで `variant=primary` を利用するように変更しました。
これによって、選択済み項目で `shr-bg-main-darken` が当たるようになり、十分なコントラスト比が確保されます。
| :-: | :-: |
| <img width="689" alt="image" src="https://github.com/user-attachments/assets/c2c387c3-0acb-4cf2-97d2-35a4d7d68d70" /> | <img width="689" alt="image" src="https://github.com/user-attachments/assets/b83c178d-8ba0-4a01-8fa2-192e91d133ad" /> |
https://www.chromatic.com/build?appId=63d0ccabb5d2dd29825524ab&number=10084
> fix: SegmentedControl内の選択済み項目でButton[variant=primary]を利用する

- packages/smarthr-ui/src/components/ComboBox/MultiComboBox/MultiComboBox.tsx
- packages/smarthr-ui/src/components/ComboBox/__tests__/useOptions.test.tsx
- packages/smarthr-ui/src/components/ComboBox/comboBoxHelper.ts
- packages/smarthr-ui/src/components/ComboBox/useOptions.ts
https://kufuinc.slack.com/archives/C06KVP5PL23/p1734060131150619
close https://github.com/kufu/smarthr-ui/pull/5190
MultiComboBoxのitem同士が同一かどうかの判定でlabelも参照されているが、labelに設定できるJSX.Elementは等価であっても等値ではない場合がありうるので、label同士の === による判定が意図通りになるかはアプリケーションの実装による。
この判定が意図通りにならない場合、同じアイテムを複数回選択できてしまう・一度選択したアイテムを選択解除できないなどの問題が発生しそう
~valueがitems内で一意（valueが同じでlabelが違うitemは無い）という前提を置き、MultiComboBox内でitem同士が同一かどうかの判定を行っていた部分でlabelも参照するのをやめました。~
item.labelがReactNodeだった場合のitemの比較を内部の文字列によって行うようにしました。
- コードの確認
- 動作を確認 
- https://github.com/kufu/smarthr-ui/pull/5201 にて不具合の挙動を再現したのでご確認ください。
- このPRには https://github.com/kufu/smarthr-ui/pull/5201 の内容を取り込んでいるので不具合が修正されていることが動作確認できると思います
> fix(MultiComboBox): item.labelがReactNodeだった場合のitemの比較を内部の文字列によって行うように

- packages/smarthr-ui/src/components/Dialog/DialogBody.tsx
- packages/smarthr-ui/src/components/Dialog/DialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/DialogHeader.tsx
- packages/smarthr-ui/src/components/Dialog/DialogTrigger.tsx
- packages/smarthr-ui/src/components/Dialog/DialogWrapper.tsx
- packages/smarthr-ui/src/components/Dialog/ModelessDialog.tsx
- packages/smarthr-ui/src/hooks/useHandleEscape.ts
> chore: Dialog周辺コンポーネントのロジックを整理する

- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialog.tsx
- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContent.tsx
- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/ActionDialogWithTrigger/ActionDialogWithTrigger.tsx
> chore: ActionDialogの内部処理を整理する

- packages/smarthr-ui/src/components/Dialog/ActionDialog/ActionDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/FormDialog/FormDialogContentInner.tsx
- packages/smarthr-ui/src/components/Dialog/dialogInnerStyle.ts
- DialogのScroll部分の処理がStackで設定されるflex系のclassNameに依存している記述になっている
- 依存関係が分かりづらく、かつ一見Stackが不要に見える記述になってしまうこと、Stack内のロジックの大半が本質的に不要であることから、必要なflex系のclassNameをDialog側で設定することでバグらせづらいコードにしたい
- DialogContentInner系からスクロール部分のStackの使用をやめ、`shr-flex shr-flex-col` だけ指定するように修正
- ActionDialog, FormDialogで画面縦幅が短い場合でも問題なくbodyがscrollできることを確認する
> chore: Dialogのscroll部分をStackではなくSection、かつ必要なflex系styleのみ設定することで余計な処理をskipする

- packages/smarthr-ui/src/components/Dialog/StepFormDialog/StepFormDialogContentInner.tsx
> fix: StepFormDialogにuseResponseMessageを適用する

- packages/smarthr-ui/src/components/Textarea/Textarea.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1739845995732009
propsで渡されるrowsの初期値が入力後にブラウザの初期値に戻ってしまうのを修正
propsで渡されるrowsの初期値が反映されないのを修正
StorybookのTextarea/rowsで入力して高さが縮まないことを確認
> fix(Textarea): rows指定が正しく動かないのを修正

- packages/smarthr-ui/src/components/Dialog/RemoteDialogTrigger.tsx
JIRAなし、アクセシビリティ簡易チェックをした際に見つけた課題です
`aria-haspopup="dialog"` のサポート状況が広がったため、正しい読み上げになる dialog に変えたい
根拠: [Test: aria-haspopup attribute | Accessibility Support](https://a11ysupport.io/tests/tech__aria__aria-haspopup-attribute)
- RemoteTriggerButton の `aria-haspopup="true"` を `aria-haspopup="dialog"` へ変更 
PC-Talker は dialog の対応なしみたいで読み上げは変わりませんでした！（開発版のみ確認）
しかし読み上げないようは true,dialog で変わらなかったので問題ない認識です！
> refactor: aria-haspopup の値をtrueからdialogに変更

- packages/smarthr-ui/src/components/Stepper/HorizontalStepItem.tsx
- packages/smarthr-ui/src/components/Stepper/VerticalStepItem.tsx
> chore: Stepperのmarkupを整える

- packages/smarthr-ui/src/components/RadioButton/RadioButton.tsx
- packages/smarthr-ui/src/components/RadioButtonPanel/RadioButtonPanel.tsx
- packages/smarthr-ui/src/components/ResponseMessage/ResponseMessage.tsx
- packages/smarthr-ui/src/components/SectioningContent/useSectioningWrapper.ts
- packages/smarthr-ui/src/components/SegmentedControl/SegmentedControl.tsx
> chore: SegmentedControl, Radio系、ResponseMessageコンポーネントの内部処理を整理する

- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1740726417428149
Fieldsetが innerMarginとして`0.5` を受け取れなくなっていたので修正
- props経由のinnerMarginのデフォルト値指定を削除
- innerMarginの値がundefinedのときだけ `1` を指定するように修正
- FieldsetのinnerMargin未指定時に`1`であることを確認 https://63d0ccabb5d2dd29825524ab-yjibkvwsnc.chromatic.com/?path=/story/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-fieldset--playground (VRTでOK)
- FieldsetのinnerMarginを0.5に指定してあたることを確認 https://63d0ccabb5d2dd29825524ab-yjibkvwsnc.chromatic.com/?path=/story/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-fieldset--inner-margin (https://story.smarthr-ui.dev では当たらないことも確認)
- FormControlの表示が変わっていないことを確認(VRT)
> fix(Fieldset): innerMarginとして0.5を受け取れるように修正

- packages/smarthr-ui/src/components/SegmentedControl/SegmentedControl.tsx
- packages/smarthr-ui/src/components/SegmentedControl/stories/SegmentedControl.stories.tsx
- packages/smarthr-ui/src/components/SegmentedControl/stories/VRTSegmentedControl.stories.tsx
https://smarthr.atlassian.net/browse/SHRUI-1179
アイコンのみの場合に `Button[square]` 相当のスタイリングをするために、`isSquare` を渡していた。
開発者は `isSquare` を気にせず使えるようになるため削除します。
Chromatic の差分がでていますが、標準サイズで isSquare が効いていなかったので修正されています。確認して accept してください。
> fix(SegmentedControl): isSquare を指定しなくても使えるように修正

- packages/smarthr-ui/src/components/Balloon/Balloon.stories.tsx
- packages/smarthr-ui/src/components/Balloon/Balloon.tsx
- packages/smarthr-ui/src/components/Button/DisabledDetail.tsx
- packages/smarthr-ui/src/components/Combobox/MultiCombobox/MultiSelectedItem.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownTrigger.tsx
- packages/smarthr-ui/src/components/LineClamp/LineClamp.tsx
- packages/smarthr-ui/src/components/TabBar/TabItem.tsx
- packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
- packages/smarthr-ui/src/components/Tooltip/TooltipPortal.tsx
- packages/smarthr-ui/src/components/Tooltip/stories/Tooltip.stories.tsx
- packages/smarthr-ui/src/components/Tooltip/stories/VRTTooltip.stories.tsx
SHRUI-573
- Tooltipの表示位置の計算ロジックを変更します
- これにより、Contentの領域を画面サイズに併せて可変することが可能になり、Tooltipの内容が画面内に収まるようになりました
> fix!: Tooltipの表示位置の計算ロジックを調整する  SHRUI-573

- packages/smarthr-ui/src/index.ts
- sandbox/next/e2e/rsc.test.ts
- sandbox/next/src/app/rsc_test/SideMenu/page.tsx
https://github.com/kufu/smarthr-ui/pull/5521
関連 URL に記載の PR で SideMenu を experimental から移動しているが、その際に export 対象から SideMenuGroup, SideMenuItem が消えてしまい import できなくなってしまったので修正したい
- `{ SideMenu }` で export していた箇所を `*` に変更
- SideMenu を RSC テストがなかったので追加
fmfm で
> fix: v69 から SideMenuGroup, SideMenuItem が export されなくなってしまったので export する

- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
https://kufuinc.slack.com/archives/CGC58MW01/p1743752214631679
FormControle, FieldsetのstatusLabels propsにStatusLabelを指定すると、`Warning: Each child in a list should have a unique "key" prop.`のwarnが出てしまうので解消したい
statusLabelsに渡されたコンポーネントにkeyを付与するようにした
- ChromaticでstatusLabelsのページを開いた際に、コンソールログにwarnが表示されないこと
- http://localhost:6006/?path=/story/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-formcontrol--status-labels
> fix: FormControle, FieldsetのstatusLabels propsを指定するとキーが付与されていないwarnが出る問題の修正

- packages/smarthr-ui/src/components/AppNavi/AppNaviDropdownMenuButton.tsx
- packages/smarthr-ui/src/components/AppNavi/stories/AppNaviDropdownMenuButton.stories.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
N/A
`AppNaviDropdownMenuButton` コンポーネントに onOpen/onClose オプションを追加したいです。
`FilterDropdown` には既にあるオプションで、プロダクト側でこのオプションを使った調整を、`AppNaviDropdownMenuButton` を使ってる箇所でも行おうとしたら onOpen/onClose がないことに気づき困ってるため追加したいです。
`AppNaviDropdownMenuButton` -> `DropdownMenuButton` -> `Dropdown` に props を伝搬します。
- 適当に Storybook 上で onClick/onClose を適用して動作確認しました。
- pkg-pr-new を使ってプロダクト側で問題解決できることも確認しました。
> feat: AppNaviDropdownMenuButton コンポーネントに onOpen/onClose オプションを追加する

- .github/workflows/startRelease.yml
n/a
package.jsonとactionでpnpmのバージョン定義されているとえらーになってしまう
ので、package.jsonのバージョン優先するためにaction側の定義をomitします
関連リンク
https://github.com/pnpm/action-setup/pull/134
https://github.com/pnpm/action-setup?tab=readme-ov-file#install-only-pnpm-with-packagemanager
> chore: actionのpnpm version定義をomitする

- packages/smarthr-ui/src/components/LineClamp/LineClamp.tsx
SHRUI-1205
LineClampのテキストが言語によって上下見切れてしまう
line-clampのcontentが overflow: hidden されているため、element boxに収まらないテキストが切れてしまう
overflow-xだけをhiddenにすると暗黙的に overflow-yのデフォルト値がvisibleからauto として計算されてしまうため、overflow-x: clipでx axisだけを切り取るように修正してみました
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-y
> overflow-x が hidden、scroll、auto のいずれかで、 overflow-y プロパティが visible （既定値）の場合、この値は暗黙的に auto として計算されます。
BEFORE | AFTER
--- | ---
Storybook や Chromatic で確認できます。LineClampのButtonの例でテキストを変えて確認しやすいと思います
以下のCodepenでも確認できます
https://codepen.io/Daichi-HASHIMURA/full/wBBvabB
> fix: LineClampのテキストが上下に見きれないように修正

- packages/smarthr-ui/src/components/Picker/style.ts
https://smarthr.atlassian.net/browse/SHRUI-1075
- TimePickerが拡大表示された場合、表示が途切れてしまう場合に対応する
- timepickerの横幅を調整
- classに `shr-min-w-[5em]` を追加
- そもそもの原因は `shr-h-[theme(fontSize.base)]` `shr-tabular-nums` の2つで、文字の横幅が増えることで発生していました
- 色々試しましたが横幅拡大が最も手軽でした
- スクショを確認する
> chore: TimePikcerを拡大表示した場合、文字が途切れてしまう場合がある問題を修正する SHRUI-1075

- packages/smarthr-ui/src/components/AppHeader/AppHeader.tsx
- packages/smarthr-ui/src/components/AppHeader/hooks/useMediaQuery.ts
- AppHeaderの表示モードの判定が、SSRの場合レイアウトシフトを引き起こしてしまう
- ロジックを修正したい
- 常にdesktop, mobileの両モードがhtml上に存在するように修正
- cssでの表示出し分けにすることでレイアウトシフトが発生しない状態にする
- なぜこのようなロジックにしているのか？をコメントとして明記
- 実プロダクトにて動作確認済み
> fix: AppHeaderの表示モードの判定をSSRでも最適に行えるようにする

- packages/smarthr-ui/src/intl/IntlProvider.tsx
- packages/smarthr-ui/src/intl/useIntl.test.tsx
#5569 
#5569 でlocalesはexportしたが、AppHeaderなどIntlProviderをネストできると便利なケースがあったり、そもそもプロダクト側でも気にせずIntlProviderだけを差し込めば良いと便利なため
- react-intlのIntlProviderをネストできるようにした
- テストがあるのでそちらの妥当性で判断いただければ！
> fix(IntlProvider): 複数のIntlProviderをネストできるように修正

- packages/smarthr-ui/src/components/SideNav/SideNavItemButton.tsx
SideNavItemButton に渡した props が握りつぶされていたので修正
> fix: SideNavItemButton に渡した props が漏れなく渡るように修正

- packages/smarthr-ui/src/components/Stepper/StepCounter.tsx
- packages/smarthr-ui/src/components/Stepper/VerticalStepItem.tsx
https://smarthr.atlassian.net/browse/SHRUI-1260
縦積みのStepperでタイトルが長いときに接続線が途切れるのを修正
- 縦積みのStepperでタイトルが長いときに接続線が途切れるのを修正
- 構造を少し変えています
- Story未整理のため、DevToolsで直接長めのタイトルを入れてみてください。
| :-- | :-- |
| <img width="1131" alt="image" src="https://github.com/user-attachments/assets/2d3a822d-c12a-44e4-85e9-8fd2d70c1986" /> | <img width="1135" alt="image" src="https://github.com/user-attachments/assets/c90629a3-0992-4c9a-848d-1111eac0ce59" /> |
> fix(Stepper): 縦積みStepperでタイトルが長いときに接続線が途切れるのを修正

- packages/smarthr-ui/src/components/RadioButtonPanel/RadioButtonPanel.tsx
- packages/smarthr-ui/src/components/RadioButtonPanel/stories/RadioButtonPanel.stories.tsx
- packages/smarthr-ui/src/components/RadioButtonPanel/stories/VRTRadioButtonPanel.stories.tsx
- [SHRUI-1251](https://smarthr.atlassian.net/browse/SHRUI-1251)
RadioButtonPanel の説明テキストはラジオボタンのアクセシブルネームではなく、 説明文として登録できるようにしたい
- RadioButton のラベルとして提供したい文字列を `label` propsで渡すようにしました
- `labelSuffix` を追加しました
- 説明文を `children` で渡すようにして、children がある場合 label に bold のスタイルが当たるように変更しました変更しました
[SHRUI-1251]: https://smarthr.atlassian.net/browse/SHRUI-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat!: RadioButtonPanelに説明テキストをdescriptionとして提供できるようにした

- packages/smarthr-ui/src/index.ts
- https://github.com/kufu/smarthr-ui/pull/5589
プロダクト側でsmarthr-uiをv70.3.0に更新する際にHelpLinkを使おうとしたが、smarthr-uiからexportされておらず利用できなかった
`src/index.ts`で`HelpLink`をexportするように修正しました
- fmfmのみでOK
> fix: HelpLinkがexportされていなかった問題修正

- packages/smarthr-ui/src/components/SideMenu/SideMenuGroup.tsx
グループタイトルは現状 TEXT_BLACK の bold ですが、SideMenuItem の current スタイルも同様に TEXT_BLACK の bold で、テキストサイズの違いしかなく、クリッカブルエリアが判別しづらいです。
DropdownContent のグルーピングタイトルに合わせて、TEXT_GRAY になるようにしたいです。
`<SideMenuGroup />` 内 `<Heading />` の type props の値を、 `blockTitle` から `subBlockTitle` に変更しました。
https://63d0ccabb5d2dd29825524ab-orfetcmnze.chromatic.com/?path=/story/navigation%EF%BC%88%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%EF%BC%89-sidemenu--grouped
> fix: SideMenu のグループタイトルの type を `blockTitle` から `subBlockTitle` に変更する

- packages/smarthr-ui/src/components/Icon/Icon.tsx
Google のロゴ利用ガイドライン違反になる可能性があるため Google Drive のアイコンを消します。
- https://github.com/kufu/smarthr-ui/pull/5483
- https://smarthr.atlassian.net/browse/SHRUI-1287
> fix!: GoogleDrive 関連のアイコンを削除

- packages/smarthr-ui/src/components/Table/Table.tsx
プロダクト側でsmarthr-ui v72.1.0に更新しようとしたが、Table周りでデグレがありそうだったので修正したい。
具体的に書くと、以下のPRの変更によって、Tableコンポーネントのpropsに渡したclassNameがtableタグに設定されなくなっており、styled-componentsで当てているスタイルが効かなくなっていた。
- https://github.com/kufu/smarthr-ui/pull/5622
Tableのpropsに渡したclassNameがtableタグに設定されるように修正しました。
- Tableに渡したclassNameがtableタグに正しく設定されていること
> fix: Tableで<table>タグにpropsのclassNameが渡されなくなっている不具合修正

- packages/smarthr-ui/src/components/Dialog/RemoteDialogTrigger/RemoteDialogTrigger.tsx
- packages/smarthr-ui/src/components/Dropdown/DropdownMenuButton/DropdownMenuButton.tsx
https://smarthr.atlassian.net/browse/SHRUI-1275
- 歴史的経緯により、RemoteDialogTriggerがvariantを持ち、childrenに設定されるButtonにはvariantを持てない状態だった
- これらの仕様はRemoteDialogTrigger内にRemoteDialogTriggerを設置するための処置であったため、整理したい
- RemoteDialogTriggerからvariant属性を削除し、childrenのButtonで設定できるように修正
- DropdownMenuButtonのstyleを調整し、表示崩れが起きないように修正
- storybookなどで表示を確認する
> fix!: RemoteDialogTriggerからvariant属性を削除し、Button自体に持つ形で修正する SHRUI-1275

- packages/smarthr-ui/src/components/Dialog/RemoteDialogTrigger/RemoteDialogTrigger.tsx
- RemoteDialogTriggerのonClickTriggerに対してasync-awaitなど、非同期処理の関数を設定した場合、event.currentTargetの取得時点でnullになってしまう可能性があることがわかったため対応したい
- 非同期処理となる可能性がある前にcurrentTarget絡みの処理を完了させるように修正
- コードをみてfmfmする
> fix: RemoteDialogTriggerがasync-awaitなど非同期処理と併用されると正常動作しない可能性があるため修正する

- packages/smarthr-ui/src/components/Dialog/StepFormDialog/StepFormDialogContentInner.tsx
なし
```StepFormDialog```でAPIリクエストを実施した際、バリデーション等で処理が進まなかった場合に「戻る」ボタンの挙動が意図しないものになるので修正したいです。
1. 「部署に追加2/2」ダイアログで実行を押下
2. バリデーションメッセージが表示される（ここでqueueが積まれる）
3. 「戻る」（1回目）押下 → 何も変化なし
4. 「戻る」（2回目）押下 → 「部署に追加 1/2」ダイアログへ戻る
次のステップに進んだ場合のみ、stepQueueにカウントするよう修正しました。
```smarthr-ui/packages/smarthr-ui/src/components/Dialog/StepFormDialog/stories/StepFormDialogItem.stories.tsx```のL.29行目を以下の形にすることで同様の状態となります。
```
if (currentStep.id === 'step-2') {
// closeDialog() ←コメントアウト
return
} else {
return { id: 'step-2', stepNumber: 2 }
}
```
> fix: StepFormDialogでバリデーションエラー時に戻るボタンが動かない問題の修正

- packages/smarthr-ui/src/components/Chip/Chip.tsx
- packages/smarthr-ui/src/components/Chip/stories/Chip.stories.tsx
- packages/smarthr-ui/src/components/Chip/stories/VRTChip.stories.tsx
- packages/smarthr-ui/src/components/StatusLabel/StatusLabel.tsx
- packages/smarthr-ui/src/smarthr-ui-preset.ts
- packages/smarthr-ui/src/themes/__tests__/createColor.ts
- packages/smarthr-ui/src/themes/__tests__/createTheme.ts
- packages/smarthr-ui/src/themes/createColor.ts
https://smarthr.atlassian.net/browse/SHRUI-1225
orange と green を preset に定義しました。
- primitive トークンの ORANGE_100 を [Sunlight_04](https://smarthr.design/basics/colors/#h4-4) に差し替え
- primitive トークンに GREEN_100 を追加
- ベタ書きたった orange と green を置き換え
- WARNING はどこでも使えないはずなので削除（すでにデザインシステムサイトからは消えている）
- WARNING が消えるため BREAKING CHANGE です
> fix!: color.ORANGE と color.GREEN を見直し

- package.json
- packages/smarthr-ui/src/components/AppHeader/components/desktop/Navigation.tsx
- pnpm-lock.yaml
- https://kufuinc.slack.com/archives/C069HF218UW/p1749549861451029
- https://github.com/kufu/smarthr-ui/pull/5659
- 上の PR で `aria-current=page` だったのが `aria-current` になったことが原因そう
- ドロップダウンナビゲーション（`AppNaviDropdownMenuButton` 配下）の子アイテムで  
`current=false` の場合でも `aria-current="false"` が DOM に出力されるため、  
- 目的は、**本当にアクティブなページのみ**親ボタンに下線が付くようにすること。
| 対象コンポーネント | 変更前 | 変更後 |
|-------------------|--------|--------|
| `DropdownMenuAnchorButton` | `aria-current={current && 'page'}` | `aria-current={current ? 'page' : undefined}` |
| `DropdownNavigationButton` | `aria-current={current && 'page'}` | `aria-current={current ? 'page' : undefined}` |
| 状態 | 修正前 | 修正後 |
|------|--------|--------|
| `current = false` | `<a aria-current="false">` が出力され、親に下線が付く | `aria-current` が出力されず、親に下線が付かない |
| `current = …
> fix: ドロップダウンナビゲーションボタンで current が false の場合は aria-current を undefined にする

- packages/smarthr-ui/tsconfig.json
https://kufuinc.slack.com/archives/C06P0L3HHDY/p1749804200523299
- export:ui-propsが失敗するのでmoduleをcommonjsに戻した
ローカルでexport:ui-propsを実行してうまく動けばOK
> fix: tsconfigのmoduleをes2022からcommonjsに戻した

- packages/smarthr-ui/src/smarthr-ui-preset.ts
https://smarthr.atlassian.net/browse/SHRUI-1300
`<StatusLabel />` の `className` に `shr-text-base` を設定すると StatusLabel に設定された `leading-[0]` も消えてしまう不具合がありました。
tailwind-merge の設定を見直し、`leading-[0]` も leading 扱いになるように修正しました。
StatusLabel など `leading-[0]` を使ったコンポーネントの Story で `className="shr-text-hoge"` を指定しても `leading-[0]` が消えないことを確認。
> fix(twMerge): leading-[0] も leading 扱いになるように修正

- packages/smarthr-ui/src/components/Table/TdCheckbox.tsx
- packages/smarthr-ui/src/components/Table/ThCheckbox.tsx
なし
プロダクトで、TableReel でラップしたテーブル内で一番左の列にあるチェックボックス(ThCheckbox, TdCheckbox)をスクロール時に固定したい要求があり、それに対応したいです。
ThCheckbox, TdCheckbox それぞれに props で fixed を受け取れるようにして、受け取った fixed をそのまま Th, Td に渡した
👇 `TableReel.stories.tsx` の thead > tr と tbody > tr に ThCheckbox, TdCheckbox を追加した際のキャプチャです。
> feat: ThCheckbox と TdCheckbox で fixed を渡せるようにしたい

- packages/smarthr-ui/src/components/FileViewer/PDFViewer.tsx
同様の対応を行っているissue: https://github.com/wojtekmaj/react-pdf/issues/1811#issuecomment-2157866061
- iOS17.3以下でFileViewerコンポーネントからPDFを開くとエラーが発生するため、修正した。
- PDFViewer内部で利用している`pdf.js`が`Promise.withResolvers`を利用していることが原因であるため、Polyfillを加えた。
- 現在CDNで読み込んでいるWeb Workerも同じく`Promise.withResolvers`を利用しているため、Promise.withResolversが未定義の場合はPolyfillされているworkerファイルを取りに行くようにした。
SimulatorからiOS17.3以下のシミュレータを起動し、SafariでstorybookのFileViewerを開く。
- **修正前**
- ローディング画面のまま動かず、コンソールを見ると`Promise.withResolvers is not a function.`といったエラーが出力されている。
- **修正後**
- pdfが表示され、コンソールにもエラーが出力されない。
| | 修正前 | 修正後 |
|----|----|----|
|iOS17.3以下の場合(17.2) | <img width="436" alt="normal_old" src="https://github.com/user-attachments/assets/e140cb22-8413-40fd-afed-23f6ea6c7d70" /> | <img width="436" alt="applied_old" …
> feat(FileViewer): iOS17.4未満でpdfを開くとエラーを吐くためPolyfill処理を加えた

- packages/smarthr-ui/src/components/FileViewer/PDFViewer.tsx
- FileViewerでCMapファイルが必要なpdfファイル(フォントが埋め込まれていない日本語pdfなど)を開くと、文字列が読み込めない現象を解消したい
- optionsでcMapUrl自体は指定されていたが、指定先のCDNではcmapファイルが配信されていなかった。
- そのため、cmapsが配信されているcdnを指定するように変更した。
> fix(FileViewer): cmapsの読み込み先が存在しないリンクになっていたため変更した

- packages/smarthr-ui/src/components/FileViewer/FileViewer.tsx
- packages/smarthr-ui/src/components/FileViewer/ImageViewer.tsx
- packages/smarthr-ui/src/components/FileViewer/PDFViewer.tsx
- packages/smarthr-ui/src/components/FileViewer/types.ts
- https://kufuinc.slack.com/archives/CGC58MW01/p1752573350694899
- FileViewerに破損したファイルが渡された際のエラー処理が設定されていないため、ユーザー側からエラーであることが確認しづらくなっている。
- エラー時のハンドラーをPropsとして渡せるようにすることで、読み込みエラー時の挙動をユーザー側でカスタマイズできるようにした。
- `onLoadError`を新しくFileViewerのPropsとして生やした。
- PDFViewerでは、内部的に使われている[react-pdfのonLoadError](https://github.com/wojtekmaj/react-pdf?tab=readme-ov-file#document)にそのまま渡すようにした。
- ImageViewerでは、HTMLImageElementのonErrorハンドラーに渡すようにした。
下記のような実装をして適当なファイルを渡し、動作していることを確認する。
```tsx
<FileViewer
file={...}
onError={ () => { alert('読み込みに失敗しました。ファイルが破損している可能性があります。') } }
```
インデントによる変更が多く出ているため、URLに `?w=1` をつけた方が差分見やすそうです！
> feat(FileViewer): 読み込みエラー時のハンドラーを追加した

- packages/smarthr-ui/src/components/Fieldset/Fieldset.test.tsx
- packages/smarthr-ui/src/components/FormControl/FormControl.tsx
- Fieldset + 可視ラベルを持たない複数のInput のときに、Inputのアクセシブルネームにlegendの文字追加を文末に変更にしました
- 以前はアクセシブルネームの計算に title属性を含めていましたが、title属性には「〇〇してください」といった補足テキストが入ることがあり、文末に legend を追加するとアクセシブルネームが不自然になるため文頭にしていました。
- しかし、title属性は補足テキストをツールチップで表示するのがメインの目的で、アクセシブルネームを設定するための手段としては `aria-label` などより良い手段があるため、title属性は考慮しないことにしました
> fix(Fieldset): アクセシブルネームの計算にtitle属性を含めるのをやめる

- packages/smarthr-ui/src/components/RangeSeparator/RangeSeparator.tsx
* https://smarthr.atlassian.net/browse/SHRUI-1331
* https://github.com/nvdajp/nvdajp/issues/440
`RangeSeparator`を非推奨化しました。また、`VisuallyHiddenText`の特殊なハンドリングを削除しました。
TSDocの`@deprecated`を利用して、ユーザーに非推奨である旨と、代替手段を提案するように変更しました。
また、`VisuallyHiddenText`で`〜`が`から`と読まれるような特殊な処理を加えていた部分を削除しました。
Storybookを確認するほか、下記のスクリーンショットのように、RangeSeparatorのアクセシビリティツリー上の解釈が普通のテキストとなっていれば問題ありません。
* https://63d0ccabb5d2dd29825524ab-dwdskwezmj.chromatic.com/?path=/docs/components-rangeseparator--docs
> fix: RangeSeparatorを非推奨化する

- packages/smarthr-ui/src/components/SpreadsheetTable/SpreadsheetTable.tsx
https://smarthr.atlassian.net/browse/SHRUI-1338
SpreadsheetTableコンポーネントにおける表の見出し要素で、前景色と背景色（`TEXT_GREY` と `HEAD`）のコントラスト比が4.34:1と十分でない問題を修正したい。
前景色を `TEXT_BLACK` に修正した
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=68ca243f084f19ad25fe5e57
> fix: SpreadsheetTableのthのコントラスト比を改善

- packages/smarthr-ui/src/components/TextLink/TextLink.tsx
- packages/smarthr-ui/src/components/TextLink/stories/TextLink.stories.tsx
TextLink の size プロパティに XS を追加しました。
FigmaのSmartHR UIコンポーネントでは XS があるので、実装側にも追加しました。
AsIs: https://story.smarthr-ui.dev/?path=/story/components-textlink--size
ToBe: https://63d0ccabb5d2dd29825524ab-smutouonqn.chromatic.com/?path=/story/components-textlink--size
> feat: TextLink の size プロパティに XS を追加する
